src/background.ts
何も開かないよりはましだと思ったので一番上にある｢ソフトウェアの利用規約｣をデフォルトで開くようにしてみました
=> ヘルプウィンドウを開いた時にソフトウェアの利用規約が開かれるよう変更

src/components/AudioCell.vue, src/store/audio.ts
#20 の案を実装しました。
https://user-images.githubusercontent.com/237271/128207026-2d1b3487-33ab-4d2f-8c97-15fff7ce3f50.mp4
=> セルにマウスオーバーしたら削除ボタンが出るように

README.md
大した内容ではないですが、ハイパーリンクが設定されていた方が親切かなと思いました。
=> docs: README にリンクを追加

src/App.vue, src/background.ts, src/store/index.ts, vue.config.js
`.vvproj`ファイルとVOICEVOXを関連付けて、プロジェクトファイルから起動、プロジェクトを読み込めるようにします。
=> プロジェクトファイルからVOICEVOXを起動する

src/background.ts, src/electron/preload.ts, src/store/audio.ts, src/store/index.ts, src/type/ipc.d.ts, src/type/preload.d.ts, src/views/Home.vue
セリフ、プロジェクトファイルをウインドウへドラッグアンドドロップすることで読み込めるようにします。
=> ファイルのドラッグアンドロップに対応する

src/components/AudioCell.vue
まだよく分っていませんが、挑戦してみました。
挑戦してみていいのかと思ったので、変な事していたら、すみません。
=> テキストコピペ時に句点でsplitした際、読点を残す

src/store/project.ts
#102 で移動したコードで #99 の修正を反映できていなかったので，バリデーションチェック部に`characterIndex`が存在することを確認するチェックを記述しました．
=> プロジェクトファイルのバリデーションチェックの修正

src/store/project.ts
=> 追加されたプロパティをプロジェクト定義にも追加

src/components/AudioCell.vue, src/views/Home.vue
close #139 
https://github.com/Hiroshiba/voicevox/pull/126 の部分revert。
この緊急対応でundo/redoを実装するときにバグが発生するかもしれません。
=> テキスト読み込み時にAudioQueryを取得するように変更（revert処理）

src/store/project.ts
=> hotfix project migration from 0.4.0 to 0.4.1

src/components/AudioInfo.vue, src/store/audio.ts
#39
0.0–1.0の範囲で各セルごとに音量を調整できます.
=> #39 音量調整機能の追加

src/App.vue, src/components/MenuBar.vue, src/store/ui.ts
q-dialog、q-loading展開中、タイトルバーに被らないようにしました
=> ダイアログ展開中にタイトルバーが隠れてしまう問題を修正

src/components/AudioDetail.vue, src/components/HelpDialog.vue, src/components/UpdateInfo.vue
=> ::v-deepが非推奨でずっと警告が出ていたので修正

src/store/audio.ts
actionであるSTART_WAITING_ENGINE内でstateが直接変更されていたので修正しておきました。
=> START_WAITING_ENGINEの修正

src/components/HeaderBar.vue, src/views/Home.vue
Homeが大きくなってきたのでヘッダーを分離しました
ついでにHomeで定義されているどこからも呼ばれていなさそうな関数を削除しました
=> ヘッダーを別コンポーネントとして分離

public/characters/dummy1/metas.json, public/characters/dummy1/policy.md, public/characters/dummy2/metas.json, public/characters/dummy2/policy.md, src/App.vue, src/background.ts, src/components/LibraryPolicy.vue, src/components/Policy.vue, src/main.ts, src/plugins/ipcMessageReceiverPlugin.ts, src/plugins/markdownItPlugin.ts
MarkdownItをVueプラグインにし、Providerパターン(?)で実装して呼び出せるようにしました
=> 音声ライブラリの利用規約をMarkdownファイルで書けるように

src/store/project.ts
#204 のリベース
pause moraがある際に読み込み失敗する問題を解決しました。
=> [HOTFIX]fix pause mora error

build/splitResources.js
オンラインインストーラーが分割ファイルについての情報を得られるようにするため、
7z ファイルの分割時に *.ini ファイルを生成するようにします。
ref #210
これによって生成されるようになる *.ini ファイルは以下のようなものです。
```ini
[files]
n=3
hash0=ABDF2492B581A4A1DF852F32BB37BD7E
hash1=281C4B619D3D5C38DCC33A075C260D1C
hash2=14DF9D5FCB0922E7BB9F51250A4B381B
size0=1073741824
size1=1073741824
size2=680587142
```
=> インストーラーのビルド時に *.ini ファイルを生成する

src/components/AudioCell.vue, src/components/AudioDetail.vue, src/store/audio.ts, src/store/project.ts
今までの`FETCH_AUDIO_QUERY`, `FETCH_ACCENT_PHRASES`, `FETCH_MORA_DATA` `FETCH_SINGLE_ACCENT_PHRASE`を`FETCH_AND_SET_AUDIO_QUERY`, `FETCH_AND_SET_ACCENT_PHRASES`, `FETCH_AND_SET_MORA_DATA` `FETCH_AND_SET_SINGLE_ACCENT_PHRASE`に変更し、
`FETCH_AUDIO_QUERY`, `FETCH_ACCENT_PHRASES`, `FETCH_MORA_DATA`をフェッチとエラーロギングのみのActionに変更しました。
ref #258
=> FETCHの副作用の分離

src/components/AudioCell.vue, src/store/audio.ts
`CHANGE_CHARACTER_INDEX`をoldCommandから新しいコマンドに実装し直しました。
ref #258
ref #233
ref #116
#267 を非同期コマンドの参考例として書きましたがこちらの方が小さいので適しているかもしれません。
=> `CHANGE_CHARACTER_INDEX`の新方式への移行

src/components/AudioCell.vue, src/components/AudioDetail.vue, src/components/AudioInfo.vue, src/components/HeaderBar.vue, src/components/MenuBar.vue, src/components/OssLicense.vue, src/components/Policy.vue, src/components/SettingDialog.vue, src/components/UpdateInfo.vue, src/store/audio.ts, src/store/command.ts, src/store/index.ts, src/store/project.ts, src/store/setting.ts, src/store/type.ts, src/store/ui.ts, src/store/vuex.ts, src/views/Home.vue
Storeの型付けを完了させます。
close #197 
`oldCreateCommandAction`などの、今後消される予定のものは手を付けずに放置しています。
=> Storeの型を厳密化する

src/background.ts
#282 で加えたリファクタリングで一部挙動を変更してしまっていたので復元します。
RESTART_ENGINEでは、ENGINEのプロセスキルにより発生するChildProcessのcloseイベントを
一度だけとらえて、終了したENGINEを新たに起動する処理をします。
#282 において、ENGINEのプロセスキルに失敗したとき、
再起動用のEventListenerの登録を解除するコードを削除しました。
再起動用のEventListenerはonceで登録されていたため、登録解除は必要ないと思っていました。
しかし、該当箇所はプロセスキルに失敗したときの処理であり、
プロセスキルに伴うcloseイベントが発生せず、once listenerが消費されないため、
RESTART_ENGINE失敗後も、ENGINEの起動処理を行うEventListenerが残存する状態になっていました。
この変更をもとに戻します。
RESTART_ENGINEでENGINEのプロセスキルに失敗したが、
まだENGINEのプロセスは終了していないとき、
次回のENGINEプロセスキルが起きても、ENGINEは再起動しない。
RESTART_ENGINEでENGINEのプロセスキルに失敗したが、
まだENGINEのプロセスは終了していないとき、
次回のENGINEプロセスキルが起きると、ENGINEが再起動される。
同じ状態で、新たなRESTART_ENGINE操作によってENGINEがプロセスキルされたとき、
ENGINEが二重起動する。
=> Revert: ENGINEのプロセスキル失敗時にENGINEの再起動を停止

src/components/MenuBar.vue, src/store/audio.ts, src/store/type.ts, src/views/Home.vue
`IMPORT_FROM_FILE`コマンドをCommandStoreに移動し`COMMAND_IMPORT_FROM_FILE`コマンドとして実装しました。
ref #258
ref #233
ref #116
=> `IMPORT_FROM_FILE`コマンドの新方式への移行

src/components/HeaderBar.vue, src/components/MenuBar.vue, src/components/MenuButton.vue
=> 設定とヘルプをメニューに移動

src/store/audio.ts, src/store/type.ts
#248 の読み変更における問題を修正しました。
close #248
=> 読み変更するとイントネーションが文中っぽくなくなる問題の修正

package-lock.json, package.json, src/store/command.ts, src/store/type.ts, src/type/globals.d.ts
#310 の問題を解決するためにimmerのsrcから直接関数を読み込みました。
close #310
=> applyPatchesをimmerのものを利用するように変更

src/components/AudioCell.vue, src/components/AudioDetail.vue, src/components/AudioInfo.vue, src/components/LibraryPolicy.vue, src/components/OssLicense.vue, src/components/SettingDialog.vue, src/helpers/previewableValue.ts, src/store/audio.ts, src/store/command.ts, src/store/index.ts, src/store/project.ts, src/store/ui.ts, src/views/Home.vue
vuex.ts以外のwarningをすべてなくしました。
エラーが出る箇所はエラーをthrowするように、握りつぶす部分は握りつぶすようにしました。
activeAudioKeyはundefinedにならないようにそもそも設計を変えました。
close: #53
（vuex.ts周りのワーニングは残っていますが、closeしちゃっていいと思います。必要であれば別issueを建てていただければ。）
=> vuex.ts以外のwarningをすべてなくした

.github/workflows/build.yml, package-lock.json, package.json, public/updateInfos.json, src/components/HowToUse.vue
=> to 0.7.4　VOICEVOX ENGINE 0.7.4への対応

src/components/HotkeySettingDialog.vue
ショートカットキー登録時、被っているかどうかを表示するようにしました。
また、被っていた場合は上書きできるようにしました。
=> ショートカットキーが被っていたときに簡単に上書きできるようにする

README.md, src/store/project.ts
私が VOICEVOX の開発環境構築を進めていくにあたり `README.md` を見ながら進めましたが躓いた箇所がありました。
それは、 `node.js` のインストール後、いつVOICEVOXのリポジトリである `https://github.com/Hiroshiba/voicevox.git` をローカルに `git clone` すれば良いのかわからなかったので追記しました。
ついでに下記も行いました。
- node.js のダウンロードURLは自分で作成すること
- リンクの前後に半角空白があったりなかったりしたので統一して追加しました。
ref https://github.com/Hiroshiba/voicevox/issues/391#issuecomment-951426235
=> Readme md の環境構築部分に git clone するタイミングを追記

docs/全体構成.md
=> 全体構成.mdにVOICEVOXホムペへのリンクを追加

src/background.ts
Eはextractのつもりです。
shift+spaceがIMEなどの設定と被っていたら教えていただけると・・・！
=> １つだけ書き出し、連続再生にデフォルトのショートカットキーを追加

package-lock.json
package-lockがNode16用になっているので戻します。
=> package-lock.jsonの更新

src/components/MenuBar.vue, src/store/type.ts, src/store/ui.ts, tests/unit/store/Vuex.spec.ts
いずれかのダイアログオープン時、メニューバーをロックします。
- #515 
- 間接的な解決策の一つです。
- 完全な解決にはなっていないと思われる(普通にダイアログを終了してもAudioCellはバグることがあるっぽい)ので、closeまではしません。
=> add menubar lock

src/store/audio.ts
=> サンプリングレート変更・ステレオ化適用時にキャッシュヒットがおかしくなる問題の修正

src/components/DefaultStyleSelectDialog.vue
スタイルが1つしかないキャラはあらかじめスタイルを選択するようなコードを書いたつもりでしたが、スタイルを選択する方法をミスっていたので、「完了」を押せますが進めなくなっていました....
確認不足で申し訳ないです....
#510 
close #515
=> ミスの修正(スタイルが1つのキャラクターは自動でスタイルを選択)

src/components/MenuItem.vue
=> セパレータに色を付ける

.npmrc
これを追加するとバージョンが==で固定されるっぽいです
- https://github.com/Hiroshiba/voicevox/pull/476
=> npmrcにバージョンを固定するオプションを追加する

.github/workflows/build.yml
=> 製品版リソースのバージョンを選択可能にする

.github/workflows/build.yml
エンジンを`0.10.preview.2`にしてビルドを試してみます。
- https://github.com/VOICEVOX/voicevox/issues/572
=> エンジンのバージョンを0.10.preview.2に変更して動作確認してみる

public/howtouse.md
ctrl+ホイールで細かく調査できることがドキュメントに書かれていなかったので、とりあえずそれっぽいところに書いてみました
言及 https://twitter.com/xBh66FSafmNw5Dd/status/1472847786026491906
=> ctrl+ホイールで細かく調査できることを追記

src/background.ts, src/components/SettingDialog.vue, src/store/setting.ts, src/type/preload.d.ts, src/views/Home.vue, tests/unit/store/Vuex.spec.ts
#553 の実装において現在未解決の #587 のバグが存在する．
バグが修正されるまでこの機能をExperimental機能とし，デフォルトで無効化する．
ref #587
=> テキスト欄並び替え機能のExperimental化

.github/workflows/build.yml
=> エンジンのバージョンを0.10.preview.8に

.github/workflows/build.yml
=> engineのバージョンを0.10.preview.9に

src/components/AudioParameter.vue
意図が分かりづらいのでコメント追記
ref https://github.com/VOICEVOX/voicevox/pull/623#issuecomment-1010750269
=> shift+ホイール操作の横方向スクロール中にスライダー操作を無視するという意図コメントを追記

docs/全体構成.md, public/ossCommunityInfos.md
libtorchからonnxruntimeになるのでドキュメントの微修正です。
=> libtorchではなくonnxruntimeを用いて開発されていることを表記

src/store/project.ts
=> バージョン比較がおかしくなる問題を修正

src/store/project.ts
プロジェクトファイルにisInterrogativeをoptionalPropertiesとして追加
close #678
=> Hotfix: プロジェクトファイルのSchemeにisInterrogativeを追加

src/store/audio.ts
=> コピペ時もpresetを継承するように変更

src/components/AudioAccent.vue, src/components/AudioDetail.vue, src/components/AudioParameter.vue
スライダークリックで再生位置指定になってしまうのを直します
close #698
=> スライダークリックで再生位置指定になってしまうのを直す

.github/workflows/build.yml
GTMの情報をビルド時にresourceから取ってくるようにしました。
close #695 
yamlのフォーマットが走ってしまいました･･･。
僕はRedhatの[Yaml VSCode Extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml)を活用しています。
=> GTM情報を書き換える

.github/workflows/build.yml
GTM用の変更をしましたが、リソースのバージョンを上げていなくてエラーになっていたので修正です
=> resourceとengineのバージョンを上げる

src/background.ts
タイトルのとおりです。よくわかっていませんが、動くはず。。
- https://github.com/VOICEVOX/voicevox/issues/721
=> electron builderでは、.envファイルが読み込まれないっぽい？のでフォールバック

src/views/Home.vue
```filter="input"```と```:preventOnFilter="false"```を追加してテキスト欄をドラッグ対象から外しました。
close #730
=> [HOTFIX] #730を修正

public/qAndA.md
アプデ方法がわからないというツイートをたまに見かけるので公式から案内
https://twitter.com/Claudius_suzuki/status/1490483138203906051
=> Q&Aにアプデ方法を追記

src/components/DictionaryManageDialog.vue
storeのUILockを使っていることで生じているバグを取り除きます。
とりあえずcreateUILockActionをコンポーネント内に定義してごまかすようにしてみました。
ref https://github.com/VOICEVOX/voicevox/issues/724
close #727
=> 辞書ダイアログ内のUI lockを分ける

src/store/audio.ts
テキスト読み込み時にデフォルトスタイルが適用されるように変更しました。
=> テキスト読み込み時にデフォルトスタイルが適用されるように変更

.github/workflows/build.yml
initializeが高速になったエンジンで試しにビルドしてみるためのアプデです。
=> エンジンのバージョンを0.12.4-previewに

.github/workflows/build.yml
- https://github.com/VOICEVOX/voicevox/pull/809
が正しくなかったので修正です。
=> エンジンのバージョンを正しく0.12.4-previewに

.github/workflows/build.yml
=> エンジンを0.12.5-previewに

src/background.ts, src/electron/preload.ts, src/store/audio.ts, src/store/index.ts, src/store/project.ts, src/store/type.ts, src/store/ui.ts, src/type/ipc.d.ts, src/type/preload.d.ts, src/views/Home.vue
warning typeの質問ダイアログを出す方法がなかったので、typeを指定可能にしました。
=> ダイアログ表示でtypeを指定可能にする

src/components/PresetManageDialog.vue, src/store/preset.ts, src/store/type.ts
プリセット管理画面においてドラッグによってプリセットの並び替えができるようにします
=> プリセットの並び替え機能

src/background.ts, src/components/SettingDialog.vue, src/electron/preload.ts, src/store/audio.ts, src/store/index.ts, src/store/project.ts, src/store/setting.ts, src/store/type.ts, src/store/ui.ts, src/type/ipc.d.ts, src/type/preload.d.ts, src/views/Home.vue
- https://github.com/VOICEVOX/voicevox/issues/801
に関連したタスクです。
- https://github.com/VOICEVOX/voicevox/pull/806
が先に必要です。
=> GPUモードに切り替えたときにエラーが発生したらCPUモードに戻す

.github/workflows/build.yml, public/updateInfos.json, src/components/DefaultStyleSelectDialog.vue
- https://github.com/VOICEVOX/voicevox/pull/836
の変更もmainに入ります
=> 0.12.4をマージ

src/store/audio.ts
題の通り
なぜか型周りのエラーが出ていなくて、取り残されていたようです。
これが起因して、エンジンモードの変更が出来なくなっていました。
=> エンジンモードを変更できない不具合を修正

src/components/AudioCell.vue, src/components/CharacterPortrait.vue, src/store/audio.ts, src/store/type.ts, src/views/Home.vue, tests/unit/store/Vuex.spec.ts
話者（キャラクター）の初期化時にloadingインジケータを表示する機能を追加しました。
以下の点が不安なので、レビューをお願いいたします。
- storeにステート（isInitializingSpeaker）を追加
- 初期化中では分かりにくいと思ったのでキャラクターを読み込み中と表示
vue、vuex等慣れていないので、ご指摘いただけますと幸いです。
ref #821
=> 話者の初期化中にloadingインジケータを表示する機能を追加

package-lock.json, package.json
題の通り、メニューバーが消えてしまう問題に対処するため、Quasar v2.4.13までバージョンを下げました。
軽く触った感じ問題なさそうでしたが、一応他の方にも確認いただきたいです。
- ref #901
=> Quasarのバージョンをダウングレード

src/components/AcceptRetrieveTelemetryDialog.vue, src/components/AcceptTermsDialog.vue
タイトルの通りです。
close #899
このPRを取り込んだバージョン0.13.1は来週の土日にリリース予定です。
=> 規約同意画面などの右上のボタンを真っ白にさせないように修正

README.md
=> Write how change Engine API Endpoint on README

docs/全体構成.md
=> VOICEVOXリポジトリに変更

src/components/CharacterOrderDialog.vue
#912 を修正します。
- close: #912 
https://user-images.githubusercontent.com/59691627/188432455-afa1de22-b545-48cf-8789-1dbf84b331bc.mp4
ダウングレードではなくエンジン追加・削除で再現しています。
=> Fix: 不明なキャラクターがいるときの並び替えダイアログのエラーを修正

src/store/audio.ts, src/store/command.ts, src/store/dictionary.ts, src/store/index.ts, src/store/preset.ts, src/store/project.ts, src/store/proxy.ts, src/store/setting.ts, src/store/type.ts, src/store/ui.ts, src/store/utility.ts, src/store/vuex.ts
型の方と同じように、キーの下にgetter、mutation、actionが生える構造に変更してみました。
変更量がとんでもないことになっていますが、実装の中身自体は弄っていないので動作上の変化はない…はずです。
ref #364
=> ストアの実装の構造を型に合わせる

src/store/index.ts, src/store/singing.ts, src/store/type.ts, tests/unit/store/Vuex.spec.ts
歌声合成用のStoreStateを追加します。
ご意見、ご指摘等いただけますと幸いです。
=> project-s: StoreStateを追加

src/store/project.ts
#616 を修正しました。
if分岐を削除し、常にプロジェクトファイルパスを更新するようにしました。
close #616
TypeScript初心者なので、おかしなところがあれば指摘してください。
=> 名前を付けて保存でプロジェクトを切り替えるように修正

src/components/DictionaryManageDialog.vue
優先度のスライダーの表記を変更し、わかりやすくします。
- resolve: https://twitter.com/midorinotouhu/status/1581939136852025345
（なし）
=> Change: 優先度のスライダーの表記を変更

build/installer_linux.sh
update-dasktop-database する際に、エラーになっていたのを修正
=> fix:(linux_installer.sh) use DESKTOP_ENTRY_INSTALLDIR

src/background.ts
.envにエンジン情報が不足している場合、かなり原因がわかりにくいエラーが表示されていたので、validateして何が不足しているかわかるようにしました。
EngineInfoの型情報を複数箇所に書く必要が出てきてしまうのですが、ボイボ貢献者の壁を１つなくせそうなので、こちらを優先したいと思っています。
=> .envのエンジン情報が想定しているものと異なったときにエラーメッセージを表示

.github/workflows/build.yml, .github/workflows/test.yml, .github/workflows/typos.yml
公式のActionをバージョンアップしました。
ref #987
master指定な場所も明確にバージョンを指定するようにしました。
`softprops/action-gh-release`をどうするかは要検討です。
ついでに`crate-ci/typos`もアップデートしました。
=> chore(actions): update

src/components/MenuBar.vue
システム側のタイトルを変更するようにします。
- closes: #1011 
（自分が使ってるキャプチャソフトだと撮れなかったので直取り）
titleをgetElementsByTagNameで取る実装になっています。
=> Add: タイトルを変更するように

src/components/AudioDetail.vue
読みをクリックするときに間違えてsplitしてしまうため，splitの位置を大きくした
close #241 
https://user-images.githubusercontent.com/40142697/182377892-396dbe45-402b-4223-aa2a-b3c2918074bb.mp4
[@takurinton ](https://github.com/takurinton)に手伝っていただきました！thx！
=> grid-rowの値を変更

src/components/MenuBar.vue
セーフモード時、タイトルの色が変わらないのを修正します。
- ref:voicevox/voicevox_project#2
（なし）
=> 複数エンジン対応：セーフモード時、タイトルの色が変わらないのを修正

public/qAndA.md
ubuntu22でvoicevoxが動かないので、案内を追加します。
ref #1006
=> ubuntu22でlibfuse2をインストールするようQ&Aに追加

src/components/MenuBar.vue, src/store/type.ts, src/store/ui.ts, src/views/EditorHome.vue
IS_CHARACTER_ORDER_DIALOG_OPENなどのダイアログ制御をSET_DIALOG_OPENにまとめます。
（なし）
（なし）
（なし）
=> Refactor: ダイアログの開閉を全てSET_DIALOG_OPENに

src/components/AudioCell.vue, src/components/CharacterButton.vue, src/type/preload.ts
モーフィングUIに使用するためにAudioCellからキャラクター選択ボタンを切り離してコンポーネント化しました。
- ref #552 
AudioCellからそのまま持ってきたものが多いです。
=> ENH: AudioCellのキャラクター選択ボタンをコンポーネント化

docs/全体構成.md
全体構成説明の図を修正する際、もう一箇所も変えないといけないことを追記します。
そもそもこの図は https://github.com/VOICEVOX/voicevox_project で管理するべきなので移動したほうが良さそう
=> リポジトリ説明README.mdも要修正なことを追記

src/components/HelpDialog.vue
=> 複数エンジン対応：エンジン起動中にヘルプを開くとエラーが発生していたのを修正

.github/workflows/build.yml
=> リリース0.14のプレビュー版ビルド用変更

src/components/MenuBar.vue, src/components/MenuButton.vue, src/components/MenuItem.vue
Menu系をscript setup構文に置き換えます。
- ref: #1065 
（なし）
（なし）
=> script setup：Menu系をscript setupに

src/components/DictionaryManageDialog.vue
辞書管理ダイアログを移行します。
- ref: #1065 
（なし）
（なし）
=> script setup：辞書管理ダイアログを移行

package-lock.json, package.json, src/store/project.ts
プロジェクトのバリデーションをzodで行うようにします。
- ref: https://github.com/VOICEVOX/voicevox/issues/1076#issuecomment-1382413341
（なし）
（なし）
=> Change: プロジェクトのバリデーションをzodで行うように

src/components/AudioDetail.vue, src/components/AudioInfo.vue, src/components/HeaderBar.vue, src/store/audio.ts, src/store/type.ts
=> mophing->morphing

src/background.ts
- https://github.com/VOICEVOX/voicevox/pull/1146#issuecomment-1404959105
でちょっと話題に上がったのでコメントを追記。
2023/01/27 15:12　そもそもこのコードは使われていなさそうなので、消去するように内容を変更しました。
=> background.tsのactivateが使われていないので消去

src/background.ts, src/components/MenuBar.vue, src/components/SettingDialog.vue, src/store/setting.ts, src/type/preload.ts, tests/unit/store/Vuex.spec.ts
マルチエンジン機能は「実験的機能」という立ち位置にしたいと考えています。
理由はリリース直前まで開発しているため未知の不具合や分かりづらい挙動があったとき、あるいはドキュメントの至らない部分があった場合に備え、期待感のコントロールをしたいためです。
（マルチエンジンは想定していた以上に強敵でした･･･。）
=> マルチエンジンを実験的機能に

src/background.ts, src/electron/preload.ts, src/store/setting.ts, src/store/type.ts, src/type/ipc.ts, src/type/preload.ts
エンジン毎の設定をSET_ENGINE_SETTINGに移動します。
- ref: #1146 
（なし）
オブジェクトのクローン周りでエラーを吐かれていたのも修正します。
=> マルチエンジン：SET_ENGINE_SETTINGを追加

.github/workflows/build.yml
エンジンを0.14.0-preview.13にします。
マージ後にビルドしてみます！
=> エンジンを0.14.0-preview.13に

.github/workflows/build.yml
=> エンジンを0.14.0-preview.14に

public/updateInfos.json
=> 0.14.1 更新履歴を更新

.github/workflows/build.yml, public/qAndA.md, public/updateInfos.json
エンジンにバグがあったのを直したのでエディタ側にも反映します。
（エンジン特有のバグだったのでエディタには影響なしでした）
=> [release-0.14] to 0.14.2（エンジンのバージョン更新）

.github/workflows/build.yml, public/updateInfos.json
=> [release-0.14] to 0.14.3（エンジンのバージョン更新） (#1174)

src/components/ContactInfo.vue, src/components/HelpDialog.vue, src/components/LibraryPolicy.vue, src/components/OssLicense.vue, src/components/UpdateInfo.vue
タイトル通り。
- close: #1065 
（なし）
（なし）
=> script setup：ヘルプダイアログをscript setup化

public/qAndA.md
こちらの不明点報告を聞いての修正です！
https://twitter.com/arigayas/status/1622318151764684800
=> [Q&A]config.jsonを消してもらうQ&Aをより詳細に

public/updateInfos.json
=> [release-0.14] to 0.14.4

src/components/DefaultStyleListDialog.vue
デフォルトスタイルのダイアログが閉じれない場合があるのを修正します。
- closes: #1195 
（なし）
release-0.14に入れてhotfixリリースしても良いかも…？
=> Fix: デフォルトスタイルのダイアログが閉じれないバグを修正

package-lock.json
npm auditを実行したらcriticalなものがいくつかあったので、npm audit fixを実行しました。
一応npm run test:unitを実行しておきました。
=> npm audit fixを実行しました

src/App.vue, src/views/EditorHome.vue
タイトル通り。
- ref: #1065 
（なし）
型エラーの修正も入っています。
=> script setup：App.vue、EditorHome.vueを移行

.github/workflows/build.yml, .github/workflows/test.yml
タイトル通り。setup-nodeのcache: npmを使うようにします。
（なし）
（なし）
（なし）
=> Change: cache: npmを使うように

package-lock.json, package.json
electronを20系統最終版に更新します(`20.3.12`)
20系統はEOLを迎えたため、移行について検討したほうが良いかと思います。特にchrome 110ベースのとこまで上げるとwin7/8.1を切り捨てることになります。
=> chore(deps): update electron

src/components/EngineManageDialog.vue, src/components/HeaderBarCustomDialog.vue, src/components/HotkeySettingDialog.vue, src/components/PresetManageDialog.vue, src/components/SettingDialog.vue
タイトル通り。
- ref: #1065 
（なし）
（なし）
=> script setup：設定ダイアログ系を移行

src/components/ErrorBoundary.vue, src/components/FileNamePatternDialog.vue, src/components/HeaderBar.vue, src/components/MinMaxCloseButtons.vue, src/components/ProgressDialog.vue, src/components/TitleBarButtons.vue, src/components/ToolTip.vue
長く苦しい戦いだった
close: #1065
（なし）
（なし）
=> script setup：残り全部を移行

package-lock.json, package.json, src/components/SaveAllResultDialog.vue, src/styles/colors.scss, vite.config.ts
=> 書き出し結果画面を書き直し

src/components/Sing/MenuBar.vue, src/infrastructures/AudioRenderer.ts, src/store/singing.ts, src/store/type.ts, src/views/SingerHome.vue, tests/unit/store/Vuex.spec.ts
wav形式で音声を書き出す機能を追加します。
ref #1041
オフラインレンダリングで使用したノードは、Electronのバージョンによってはdisconnectしないと解放されないようで、現在のバージョンでは大丈夫だと思いますが、念のために一通り実装してからまた確認したいと思います。
=> [project-s] 音声を書き出す機能を追加

README.md
READMEにて、VOICEVOX非公式Discordサーバーへの案内を行います。
ついでにバッジもいくつか付けてみました。
現在Dicordサーバー管理の方にご相談中です。
=> READMEにDiscordへの案内などを追加

README.md
バッジのURLがおかしかったのを修正します。
- https://github.com/VOICEVOX/voicevox/pull/1283
=> バッジのURLがおかしかったのを修正

docs/全体構成.md
=> Update: 全体構成のコアの項目を更新

README.md
環境構築のとこのREADMEの説明順序がおかしくなっていたので改修しました。
* 変更前
* Nodejsインストールして
* 下のコマンド実行して（npm ci）
* nvsとVoltaが便利
* `npm ci`
* 変更後
* Nodejsインストールして
* nvsとVoltaが便利
* 下のコマンド実行して（npm ci）
* `npm ci`
- https://github.com/VOICEVOX/voicevox/pull/1315
フォーマットが走っちゃいましたが、まあ良いかなと。。。
=> 環境構築のREADMEを改修

src/store/audio.ts, src/store/project.ts, src/type/preload.ts
- https://github.com/VOICEVOX/voicevox/issues/1043
を解決します。
close #1043
issue側にも書いてますが、結果を使わないResult型はエラーハンドリングを忘れがちになるのどうすれば良いんでしょう。。
=> writeFileのエラーハンドリングを行う

public/ossCommunityInfos.md
VOICEVOX内から参照できる開発コミュニティに関するヘルプが C++ のままになっていたので、Rust へ更新します。
#1287 のドキュメントへの更新と同様の内容です。
=> fix: 開発コミュニティについてのヘルプを更新する

package-lock.json, package.json
題のとおりです。
さっと動作確認した感じでは、特に問題点はなさそうでしたが、もう少し色々動作確認はしたほうがいいかもしれません。
- ref #1227 
- close #1360 
- close #1368
=> Electronのバージョンを23系のlatestにする

src/background.ts
- https://github.com/VOICEVOX/voicevox/issues/1316
の解決です。
fix #1316
FIXMEコメントに書いてある通り、本当は必ずしも再起動は必要ではないのですが、安全方向に倒して再起動を要求するようにしています。
おそらく↓の課題が解決したらそもそもこの経路がなくなるはず。
- https://github.com/VOICEVOX/voicevox/issues/1398
=> vvppインストール時に再起動促す

src/components/AudioCell.vue, src/components/DictionaryManageDialog.vue
バグ #1426 の修正PRです。
#976 を参考しました。
ref #1426
=> fix: #1394 由来のバグを修正

package-lock.json, package.json, src/background.ts, src/background/engineManager.ts
- https://github.com/VOICEVOX/voicevox/issues/1424
の解決プルリクエストです。
electronのバージョンを2つ上げています。
おそらく影響のある変更は特にないはず。
https://www.electronjs.org/ja/blog/electron-24-0
https://www.electronjs.org/ja/blog/electron-25-0
解決策はこちらに従っています。
https://www.electronjs.org/ja/docs/latest/breaking-changes#planned-breaking-api-changes-250
実際に手元でビルドしてみてちゃんと動きそうなことを確認しました。
fix #1424
=> registerFileProtocolの離脱

src/background.ts
- https://github.com/VOICEVOX/voicevox/pull/1441
こちらのプルリクエストで解決しきれなかったところを修正します。
https://discord.com/channels/879570910208733277/893889888208977960/1136277972437975153
=> registerProtocol周りがビルド済みアプリが起動しないバグを修正

src/store/audio.ts, src/store/utility.ts
テキスト変更時、読みが変わらなかった時はイントネーション等のパラメータがリセットされないようにする #1421
{}かっこもどうようにテキスト書き出し部分への入力は完全に無視されています。
ref #1421
修正後
https://github.com/VOICEVOX/voicevox/assets/100256521/15125e3b-929b-457c-8cae-528f73273de8
=> テキスト変更時、読みが変わらなかった時はイントネーション等のパラメータがリセットされないようにする  

src/store/audio.ts
EBUSYの日本語メッセージを追加します。
（なし）
（なし）
=> Add: EBUSYのメッセージを追加

src/components/SaveAllResultDialog.vue
それぞれの結果をアコーディオンにし、一覧性を高めます。
また、[閉じる] ボタンを下部に固定し、以下の問題も解決します。
- #1449
close #1449
https://github.com/VOICEVOX/voicevox/assets/7900586/502bb342-ec27-4694-8536-d10759c2b087
=> 音声書き出し結果ダイアログの見た目を調整

tests/e2e/browser/ヘルプ.spec.ts
ヘルプダイアログをクリックしたときのテストの内容を更新しました
ref #1462
=> ヘルプダイアログのテスト内容更新

tests/e2e/browser/ツールバーカスタマイズダイアログ.spec.ts
ツールバーのカスタマイズのe2eテストを実装しました
ref #1462
=> ツールバーのカスタマイズのe2eテスト実装

tests/e2e/browser/音声パラメータ.spec.ts
- パラメータ引き継ぎがオンのときに実際に引き継ぐかどうかを確認するe2eテストを追加しました。
- パラメータ引き継ぎがオフのときに実際に引き継がないことを確認するe2eテストを追加しました
ref #1462
=> パラメータ引き継ぎのe2eテスト追加

docs/色について.md, public/themes/dark.json, public/themes/default.json, src/components/AudioAccent.vue, src/components/AudioCell.vue, src/components/AudioDetail.vue, src/components/AudioInfo.vue, src/components/AudioParameter.vue, src/components/CharacterButton.vue, src/components/CharacterOrderDialog.vue, src/components/CharacterTryListenCard.vue, src/components/DefaultStyleListDialog.vue, src/components/DefaultStyleSelectDialog.vue, src/components/DictionaryManageDialog.vue, src/components/SettingDialog.vue, src/components/help/LibraryPolicy.vue, src/components/help/OssLicense.vue, src/styles/_index.scss, src/styles/colors.scss, src/type/preload.ts, src/views/EditorHome.vue
primary-lightとprimaryが全く同じ定義だったのでprimaryに統一しました。
close #1447
=> primary-lightを消しました

tests/e2e/browser/音声パラメータ.spec.ts
キーボードからパラメータを入力するテストは書いてありましたが、スライダーから入力するのはまだ書いていなかったので書きました。
ref #1462
=> スライダーでのパラメータの変更のe2eテスト追加

src/store/audio.ts, src/store/audioPlayer.ts, src/store/index.ts, src/store/type.ts, tests/unit/store/Vuex.spec.ts
`HTMLAudioElement`に関連する処理を`audioPlayer.ts`に移動します。
ひとまず現状でほぼコピペで終わるもののみに絞ります。
- #1475
上記の一環です。
=> refactor: `audioPlayer.ts`を新規作成し`audio.ts`の一部機能を移転

src/infrastructures/AudioRenderer.ts, src/store/singing.ts
音声コンテキストとトランスポートを直接扱う形に変更します。
バッファーにレンダリングする処理などもメソッドとしてまとめずに直接行うようにします。
こうすることで、少しコードが増えますが、見通しは良くなると思います。
また、フレーズの音声を`AudioBuffer`ではなく`Blob`で保持し、レンダリングの際に`AudioBuffer`を生成するようにします。（音声コンテキストと`AudioBuffer`のサンプリングレートが合うようにします）
ref #1041
=> [project-s] 音声コンテキストとトランスポートを直接扱う形にして、音声をBlobで保持するようにする

src/components/AccentPhrase.vue, src/components/AudioDetail.vue
#1576 で`<div>`を`AccentPhrase.vue`内に移動する必要がある可能性が出てきました。
変更規模の確認のため、ひとまずDraft PRを送りたいと思います。
- #1576
=> divタグを`AudioDetail.vue`から`AccentPhrase.vue`へ移動

src/components/AudioAccent.vue, src/components/AudioInfo.vue, src/store/utility.ts
previewSliderHelperで使われているマジックナンバーが使用されたパラメーターを、ひとまとまりのデータとして統合し、統合した値を各ファイルに適用しました。
ref #1244
=> AudioInfoコンポーネントに表示されるパラメータの初期値や範囲を構造化する 

public/qAndA.md
=> Q&AにUbuntu 版のインストール先を追加

src/components/Sing/CharacterMenuButton.vue, src/components/Sing/ScoreSequencer.vue, src/components/Sing/SequencerNote.vue, src/components/Sing/SingerPanel.vue, src/components/Sing/ToolBar.vue, src/helpers/singHelper.ts, src/store/singing.ts, src/store/type.ts, src/views/SingerHome.vue, tests/unit/store/Vuex.spec.ts
以下を行います。
- `state.score`の`undefined`チェックを削除
- `engineId`、`styleId`を`Singer`型で持つようにする
- `Tempo`型の`tempo`を`bpm`に変更
- スコア設定時に`CLEAR_SELECTED_NOTE_IDS`を行うようにする
- `selectedNoteIds`の設定時に`noteIds`のチェックを行うようにする
- リファクタリング
=> [project-s] データ構造の整理とリファクタリング

public/updateInfos.json
バージョン0.14.10にアップデートします。
- https://github.com/VOICEVOX/voicevox/pull/1652
=> [release-0.14] to 0.14.10

src/components/AudioDetail.vue, src/store/audio.ts, src/store/type.ts
タイトル通り。
- ref: #457 
（なし）
（なし）
=> 複数選択：イントネーションのリセットを複数選択対応

src/components/Sing/ScoreSequencer.vue, src/components/Sing/SequencerPhraseIndicator.vue, src/store/singing.ts, src/store/type.ts
レンダリング中の範囲を表示する機能を追加します。
また、以下も行います。
- ノートの数とモーラの数が一致しない場合に例外をスローしないように変更
- レンダリング時にPhraseのソートを行っていなかったので修正
- リファクタリング
https://github.com/VOICEVOX/voicevox/assets/62321214/9b37ecef-4c94-428b-9365-643c00d71f6b
=> [project-s] レンダリング中の範囲を表示する機能を追加

src/infrastructures/AudioRenderer.ts, src/views/SingerHome.vue
シンセにフィルターを追加して聞きやすい音にします。
また、以下も行います。
- オプション周りの修正
- 全体の音量を0.3から0.6に変更
=> [project-s] フィルターの追加とオプション周りの修正

build/splitNsisArchive.js
↓ こちらのissueによりwarningになっているbuildファイルを修正したPRになります。
- #1513
ref #1513
=> buildファイルの比較を緩い等価比較に変更

.github/workflows/test.yml, src/components/AudioCell.vue, src/components/CharacterButton.vue
タイトル通り。
- close: #1674 
https://github.com/VOICEVOX/voicevox/assets/59691627/cf05548a-782f-4f25-8e39-6a236cbb1a2b
（なし）
=> 複数選択：選択中の背景を濃くする

src/helpers/singHelper.ts, src/infrastructures/AudioRenderer.ts, src/store/singing.ts
以下を行います。
- 即座にノートオン・ノートオフする場合は`"immediately"`を指定するようにする
- ノートオンで長さを指定した場合はノートオフも一緒にスケジュールするようにする
- 汎用的なクラス・関数を`singHelper.ts`に移動
- リファクタリング
=> [project-s] シンセ周りのリファクタリング

.github/workflows/build.yml, public/updateInfos.json
* キャラクター「小夜」「ずんだもん」「もち子さん」「青山龍星」のスタイルを追加・更新
=> [release-0.14] to 0.14.11

src/components/Sing/ScoreSequencer.vue, src/components/Sing/SequencerNote.vue
ノートを右クリックでコンテキストメニューが表示されるようにして、
「削除」をクリックでノートが削除されるようにします。
また、ノートの端の判定の修正なども行います。
=> [project-s] ノートを右クリックでコンテキストメニューが表示されるようにする

src/components/AudioCell.vue, src/components/AudioDetail.vue, src/composables/useModifierKey.ts, tests/unit/composable/useModifierKey.spec.ts
タイトル通り。ついでに押したままフォーカス外すと押されたまま判定になるのも直してます。
（なし）
（なし）
（なし）
=> Refactor: 修飾キーのcomposableを追加

src/components/help/UpdateInfo.vue
ワーニングが出ていたので修正します。
相当前から出ていたはず…
=> fix: 追加エンジンでのUpdateInfoの型エラーを修正

.github/workflows/build.yml, public/updateInfos.json
Mac版が動かない問題を解決しました。
- https://github.com/VOICEVOX/voicevox_engine/issues/1022
=> [release-0.15] to 0.15.1

src/views/EditorHome.vue
先程のmainブランチのマージにミスがあったので修正です･･･。
流石にテストの結果くらいは待とうと思います･･･。
=> [project-s] #1743 のマージミスを修正

eslint-plugin/no-strict-nullable.md
#1752 で発生している[lintのエラー](https://github.com/VOICEVOX/voicevox/actions/runs/7642727596/job/20823042912#step:7:15)を修正します．
=> fix from markdownlint

.github/workflows/build.yml
0.16-preview.0のエンジンを用いて、エディタ0.16をとりあえずビルドしてみます。
ちょっとすぐマージさせていただきます 🙇
=> 0.16をとりあえずビルドしてみる

src/sing/viewHelper.ts
singタイプのスタイルの表示でエラーが出ていたので修正します。
=> singタイプのスタイルの表示でエラーが出るのを修正

src/store/audio.ts
タイトル通りです。
（なし）
（なし）
e2eの起動テストにマルチエンジン環境を入れても良いかも？
=> Fix: 歌声対応してないエンジンからsingerを取ろうとするのを修正

src/components/base/BaseButton.vue, src/components/base/BaseDocumentView.vue, src/components/base/BaseRowCard.vue, src/components/base/BaseScrollArea.vue, src/components/template/HelpContactInfoSection.vue, src/components/template/HelpHowToUseSection.vue, src/components/template/HelpOssCommunityInfoSection.vue, src/components/template/HelpOssLicenseSection.vue, src/components/template/HelpPolicySection.vue, src/components/template/HelpQAndASection.vue, src/components/template/HelpUpdateInfoSection.vue, src/styles/_index.scss, src/styles/new-colors.scss
新しい色変数用のscssファイルを作成し、これまでリデザインしてきた箇所のUIでの色の指定にそれを用いるよう変更しました。それにより、新デザイン部分がダークモードに対応しました。
=> 新しい色変数の作成（リデザイン後のUI部分のダークモード対応）

src/components/Sing/CharacterMenuButton.vue, src/components/Sing/CharacterPortrait.vue, src/components/Sing/ScoreSequencer.vue, src/components/Sing/SequencerNote.vue, src/components/Sing/ToolBar.vue, src/store/singing.ts, src/store/type.ts
getter（`SELECTED_TRACK`）でトラックを取得するようにします。
close #1800
=> getterでトラックを取得するようにする

src/components/Talk/AudioInfo.vue
音高などの色々な入力欄を入力した際、全角数字や一部記号から半角数字や記号へ変換する
ref #1729
=> Add: 入力欄の全角を半角に変換する機能の追加

src/components/Sing/SingEditor.vue
=> Fix: 必要なセットアップが行われていなかったのを修正

.github/workflows/build.yml
upload_artifactの判定フラグが間違えていて、ビルド時間が15分から20分ぐらい伸びていることに気づいたのでついでに修正しておきます。
=> [release-0.17] upload_artifactの判定フラグが間違えているので修正

src/components/Dialog/SettingDialog.vue
- https://github.com/VOICEVOX/voicevox/issues/1944
の解決プルリクエストです。
もしかしたら環境によってはうまく表示されなかったりするかもしれないので実験的機能としています。
- https://github.com/VOICEVOX/voicevox/pull/1828
close #1944 
ついでに機能追加アナウンスもしようと思います！
=> ピッチ表示機能を開発版のみ機能から実験的機能に

public/updateInfos.json
追加を忘れてしまっていたので追加です 🙇 
Xでポストする直前に気づいたので、急遽エンジン側もスクショを撮影させていただきました 🙇 
https://twitter.com/voicevox_pj/status/1771376267444854821
=> [release-0.18] 0.18.0にエンジンコントリビュータも追加

src/store/singing.ts
次のハミングキャラクター追加アプデはマイナーバージョンをあげずに 0.18.1 でリリース予定です。
そのため #1957 のバグ修正のみをマージしてリリースします。
#1957
あまり変わらない気がしますが FF mergeします
=> [release-0.18] #1957 をcherry-pick

src/store/singing.ts
MusicXML・UST読み込み時に歌詞のtrimを行うようにします。
close #1987
=> Fix: MusicXML・UST読み込み時に歌詞のtrimを行うようにする

src/store/singing.ts
- https://github.com/VOICEVOX/voicevox/pull/2015
で声量調整のパラメータ適用を忘れていたので適用するようにしました。
#2015
結構危うかったので注意喚起と課題点まとめのためにissue作ってみました。
- https://github.com/VOICEVOX/voicevox/issues/2018
=> 声量調整が適用されていないのを修正

public/updateInfos.json
このPRはアプデ情報の更新だけです。
マージして0.19.1をリリースしようと思います。
=> [release-0.19] to 0.19.1

src/store/type.ts
`SingingStoreState`が重複していたので削除します
=> SingingStoreStateが重複していたので片方削除

src/components/Sing/ToolBar/EditTargetSwicher.vue
=> ソング：編集対象切り換えにQBtnToggleを使うようにする

src/components/Sing/SingEditor.vue, src/components/Sing/ToolBar/ToolBar.vue, src/sing/domain.ts, src/sing/storeHelper.ts, src/store/project.ts, src/store/singing.ts, src/store/type.ts, tests/unit/lib/selectPriorPhrase.spec.ts
以下を行います。
- `Score`型、`isValidScore`、`SET_SCORE`を削除
- `SET_TPQN`、`SET_TEMPOS`、`SET_TIME_SIGNATURES`、`SET_NOTES`を追加
- リファクタリング
ref #1971
=> ソング：Score型をなくす

src/components/Sing/SequencerNote.vue, src/components/Sing/SequencerPitch.vue, src/sing/utility.ts, src/sing/viewHelper.ts
ピッチ編集モードでテンポ変更を行うとユーザーが描いたピッチがずれるのを修正します。
また、以下も行います。
- ピッチ編集モードでノートの端や縁の色が変わらないようにする
- リファクタリング
close #2096
=> ピッチ編集モードでテンポ変更を行うとユーザーが描いたピッチがずれるのを修正

.github/workflows/build.yml, public/updateInfos.json
=> [release-0.19] to 0.19.2

.github/actions/setup-environment/action.yml, .github/workflows/build.yml, .github/workflows/check_version.yml, .github/workflows/labeler.yml, .github/workflows/release_latest_dev.yml, .github/workflows/test.yml, .github/workflows/typos.yml, _typos.toml, docker-compose.yml
すべてのアクションのバージョンを最新バージョンにアップグレードしました
- 他のアクションは問題ありませんが、[github/issue-labeler@v3](https://github.com/github/issue-labeler/releases/tag/v3.0)において以下のようなブレイキングチェンジが発生しましたが、無視しても問題ないでしょうか？
> Breaking change: Issue labels that do not match a regex will no longer be removed by default unless you set sync-labels: to 1
- 「create-ci/typos」アクションでエラーが発生し、修正するためのコミットも含めました。
=> Bump actions

src/components/Sing/CharacterMenuButton/CharacterSelectMenu.vue, src/components/Sing/CharacterMenuButton/MenuButton.vue, src/components/Sing/SingerIcon.vue
サイドバーのためにコンポーネントを分離します。
#1971 の変更です。
- ref: #1906 
- ref: #1971
（なし）
（なし）
=> マルチトラック：コンポーネントを分離する

.github/workflows/chromatic.yml
まだダメで、差分が必要だからdepth 0をつける必要がありそうでした 🙇 
- https://github.com/VOICEVOX/voicevox/pull/2140
- https://github.com/VOICEVOX/voicevox/pull/2145
=> fix: chromaticのgithubactionsのエラー直す２

src/helpers/fileHelper.ts, src/store/audio.ts
`GENERATE_AND_CONNECT_AND_SAVE_AUDIO`、ついでに`CONNECT_AND_EXPORT_TEXT`のファイルエラーメッセージを表示できるようにします。
- https://github.com/VOICEVOX/voicevox/issues/2102
の解決です。
close #2102
=> 「音声をつなげて書き出し」のファイルエラーメッセージを表示する

src/components/Sing/ScoreSequencer.vue, src/components/Sing/SequencerNote.vue, src/components/Sing/SequencerPhraseIndicator.vue, src/components/Sing/SequencerPitch.vue, src/components/Sing/SequencerShadowNote.vue
シーケンサー周り（ノート、ピッチ）をマルチトラックに対応させます。
- ref: #1906
（なし）
=> マルチトラック：シーケンサー周りを対応

src/components/Dialog/ImportSongProjectDialog.vue
- https://github.com/VOICEVOX/voicevox/pull/2184
=> マルチトラック：detailsタグのコンフリクト解消ミス修正

README.md
- https://github.com/VOICEVOX/voicevox/pull/2112
でエンジンパスが変わっていたので追従します。
=> doc: READMEのmacOS向けのエンジンパスの案内を追従

.github/actions/download-engine/action.yml, build/codesign_setup.bash
curlが結構エラーになってるので、リトライ引数を入れてみました。
結構Github releasesからのダウンロードがエラーになって、↓みたいになります。
- https://github.com/VOICEVOX/voicevox/actions/runs/10348593487/job/28641147627
aliasにしようかと思いましたが、そんなに数多くないのでコピペにしておきました。
あとVOICEVOX ENGINEもたまにエラーになるので、そっちにもPRしようと思います。
=> fix: curlがエラーになるのでリトライを入れる

.github/workflows/chromatic.yml
- https://github.com/VOICEVOX/voicevox/issues/2241
の解決PRです。
nodeのメモリを増やしたらとりあえず通ることを確認しました。
- https://github.com/Hiroshiba/voicevox/actions/runs/10495393558
resolve #2241 
chromatic側こんな感じ
https://www.chromatic.com/build?appId=667d9c007418420dbb5b0f75&number=47
もともとメモリは7GB割り当てられていたっぽいけど、7GBで落ちるのはなかなかな気がしなくもない･･･。
=> add: Chromatic用にNodeのメモリを増やす

docs/細かい設計方針.md, src/domain/defaultEngine.ts, tests/unit/backend/common/configManager.spec.ts, tests/unit/domain/defaultEngine/defaultEngine.spec.ts, tests/unit/domain/defaultEngine/latestDefaultEngineInfos.json
[エディタとエンジン分離タスクのタスクの第二弾](https://github.com/VOICEVOX/voicevox/issues/1194#issuecomment-2296599278)です。
デフォルトエンジン更新情報の仕様とスキーマを書いてみました。
また実際にjsonをfetchする関数も作りました。現状テストでのみ使っています。
一応web上にjsonファイルは[作ってみました](https://raw.githubusercontent.com/VOICEVOX/voicevox_blog/master/src/data/latestDefaultEngineInfos.json)が、まだ実際にfetchするコードは書いてません。
次のPRで取り組む予定です。
ref #1194 
マルチエンジン周りに詳しい方をレビュワーにアサインさせていただきました。
もしお時間あればコメントいただけると心強いです！ 🙏 
@sabonerune さんもメインプロセスや分離周り詳しいので、もしよかったら見ていただけると･･･！
=> デフォルトエンジン更新情報jsonの仕様を書き、スキーマを定義

.github/workflows/chromatic.yml
ChromaticのTurboSnap機能を有効にしてみました。
https://www.chromatic.com/docs/github-actions/#enable-turbosnap
Chromatic側でStoryのスクショを撮っているのですが、これで変更があった部分だけ更新されるようになるらしいです。
高速になるのと、あと無料のスクショ数は月5000枚なので節約になるかなと。
ちなみにスキップされるのではなく、価格が1/5になるという感じっぽい？
https://www.chromatic.com/docs/turbosnap/#pricing
=> add: TurboSnapを有効にする

README.md
README内のライブラリをインストールする方法を明示的にしました。
もともと書いてあったんですが、ちょっと分かりにくかったので見出しを作るようにしました。
=> Docs: 依存ライブラリをインストール方法を明示

src/backend/electron/manager/vvppManager.ts
=> fix: VVPP削除エラーのメッセージが間違っていたので修正

.github/workflows/build.yml
- https://github.com/VOICEVOX/voicevox/pull/2322
で出してマージしたPRですが、再施行すると問題なく通ったのと、修正方法がちょっと強引だったと思うので、一旦revertするのが良さそうに思いました。
一旦落ち着いてから治すので良さそうかなと。
まあでもまあまあテストはコケてそうでした。
- https://github.com/VOICEVOX/voicevox/actions/workflows/build.yml?query=branch%3Amain+is%3Afailure
=> Revert "hotfix: リリースがコケるのをなおす

.github/workflows/build.yml, public/updateInfos.json
=> merge 0.21.1

.github/workflows/build_preview_pages.yml, src/backend/browser/sandbox.ts, src/store/utility.ts
日付フォーマットの月の部分が１月ズレているのを修正します。
あとプレビューのWorkflowにコメントを追加します。
- fix: https://twitter.com/Eternal_Zunda/status/1853304275922981060
（なし）
（なし）
=> Fix: ファイル名パターンのmonthが1月ズレているのを修正

package-lock.json, package.json
なぜかローカルで起動しなかった（起動はする？けどテストが始まらなかった）のでアップデートしてみました。
動いた気がします。
=> Update: Playwrightのバージョンを1.48.2に更新

README.md
タイトル通りです。
Chromatic、捨てても良いかも？
（なし）
（なし）
（なし）
=> preview-pagesをREADMEに追記する

.github/workflows/build.yml
=> macos-12 を macos-13 に置き換えるプルリクエスト

tests/e2e/browser/スクリーンショット.spec.ts
TODOコメントのスペルミスを修正しました。
すみません。。。。。
=> fix: TODOコメントのスペルミスを修正

public/updateInfos.json
バグ修正を反映した0.22.1バージョンリリースのための変更です。
このPRではアプデ履歴を更新するだけです。あとは0.22.1を作るGithub Actionsを回せば良いはず。
- https://github.com/VOICEVOX/voicevox_project/discussions/57#discussioncomment-11637902
=> [release-0.22] to 0.22.1

.github/workflows/build.yml, public/updateInfos.json
バージョン0.22.2にアップデートします。
- https://github.com/VOICEVOX/voicevox_project/discussions/57#discussioncomment-11660076
=> add: [release-0.22] to 0.22.2

.github/actions/setup-environment/action.yml
動かなくなってそうなvendoredのキャッシュを削除しました。
たぶんなくてもそんなに速度とか変わらない＆メンテできないので消しとくのが良さそう･･･？
=> add: 動かなくなってそうなvendoredのキャッシュを削除

tests/unit/domain/hotkeyAction.spec.ts
mainのCIが落ちてるのを直します。
（なし）
（なし）
（なし）
=> Fix: mainのCIが落ちてるのを直す

.github/workflows/build.yml, public/updateInfos.json
バージョン0.22.3にアップデートします。
（何かに気づいてもSNSやDiscordで言及せず見守ってください 🙏 ミスっぽいものの指摘は大歓迎です！）
- https://github.com/VOICEVOX/voicevox_project/discussions/57#discussioncomment-11686197
=> add: [release-0.22] to 0.22.3

.github/workflows/build.yml, public/updateInfos.json
=> add: merge 0.22.3

.github/workflows/merge_gatekeeper.yml, .github/workflows/test.yml
マージキューを追加します。
- ref: https://github.com/VOICEVOX/voicevox_project/issues/53
（なし）
（なし）
=> Add: マージキューを追加

.github/workflows/merge_gatekeeper.yml
=> Fix: フォークからだとgatekeeperが正しく動かないのを治す

.github/actions/download-engine/action.yml, .github/workflows/build.yml, .github/workflows/test.yml
ダウンロードしたエンジンのrunの権限を変更する部分のリファクタリングします。
実行前に権限を付与するのではなく、ダウンロード時に権限を付与するようにします。
- https://github.com/VOICEVOX/voicevox/pull/2442
から切り出しました
マージされた後、macOS辺りで実際に起動できるかのチェックが必要。
=> refactor: ダウンロードしたエンジンのrunの権限を変更する部分のリファクタリング

src/sing/stateMachine/sequencerStateMachine.ts, src/sing/utility.ts
以下を行います。
- SelectNotesWithRectStateを追加
- IdleStateを変更（変更し忘れていたので）
- リファクタリング
=> [project-sequencer-statemachine] SelectNotesWithRectStateを追加してIdleStateを変更

src/sing/stateMachine/sequencerStateMachine.ts
DrawPitchStateの追加とIdleStateの変更を行います。
=> add: [project-sequencer-statemachine] DrawPitchStateを追加

public/updateInfos.json
バージョン 0.22.4 にアップデートします。
- https://github.com/VOICEVOX/voicevox_project/discussions/57#discussioncomment-11833538
=> add: [release-0.22] to 0.22.4

public/updateInfos.json, src/store/audio.ts
=> feat: merge 0.22.4

package.json
package.jsonのscripts欄を整理します。
（なし）
（なし）
（なし）
=> chore: scriptsを整理

src/composables/useSequencerStateMachine.ts, src/sing/sequencerStateMachine/common.ts, src/sing/sequencerStateMachine/states/addNoteState.ts, src/sing/sequencerStateMachine/states/drawPitchState.ts, src/sing/sequencerStateMachine/states/drawPitchToolIdleState.ts, src/sing/sequencerStateMachine/states/editNotesToolIdleState.ts, src/sing/sequencerStateMachine/states/erasePitchState.ts, src/sing/sequencerStateMachine/states/erasePitchToolIdleState.ts, src/sing/sequencerStateMachine/states/moveNoteState.ts, src/sing/sequencerStateMachine/states/resizeNoteLeftState.ts, src/sing/sequencerStateMachine/states/resizeNoteRightState.ts, src/sing/sequencerStateMachine/states/selectNotesToolIdleState.ts, src/sing/sequencerStateMachine/states/selectNotesWithRectState.ts
=> feat: [project-sequencer-statemachine] CursorStateの更新を行うようにする

src/composables/useSequencerStateMachine.ts, src/sing/sequencerStateMachine/common.ts, src/sing/sequencerStateMachine/states/addNoteState.ts, src/sing/sequencerStateMachine/states/drawPitchState.ts, src/sing/sequencerStateMachine/states/erasePitchState.ts, src/sing/sequencerStateMachine/states/moveNoteState.ts, src/sing/sequencerStateMachine/states/resizeNoteLeftState.ts, src/sing/sequencerStateMachine/states/resizeNoteRightState.ts, src/sing/sequencerStateMachine/states/selectNotesWithRectState.ts, src/sing/viewHelper.ts
nowPreviewingを無くして、previewModeを追加します。
=> feat: [project-sequencer-statemachine] previewModeを追加

src/domain/defaultEngine/envEngineInfo.ts
タイトル通りです。
- ref: #2521 
（なし）
（なし）
=> fix: getDefaultEngineInfosEnvの条件分けを修正

src/backend/electron/main.ts
ただのリファクタリングです。
すごい長いmain.ts内でletだと危ないのでconstに変えてみました。
=> refactor: electron/main.tsのappDirPathと__staticをカプセル化

.github/workflows/build.yml, public/updateInfos.json
バージョン0.23.0に更新します。
- https://github.com/VOICEVOX/voicevox_project/discussions/60
=> build: to 0.23.0

src/components/Dialog/AllDialog.vue, src/components/Dialog/PresetManageDialog.vue, src/components/Talk/AudioInfo.vue, src/store/type.ts, src/store/ui.ts
=> fix: プリセット管理ダイアログをSET_DIALOG_OPENで開くように変更する

src/store/singing.ts, src/store/type.ts
FrameAudioQueryを生成する処理と音声合成の処理をaction化します。
また、以下も行います。
- `FETCH_SING_FRAME_F0`と`FETCH_SING_FRAME_VOLUME`で発生したエラーをロギングするように
- エンジンがreadyかどうかチェックする処理を追加
=> refactor: FrameAudioQueryの生成と音声合成の処理をaction化

src/mock/engineMock/index.ts
`singFrameF0`のモックを追加します。
- https://github.com/VOICEVOX/voicevox/pull/2651
=> test: `singFrameF0`のモックを追加

.github/workflows/build.yml
- https://github.com/VOICEVOX/voicevox/pull/2659
で漏れていたものの修正です
=> fix(build): [release-0.23] Linux Nvidia ビルドのコメント忘れ

.github/workflows/build.yml
Linux Nvidia GPU版がビルドされないようにしていたのを、全ビルドが実行されるように戻します。
- https://github.com/VOICEVOX/voicevox/issues/2661
=> build: [release-0.23] Linux NVIDIA の設定を復元

src/backend/electron/renderer/backendApiLoader.ts, src/backend/electron/renderer/preload.ts, src/components/Talk/TalkEditor.vue, src/type/preload.ts
- https://github.com/VOICEVOX/voicevox/issues/2683
を修正しました。
応急処置的な解決策かもしれません。
ちょっと @sevenc-nanashi さんに微妙そうだったら、FIXMEコメントつけようと思います 🙇 
close #2683
=> fix: ドラッグアンドドロップでvvprojファイルが開けないバグを修正

src/store/singing.ts
タイトル通りです。
- ref: #2693 
（なし）
問題自体はないけど、Proxyを引きずり回したくないので...
=> chore: importedTrackにcloneWithUnwrapProxyをかける

public/updateInfos.json
0.24.1アップデートをします。
#2693 と #2694 をcherry-pickしています。
- https://github.com/VOICEVOX/voicevox_project/discussions/64#discussioncomment-13619132
- #2693 
- #2694
=> build: [release-0.24] to 0.24.1

tests/e2e/browser/mockUtility.ts, tests/e2e/browser/音声書き出し.spec.ts
音声書き出し時にエラーが出るはずですが、そのテストがなかったので書いてみました。
- https://github.com/VOICEVOX/voicevox/issues/1561
=> test: 音声書き出し機能のエラーハンドリングテストを追加

build/afterPack.ts, build/electronBuilderConfig.ts, package.json, pnpm-lock.yaml
セキュリティのベストプラクティスに基づきElectronの機能や制限を有効化/無効化します。
[19. どの Fuse を変更できるか確認する](https://www.electronjs.org/ja/docs/latest/tutorial/security#19-%E3%81%A9%E3%81%AE-fuse-%E3%82%92%E5%A4%89%E6%9B%B4%E3%81%A7%E3%81%8D%E3%82%8B%E3%81%8B%E7%A2%BA%E8%AA%8D%E3%81%99%E3%82%8B)
fuseの関連ドキュメント
- [Electron Fuse](https://www.electronjs.org/ja/docs/latest/tutorial/fuses)
- [ASAR 整合性](https://www.electronjs.org/ja/docs/latest/tutorial/asar-integrity)
- [electron-builderのドキュメント](https://www.electron.build/tutorials/adding-electron-fuses)
なぜか`pnpm-lock.yaml`の`vue-component-type-helpers`が書き換わりました。
原因が分からないのでインストールは慎重に行うべきな気がします。
次の機能はリスクやデメリットがあるのでこのPRで有効化していません。
- [cookieEncryption](https://www.electronjs.org/ja/docs/latest/tutorial/fuses#cookieencryption)
そもそも現在のコードではCookieを使っていないという認識です。そのため有効化する意味が薄いような気がします。 …
=> feat: `@electron/fuses`を使用してセキュリティを向上させる

vite.config.ts
タイトル通りです。
- ref: #2761 
（なし）
（なし）
=> chore: electronのパスを得るときの挙動を解説する
