VOICEVOX/voicevox

src/store/audio.ts

市販の音声合成ソフトでは、音声ファイルと同じ名前でセリフ本文をテキストファイルに保存する機能があることが多いです。
その動作に倣い、BOM 付き UTF-8 でテキストファイルを作成する機能を追加します。
この機能があると、動画編集ソフトで字幕として取り込めるようになることがあります。
（例: [YMM4](https://manjubox.net/ymm4/faq/%E3%82%86%E3%81%A3%E3%81%8F%E3%82%8A%E3%83%9C%E3%82%A4%E3%82%B9/%E5%A4%96%E9%83%A8%E3%81%AE%E9%9F%B3%E5%A3%B0%E5%90%88%E6%88%90%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%B3%E3%81%A7%E4%BD%9C%E6%88%90%E3%81%97%E3%81%9F%E9%9F%B3%E5%A3%B0%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%9F%E3%81%84/)）

音声ファイルと同じ名前でテキストファイルを保存する

---

src/background.ts
src/electron/preload.ts
src/store/audio.ts
src/type/preload.d.ts

ファイル名が `001.wav` だと後でファイルの内容がわかりづらくなってしまうので、
`001_四国めたん_こんにちは.wav` のような `通し番号_キャラ名_セリフ.wav` の形式になるように変更しました。
セリフが長い場合は `001_四国めたん_長いセリフを喋って….wav` のように9文字＋ "…" の形式になります。
また、`GENERATE_AND_SAVE_AUDIO` で `filePath` を省略したときに表示される「名前を付けて保存」のダイアログでも、
同じ形式のファイル名が予め入力されている状態になるよう変更しました。

保存するファイル名を `001_四国めたん_こんにちは.wav` のようなものに変更する

---

src/background.ts
src/electron/menu.ts

close: https://github.com/Hiroshiba/voicevox/issues/23
機能の充実に連れて、UIの上段のバーにボタンが増えていくことが予想される。
そのため、使われる頻度の低い機能の実装箇所であったり、ショートカットキーでの操作などが実装しやすいMenuを提供し、そこに機能を追加していくことはUIやUXの観点で良いだろうと判断した。
今回そのMenuに、使われる頻度は非常に低い機能であると考えられる音声合成エンジンの起動モードの変更機能を実装した。
今回は使われる頻度が低い機能と判断しMenuに実装したが、一つしかMenuItemがなく逆に目立ってしまっている
これがアプリケーションの表示的なデザインとして妥当であるかレビューをお願いしたいです
今回エンジンというMenuLabelにした理由としては
https://github.com/Hiroshiba/voicevox/issues/16
MenuにEngineの状態に応じてEngineをリスタートする機能なども追加できるのではと考えたり、
またEngineの待ち受けのURL（外部GPUマシンなど）の変更の機能（あったらいいなと思っているのですが）がそのItemにまとめられるのではと考えたためです

Menuから音声合成エンジンの起動モードを変更出来るようにする

---

src/store/audio.ts

テキストファイルからセリフを読み込む機能において、改行で区切るとキャラクター名が正しく設定されないことに気づきました。
改行コードがCRLFである場合を見落としていたことが原因だったので、区切り文字に"\r\n"を追加しました。

セリフ読み込み時のバグを修正

---

src/background.ts
src/electron/menu.ts

#29 でカスタムメニューが追加されたため、開発時にリロードなどの機能が使えなくなっていました。
よって、開発時にはelectronのデフォルトメニューがカスタムメニューと一緒に表示されるようにしました。

開発時にelectronのデフォルトメニューを表示する

---

src/components/AudioDetail.vue

音声を書き出すためのボタンを左下に追加します。
せっかくコンパクトになった左下の領域にボタンを追加するのは心苦しいのですが、
一番適切な場所はここだと思うので左下にしました。
このボタンは再生に比べると使用頻度が低いはずなので、大人しめのデザインにしました。
Close #47

音声を１つだけ書き出すボタンを追加

---

src/store/audio.ts

音声を一つだけ保存するボタンを押した際、元々のコードでは
1. `GENERATE_AUDIO` が終わるまで待機
2. 「名前を付けて保存」のダイアログを表示する
という処理の流れになっています。
これだとボタン押してもすぐにダイアログが出ないのでレスポンスが悪く感じますし、
人間がダイアログで必要な操作を終えるには速くても数秒程度かかるはずなので、
この時間を利用して裏で `GENERATE_AUDIO` を進めておいたほうが、待ち時間を減らせます。
そこで `GENERATE_AUDIO` をすぐに `await` せずに一旦 `Promise` で受け取り、あとで `await` するように変更しました。
ここは `Promise.all` が使えそうなシーンですが、`??=` 演算子のエレガントな処理に悩んだので単純な方法にしました。

音声を一つだけ保存する時の GUI レスポンスを改善

---

src/background.ts

デフォルトだとシステム側の設定によってメニューバーの色が変わってしまうようなので、常にライトテーマを使用するようにしました
UI全体をダークテーマに対応させようかとも考えましたが、タイトルバーはどうあがいても色を変えられないようです electron/electron#27100
フレームレスウィンドウにしてタイトルバーを自作するという手もありますが、そうすると今度はメニューバーも自作することになってしまうのでかなり大きな変更になってしまいます

システム設定に関わらずライトテーマを適用する

---

README.md

https://github.com/Hiroshiba/voicevox/issues/37
`npm install`から`npm ci`にすることによって、package-lock.jsonの差異が生じないようにする

環境構築で使うコマンドを変更

---

src/background.ts
src/electron/preload.ts
src/store/index.ts
src/type/ipc.d.ts
src/type/preload.d.ts

現在、以下の様なプロジェクトを読み込むと、バリデーションは通りますが、`Unhandled Error`が出ます。([error.log](https://github.com/Hiroshiba/voicevox/files/6988194/error.log))
`audioItems`に`characterIndex`が存在しないプロジェクト
```json
{
"appVersion": "0.3.1",
"audioKeys": [
"0f2f6793-27a7-4379-bc99-3be76a189196"
],
"audioItems": {
"0f2f6793-27a7-4379-bc99-3be76a189196": {
"text": "プロジェクト",
}
}
}
```
view側の複数のコードが`characterIndex`が`undefined`でないことを前提に書かれていることが原因だと思います。
通常なら問題ありませんが、#65 でプロジェクトファイルのキー`charactorIndex`が`characterIndex`に修正されたので、バージョンを上げるとユーザーが遭遇する可能性があります。
よって、プロジェクト読み込み時、`characterIndex`を必須パラメータとし、バリデーションでエラーを出す + エラーをダイアログで通知するように変更しました。

プロジェクト読み込み時の問題を修正

---

.github/workflows/typos.yml
README.md
_typos.toml

https://github.com/Hiroshiba/voicevox/pull/65#issuecomment-898911701 の実装です．
誤判定の回避は https://github.com/crate-ci/typos#false-positives のように ``_typos.toml``を編集します

GitHub Actionsにタイポ検知を追加

---

src/components/AudioDetail.vue

close #79 
マウスカーソルがSliderの上にいるときに音高の値を表示するようにしました。
該当IssueではQSliderのlabelをCSSで変更して利用してはどうか、という事でしたが、値の桁数が多くなると隣のSliderに被ってしまうため、Slider上部に表示するようにしてみました。
音高の表示に関しては完全にViewの見た目のみの状態のためdata/methodsを使っていますが、Storeに追加してsetupを使うべき、等があれば指摘いただけると助かります

音高の値をSliderの上に表示する

---

src/App.vue
src/main.ts
src/plugins/ipcMessageReceiverPlugin.ts
src/type/ipc.d.ts
src/type/preload.d.ts

現時点Windowにelectronが見えるので、.vue内で呼びたくなってしまうけれども、View内に置いてしまうと将来的にテストが困難になる恐れがあるため.vueファイルから排除しておきたい。
pluginという形で依存を一か所にまとめることが出来るのではと考えこのような実装を行った。
vueのplugin機構を使っているのでpluginsというディレクトリを掘りましたが、今後voicevox自体がplugin機構みたいのを実装したらディレクトリ名が被ってどうかなと思ったので、この辺りの塩梅のレビューもお願いしたいです。

mount前にelectronへの依存を一箇所に詰め込む

---

src/main.ts
src/styles/_index.scss

今までQuasarのスタイルは `_index.scss` で読み込んでいましたが、これを複数のvueファイルで呼んでいたため、重複して適用されていました
見た目上は問題ありませんが、DevToolsで見た時に同じスタイルが複数適用されていて邪魔だったので1度だけ読み込まれるようにしました

Quasarのスタイルが重複して適用されていたのを修正

---

src/background.ts

環境変数に`NODE_ENV`と`IS_TEST`の似たような役割の変数が存在したので統合しました。
また、`electron`のdeprecatedに指定されている機能である[`RemoteModule`](https://www.electronjs.org/docs/api/remote)が使用されていなかったので無効化しました。
ロードする拡張機能をVue2用のものからVue3用へと差し替えました。この変更により開発者ツールのタブからViewに提供されている情報を見ることができるようになります。

環境変数の統合および拡張機能の有効化

---

.github/workflows/typos.yml
src/components/AudioDetail.vue

- typosのアップデート
- splitの過去分詞はsplitなので修正

Typos update

---

src/components/AudioCell.vue
src/store/audio.ts

#116 を他の方が担当されそうと言うことで、楽が出来るようこちらで直していた部分を上げておきます。
修正したのは、
* テキスト編集時、`v-model`でTwo-Wayバインディングされていたために`produceWithPatches`で返ってくるPatchが空になっていた問題の修正
* AudioCellの初期化処理で`FETCH_AUDIO_QUERY`をdispatchしていたためにRedoでセルの追加を戻すと以降のヒストリが消える(FETCH_AUDIO_QUERYによってヒストリが上書きされてしまう)問題の修正
の2点になります。
この修正により、一部動作が変わり、
* Enterを押したり、フォーカスを外さなくてもアクセントの生成が行われる
* 逆にこれらの操作ではアクセントの生成は行われなくなる
* AudioCell追加時には`FETCH_AUDIO_QUERY`はdispatchされず、`setAudioText`の呼び出し、または`PUT_TEXTS`がdispatchされるまで`audioItem.value.query`は空のまま
* `PUT_TEXTS`は最後にまとめて`FETCH_AUDIO_QUERY`をdispatchするように
となります。
使用感が若干変わるのと、AudioCell周りのUndo/Redoの実装の仕方が変わるため、逆に障害になりそうであればCloseしていただいて問題ありません

Undoヒストリが正しく積まれない/壊れる問題の修正

---

src/background.ts
src/electron/ipc.ts
src/electron/preload.ts
src/type/ipc.d.ts
src/type/preload.d.ts

今までの実装では元からある関数のオーバーロードを足す形で実装していたため、想定外の使われ方をしてもエラーにならず元の型が適用されてanyになるだけでした
TypeScriptの仕様上既存の型を完全に上書きすることは困難であるため、ラッパー関数を作りました

ipcの型をより厳格に

---

src/styles/_index.scss
src/views/Home.vue

ウィンドウボーダー幅を変数で持ち、ずれていた分を修正しました
左右が2pxだったのに対しbottomだけ4pxだったのが気になったので2pxに揃えました
何か理由があって4pxになっていたのであれば戻します

ウィンドウボーダーを変数で持つ

---

build/installer.nsh
vue.config.js

close #160
electron-builderで作ることができるNSISインストーラはカスタマイズできるもののエラーハンドリングをすることは難しいです。
特にショートカット作成などの失敗を検知する方法はありません。
そこで、インストール前にディスクの空き容量をチェックする機能を追加しました。
このPRに含まれる改善を行ったインストーラーのサンプルを以下のGitHub Releaseで公開していますので、ご確認ください。
https://github.com/HyodaKazuaki/voicevox/releases/tag/0.4.1
* インストール確認/空き容量不足のダイアログを追加
以下のIssueで記載したように必要な容量と空き容量を表示し、本当にインストールしてよいか確認するダイアログも追加しました。
https://github.com/Hiroshiba/voicevox/issues/148#issuecomment-904536041
また、インストール前にシステムドライブの空き容量を取得し、空き容量が明らかに不足している場合はエラーダイアログを発生させるようにしました。
* 圧縮オプションを除去
インストーラ作成時の圧縮オプションを`maximum`にしていましたが、以下に記載があるように処理時間の割に効果が殆どないため削除しました。
> `compression` = `normal` “store” | “normal” | “maximum” - The compression level. If you want to rapidly test build, `store` can reduce build time significantly. `maximum` doesn’t lead to noticeable size …

インストール前にディスクサイズを確認する

---

src/background.ts

#183 
見えていませんがelectronのメニューが存在しているため、そのショートカットキーが機能しているようです。
メニューを明示的に削除することで、リロードできなくなります。

リロードのショートカットキーを無効にする

---

src/store/project.ts

現在、プロジェクト読み込み時にはエラー内容にかかわらず、"ファイルフォーマットが正しくありません。"と表示するようになっています。
https://github.com/Hiroshiba/voicevox/blob/39ac97ceda732e02739fb6296525d489d67c70c7/src/store/project.ts#L172-L175
これでは、API取得エラーでもユーザがファイルが正しくないと勘違いしてしまうので、エラーに応じたエラーメッセージに変更します。

プロジェクト読み込み時のエラーメッセージを改善

---

src/App.vue

画像をドラッグ出来てしまい、そのままエクスプローラーにドロップすると立ち絵画像等がファイルとして取得出来てしまうので、画像をドラッグできないように修正しました

画像をドラッグできないように修正

---

src/components/AudioInfo.vue
src/store/audio.ts

音声の前後の無音部分の長さを制御するスライダーを追加
とりあえず0〜2秒（0.05秒刻み）にしています
PRするときにプロジェクトファイル関係を確認していないことに気づいたのでDraftにしています
close #106 
自環境では再生時・保存されたファイルで変更が反映されているのを確認
ほとんど初めて触る言語なので自信がない

無音時間のスライダーを追加

---

package-lock.json
package.json
src/components/AudioCell.vue
src/components/HeaderBar.vue
src/store/audio.ts
src/store/command.ts
src/store/index.ts
src/store/type.ts

#138 のコマンドの主要処理部分のみを含むプルリクエストです。
Commandを一つのMutationとして実装することで、UNDO/REDOの順序を保証しています。非同期処理がコマンドに必要な場合、コマンドの発行前に(Action内で)非同期処理に必要な情報を事前に取得してから、Mutationに渡してください。
immerを用いたUNDO/RODOのOperationの記録の為にState全体のスナップショットを撮るためパフォーマンス上のボトルネックになる可能性が高いです。
例として`REMOVE_AUDIO_ITEM`を`COMMAND_REMOVE_AUDIO_ITEM`として変更しています。
以前の処理を完全に置き換えてはいないのでコメントで`@deprecated`を指定しています。
ref #116

コマンド実装方式の追加

---

src/components/AudioCell.vue
src/components/AudioInfo.vue
src/store/audio.ts
src/views/Home.vue

#233 で追加したコマンドの実装方式を他のプルリクエストに影響の少なそうな非同期的なコマンドに限って移行しました。
移行したコマンドは
`REGISTER_AUDIO_ITEM`
`SET_AUDIO_SPEED_SCALE`
`SET_AUDIO_PITCH_SCALE`
`SET_AUDIO_INTONATION_SCALE`
`SET_AUDIO_VOLUME_SCALE`
`SET_AUDIO_PRE_PHONEME_LENGTH`
`SET_AUDIO_POST_PHONEME_LENGTH`
です。
ref #138
ref #233 
ref #116
`REGISTER_AUDIO_ITEM`は記録すべきでない（コマンドでない）操作も担っていたのでactionとしても残っています。

同期的コマンドの新方式への移行

---

src/components/AudioDetail.vue
src/store/audio.ts

related #196
Issue内部で述べられている件に関する完全な解決策ではないと思われるため、relatedにしてcloseしないようにしています。

アクセントなどを操作したアクセントフレーズ以外のピッチを固定する

---

vue.config.js

`vue.config.js`に`publish`を追加し、publish場所を固定(`installer.nsh`内の`APP_PACKAGE_URL`が、ビルドリポジトリに影響されることなく、固定される)。
さらに、`installer.nsh`内の`APP_PACKAGE_URL`に`version`値として`v`が入ることを抑止(`vPrefixedTagName`オプションを`false`に)
この設定により、どんな環境でビルドされても、nsis-webが見に行くダウンロード元が固定されます。
ref #210 
ref #244

[HOTFIX(for developer)]add publish option (fixed owner and repo, remove version's "v")

---

src/store/project.ts

`kana` プロパティがある vvproj ファイルの読み込みに失敗する

[HOTFIX] add kana as optionalProperties on audioQuerySchema

---

src/components/AudioDetail.vue
src/store/audio.ts

旧コマンドの方式を新コマンドに移行する最小例として`SET_AUDIO_MORA_DATA`を'COMMAND_SET_AUDIO_MORA_DATA'に移行しました。
ref #258
ref #233
ref #116

同期コマンドの新方式への移行例

---

vue.config.js

Electronビルド時に、同梱するVOICEVOX ENGINEのビルド成果物のディレクトリを環境変数から変更できるようにします。
ref #219 
ref #264 
#264 の進め方によっては、VOICEVOX ENGINEのディレクトリを変更するのではなく、VOICEVOX ENGINEを同梱しないようにするオプションを追加するPRを作成するかもしれません。
例えば用途としては、CIの容量制限回避のため、ArtifactにElectronのビルド成果物のみを一度アップロードしてから、別JobでVOICEVOX ENGINEを結合するような形を考えていますが、NSIS側で結合後の7zのハッシュチェックをしていたらできなさそうです..。
GitHub Actionsの容量制限は14GBですが、
VOICEVOX ENGINEのWindows NVIDIA GPU用実行バイナリは、5.5GBあるため、現在の実装では、
コピー元のVOICEVOX ENGINE・Electronビルド成果物の分割前7z・分割後7zの3つ合わせて16.5GB必要になってしまいます。
一応、現在もVOICEVOX ENGINEが存在しなくてもビルドすることはできますが、ビルド時の警告を消すような形と思います。
また、この方法をとる場合、 `build/splitNsisArchive.js` の処理をスキップするオプションも追加して、これをCI側で再実装する必要がありそうです。
- `*.7z.ini`ファイル生成の実装例: https://gist.github.com/aoirint/71368263dd5118abab699ccaed67379c

Electronビルド時に同梱するVOICEVOX ENGINEのディレクトリを環境変数から変更できるようにする

---

src/components/AudioDetail.vue
src/store/audio.ts

非同期な旧コマンドを新コマンドに移行する例としてアクセントの操作に関連する以下のコマンドを移行しました。
| 移行前 | 移行後|
| --- | --- |
| `CHANGE_ACCENT` `SET_AUDIO_ACCENT` | `COMMAND_CHANGE_ACCENT`|
| `CHANGE_ACCENT_PHRASE_SPLIT` `TOGGLE_ACCENT_PHRASE_SPLIT` | `COMMAND_CHANGE_ACCENT_PHRASE_SPLIT` |
ref #258
ref #233
ref #116

非同期コマンドの新方式への移行例

---

src/store/vuex.ts

題の通り
close #197 
以下のようにtype(or interface)でpayload部分と返り値(getterは返り値のみ、ミスってますがmutationは引数のみ)を定義してあげると
自動的に型が反映されます
(文字列を代入してもOK)
これにより、typeの時点で定義していないものは型エラーを吐くようになります。
無理くりVuex Storeの型を拡張した形のものになります。
Genericsの引数が増え、コードとしてのきれいさが失われているような気もしますが、できる限りGenericsを渡す頻度を下げるように実装したつもりです。
また、GetterやAction、Mutationをそれぞれ文字列の定数として定義していたものが、この型定義強化で不要になると思われます(文字列を直接代入して、間違っていれば型エラーを吐いてくれるようになるので)。
かなり大きなPRになる予定ですが、分けると型エラーだらけになってしまうので、このPRにひとまとめにするしかないかなと考えています。

Vuex Storeの型を厳密化するためのラッパーを追加する

---

.gitignore
README.md
build/generateLicenses.js
build/mergeLicenses.js
package-lock.json
package.json

https://github.com/Hiroshiba/voicevox/issues/219#issuecomment-927917044 のコードをベースに、
VOICEVOXの依存関係のライセンス情報を格納したlicenses.jsonの生成スクリプトを追加します。
- `npm run license:generate -- -o voicevox_licenses.json`
- `npm run license:merge -- -o public/licenses.json -i engine_licenses.json -i voicevox_licenses.json`
ref https://github.com/Hiroshiba/voicevox/issues/219#issuecomment-928237590
ref https://github.com/Hiroshiba/voicevox/pull/264
ref https://github.com/Hiroshiba/voicevox_engine/pull/125

licenses.jsonの生成スクリプトを追加

---

src/components/AudioDetail.vue
src/store/audio.ts
src/store/type.ts

`FETCH_AND_SET_SINGLE_ACCENT_PHRASE`をoldCommandを利用しない`COMMAND_CHANGE_SINGLE_ACCENT_PHRASE`に変更しました。
ref #258
ref #233
ref #116

`FETCH_AND_SET_SINGLE_ACCENT_PHRASE`の新方式への移行

---

build/generateLicenses.js
package-lock.json
package.json

#275 で `license-checker` の出力フォーマットを決めるJSONのファイルパスである、`--customPath`オプションに誤ってJSONそのまま渡していたため、出力フォーマットが設定されずにデフォルトの出力となり、`licenses.json`の`name`や`version`がundefinedになる（JSONに出力されない）問題を修正します（確認不足でした）。
ref #275

licenses.json: nameやversionが出力されない不具合を修正

---

src/store/audio.ts
src/store/command.ts
src/store/index.ts
src/store/project.ts
src/store/setting.ts
src/store/type.ts
src/store/ui.ts
src/store/vuex.ts

#273 の中のレビューを元に、Vuex Storeの型を改善しました。
1. Vuex Storeの独立性を確保したまま型を拡張し、`useAllStore`系関数を撲滅しました。
2. 1に伴って、Vuex Storeに渡す`StoreOptions`をこのプロジェクト用にカスタムした、`VoiceVoxStoreOptions`を`store/type.ts`に配置、各ファイルでStoreOptions定義時にこれを使うようになりました。
3. `createCommandMutation`や`recordOperations`でMutationとそのキーを型として渡すのは健全ではないということで、Payloadを直接渡す形に戻しました。
4. 1のVuex Storeの型改善と、2で作られた`VoiceVoxStoreOptions`により、`gettersMixer`、`actionsMixer`が不要になったので排除しました。
eslintにより大幅にインデントが変更されているせいで、少し大きなPRに見えますが、そこまで大きな変更ではありません。
PRの粒度に迷いましたが、切り離せて`3`だけだったのでまとめてしまいました。
ref #273

Vuex Storeの型を改善する

---

src/components/AudioCell.vue
src/components/CharacterPortrait.vue
src/store/audio.ts
src/store/project.ts
src/store/type.ts
src/views/Home.vue

AudioItemのcharaterIndexをspeakerに変更します。
https://github.com/Hiroshiba/voicevox/issues/229 のために`speakerUuidとstyleId`を用いる必要がありますが、まずは変更料が少なくて住むspeakerに変更してみました。
ref: https://github.com/Hiroshiba/voicevox/issues/229
マイグレーションが一旦壊れます。

AudioItemのcharaterIndexをspeakerに変更

---

src/components/AudioCell.vue
src/store/audio.ts
src/store/type.ts

以前のコードで`AudioCelll.vue`内でテキスト編集に用いられていた`setAudioText`, と`updateAudioQuery`を纏めてundo/redoに対応した`COMMAND_CHANGE_AUDIO_TEXT`コマンドを実装しました。
ref #258
ref #233
ref #116
`FETCH_AUDIO_QUERY`の発行頻度を下げるために`AudioCell`の`qinput`に`debounce`を付けた上で`enter`で確定する挙動を消しています。

`COMMAND_CHANGE_AUDIO_TEXT`コマンドの追加

---

src/background.ts

#282 から分割しました。
Linux上で、ENGINEが外部からプロセスキルされると、
VOICEVOXのUI上で「エンジンの再起動」操作（RESTART_ENGINE）が終了しない問題を修正します。
現在 5488b92e3abe919aa89713d01bea23cf8455f94e のロジックである `engineProcess.exitCode !=== null` のみでは、child_processを使って起動されたENGINEのプロセスが終了しているかどうかを完全には判定できません。
例えば、 `kill $PID` でENGINEがプロセスキルされたとき、`exitCode === null` にもかかわらず、ENGINE のプロセスは終了しているという状態になります。
このとき、RESTART_ENGINEでは、すでに終了しているENGINEのプロセスをkillしようとする動作をします。
killされているプロセスをkillしようとしても、ChildProcessの `close` イベントが起こらないため、起動処理 `runEngine()` が実行されず、「再起動」が終了しません。
ENGINEがプロセスキルされたとき、`signalCode` は設定されるため、
`signalCode !== null` を合わせてチェックすることで、この問題を修正します。
- signalCodeの例: https://nodejs.org/api/process.html#process_signal_events
- https://nodejs.org/api/child_process.html
#281 で追加した `process.on("close", ...)` でのログ出力で、exitCode、signalCodeの挙動を確認してみました。 …

Linux上で外部からKillされたENGINEを再起動できない問題を修正

---

src/components/AudioCell.vue
src/components/HeaderBar.vue
src/components/MenuBar.vue
src/components/OssLicense.vue
src/components/Policy.vue
src/components/SettingDialog.vue
src/components/UpdateInfo.vue
src/store/audio.ts
src/store/command.ts
src/store/ui.ts
src/store/vuex.ts
src/views/Home.vue

Storeの厳密な型付けの過程で必要になってしまっていた`undefined`を消せるような型に書き直し、消しました。
- #197 
- #273 
- #277 
ただし、この変更によって一部機能が無効化されました(`DispatchOptions`と`CommitOptions`を型的に使えなくしました)。
現状使われておらず、かつ今後使われる予定もないと思われるのでいったん無効化しましたが、必要であればもう少し頑張って型を復旧します。
また、一部環境において型推論が壊れます(私の開発環境のWebStormでは型推論がおかしくなり、型を正しく認識してくれませんでした...が、VS Codeでは問題なかったのでたぶん大丈夫でしょう...)

Storeのactions/mutationsのundefined引数を消す

---

src/components/AudioCell.vue
src/store/audio.ts
src/store/type.ts

`audioStore`上にあった`PUT_TEXTS`アクションをコマンド化し`COMMAND_PUT_TEXTS`として実装し直しました。
これによってペースト処理がUNDO/REDOのHistoryに記録されるようになります。
また、#284 でqinputにdebounceが付いたことにより、Storeの値が古くなることがあったためセルが空文字列("")の時にそのセルを上書きする処理を無効化しました。
追加したコマンドはActionが追加した`audioKey`の配列を返すのでペーストした最後の要素にフォーカスするようにしました。
ref #258
ref #233
ref #116

`PUT_TEXTS`のコマンドへの移行

---

src/components/AudioCell.vue

#284 でAudioCellに入った仕様変更を元に戻し、EnterでAccentPhrasesを確定する挙動に修正しました。
この変更に伴い、IMEで入力中のテキストがフラッシュする挙動が改善されました。

AudioCellのEnterの挙動を前バージョンのものに修正/テキストのフラッシュを改良

---

.github/workflows/build.yml
build/installer_linux.sh
build/splitNsisArchive.js
vue.config.js

Windows・Linux用のCPU版自動ビルドを有効化します。
#264 では、GitHub Releaseにアップロードするインストーラ・分割7zのファイル名が重複する問題 https://github.com/Hiroshiba/voicevox/pull/264#issuecomment-927196258 が起き、対応を考えるため、CPU版対応はいったんコメントアウトして、別PR（このPR）にしました。
ファイル名重複の回避方法としては、以下のような候補を考えました。
1. `package.json`の`name`（`packageName`）、`vue.config.js`の`productName`の一時的な書き換え（このPRで採用している方法）
2. NSISインストーラ・分割7zをビルド後にファイル名変更し、`installer.nsh`で分割7zのダウンロードURLを書き換え
3. VOICEVOXはデバイス別リリースしない（ENGINEやCOREを別々にダウンロード）
このPRでは暫定的に、ほぼCIだけで簡単に対応できる1を採用しています。
ビルドの段階によって、`packageName`・`productName`が変わるのを防ぐため、VOICEVOX ENGINEが含まれないArtifactについて、CPU版とGPU版をそれぞれ作成するように変更しました。
`productName`内でスペースではなくハイフンを使用しているのは、GitHub Releaseにアップロードしたときにスペースがピリオドに置き換えられて名前の不一致が起こる可能性があること、シェルスクリプト上での扱いが不便なことが理由です。
将来的には、回避方法3を実装するのが理想的なのかなと思っています。 …

CPU版自動ビルドを有効化

---

src/store/audio.ts
src/store/command.ts
src/store/type.ts

project.tsで使われていた`REMOVE_ALL_AUDIO_ITEM`アクションを`oldCreateCommandAction`を用いずにmutationを叩くように変更しました。また、それに伴い不要となったoldCommandを削除しました。
ref #116

REMOVE_ALL_AUDIO_ITEMのoldCommandの削除

---

src/store/audio.ts

以前 https://github.com/Hiroshiba/voicevox/pull/62 にて、音声の保存先を選択するダイアログを表示している裏で、
音声の生成も同時に進めておくような変更を行いました。
これにより、通常の保存時には体感上の待ち時間を少しだけ減らしていました。
しかし保存をキャンセルした場合にも保存が進行してしており( https://github.com/Hiroshiba/voicevox/issues/190 )、
現状これを中断する方法がなく、少なくとも短期的には解決が難しい状況です。
現在は CPU 版においても保存処理が速くなったため、
相対的に見てこの処理はメリットよりもデメリットが大きくなっていると感じます。
そこで、保存先を選択してから音声の生成を行うようにすることで、キャンセル時の問題を解決します。
close #190
※エンジン側での音声生成中断のニーズは依然としてあるはずなので、https://github.com/Hiroshiba/voicevox_engine/issues/64 は残しておきます。

保存先を選んでから音声の生成を行う

---

src/views/Home.vue

以下のissueの修正です。
セルをラップしている、`audio-cells`にpaddingを追加して、最後のセルの削除ボタンを押せるようにします。
close #371

最後のセルも削除できるよう修正

---

src/components/AudioAccent.vue

#368 の変更で設定漏れがあったので修正です．シフトキーを押した際にアクセントのスライダーがスクロールの挙動を吸わずに，画面スクロールをするようにします．

Bugfix: アクセントスライダーのシフトキーによるスクロール無効化

---

src/store/project.ts

「ファイル」→「プロジェクトを上書き保存」と「プロジェクトを名前を付けて保存」のダイアログボックスの「タイトル」が「プロジェクトファイルの選択」となっており違和感を感じたのを修正するプルリクです。
close #391
人生初のプルリクです。
よろしくお願いいたします。

保存処理のダイアログボックスタイトル「プロジェクトファイルの選択」から「プロジェクトファイルの保存」に変更

---

src/helpers/previewSliderHelper.ts

#423 の修正です．scrollMinStepとscrollStepの値のうち，より高い方の精度で丸め込むように変更しました．
close #423 
ついでにPreviewSliderHelper.tsにコメントを少々足しておきました．

スクロールでのスライダーの値変更時に値の丸め込み精度を最も細かいstepに合わせる

---

src/infrastructures/EngineConnector.ts
src/store/audio.ts
src/store/setting.ts
src/store/type.ts
tests/unit/store/Vuex.spec.ts

OpenAPIのAPIクライアントは audio.ts でインスタンス化され、Storeで対象のインスタンスに依存するように実装されている。
そのため動的にインスタンスを変更するのが困難であり、StoreのMutationなどにEngineに接続するためのClientの変更を行う関数などを実装をするなどの変更が必要である。
また audio.ts は音声に関する知識だけを持っていてほしいので設計がいびつになることは想像に難くない。
そのため本PRではstoreに直接APIクライアントに依存させず、storeの状態に管理されたFactoryに依存する形に変更する。
この変更により、FactoryのInterfaceを実装したMockのFactoryをStoreのstateに入れることで、EngineなしにUIやStoreの開発も容易になる。（実際の所electron依存のところもInterfaceにする必要はある…）
ref: https://github.com/Hiroshiba/voicevox/issues/220

APIクライアントのFactoryを作って、動的にAPIクライアントを変更できるようにする

---

src/components/TitleBarButtons.vue

macOS において最大化ボタンと最小化ボタンの挙動が逆になっていた問題を修正しました。
また、以下の Quasar のドキュメントを参考にボタンのサイズを調整しました。
https://quasar.dev/vue-components/bar#styling
close #427 
https://user-images.githubusercontent.com/41382894/139923390-a7db5190-4636-4ed7-aef9-7793ddffe08b.mov

macOS上での最大化・最小化・閉じるボタンの挙動や外観の調整

---

src/components/DefaultStyleSelectDialog.vue
src/components/HelpDialog.vue
src/components/HotkeySettingDialog.vue
src/components/SettingDialog.vue

ダイアログの遷移が唐突でどこが遷移したかわからないので、画面全体が遷移していることがわかるようにアニメーションを付けました。
これでどこがメインで、どういう階層にいるのかちょっと分かるようになったと思います。
https://user-images.githubusercontent.com/4987327/140194588-b05d552d-5cca-4cdf-86eb-bda78c53cc25.mp4

ダイアログ表示にアニメーションを付ける

---

src/components/DefaultStyleSelectDialog.vue

右のスタイルアイテムをリストからカードにしました
初回起動時のタイトルの「スタイル」を「喋り方」に変えるという話もありましたが、よく考えるとそこ以外は「スタイル」表記なのでちょっと微妙な気がしました
そのままにするか、いっそ全部変えるかのどちらかがいいかなと考えています
ということで、変更は一旦保留にしました

デフォルトスタイル選択画面のレイアウトを調整

---

src/components/DefaultStyleSelectDialog.vue
src/store/index.ts
src/views/Home.vue

デフォルトスタイル選択時に音声を再生するようにしてみました。
あと未選択の場合は進めなくしました。
あと https://github.com/Hiroshiba/voicevox/issues/439 をついでに解決しました
close: #439

デフォルトスタイル選択時に音声を再生

---

src/components/DefaultStyleSelectDialog.vue

ダイアログが生成されるタイミングと表示されるタイミングが違って、ユーザーの意図と異なる初期値が入っていました。
（ソフトウェア再起動後にデフォルトスタイルダイアログを開くと以前のスタイルが選ばれていない、など）
開かれたときに初期値を再度生成するようにしました。

デフォルトスタイルダイアログが開かれたタイミングで初期値を代入する

---

build/installer.nsh
src/components/AudioDetail.vue
src/components/AudioParameter.vue

すべての環境で同じ挙動かはわかりませんが、少なくとも11月7日5時時点の私の環境においては
[voicevox-0.8.0-x64.nsis.7z.1](https://github.com/Hiroshiba/voicevox/releases/download/0.8.0/voicevox-0.8.0-x64.nsis.7z.1) をブラウザでダウンロードすると進捗ゲージが表示されるまでに40秒程度掛かり、
この最初の待ち時間でインストーラーがタイムアウトしているのか、ダウンロードに失敗します。
この失敗を回避するため、明示的に **5分** のタイムアウト時間を指定するようにします。
これは「1GBを5分以内に全部ダウンロードできないとタイムアウト」ではなく、
「5分以内にデータを何も落とせないとタイムアウト」のはずなので、
一般的には充分に長い設定だと思われます。
close #448

nsis-web インストーラーでのダウンロード処理にタイムアウト時間の指定を追加

---

src/background.ts
src/components/AudioDetail.vue
src/components/AudioParameter.vue
src/components/SettingDialog.vue
src/electron/preload.ts
src/store/setting.ts
src/store/type.ts
src/type/preload.d.ts
tests/unit/store/Vuex.spec.ts

undo/redoが安定したので無声化処理をデフォルトで有効にする
ref: https://github.com/Hiroshiba/voicevox/pull/435#pullrequestreview-799461061
無声化についての説明をどこかに置いておく必要がありそう
ref: #243 
ユーザーによる無声化とデフォルト無声で微妙に表示がことなるのですが無視してもいいですか？
ユーザーによる無声化
audioquery時にデフォルトで無声化

無声化処理のexperimentalタグを外しデフォルトで有効にする

---

src/components/AudioDetail.vue
src/components/MenuBar.vue

音声を１つだけ書き出す機能をメニューに付けました。
これで（クリック数は多いですが）コーヒー片手に音声を１つ書き出すことができます。

音声を１つだけ書き出す機能をメニューに付ける

---

src/store/audio.ts
src/store/index.ts
src/store/proxy.ts
src/store/type.ts
tests/unit/store/Vuex.spec.ts

ref: https://github.com/Hiroshiba/voicevox/pull/420
上記PRでEngineに対しての呼び出しを一層挟んで行うようにした。
その際にAudioStoreに直接Engineの呼び出しのためのObjectを流し込んだ。
しかし単純にStoreを生成する際に多くの知識が必要になってしまい、テストが行いづらいのではないかと考えた。
そのため本PRでは、AudioStoreから見ると別のStoreのActionを呼び出した結果Engineへの呼び出しが行われていてその結果が得られた、みたいな形に変更する。
これによりAudioStoreのrootStateへの依存がなくなり、単純にStoreのDispatch操作だけになったのでAudioStore単体のテストが行いやすくなった。

AudioStoreからEngineへの接続Objectを引き剥がす

---

src/background.ts
src/electron/preload.ts
src/store/project.ts
src/store/ui.ts
src/type/ipc.d.ts
src/type/preload.d.ts

変更が保存されていないときの終了時に表示されるダイアログのボタンを「OK」から「破棄」に変更しました。
新たに、showInfoDialogメソッドを作成しました。
引数にbuttonsを定義し、ボタンを自由に設定できるようにしました。
また、戻り値を押されたボタンのインデックスにしました。
#467
TypeScript初めてなので、至らぬ点があればご指摘ください。

保存確認ダイアログのボタンを「OK」から「破棄」に変更

---

package-lock.json

ビルド時に
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
```
が繰り返し出てるので、更新します。

Bump caniuse-lite from 1.0.3001228 to 1.0.3001282

---

src/components/AudioCell.vue

#470 の話がまとまってそうだったので、最終的に出されていた案を実装してみました
close #470 
https://user-images.githubusercontent.com/25514849/141719046-fb019657-4c81-4cb8-b194-4570bb9ca16c.mp4

#470 キャラ・スタイル変更UIの改良

---

src/background.ts
src/components/SettingDialog.vue
src/store/audio.ts
src/store/setting.ts
src/type/preload.d.ts
tests/unit/store/Vuex.spec.ts

音声の再生デバイスを変更する設定を追加しました。
再生するたびに利用可能なデバイスを探索し、見つからなかった場合はデフォルトのまま再生します。
再生デバイスを変更するsetSinkIdという関数ががexperimentalな機能であるためか、
typescriptに(?)認識されておらず怒られてしまったため、変則的な方法で対応することになってしまいました。
Chromiumが対応してくれているので使用するのに問題は無いかと思いますが、
今後諸々のアップデートで対応されたり変更になったりしたら更新する必要があります。
close #459

音声の再生デバイスを変更できるようにする

---

src/components/CharacterPortrait.vue

Electronのバージョンを上げたことで、立ち絵のCSSが正しく適用されていない問題を修正しました。
~~現状は、元のものとほとんど同じ動作をします。~~ 元のものと全く同じ動作をしているはずです...!
~~ただし、名前の部分で`rgba($background, 0.5)`の表記が無効になった(逆に何故今まで使えていたかがわからない)ので、そこだけコメントアウトしています。
この表記が使える状態にするには、テーマを定義しているjsonを書き換える必要があります(そこまではやっていません)。~~
コメントで頂いたrgb化のもののおかげで、json変更の必要がなくなりました！
@MT224244 さん、機能実装・助言ありがとうございます！
close #499

立ち絵の表示が狂う問題の修正

---

src/views/Home.vue

題の通り
元の色は`#0002`だったのですが、若干変更しました。
ダークテーマ時は全然透かしにならないので、ちょっと工夫が必要かもしれません。
AudioCellが非表示になってしまっているように見えるのは、単純に白塗りになっていたからみたいです。
close #504

エンジン(再)起動時の色を修正

---

src/background.ts
src/components/AudioCell.vue
src/components/DefaultStyleSelectDialog.vue
src/components/MenuBar.vue
src/electron/preload.ts
src/store/index.ts
src/store/type.ts
src/type/ipc.d.ts
src/type/preload.d.ts
src/views/Home.vue

- #509 での問題である、`IS_UNSET_DEFAULT_STYLE_IDS`などをリファクタリングし、`IS_UNSET_DEFAULT_STYLE_ID`に改名したうえで、speaker uuidを引数として各話者ごとにデフォルトスタイルがセットされているか否かを取得できるようにしました。
また、その改変に伴って必要な周辺の修正も行いました。
- これによって、新規キャラが増えた際に、再度デフォルトスタイルについて問うようになります。
- 加えて、非常に内容が近しい #501 のために以下の修正を行いました。
- スタイルのないキャラにおいてはスタイル選択画面で「試聴ができる」ことを表すような文言を表示するように変更
- これに伴い、メニュー名を「デフォルトスタイル・試聴」に変更
- 別にこれである必要はない気がするので、元に戻しても良さそうです。
- 新規キャラが増えた際、起動時にそのキャラに対してのみデフォルトスタイルを問うようにしました。
- ただし、既存キャラのスタイルが増えても、そこに関しては問い直せないのが、現状の問題です。
- スタイルが一つしかないキャラに関して、キャラ選択UIを改善しました。
- ![image](https://user-images.githubusercontent.com/34832037/143505943-d3fdc2ac-2338-4c97-99a4-8aa1142fe825.png)
- また、#501 や #509 とは関係ないですが、デフォルトスタイルを選択できる画面において、立ち絵が崩れる問題を修正しました。
- close #501 
- close #509 
デフォルトスタイルを聞かれている時に、メニューバーからほかのものにアクセスできる状況を何とかしたいですね...

スタイルのないキャラのためのUI・機能修正

---

src/background.ts

リリース版と開発版で同じユーザーデータを使用していることで通常起こりえない挙動をしてしまう問題が出てきたため、開発時のみ別ディレクトリを使用するように変更しました
close #455
ref #517

開発時はユーザーデータのディレクトリを変更する

---

src/App.vue

Volarがエラーを吐いていたので何かなと思ったら `lang="ts"` が `type="ts"` になっているせいでTypeScriptとして認識されていないようでした
これが原因でこのファイルだけESLintのエラーも出なくなっていたようです

App.vueのscriptがtypeになっていたのをlangに修正

---

build/installer_linux.sh

`build/installer_linux.sh`の必要パッケージチェック失敗時のメッセージ(curl,p7zip,libsndfile)にArchLinux向け(pacman)の項目を追加

installer_linux.shのメッセージを追記

---

src/background.ts

タイトルの通りです。`"window-all-closed"` イベントの時にmacOSだけ例外的に終了させていなかったのを終了するようにして実現しました。
close #546 
なし
副作用として閉じるボタンやCmd+Wでも終了するようになります。

macOSでCmd+Qでアプリケーションを終了できるようにする

---

src/plugins/ipcMessageReceiverPlugin.ts
src/store/index.ts
src/store/project.ts
src/store/vuex.ts

Dispatchの型が少しおかしかったので修正しました。( `LOG_ERROR` 等で使われているスプレッドが許容されていませんでした。)
`dispatch()` の引数が無かった場合にundefinedを付けているところがいくつかありましたが、これはこの変更により完全に許容されなくなったので削除しています。
ref #556

Dispatchの型を修正

---

src/components/MenuBar.vue
src/components/MinMaxCloseButtons.vue
src/components/TitleBarButtons.vue

タイトルの通りです。 #554 の最初の案を採用しています。
close #554 
Issue #554 に他のデザイン案もあります。より良い案が見つかればそちらに変更します。
手持ちのWindows環境がないので、macOS以外に動作確認を行ったのはLinuxのみです。
Vue.js や TypeScript に不慣れなので、ナンセンスなことをおこなっていた場合はご指摘よろしくお願いします。

macOSにおいて最小化・最大化・閉じるボタンをタイトルバーの左側に表示する

---

src/background.ts
src/type/preload.d.ts

タイトルの通りで、以下の2点です。
- 「長さ欄を表示」ショートカットキーの初期化ができない不具合の修正 (#541)
- ショートカットキーの重複追加防止
ref #541 
ショートカットキーの重複追加防止について：
保存されたショートカットキーの中に追加しようとしているキーと同じ操作名(action)がある場合はその操作が重複して追加・保存されていましたが、この場合はキーの追加をしないようにしました。
0.8 → 0.6 → 0.8 などとバージョンダウン→アップをした場合に重複が起こるかもしれません。
バージョンダウンは通常あまりしませんし、migrationsの仕様に詳しくないので重複は起こり得ないかもしれませんが…念のため入れました。

「長さ欄を表示」ショートカットキーの初期化ができない不具合の修正とショートカットキーの重複追加防止

---

src/components/AcceptRetrieveTelemetryDialog.vue
src/components/SettingDialog.vue
src/main.ts
src/views/Home.vue

* #497 でdisableで追加したvue-gtmの有効化する処理の追加、およびテレメトリーの収集の許可・拒否を行うダイアログの追加
* [opt-outの方法がわかった](https://github.com/VOICEVOX/voicevox/issues/487#issuecomment-986084984)ため、あらためてテレメトリーの収集をできるようにしたもの
ref: #487
動画: https://github.com/VOICEVOX/voicevox/issues/487#issuecomment-989877701

vue-gtmの有効化・およびテレメトリー収集のダイアログの追加

---

.github/workflows/build.yml
.github/workflows/test.yml
.github/workflows/typos.yml

https://github.com/VOICEVOX/voicevox_engine/pull/198 にならって、エディタのリポジトリでも CI の実行タイミングに `workflow_dispatch` を追加します。以下、上記PRより引用：
> リポジトリのActionsタブから個別のCIジョブのページを開くと、ブランチを指定して手動実行できるようになります。
> fork先で、実行ブランチが固定されたCIを実行するのに、実行条件を書き換えるコミットを作ったり、（Releaseのテスト以外で）Releaseを作成しなくてよくなります。
https://github.com/VOICEVOX/voicevox/pull/570#discussion_r767220139 の提案を受けて、便利なので追加したいと思いました。

手動でCIジョブを実行できるようにする

---

.github/workflows/labeler.yml

必須パラメータの`enable-versioned-regex`が抜けていたので追加
#580 
https://github.com/VOICEVOX/voicevox/actions/runs/1571876696

`labeler.yml`に`enable-versioned-regex`を追加

---

build/installer_linux.sh
vue.config.js

Linux用インストーラに、vvprojファイルをVOICEVOXに関連付けする処理を追加します。
- `voicevox.desktop`ファイルの実行コマンドに`%U`を追加
- VOICEVOXの関連付け設定ができるようになる
- vue.config.jsのLinux用ビルド設定に`mimeTypes`を追加
- `voicevox.desktop`ファイルにMimeType`application/x-voicevox`が書き出される
- ローカルビルドして確認した
- インストール時にMimeType`application/x-voicevox`と拡張子`vvproj`の関連付け設定ファイルを、Linuxの設定ディレクトリに出力
- デフォルトの`vvproj`関連付け先がVOICEVOXになる
- close #575 
@eggplants さんありがとうございます！
- 環境: Ubuntu 20.04
<details>
</details>
<details>
</details>

Linux用インストーラ: vvprojファイルの関連付けをする

---

.github/workflows/build.yml
.github/workflows/labeler.yml
.github/workflows/test.yml
.github/workflows/typos.yml

`build.yml`を`voicevox_resource`のリサイズに合わせて修正しました。
`*.png_large`は`public`から除外されます。
Bashスクリプトの気になった細かいとこも修正しています。
https://github.com/VOICEVOX/voicevox_resource/issues/2
https://github.com/VOICEVOX/voicevox_resource/pull/4

`build.yml`の修正

---

src/background.ts

vvprojファイルからVOICEVOXを開くと、VOICEVOXは立ち上がりますがプロジェクト内容を開くことができていませんでした。この問題について、プロジェクト内容を開けるように修正しました。
close #586 
ref #572 
以下のように、vvprojファイルをダブルクリックしてVOICEVOXを開いたとき、プロジェクト内容がエディタに反映されます（コンテキストメニューからの起動でも同様です）。
https://user-images.githubusercontent.com/41382894/145824467-7c0e6f91-37c0-40ea-9827-b5e28dbe4b9d.mov
https://github.com/PickledChair/voicevox/actions/runs/1572994607 の `macos-cpu-prepackage-zip` から今回の変更を加えた Mac 向けビルドをダウンロードできます。
また「system preferenceからアプリケーション実行を許可した初回起動時にエラーが出る」という問題（ https://github.com/VOICEVOX/voicevox/pull/570#issuecomment-991601013 や  https://github.com/VOICEVOX/voicevox/issues/572#issuecomment-991875050 を参照）は、調べた限りは Mac において `process.argv` でファイルパスを得ようとした時に起こっているようだったので、今回の変更で同時に修正された可能性があります。修正されていなかった場合は、このPR内で引き続き作業します。動作確認できる方は確認をよろしくお願いいたします。 …

Mac: vvprojファイルからVOICEVOXを正しく開けるようにする

---

public/privacy_policy.md

google analytics用のプライバシーポリシーを書いてみました。
ビルド時だけ入るようにすることもできるのですが、google analyticsを使うコードがOSS版に含まれている以上、プライバシーポリシーも含めてしまったほうが無難なのかなと思い、OSSに含めようとしています。
- https://github.com/VOICEVOX/voicevox/issues/487

プライバシーポリシーを記載

---

src/store/project.ts

2点です。
- (タイトル通り) 0.4.1で保存されたプロジェクトファイル(.vvproj)が0.9.3で開けないバグを修正
- undefinedの判定を厳密化
close #592 
0.4.1、0.5.3、0.6.1、0.7.5、0.8.2、0.9.3で保存されたプロジェクトが開発バージョンで正常に読み込まれることを確認しました。

0.4.1のプロジェクトが0.9.3で開けないバグを修正

---

src/components/HotkeySettingDialog.vue
src/components/MenuItem.vue
src/store/setting.ts

ショートカットキーの設定について、Mac でも Shift とCtrl, Alt キーは修飾キーとして使えていましたが、Cmd キーは修飾キーとして使用できませんでした。これを使用できるようにします。
備考： Mac のショートカットキー操作は Undo 操作は Cmd + Z、保存操作は Cmd + S など、Cmd キーを多用します。Mac 対応において Cmd キーが使えるかどうかということは大きい問題だと考えています。
ref #572 
https://user-images.githubusercontent.com/41382894/146002019-7ee5020d-6561-4b80-8987-6ce35e887cd1.mov
Windows と Linux のショートカットキーの設定や使用には影響を与えていないと思います（Ubuntu で Windows キーを押した時などの動作を確認しました）。しかし、いくつか議論の余地がある箇所がありそうです。レビュワーのご意見によっては一旦クローズして、課題解決のための Issue を開くかもしれません。
Mac の Cmd キーはブラウザ上では Meta キーとして扱われます。Meta キーは Windows や Ubuntu では通常 Windows キーです（ Ubuntu では Super キーと呼ぶようです）。現状、VOICEVOX では Windows や Ubuntu で Meta キーを使えないようにしているため、「Mac のみが Meta キーを修飾キーとして扱う」と仮定して実装しました。そこで、vue のコンポーネントに「 key の名前として Meta が来たら Cmd に置き換える」という処理をハードコードしてしまっています。例として以下のような箇所があります：
```vue …
```

Mac: Cmdをショートカットキーの修飾キーとして使えるようにする

---

src/background.ts

Mac のショートカットキーは Ctrl の代わりに Cmd を使っているケースがあるなど、他の OS とデフォルトの操作体系が異なります。これを再現するために、Mac 向けのデフォルト設定を追加しました。
基本的には Mac 版 VSCode のショートカットキーを参考にしました。
close #604

Mac向けのショートカットキーのデフォルト設定を追加

---

src/components/MenuBar.vue

windowのタイトルにバージョン情報を載せます。
ref #581

Windowのタイトルにバージョン情報を載せる

---

src/background.ts
src/components/SettingDialog.vue
src/electron/preload.ts
src/store/audio.ts
src/store/index.ts
src/store/setting.ts
src/store/type.ts
src/type/ipc.d.ts
src/type/preload.d.ts
tests/unit/store/Vuex.spec.ts

Engineに疑問文自動調整機能が追加されたので、front側でその有効無効を調整できるようにする
refs #608

feat: 疑問文自動調整設定機能追加

---

public/howtouse.md
src/components/HowToUse.vue

voicevox_blog用に、使いかたの画像に代替テキストを追加しました。
矢印が画像のすぐ隣縦中央に配置するようにしました。
ref https://github.com/VOICEVOX/voicevox_blog/issues/13

使いかたの画像に代替テキストの追加

---

.github/workflows/build.yml
src/background.ts
src/components/MenuBar.vue
src/plugins/ipcMessageReceiverPlugin.ts
src/store/type.ts
src/store/ui.ts
src/type/ipc.d.ts
tests/unit/store/Vuex.spec.ts

Mac 版の三色ボタンを自前のもの（`<min-max-close-buttons />`）から OS ネイティブのものに変更します。
Mac 版の三色ボタンはこれまでネイティブのものではなく、挙動を真似たものを自前で用意していました。しかし、マウスオーバーしたときにボタンの役割を説明する模様が表示されないなど、ネイティブのボタンに比べて機能が欠けていたり異なっていたりしました。
ref #572 
https://user-images.githubusercontent.com/41382894/147450662-9144f742-0e12-48c6-ad8e-ff43c1161825.mov
- フルスクリーンにした時は三色ボタンが画面外に移動するため、三色ボタンのためにメニューバーに空けたスペースが余分になってしまいます。かといってスペースを除去するだけだとデザイン的に寂しくなったので、他の OS 版と同様に VOICEVOX アイコンを表示するようにしています。
- 今回の変更が採用される場合、`<min-max-close-buttons />` の Mac 向けの条件分岐が余分になります。これを削除するかどうか迷っています。
- 今回の変更に伴って、閉じるボタンを押した時の終了処理に致命的な影響はなさそうでしたが、Mac 版と他の OS 版でやや異なる手順を踏むようになりました（具体的には、今までの仕様では閉じるボタンで直接 `CHECK_EDITED_AND_NOT_SAVE` イベントを起こしますが、今回の変更で Mac 版だけ、まず electron のアプリ終了関連のイベントが呼ばれます。`before-quit` イベントの中で結局 `CHECK_EDITED_AND_NOT_SAVE` イベントを起こしているので問題ないようになっています）。 …

Mac: ネイティブの三色ボタン（最小化・最大化・閉じるボタン）を使うように変更

---

.github/workflows/build.yml
package-lock.json
package.json
public/updateInfos.json

ENGINEのpreview版ビルドが完了したらビルドするつもりでしたが、「雨晴はう」がonnx版エンジンに含まれていないのであまり意味がなさそうな気がしました。
気が向いたらpreview版を更新します。

Merge 0.9.4

---

.github/workflows/build.yml
vue.config.js

Mac 版でネイティブ UI の部分（閉じるボタンにマウスオーバーして表示されるポップアップや、保存ダイアログなど）が英語になる問題がありました。日本語になるように修正します。
（この問題の原因と対策についての詳細は https://github.com/VOICEVOX/voicevox/issues/624#issuecomment-1002880923 に書きました。）
close #624 
~~`actions/upload_artifact@v2` が空のディレクトリ `ja.lproj` をアップロードできる簡単な方法があれば、そちらの方が良い解決法だと思うので、詳しい方がいらっしゃれば教えていただければとても助かります。~~
`actions/upload_artifact@v2` のアップロード機能は [@actions/artifact](https://github.com/actions/toolkit/tree/main/packages/artifact) の `uploadArtifact` 関数の仕様に依存しているのですが、この関数がアップロード項目としてファイルのみをサポートしているため、原理的に無理のようです。アップロード結果の `artifactItems` について以下のように書かれています：
> A list of all files that describe what is uploaded if there are no errors encountered. Usually this will be equal to the inputted files with the exception of empty directories (will not be uploaded)
cf. …

Mac: ネイティブUI部分の日本語化

---

src/views/Home.vue

起動時に一瞬真っ白になるのを防ぎます。
エンジン起動が完了するとインジケータが消えていたのですが、実際はエンジン起動後にキャラクターロードが完了したあとにUIが表示されるので、その間真っ白になっていたのが原因でした。
なので、キャラクターロードなどが完了したあとにUIが表示されるようにしました。
close #637 
engineState以外にisCompletedInitialStartupという制御変数を設けました。
engineStateはエンジン再起動時にも参照されます。

起動時に一瞬真っ白になるのを防ぐ

---

.github/workflows/build.yml

今までzip版は、artifactからダウンロードしてからgoogle driveにアップロードしていました。
結構煩雑で時間がかかっていたので、zipファイルが2GB未満になったのもあって、releasesにアップロードすることにしたいです。
close #636 
close #638 
zipファイルの容量は大体1.8GBで、github releasesの制限の2GBギリギリです。
electronのアップデートなどでいつかこの制限を越してしまう可能性はあります。
超してしまったら悲しみつつgoogle driveにアップロードする運用に戻すことにして、2GB未満の間はreleasesにアップロードとしたいと思います。

zipファイルをreleaseにアップロードする

---

src/background.ts

background側（メインプロセス）のRESTART_ENGINEを関数に切り出します。
複数エンジン対応時に、再起動するエンジンを指定する引数を追加、全エンジンを再起動する関数を作成するつもりです。
- ref #609

複数エンジン対応: RESTART_ENGINEを関数に切り出し（リファクタリング）

---

src/background.ts
src/electron/preload.ts
src/store/project.ts
src/store/ui.ts
src/type/ipc.d.ts
src/type/preload.d.ts

ソフトウェアを閉じようとしたときに出てくる確認ダイアログを閉じると、キャンセルではなく破棄の扱いになります。
これはデフォルトで一番左のボタンをキャンセルボタンだとみなすためです。
キャンセルボタンの番号を指定可能にし、キャンセルされるようにしました。
close #662

保存確認ダイアログの×ボタンをキャンセル扱いにする

---

.github/workflows/build.yml
package.json

詳細はissueに記載しています
- https://github.com/VOICEVOX/voicevox/issues/659
npm versionはalpha等が付いていても大丈夫っぽいので、普通にpackage.jsonのversionを書き換えてみました。
close #659
エンジン側のコードに寄せてみました
- https://github.com/VOICEVOX/voicevox_engine/pull/288
2022/01/23 21:59 release作ってみました
https://github.com/VOICEVOX/voicevox/releases/tag/0.10.check.0
2022/01/23 22:07 0.10.preview.0のタグ名だとダメだったので再度挑戦しました
https://github.com/VOICEVOX/voicevox/releases/tag/0.10.0-preview.0

リリース時にバージョン情報が自動的に入るようにする

---

.github/workflows/build.yml
README.md
build/installer_linux.sh
public/ossCommunityInfos.md
src/store/audio.ts

いい加減VOICEVOX org内のリポジトリで作業するのをやめて、個人リポジトリで作業できるようにしたいと思いました。
リダイレクトが死んでしまいますが、こんな感じの案内を出そうとと思います。
https://github.com/Hiroshiba/voicevox_engine

リポジトリのURLをHiroshibaからVOICEVOXに

---

public/Contact.md
src/background.ts
src/components/ContactInfo.vue
src/components/HelpDialog.vue
src/electron/preload.ts
src/type/ipc.d.ts
src/type/preload.d.ts
tests/unit/components/Contact.spec.ts

お問い合わせ画面の増設の修正

---

public/qAndA.md
src/background.ts
src/components/AudioInfo.vue
src/components/SettingDialog.vue
src/electron/preload.ts
src/store/audio.ts
src/store/setting.ts
src/store/type.ts
src/type/preload.d.ts
tests/unit/store/Vuex.spec.ts

プリセットのUIを変更しました。
* プリセット→パラメータの適用ボタンを無くし、データの流れを一方向にしました
* パラメータ→プリセット→他のテキスト欄
* 再登録ボタンを表示し、パラメータ変更時に現れるようにしました
* これで編集中のパラメータをプリセットに反映されるには更に操作が必要だとわかるようになった･･･はず！
* プリセットを実験的機能に変更
* 再適用の挙動など、まだ最も良い状態ではないかもと感じたので、実験的機能にして将来の変更に備えます
ref #428 
いろいろ考えた思考回路を少し残してみたので参考になりますと幸いです
* プリセットUIの最大の問題は、どっちを編集しているのかがわからない点
* プリセット欄を常時表示する以上必ず問題になる
* パラメータ変更時にプリセット欄が外れる場合 → プリセット値を変えたいのになぜ勝手に外れるんだ
* はずれない場合 → プリセット値を設定したのに反映されてない
* こっちはパラメータ変更時に見た目を変えてプリセットを設定していないことを伝える手もある
* 見た目の変更が何を意味するのかわからないかもしれない（未保存）
* そもそもそのUIがスクロール範囲外に行って見えてないこともある
* 「適用」が設定→プリセットなのかプリセット→設定なのかわからない
* 「登録」は設定→プリセットっぽさがあるので、その逆だと考えると理解できる
* 「適用」はできる限り使わないようにした
* プリセットの変更をしているわけではないことがわかるUIにする
* 再登録ボタン、再適用ボタンで区切る方法
* これはセルとプリセットが結びついていることがわかりにくくなってしまう
* 再登録ボタンだけにし、変更が入ったタイミングで再登録ボタンを表示する
* これでプリセットに登録するには操作が必要だということがわかる･･･はず！

プリセットのUIを変更

---

public/themes/dark.json
public/themes/default.json
src/components/AudioDetail.vue
src/styles/colors.scss
src/type/preload.d.ts

ユーザーには落ち着いて調整作業をできる環境を提供したいので、選択色を赤色系統から青色に変更してみました。
次リリース前にマージしたいと思います

アクセント句の選択色を青系統に変更

---

src/components/UpdateInfo.vue
src/store/project.ts

ソフトウェアのバージョン と GitHub の Release の最新バージョンを比較して、ヘルプでアップデートを確認します。
https://github.com/VOICEVOX/voicevox/issues/235
最新版を使っているとき
古いバージョンを使っているとき

ヘルプでアップデートを確認できるようにする

---

src/store/audio.ts

読み仮名の修正に「、」や「？、」を含んでいるときでも `is_kana=true` としての修正を可能にする
close #691

読点を含んだ読み仮名修正に対応

---

src/store/index.ts

vuex loggerの出力を見ていたらstateに入っているのが`audioCommandStoreState`ではなく`audioCommandStore`だったので修正

stateに間違えてstoreが入っている状態を修正

---

src/background.ts

Mac 版において、テキスト欄で一部のショートカットキーが使用できない状態になっていました。
https://github.com/VOICEVOX/voicevox/issues/675#issuecomment-1024902466 で説明した通り、これを解決する最も簡便な方法は、使用したいショートカットキーと紐づいている Mac のネイティブメニューを設定することのようでした。そのため、Mac 環境でのみ Electron のネイティブメニューを最低限設定するように変更しました。
今回、
- `Cmd + X`
- `Cmd + C`
- `Cmd + V`
- `Cmd + A`
の４つのショートカットキーを利用可能なようにしました。
close #675 
Mac のネイティブメニューとして以下のものが追加されます（`fn D` と `fn E` は自動で追加されていました）。

fix: Mac において Cmd + V 等のショートカットキーを利用可能にする

---

src/store/audio.ts
src/store/utility.ts

ひらがなやカタカナのみの正規表現生成や、ひらがなtoカタカナの関数や、長音置き換えなどを関数として切り出しました。
辞書のために、読みをカタカナorひらがなで書く必要がありますが、そのための検証機能として利用するために、これらを関数として切り出す必要がありました。
- ref #709

AquesTalk記法等のための関数切り出しとリファクタリング

---

src/store/audio.ts
src/store/type.ts
src/type/globals.d.ts

辞書実装の中で、アクセント調整のプレビュー再生機能を作るときにaudio storeの機能が使えると便利そうだったので、それ用にリファクタと関数分けを行いました。
AudioItemをstateに持たせたくないながら、再生はしたいというときのためのリファクタリングです。
- ref #709

Audio Storeのリファクタリング

---

src/components/AudioCell.vue
src/components/DefaultStyleSelectDialog.vue
src/components/MenuBar.vue
src/store/index.ts
src/views/Home.vue

デフォルトスタイル選択ダイアログは、デフォルトスタイルを選ぶ役割と、サンプルボイスを聞いてもらう役割がありました。
後者の目的を果たすために全キャラクターを別ページで表示していましたが、キャラクター数が多くなると使えるようになるまでのステップが増えてしまうという課題がありました。
- https://github.com/VOICEVOX/voicevox/issues/614
そこで「キャラクター並び替えダイアログ」を別途作って、そちらでサンプルボイスを再生可能にする予定です。
そのプルリクエストも用意していますが、変更量が大きくなってしまったので、デフォルトスタイル選択の仕様変更だけを切り分けてプルリクエストにしました。
ref https://github.com/VOICEVOX/voicevox/issues/614
スタイル数が１のキャラクターはデフォルトスタイル選択ダイアログに出さない仕様にしています。

デフォルトスタイル選択ダイアログの仕様変更

---

src/components/DictionaryManageDialog.vue
src/components/MenuBar.vue
src/store/audio.ts
src/store/type.ts
src/store/ui.ts
src/views/Home.vue
tests/unit/store/Vuex.spec.ts

題の通り。
詳細として、以下のことが可能です
- 登録単語の一覧化
- 50音順にソートして表示されます
- 単語の新規登録
- 単語の編集
- 新規登録と編集では、表記、読み、アクセント位置の調整が可能です
- 単語の削除
- 編集した単語パラメータのリセット
- 登録した・登録する単語のプレビュー再生機能
close #709

辞書の編集UIを追加

---

src/components/DictionaryManageDialog.vue
src/components/MenuBar.vue
src/styles/_index.scss
src/views/Home.vue

辞書登録UIを、左を操作しているときと右を操作しているときのステートが違うことをわかりやすくしてみました。
消去・編集・追加ボタンは左に、リセット・保存・キャンセルボタンは右にあります。
https://user-images.githubusercontent.com/4987327/155902095-873c3b0d-433e-454f-bee5-70d44cec44c8.mp4
@y-chan （共有のためのメンションです）

辞書登録UIのデザインちょっと修正

---

src/background.ts

0.11.0でエンジン起動が終わらない問題 #721 の原因を修正します。
dotenvが.envから設定をprocess.envに読み出す（`dotenv.config()`）前に、
`engineInfos`の初期化処理をしていたため、electron builderでビルドしたバイナリで、
`process.env.DEFAULT_ENGINE_INFOS`が`undefined`になり、エンジン設定`engineInfos`が空リストになっていました。
`engineInfos`の初期化処理を`dotenv.config()`の後に移動して、修正します。
ローカルで`npm run electron:build_pnever`で（エンジンなしで）ビルドして、.envを0.11.0エンジンが起動するように差し替えて、エンジンが起動・接続できることを確認しました。
一応ビルドを回しています。
- <https://github.com/aoirint/voicevox/releases/tag/0.11.1-aoirint-1>
- close #721
- ref #722

Hotfix: バイナリでエンジン設定が読み出せず、エンジンが起動しない問題の原因を修正 (#721)

---

src/store/audio.ts

BlobとAudioElementだけで再生させられるようにリファクタを行いましたが、`currentTime`をセットしてから`src`をセットすると`currentTime`の方がリセットされてしまうようなので、そうならないように`currentTime`をセットするコードを移動させました。
しっかり動作確認せずにPRしてしまった私の問題です、ご迷惑をおかけしました...
close #732

[HOTFIX]再生位置を指定するコードを移動させる

---

src/components/CharacterOrderDialog.vue

キャラクター並び替えダイアログ（CharacterOrderDialog）について、スタイルを切り替えたときに、アイコンをスタイルに対応するものに切り替えるようにします。
複数エンジン対応中に気になったのでPRを作成しました。
（キャラクター並び替えダイアログではデフォルトスタイルが変更されないので、意図的にアイコンを切り替えていないのかも・・・？　その場合はCloseしてください）
これまでの実装では、常に0番目のスタイルのアイコンが表示されていました。
<https://github.com/VOICEVOX/voicevox/pull/754> の変更と互換性があります。

キャラクター並び替えダイアログ: スタイルごとにアイコンを変える

---

src/components/DefaultStyleSelectDialog.vue

デフォルトスタイルダイアログ（DefaultStyleSelectDialog）について、speakerUuidが異なるキャラクターが重複したstyleIdを持つことを許容する実装にします。
スタイル付きのキャラクターを一意に識別する方法について、 #754 と同様の対応をしています。
- ref #609

デフォルトスタイルダイアログ: speakerUuidが異なる場合にstyleIdの重複を許容する

---

src/components/DictionaryManageDialog.vue
src/store/dictionary.ts
src/store/index.ts
src/store/type.ts
tests/unit/store/Vuex.spec.ts

辞書ダイアログコンポーネントからエンジンの情報を取り除いて、vuex側で呼ぶようにしました。
ref #724

辞書ダイアログからengineInfoを取り除く

---

src/components/DefaultStyleSelectDialog.vue

初回起動時に表示される音源のデフォルトスタイル選択画面において、disabled な「次へ」のボタンが表示されているとスキップできると誤解されうるので、未選択の状態で非表示となるようにしました。
close #597

スタイル選択画面で未選択時に「次へ」ボタンを非表示

---

src/components/AudioAccent.vue
src/components/AudioDetail.vue
src/components/DefaultStyleSelectDialog.vue

アクセント句分割の当たり判定を広げてみました。いくつか方法はあると思うのですが、もっとも単純に「文字部分の範囲を削り、分割部分の判定を増やす」という方法を試してみました。全体の表示幅に影響が出ないよう調整しました。
ref #453
提案の確認用なので merge せずに閉じても構いません。

アクセント句分割の当たり判定を広げる

---

src/background.ts
src/components/AudioDetail.vue
src/store/audio.ts
src/store/type.ts
src/type/preload.d.ts

アクセント句の内容からイントネーション（moraのpitch）を再設定する機能を追加しました。
ショートカットには仮に `Ctrl + G` を割り当てています。
イントネーションタブを開いていないと実行時のユーザへのフィードバックがないので、意図せず誤爆しないように微妙に押しづらいものを選択した、程度の意図なのでよりふさわしいものがありそうです。
issueの粒度的に使ってみてUIを追加するかどうか？まで含んでいる気がしたのでcloseしないようrefにしておきます
ref #524 
音素長をリセットしないように `/mora_pitch` を使いましたが、 `/mora_data` を使えば音素長も一緒にリセットします
イントネーションをリセット、に音素長も含まれるかどうか判断できなかったので、とりあえずpitchのみリセットするようにしました

アクセントからイントネーションを再設定する機能

---

.env.production
README.md

.envに書くエンジンのパスは、\じゃだめで/区切りである必要があるかもしれません。
（もし\区切りだと、`[00:28:09.365] [error] SyntaxError: Unexpected token P in JSON at position 95`といったエラーが表示されるとのことです）
それがちょっとでもわかりやすいように、例のパスを/区切りにしてみました。

.envのエンジンへのパスは\区切りではなく/区切りだとわかりやすくする

---

src/components/SettingDialog.vue

設定画面の項目にて，トグルボタンにカーソルを当てるとその項目の詳細が表示されるようになっていた状態から，項目ごとに（？）アイコンを追加して詳細情報を表示するようにし，設定の項目についてわかりやすいUIに変更しました．
close #647 
https://user-images.githubusercontent.com/40142697/161590143-4cd29f04-3367-4f6f-91c1-e6841210e744.mp4

設定画面の項目の詳細情報をヘルプとして表示する

---

.github/workflows/build.yml

DirectMLにも対応することで、GPUモードをAMD/Intel製GPUでも使用可能にします。
ref #775

DirectMLへの対応

---

package-lock.json
package.json
src/background.ts
src/electron/preload.ts
src/store/index.ts
src/store/setting.ts
src/store/type.ts
src/type/ipc.d.ts
src/type/preload.d.ts
src/views/Home.vue
tests/unit/store/Vuex.spec.ts

ウィンドウ位置とスプリッターの位置を記憶できるようにしました。
ウィンドウ位置は [electron-window-state](https://github.com/mawie81/electron-window-state) を利用し、
スプリッターの位置は electron-store の設定ファイルに保存するようにしました。
- `config.json` と同じディレクトリに `window-state.json` というファイルが作成され、そこに記録されます。
- 表示していたディスプレイを外した場合の復帰処理は electron-window-state が面倒見てくれるのでこちらのコード内には入っていません。
- 最大化やフルスクリーン状態も記憶して復帰してくれます。
- ただし、その復帰処理の[ライブラリ内バグ](https://github.com/mawie81/electron-window-state/issues/68)で「複数モニタにまたがるようにウィンドウを配置して終了→起動した場合、復帰できず初期位置に戻る」という現象が起こります。。。
- もしこれが許容し難い場合はこのライブラリを使わず自前で実装が必要と思います（自前でもそんなに重くはなさそうです）
- 設定ファイルへの保存タイミングは、スプリッターをつまんで動かして離したタイミングです。
- ユーザが設定ファイルを編集してとんでもない値にした場合でも表示が壊れないようにしています。
close #195
----
EDITED:
両OSでウィンドウ位置の保存と、マルチモニタでの復帰、windowsで最大化・macでフルスクリーン状態が復元されることを確認しています。（linuxは確認できてないです、すみません）
- windows10
- Intel mac (Monterey)

ウィンドウ位置・splitterの位置を記憶できるようにする

---

.env.production
package-lock.json
package.json
src/background.ts

- Jsonを1行で書いてあるのは見づらかったので改行するようにしました。
- 開発環境だと `envPath` はnode_modulesの中を指していてうまく読めていなかったので修正しました。
- 本番環境でも `dotenv` が使われているっぽいのにdependenciesに入っていなかったので追加しました。

.envのDEFAULT_ENGINE_INFOSを改行して定義

---

src/components/AudioDetail.vue
src/components/AudioParameter.vue

以前 Split の当たり判定を広げる修正を行いました (#772) が、その際に生じていた
- 複数文字のモーラ（「シャ」など）が改行されてしまう
- イントネーションタブとアクセントタブで文字とスライダーの表示位置がずれている
という二つの問題を修正しました。
fix #777 
ref #772
修正前画像は #777 を参照してください。
改行されないように表示している点について、 `white-space: nowrap;` によって無理やり狭いスペースに押し込めている都合上、特に複数文字のモーラの右側部分に「文字が表示されているが当たり判定としては split」というスペースができてしまっています。
（「ショ」の直後の split にカーソルを合わせています。）
- 読みを変更する場合どの文字を押してもいい
- ハイライトでどちらの機能が起動するかわかる
ことから緊急性は低いと思われますが、余裕があれば修正したほうが良いかもしれません。
`text-align: center` はしているものの、overflow していることにより文字がグリッド先頭部分ぞろえになってしまっています。そのため、スライダーに対して複数文字モーラの表示位置が右に若干ずれています。これを中央に表示できれば、表示は両側にはみ出ることになるので、上で述べた当たり判定に関しても被る量が減り、使用感が改善されるかもしれません。

イントネーション欄の文字横幅をそろえる

---

src/background.ts
src/components/Dialog.ts
src/components/MenuBar.vue
src/electron/preload.ts
src/store/audio.ts
src/store/type.ts
src/type/preload.d.ts

ファイルメニューに、"テキストを繋げて書き出し"項目を追加し、クリックすると、全テキスト欄の文章をキャラ名とともに一括してテキスト書き出す機能を追加
ref #786

全テキスト欄の文章をキャラ名とともに一括してテキスト書き出す機能

---

src/background.ts

#794 の検証用のリリース https://github.com/VOICEVOX/voicevox/releases/tag/0.12.2-preview を Linux と macOS で試したところ、`.env` を見つけられずエンジンが起動できないことがわかりました（ #794 の変更で、起動時に `.env` がカレントディレクトリにある想定になったためと考えられます。一方で、配布パッケージではカレントディレクトリがどこであったとしても、`.env` が実行ファイルと同じディレクトリにあることを想定しています。Linux の AppImage については詳しくないのですが、少なくとも macOS の App bundle では、カレントディレクトリは実行ファイルのあるディレクトリにはならないです）。
以上の問題を解決するため、配布パッケージの実行時にはこれまで通り `appDirPath` にある `.env` を読みに行くように条件分岐を加えました。
https://github.com/PickledChair/voicevox/releases/tag/0.12.0-pickledchair-0 に試験的にリリースを公開しています。手元の環境で Linux と macOS 双方での動作を確認しました。
#794

Fix: LinuxとmacOSの配布パッケージを動作可能にする

---

src/store/audio.ts

「テキスト読み込み」とテキストを繋げて書き込み」機能で「キャラ名」だけでなく「キャラ名(スタイル名)」を扱えるようにする。
*「テキスト読み込み」機能：「キャラ名」のみ指定された場合デフォルトスタイルを採用し、「キャラ名(スタイル名)」が指定された場合、該当スタイルを採用する。
*「テキストを繋げて書き込み」機能：常に「キャラ名(スタイル名)」で出力する。
ref #802

テキストの「読み込み」及び「繋げて書き出し」で「キャラ名(スタイル名)」を利用可能に

---

src/store/audio.ts
src/store/type.ts

- https://github.com/VOICEVOX/voicevox/issues/813
の解決です。
キャラクター切り替え時にinitialize speakerを別途叩くようにし、UI_LOCKをすることでユーザーが処理中であることを気づけるようにしました。
- https://github.com/VOICEVOX/voicevox/pull/817 のマージが先
close #813 
https://user-images.githubusercontent.com/4987327/170884121-5a1d8345-60a5-4c76-b33f-6c670098f47a.mp4
キャラクターロード中に真ん中にインジケータなどを表示したり、
キャラクターを裏で全部ロードするPromiseを動かしたりしても良さそうです。

話者切り替え時にinitialize speakerを叩く

---

src/components/AudioDetail.vue

AudioDetailのタブ（アクセント・イントネーション・長さ）について
再生中にホットキーで移動できない問題を修正しました。（クリックでは移動可能）
不要だと思われるuiLockedのチェックを削除しました。
close #590
初PRです。不手際等ありましたらお知らせください。

再生中、イントネーションなどのタブ移動がショートカットキーで無効になっている

---

src/components/DefaultStyleSelectDialog.vue

タイトル通りです。
デフォルトスタイル選択したときに勝手に流れる部分はそのまま再生されるので、hotfixは出さない予定です。
とりあえず0.12に向けてPRします。
fix #835
VSCodeのVolarだとちゃんと型エラーが出ていました。
Vueテンプレート部分も型検査をテストしても良いかもしれない。

デフォルトスタイル選択画面で音声が再生できなくなっていた

---

package-lock.json
package.json

Electronをv19.0.6に更新します。
軽く使っても特に問題は起こらなかった上、Electronの[v17](https://www.electronjs.org/ja/blog/electron-17-0)、[v18](https://www.electronjs.org/ja/blog/electron-18-0)、[v19](https://www.electronjs.org/ja/blog/electron-19-0)のリリースノートの破壊的変更を見ても特に影響が無かったので大丈夫だと思います。
- Closes: #838

Update: Electron v19.0.6に更新

---

src/components/DictionaryManageDialog.vue

題の通り
フレキシブルなUIを維持するために、少しデザインを変更しました(単語リストのボタン位置修正)
アクセント句が短い場合にセンタリングする機能はうまく動かないのと、別に必要がない気がしたので、削除しました。
さらに、アクセント句関連の変更によって一部デザインが崩れていたので、修正を行いました。
ref #724

辞書のUI修正と不要なCSS/JSの削除

---

src/components/AudioDetail.vue

メイン画面で音声再生ボタンを押した後、音声生成が終わるまで音声停止ボタンが無効になるようにしました。
音声再生/停止ボタンがある箇所はメイン画面と「読み方＆アクセント辞書」画面の2箇所で、それぞれ[AudioDetail.vue](https://github.com/VOICEVOX/voicevox/blob/b6abc60a284cfd3ade1c273d3950f32d91a7d171/src/components/AudioDetail.vue#L22)と[DictionaryManageDialog.vue](https://github.com/VOICEVOX/voicevox/blob/b6abc60a284cfd3ade1c273d3950f32d91a7d171/src/components/DictionaryManageDialog.vue#L134)で定義されています。
元々「読み方＆アクセント辞書」画面の音声停止ボタンは音声生成中は無効になる仕様なのですが、メイン画面の音声停止ボタンでは無効になっていませんでした。
今回の修正でメイン画面の音声停止ボタンに足りなかった記述を追加し、2つの画面の音声停止ボタンの仕様を統一しました。
close #696

音声生成中は音声停止ボタンを無効にする

---

package-lock.json
package.json
src/components/AudioDetail.vue
src/components/AudioParameter.vue
src/components/CharacterOrderDialog.vue
src/components/SettingDialog.vue

辞書優先度UIにおいて、marker labelsというものが使いたいです。
https://quasar.dev/vue-components/slider#marker-labels
この機能を使うためにはQuasarのバージョンをv2.4以上にしなければならいため、更新を行いました。
その際、設定画面が開けなくなる問題、音素長調整UIのデザイン崩壊が起きたため、修正を行いました。
なお、そもそもsliderのUIが変化している(調整可能部分が`3px->4px`と従来のものより太くなっている)のですが、これを許容していいかが知りたいです。
- ref #790

辞書優先度UIのためにQuasarのバージョンを更新

---

src/components/DictionaryManageDialog.vue
src/store/dictionary.ts
src/store/type.ts

題の通りです、優先度スライダーを追加し、優先度を選べるようにしました。
close #790

単語の優先度を設定可能にする

---

src/store/audio.ts
src/store/dictionary.ts
src/store/proxy.ts
src/store/type.ts

EngineProxyからインスタンスをラップしたObjectを返すようにして、Vuexを通しても型が一意に決まるようにした。
Objectに生えているinvokeメソッドを通してDefaultApiのメソッドを実行する実装にした。
この様に一層挟み、かつ `(行いたいAction) => (行いたいActionの引数)` という形で実装したため、Mockやバックエンドの実装がWebWorkerなどに変わってOpenAPI準拠のAPIでなくなってもアダプタが書きやすい形になった。
その処理は本来Factoryに実装するべきなので、将来的にバックエンドが増えた時に再検討する。
ref: https://github.com/VOICEVOX/voicevox/issues/864

EngineProxyの型の整理を行った

---

package-lock.json

```
npx browserslist@latest --update-db
```
を実行してbrowserslistのdbをアップデートしました。
これにより実行時の警告（`Browserslist: caniuse-lite is outdated.`）が消えます。
自分の環境では正常に動きました。
None
None
None

Update: browserslistをアップデート

---

src/components/AudioDetail.vue
src/components/Tip.vue

z-indexがたりなくてsliderのつまみがオーバーレイしていたので修正

ツールチップが手前に来るようにする

---

src/store/dictionary.ts

辞書に単語新規登録時にプライオリティが設定されない不具合を修正。
store/dictionary.tsのADD_WORD処理部分で、priorityの取得と、addUserDictWordUserDictWordPostへの引き渡しが漏れていることが原因。
ref #907

Fix: 辞書に単語新規登録時にプライオリティが設定されない不具合を修正

---

.github/workflows/typos.yml
_typos.toml
build/installer_linux.sh
build/splitNsisArchive.js
src/store/audio.ts

- typosのバージョンをv1.10.3に更新
- 更新に伴って見つけたtypoを同時に解消

typosのバージョンをv1.10.3に更新

---

.env.production
src/background.ts
src/components/MenuBar.vue
src/components/MenuItem.vue
src/electron/preload.ts
src/store/audio.ts
src/store/type.ts
src/type/ipc.ts
src/type/preload.ts
tests/unit/store/Vuex.spec.ts

エンジン毎の再起動ボタンを追加します。
voicevox/voicevox_project#2
エンジンが一つしかない場合は従来のUIのようになっています。
<s>![image](https://user-images.githubusercontent.com/59691627/182767205-58e40c80-d4d5-4127-9aa7-7407d54fdc22.png)
何故かクリックできてしまうのでDraft。</s>→修正。

複数エンジン対応：エンジン毎の操作欄を追加

---

src/background.ts
src/type/preload.ts

ユーザーディレクトリ（%appdir%）にenginesディレクトリを追加し、その下にあるエンジンを読み込むようにします。
１．シロワニさんのCOEIROINK試作エンジンをダウンロードして展開（ディレクトリ名はなんでもOK
- https://github.com/VOICEVOX/voicevox_engine/issues/237#issuecomment-1019102584
２．展開した後、そのディレクトリにengine_manifest.jsonが必要なので、適当に↓を保存
```json
{
"manifest_version": "0.13.0",
"name": "COEIROINK ENGINE",
"uuid": "d9212658-962f-4918-80b2-310b7de70c41",
"version": "999.999.999",
"url": "https://github.com/shirowanisan/voicevox",
"command": "run",
"port": 50031,
"icon": "icon.png",
"default_sampling_rate": 24000,
"terms_of_service": "engine_manifest_assets/terms_of_service.md",
"update_infos": "engine_manifest_assets/update_infos.json",
"dependency_licenses": "engine_manifest_assets/dependency_licenses.json",
"downloadable_libraries_path": null,
"downloadable_libraries_url": null, …
```

ユーザーディレクトリにあるエンジンを検知して読み込めるようにする

---

src/store/audio.ts

https://github.com/VOICEVOX/voicevox/blob/5482e27a5e9e60a0d69499a498cdc6bf1ca368f4/src/store/audio.ts#L717-L721
が更新されていないのを修正します。
https://github.com/VOICEVOX/voicevox/blob/5482e27a5e9e60a0d69499a498cdc6bf1ca368f4/src/store/audio.ts#L746-L749
でengineIdつきで呼び出されていることから修正漏れと判断しました。
- ref: #883
（なし）
（なし）

複数エンジン対応：INITIALIZE_ENGINE_SPEAKERの修正漏れを修正

---

src/type/preload.ts

- #872 で、`savingSetting`関数が削除され、同時に`types/preload.ts`に書かれていた型も削除されましたが、 #871 で型だけなぜか戻ってきていました。それが`electron/preload.ts`で型エラーを起こしていたので、修正です。

誤って残っている`savingSetting`の型を削除する

---

src/background.ts

すぐ上でreturnしているので動作上の影響は無さそうでしたが、型的にはundefinedの可能性があるとしてエラーが出ていたので修正しました。

engineProcessのundefinedチェックを追加

---

package-lock.json
package.json
src/store/index.ts

Vuexを4.0.2に更新します。
これにより、DevtoolsからVuexの内容を見ることが出来るようになります（[参考](https://github.com/vuejs/vuex/issues/1942#issuecomment-847427714)）
（なし）
（なし）

Update: Vuexを4.0.2に更新

---

src/views/Home.vue

画面下部に存在していた空白を削除することで対処しました
なぜ下部の空白が消えるとメニューバーが消えなくなるかは 
https://github.com/VOICEVOX/voicevox/issues/901#issuecomment-1243810746 ←こちらのコメントを参照してください
close #901 
どちらもQLayoutのElementを選択している状態で、bodyの `overflow: hidden` を外した状態です
beforeは空白が存在します
afterでは空白が消えているので `overflow: hidden` を外してもスクロールバーが出ません
|before|after|
|----|----|
|![before](https://user-images.githubusercontent.com/241973/190627556-d602dcf2-917c-48a6-b14a-f5d4b3d4e6c8.png)|![after](https://user-images.githubusercontent.com/241973/190627580-1ed9536c-545e-42a8-9886-c21246f976c1.png)|
- ✔️  `<body>` の `overflow: hidden` を外して空白がないことを確認
- ✔️  quasar@2.7.0以上をインストールして #901 と同じ操作を行ってもメニューバーが消えないことを確認
- ✔️  quasar@2.7.0以上をインストールして、適当なスライダーを操作しフォーカスを与えた状態で `document.querySelector("#app > div.q-layout-container").focus()` …

メニューバーが消える不具合に対処

---

src/components/CharacterPortrait.vue

キャラ立ち絵の左下にエンジン名を表示するようにします。
- ref: voicevox/voicevox_project#2：キャラ立ち絵（どこかにエンジン名を書く）
エンジンが１つだけの時は表示されません。
（なし）

複数エンジン対応：キャラ立ち絵にエンジン名を追加

---

src/components/AudioDetail.vue

無効化されたタブにショートカットキーで移動できてしまったバグを修正します。
- closes: #938 
（なし）
（なし）

複数エンジン対応：ショートカットキーで無効化したタブに移動できるバグを修正

---

src/components/AudioCell.vue
src/store/audio.ts
src/type/preload.ts

エンジンのアイコンをキャラアイコンの近くに表示するようにします。
- ref: voicevox/voicevox_project#2：キャラ選択（キャラ名の右下にエンジン名を目立たなく書く）
エンジンが1つの時は表示されません。
エンジン名だと少し微妙だったのでアイコンにしています。

複数エンジン対応：エンジンのアイコンをキャラアイコンの近くに表示するように

---

src/background.ts

#941 を修正します。
自分の環境ではこのパッチでEISDIRがでなくなりました。
- closes: #941
（なし）
Macの分岐コードについてはテストできていませんが、多分大丈夫だと思います。

Fix: 開発中に出るEISDIRを修正

---

src/components/DictionaryManageDialog.vue
src/components/HotkeySettingDialog.vue

キャンセルボタンの位置を左に統一しました。
ref #903
ショートカットキーの画面も一応左に移動しておりますが、こちら不要でしたらお知らせください。
他何かありましたら、微力ながらご協力させていただきます。

キャンセルボタンの位置を統一

---

src/components/HeaderBarCustomDialog.vue

ツールバーのカスタム画面にあるボタンをドラッグ&ドロップで入れ替えられるようにします。
（なし）
https://user-images.githubusercontent.com/59691627/191862191-f1af6f5f-be62-476e-b236-565c7f2de7d9.mp4
（なし）

Add: ドラッグでボタンの並びを変更できるように

---

.env.production
src/background.ts
src/components/AudioCell.vue
src/components/MenuBar.vue
src/helpers/imageHelper.ts
src/store/audio.ts
src/type/preload.ts

MenuBarやAudioCellのアイコンをengine manifestから取得するようにします。
- ref: voicevox/voicevox_project#2： envではなくengine_manifest.jsonから情報を得るようにする
正常に動作しているのが確認出来ました。
（なし）

複数エンジン対応：アイコン情報をengine manifestから取得するように

---

src/components/HelpDialog.vue
src/components/LibraryPolicy.vue
src/components/OssLicense.vue
src/components/Policy.vue
src/components/UpdateInfo.vue

ヘルプにエンジン毎の項目を表示するようにします。
- ref: voicevox/voicevox_project#2： ヘルプの移動 
（なし）

複数エンジン対応：ヘルプにエンジン毎の項目を表示するように

---

src/background.ts
src/electron/preload.ts
src/store/ui.ts
src/type/ipc.ts
src/type/preload.ts

ウィンドウの最大化状態がvuexに反映されてなかったのが原因だったので、
今最大化状態か問い合わせるipcメッセージを追加してstore初期化時に呼ぶようにしました。
close #851 
- 最大化した状態でウィンドウを閉じ、再度起動した際に右上のアイコンが最大化状態になっている
- 元々 `electron:serve` では再現しない問題だったため、
- `electron:build_pnever` でビルド
-  `dist_electron/win-unpacked` に `.env` ファイルをコピー
-  `dist_electron/win-unpacked/electron.exe` を起動
- で再現確認＋動作確認しました

最大化状態で起動しても最大化ボタンのアイコンが変わらないのを修正

---

src/components/AudioDetail.vue

右端にのみ余白を追加してスライダーのツールチップが見切れないようにしました。
cssのlast-childセレクタで実現しています。
close #857 
- 下ペインに横スクロールバーが出る状態で、右端のスライダーツールチップが見切れないことを確認
- 右端以外に影響が出ないことを確認

右端のスライダーツールチップが見切れないようにした

---

src/components/SingerTab.vue
src/router/index.ts
src/views/Home.vue
src/views/SingerHome.vue

開発用に「ボイス」「シング」を分離した環境としてタブ分割する
試行のためなし

project-s: 開発用にタブ分割する

---

src/background.ts
src/components/DefaultStyleSelectDialog.vue
src/electron/preload.ts
src/store/index.ts
src/store/type.ts
src/type/ipc.ts
src/type/preload.ts
src/views/Home.vue

タイトルのとおりです。
0.13.2でスタイル持ちのキャラクターが倍ほどに増えるので、issueにある通り初回のスタイル選択ダイアログを出ないようにします
close #885

初回起動時のデフォルトスタイルID選択のとき、「ノーマル」を最初から選ばれている状態にする

---

src/views/Home.vue

`FETCH_AND_SET_ENGINE_MANIFESTS`を`START_WAITING_ENGINE_ALL`の後に読み込むようにします。
- close: #940 
（なし）
いつもはエンジンを別で動かして常時稼働していたため問題に気がつけませんでした。ごめんなさい。

Fix: Engine Manifestを起動後に読み込むように

---

src/components/AudioCell.vue

キャラクターのスタイル選択にて、q-avatarのサイズが変わっていなかったためスクロールバーが表示されていました。これを修正します。
（なし）
（なし）

Fix: スクロールバーを表示しないように

---

package-lock.json
package.json
src/components/Sing/MenuBar.vue
src/components/Sing/Score.vue
src/components/Sing/ScorePosition.vue
src/components/Sing/ScoreSequencer.vue
src/components/Sing/SingerPanel.vue
src/components/Sing/ToolBar.vue
src/components/SingerTab.vue
src/main.ts
src/store/index.ts
src/store/singing.ts
src/store/type.ts
src/views/SingerHome.vue
tests/unit/store/Vuex.spec.ts

project-s:
- UIベースの追加  `/components/Sing`以下
- SingingStoreとの接続(試行としてシンガー表示領域の表示/非表示切り替え)
※ 別にIssue作成したもののわかりづらいため、次回以降voicevox側に作成いたします
ref: https://github.com/VOICEVOX/voicevox_project/issues/15
ref: https://github.com/VOICEVOX/voicevox_project/issues/16

project-s: UIスケルトンの用意

---

.github/workflows/build.yml

`svenstaro/upload-release-action@v2`で自動作成されたリリースに紐づくtagが、メインブランチの最新コミットを指してしまう問題を修正し、CIが実行されたコミットを指すようにします。
tagのコミットIDを指定できる、`softprops/action-gh-release@v1`を使用するように変更しました。
- 動作確認: <https://github.com/aoirint/voicevox/actions/runs/3270820503>
- 自動作成されたリリース: <https://github.com/aoirint/voicevox/releases/tag/0.13.0-aoirint.1>
- ref <https://github.com/VOICEVOX/voicevox/issues/904>
- コア、エンジン、エディタの修正ができてcloseと思うのでref
- ref <https://github.com/VOICEVOX/voicevox_core/pull/311>
- ref <https://github.com/VOICEVOX/voicevox_engine/pull/489>

CI: 自動作成されるリリースのタグの場所を正しくする

---

.github/workflows/build.yml

code_signingがtrueじゃないとき「false」environmentを使おうとしてしまう問題を解決します。

code_signingがtrueじゃないとき「false」environmentを使おうとしてしまう問題を解決

---

src/store/singing.ts
src/store/type.ts
src/views/SingerHome.vue

SingingStoreStateの初期化と、以下のaction/mutationを追加します。
- シンガーの設定
- デフォルトScoreの取得
- Scoreの設定
デフォルトシンガーの設定は、ひとまずSET_SINGERで行っています。
ご意見、ご指摘等いただけますと幸いです。
ref VOICEVOX/voicevox_project#15
ref #981

project-s: 初期化とシンガー・楽譜を設定するaction/mutationを追加

---

src/store/audio.ts

複数エンジンを登録している場合、「テキストを繋げて書き出し」の話者欄が他のエンジンのキャラクターになってしまうバグを修正します。
ref: voicevox/voicevox_project#2
（なし）
（なし）

複数エンジン対応：書き出し時の名前を修正

---

.env.production
package-lock.json
package.json
src/background.ts
src/type/preload.ts
tests/unit/store/Vuex.spec.ts

engine_manifest.jsonのcommandsフィールドをnode-shlexで分割し、引数を指定できるようにします。
（なし）
（なし）

複数エンジン対応：engineManifestで実行時引数を指定できるように

---

src/store/audio.ts
src/store/engine.ts
src/store/index.ts
src/store/type.ts
tests/unit/store/Vuex.spec.ts

エンジン関連のstoreをaudio.tsから分離します。
（なし）
（なし）
（なし）

Refactor: engine関連のstoreを分離

---

src/components/Sing/CharacterMenuButton.vue
src/components/Sing/SingerPanel.vue
src/components/Sing/ToolBar.vue

シンガーの表示と設定を行うUIを追加します。
AudioCellのCharacterMenuを利用するため、コンポーネントとして切り出しています。
シンガーの表示ですが、キャラクターによって頭身や縮尺が違うため、現状一部キャラクターで見切れます。
レビューよろしくお願いいたします。
ref https://github.com/VOICEVOX/voicevox_project/issues/15
ref https://github.com/VOICEVOX/voicevox/issues/981

project-s: シンガーを表示・設定するUIを追加

---

.github/ISSUE_TEMPLATE/bugreport.md
.github/ISSUE_TEMPLATE/featurerequest.md

Issueを立てたときに自動でラベルがつかないのを修正します
質問は現在タグがないので触ってません

fix: Issue label

---

src/components/MenuBar.vue
src/store/audio.ts
src/store/engine.ts
src/store/type.ts
src/store/ui.ts
src/views/EditorHome.vue

複数エンジン登録時の起動を高速化します。
旧実装：
```mermaid
graph LR
T1[ ]:::empty
A[起動] --- T1
T1 --> B1 & B2
subgraph START_WAITING_ENGINE_ALL
B1[エンジンAの起動待機]
B2[エンジンBの起動待機]
end
T2[ ]:::empty
T2p[ ]:::empty
B1 & B2 --- T2p
T2p --- T2
T2 --> C1 & C2
subgraph FETCH_AND_SET_ENGINE_MANIFESTS_ALL
C1[エンジンAのManifest読み込み]
C2[エンジンBのManifest読み込み]
end
T3[ ]:::empty
T3p[ ]:::empty
C1 & C2 --- T3p
T3p --- T3
T3 --> D1 & D2
subgraph LOAD_CHARACTER_ALL
D1[エンジンAのキャラクター読み込み]
D2[エンジンBのキャラクター読み込み]
end
T4[ ]:::empty
T4p[ ]:::empty
D1 & D2 --- T4p
T4p --- T4
T4 --> E[UNLOCK_UI]
classDef empty width:0px,height:0px;
```
新実装：
```mermaid
graph LR
t1[ ]:::empty
a[起動] --- t1
t1 --> b1 & b2
subgraph  
b1[エンジンAの起動待機] --> c1
c1[エンジンAのManifest読み込み] --> d1
d1[エンジンAのキャラクター読み込み]
end
subgraph  
b2[エンジンBの起動待機] --> c2
c2[エンジンBのManifest読み込み] --> …
```

Improve: 複数エンジン登録時の起動を高速化

---

src/components/EngineManageDialog.vue

エンジン管理ダイアログにて、バージョンの欄が埋まらなかったバグを修正します。
（なし）
（なし）
（なし）

複数エンジン対応：エンジンバージョンが更新されないのを修正

---

src/background.ts
src/components/Sing/MenuBar.vue
src/electron/preload.ts
src/store/singing.ts
src/store/type.ts
src/type/ipc.ts
src/type/preload.ts
src/views/SingerHome.vue

MIDIファイルとMusicXMLファイルをインポートする機能を追加します。
MusicXMLを扱えるライブラリで導入しやすそうなものが見つからなかったので、ひとまずパース処理を実装しました。
簡単な楽譜で動作を確認していますが、読み込めない楽譜もあるかもしれません…
また、showImportFileDialogで、ファイルの種類を指定できるように変更しています。
レビューよろしくお願いいたします。
ref VOICEVOX/voicevox_project#15
ref #981

project-s: MIDIファイルとMusicXMLファイルをインポートする機能を追加

---

src/components/Sing/ToolBar.vue
src/store/singing.ts
src/store/type.ts

テンポ・拍子の表示と設定を行う機能を追加します。
action/mutationとリアクティブ周りの実装が不安なので、ご指摘等いただけますと幸いです。
レビューよろしくお願いいたします。
ref VOICEVOX/voicevox_project#15
ref #981
UIのデザインは仮なので、また後で調整できればと思います。

project-s: テンポ・拍子の表示と設定を行う機能を追加

---

.github/workflows/build.yml
.github/workflows/test.yml

非推奨警告が出ないように、`set-output`を`GITHUB_OUTPUT`に変更します
- 現在のmainブランチのbuild.ymlによるCI: <https://github.com/VOICEVOX/voicevox/actions/runs/3575688234>
- 現在のmainブランチのtest.ymlによるCI: <https://github.com/VOICEVOX/voicevox/actions/runs/3575688236>
- GITHUB_OUTPUTのドキュメント: <https://docs.github.com/ja/actions/using-jobs/defining-outputs-for-jobs>

CI: 非推奨化されたset-outputをGITHUB_OUTPUTに変更

---

src/components/EngineManageDialog.vue

タイトル通り。engineManifestが取得できたときはエンジンが起動しているのは確定しているので、engineManifestsも監視するようにしました。
- ref:voicevox/voicevox_project#2
（なし）
（なし）

複数エンジン対応：エンジン管理ダイアログでバージョンが出ないときがあるのを修正

---

src/background.ts

複数エンジン時、エンジンのエラー終了時のダイアログにエンジン名を表示するようにします。
（なし）
（なし）

複数エンジン対応：エラーダイアログを複数エンジン時に変えるように

---

src/components/EngineManageDialog.vue

`セキュリティ上の驚異を紹介し、信頼できるエンジンかを問う`というタスクです。
- https://github.com/VOICEVOX/voicevox_project/issues/2
文面の方針として次のことに意識しました。
* わからない人は追加を辞めるように強い表現にする
* 大丈夫そうかを自己判断できる指標を文面に加える
* 「～して追加してください」という表現を避ける

エンジン追加の際にセキュリティ上の驚異を紹介し、信頼できるエンジンかを問う

---

src/components/EngineManageDialog.vue

engineVersionsで`continue`を使うべきところを間違えて`return`していました。これを修正します。
（なし）
（なし）

複数エンジン対応：enginveVersionsが埋まらないのを修正

---

src/components/AudioCell.vue
src/components/AudioDetail.vue
src/components/AudioInfo.vue
src/components/CharacterButton.vue
src/components/CharacterPortrait.vue
src/store/proxy.ts

AudioCellに未起動のエンジンのスタイルが適用されているとセルが一切表示されなくなっていました。
複数エンジンに対応するとこの状況は普通に起こり得る現象になります。
最低でもスタイルを再選択できるように修正を行います。
- ref https://github.com/VOICEVOX/voicevox_project/issues/2#issuecomment-1341495231
プロジェクトファイルを手動で編集してテスト
- 未起動のエンジンや存在しないスタイルを利用したプロジェクトを読み込んだもの
- 無効なスタイルが適用されているキャラクター選択ボタン
AudioCellとCharacterButtonだけを直せばいいかと思っていましたが割と影響範囲が多く場当たり的な対応をしている部分もあります。

FIX: AudioCellのStyleが不明でも表示が壊れないようにする

---

src/background.ts
src/components/EngineManageDialog.vue

VVPPアンインストール時と、ディレクトリ見つからない時のエラーハンドリング追加しました。
- https://github.com/VOICEVOX/voicevox_project/issues/2

VVPPアンインストール時とディレクトリ見つからない時のエラーハンドリング追加

---

src/background.ts
src/components/EngineManageDialog.vue
src/components/MenuBar.vue
src/electron/preload.ts
src/store/engine.ts
src/store/type.ts
src/type/ipc.ts
src/type/preload.ts
src/views/EditorHome.vue
tests/unit/store/Vuex.spec.ts

「サブエンジン」と「メインエンジン」と合わせて「デフォルトエンジン」と呼び、
「ユーザーディレクトリにあるエンジン」をなかったことにするプルリクエストです。
参考コメント https://github.com/VOICEVOX/voicevox_project/issues/2#issuecomment-1356267138
- https://github.com/VOICEVOX/voicevox_project/issues/2
`.env`の`DEFAULT_ENGINE_INFOS`に２つ登録したときのスクショです。
デフォルトエンジンとして２つ表示されています。

デフォルトエンジンに変更、ユーザーディレクトリにあるエンジンを省略

---

src/background.ts

Macでvvppを開けないようになっていたので、`openFile`プロパティを付与し、ファイルを開けるようにしました。
- VOICEVOX/voicevox_project#2
変更前
変更後

vvpp: MacでVVPPファイルを開けるように修正

---

src/background.ts

[SHAREVOX/sharevox_engine:0.2.0-preview.1](https://github.com/SHAREVOX/sharevox_engine/releases/tag/0.2.0-preview.1)で試して見付かった幾つかのバグを修正します。
- Voicevoxが複数起動していないとき（=`requestSingleInstanceLock`が成功したとき）、vvppファイルをvvprojファイルとして見なしてしまいエラーが出ていたのを修正
- Voicevoxが複数起動していないときに、一回再起動しなくても良い実装があったので変更
- Voicevoxが複数起動しているとき、起動したVoicevoxが終了されないのを修正
- cwdがインストールディレクトリにならず、エンジン起動時にENOENTを吐いていたのを修正（Firefoxのダウンロードタブから直で開くと、cwdがダウンロードフォルダになる？）
また、Linux/Macにて実行権限がついておらず、起動できないバグもあります。これはLinux/Macを持っている方にお願いしたいと思います。
（なし）
（なし）

複数エンジン対応：いくつかのvvpp関連のバグを修正

---

src/views/EditorHome.vue

単一エンジン起動時の時はセーフモードのボタンを出さないようにしました。
また、時間を10秒から1分にしています。
今までの平均起動時間みたいにしても良いかもしれない…？
（なし）
（なし）

複数エンジン対応：単一エンジン時はセーフモードボタンを出さないように

---

.github/workflows/build.yml

publicディレクトリにキャラデータコピーは不要なので省きます。
昔はリソースファイルをエディタに実装していました。
キャラ名がファイル名になる設計だったらしく、`小夜/SAYO`がディレクトリ名と勘違いされてエラーになってしまいました。
おそらくコード自体不要なはずなので、消去します。

[release-0.13] publicディレクトリにキャラデータコピーは不要なので省く

---

src/background.ts
src/components/SettingDialog.vue
src/store/proxy.ts
src/store/setting.ts
src/store/type.ts
src/type/preload.ts

- https://github.com/VOICEVOX/voicevox/issues/1044
を受けて、`outputSamplingRate`用の"default"を"engineDefault"に変更します。
close #1044

outputSamplingRate用の"default"を"engineDefault"に変更

---

src/background.ts

mac版は.app内にエンジンディレクトリがあるけど、デフォルトでは.appの中に入れないので入れるようにしてみました。
- https://github.com/VOICEVOX/voicevox_project/issues/2#issuecomment-1369506837
ディレクトリ選択以外は不要そうですが、.appを選ぶ機会が無い気がするのでついでに他のとこにも付けておきました。
サンプルvvprojが`.app`にあっても開けるので安心です。

エンジンディレクトリ選択で.app内に入れるようにする

---

src/components/DictionaryManageDialog.vue

辞書UIの操作感を改善します。
- 単語をダブルクリックで編集
- 左のペインをクリックでキャンセル
- 単語編集中は辞書UIを閉じるボタンを無効化
（なし）
https://user-images.githubusercontent.com/59691627/210121789-d1dfe4b8-8108-40f9-b1a8-822f77c1f532.mp4
（なし）

Improve: 辞書UIの操作感を改善

---

public/qAndA.md
src/background.ts

- #337 の解決です。
close #337 
最初は`app.setName()`でアプリ名を操作するつもりでしたがそれだけでは保存ディレクトリが変更されなかったので`userData`のディレクトリを`voicevox`と指定しまうことにしました。
開発版のログが製品版のディレクトリに保存されてしまう問題もついでに修正されました。
`electron-log`の既知の問題によりデフォルトのログのディレクトリが必ず作成されてしまいます。

FIX: electron-storeの保存場所をGPU版と統一する

---

src/background.ts
src/background/engineManager.ts
src/electron/preload.ts
src/type/preload.ts

エンジンを全部再起動するのが２経路存在してしまっていたので、使われていない片方を消します。
残しといても良いかもなのですが、メンテされなくなったこれを使っちゃったり、間違ってこちらを使っちゃったりするのが容易に起こりそうだったので、気づいた今消しておこうかなーと･･･。
（残しといても良いのでは的な賛否両論ありそう）
- https://github.com/VOICEVOX/voicevox/pull/1062
は使われてる方の`RESTART_ENGINE_ALL`を変更しているのですが、こちらとコンフリクトしない（つまり完全に独立してる）ことは確認済みです。

メインプロセス側のRESTART_ENGINE_ALLが使われてないので消しておく

---

src/background.ts
src/electron/preload.ts
src/store/index.ts
src/store/type.ts
src/store/ui.ts
src/type/ipc.ts
src/type/preload.ts

window.electron.errorなどはコンソールにエラーを出しますが、コードジャンプができないのでちょっと不便です。
electron側（ブラウザ側）にも表示すれば便利かなと思ったのでそうしてみました。
ついでにlogWarnを作っています。

ログをブラウザのconsole.logにも出力

---

package-lock.json
package.json
src/components/AcceptRetrieveTelemetryDialog.vue
src/components/AcceptTermsDialog.vue
src/components/HelpPolicy.vue
src/components/HowToUse.vue
src/components/OssCommunityInfo.vue
src/components/QAndA.vue

マークダウン系のコンポーネントをscript setupに移行します。
どのファイルを変更したかはFiles Changedを参照して下さい。
- ref: #1065 
（なし）
（なし）

script setup：マークダウン系のコンポーネントを移行

---

.github/workflows/test.yml

node_modulesをキャッシュして、テストを高速化します。
（なし）
（なし）
（なし）

Add: node_modulesをキャッシュするように

---

docs/細かい設計方針.md

StyleIdが話者ごとに唯一であれば良い、という説明は実際と乖離しているので修正します。
理想はそうなったら嬉しいなということなので、その点を追記しました。

EngineId、SpeakerId、StyleIdの説明が間違ってるところを修正

---

.eslintrc.js
docs/細かい設計方針.md
src/components/MenuItem.vue

template、script、styleの順序を統一する[eslint-plugin-vueのルール](https://eslint.vuejs.org/rules/component-tags-order.html)を導入します。
また、細かい設計方針にこのことについて追記します。
MenuItem.vueが違反していたので直しています。
（なし）
（なし）
（なし）

script setup：template、script、styleの順序を統一

---

src/components/EngineManageDialog.vue

再起動ボタンをエンジンがエラー落ちしたときに押せるようにします。
（なし）
（なし）

複数エンジン対応：再起動ボタンをエラー時に押せるように

---

.github/workflows/build.yml

+ https://github.com/VOICEVOX/voicevox_engine/pull/537
+ https://github.com/VOICEVOX/voicevox/issues/1109
に従いエンジンの取得先を修正しました。
close #1109
手元で動かしたところ`upload-distributable-to-release (ubuntu-18.04, windows-nvidia-prepackage-zip)
`で`Error: File size (2213762496) is greater than 2 GB`のエラーで落ちました。

VOICEVOX ENGINEのパッケージ名変更に追従

---

src/background/engineManager.ts
src/background/vvppManager.ts
src/type/preload.ts

題の通り
エンジンの実行ファイルに実行権限が付与されないために、エンジンの起動に失敗する問題があったので、それを修正しました。
- ref #991 
- ref #1058 
- ref voicevox/voicevox_project#2
エンジンのAPIから帰ってくる`engine_manifest`と`engine_manifest.json`は実態が全然違うので、本来は分けて型定義すべきな気がするので、FIXMEやTODOにするべき...?

vvpp経由でインストールされたエンジンをmacとlinuxでも起動できるようにする

---

src/background.ts
src/background/configMigration014.ts

config.jsonの場所（設定の場所）が、以前はデバイス依存でディレクトリ名が変わっていたのが、0.14で`%appdata%/voicevox`に固定されます。
- https://github.com/VOICEVOX/voicevox/issues/1008
このPRでは、以前の場所にconfig.jsonがあればコピーするようにします。
- https://github.com/VOICEVOX/voicevox/issues/1008
- https://github.com/VOICEVOX/voicevox/pull/1005
close #1008
開発バージョンの場合、以前は`%appdata%/voicevox`、今は`%appdata%/voiecvox-dev`になっています。
なので`voicevox/config.json`を消したり`voiecvox-dev/config.json`のバージョンを変えたりでデバッグできると思います。
あまり興味持たれない場所だと思うので、ある程度時間が経ってから見直されたときにわかるよう、ちょっと丁寧にログ出力しています。

0.14でconfig.jsonの場所が変わるのでマイグレーション

---

src/background/vvppManager.ts

題の通りです
今まではユーザーに対して実行権限を付与するようなコードでしたが、`fs.chmod`ではそのような書き方ができなかったので、`755`(ユーザーは読み書きと実行、それ以外は読みと実行ができる)にしました。
- ref #1112

vvppエンジンへの実行権限付与に`spawnSync`ではなく`fs.promises.chmod`を使うようにする

---

src/components/HeaderBar.vue

連続再生時にエラーが発生すると投げられたエラーメッセージがそのまま表示されてしまう。
https://twitter.com/BEAT_CAT2/status/1615474061781630978
モーフィングUI作成時にエラーハンドリングを何度か変更したのですが最終的に変更を忘れてしまったことが原因です。

FIX: 連続再生時にエラーが正しく表示されない問題を修正

---

src/background.ts
src/components/DefaultStyleSelectDialog.vue
src/store/audio.ts
src/store/index.ts
src/type/preload.ts

テキストファイルの読み込み機能が複数エンジンに対応できていなかったので対応させました。
また、テキストファイルの読み込みに利用している`DEFAULT_STYLE_IDS`にEngineIDが追加されていませんでしたので追加しました。
とりあえず急ぎで対応させたので無駄が多いかもしれません。

複数エンジン対応: テキスト読み込みを複数エンジンに対応

---

src/components/DictionaryManageDialog.vue

単語登録時に含まれている半角スペースを全角スペースに変換するようにしました。
ref #1115 
入力時
入力後
目に見えないような文字で同じような問題が起こるのを防ぐために、
半角スペースだけではなくUnicodeプロパティがSeparatorのものすべて全角スペースに変換するようにしました。
何か問題等ございましたら微力ながら対応いたします。

辞書単語登録時の半角スペースを全角スペースに変換

---

src/background.ts
src/electron/preload.ts
src/store/setting.ts
src/type/ipc.ts
src/type/preload.ts

macOS環境で、ChromiumのテーマをVOICEVOXのテーマに合わせるように変更しました。
Chromiumのテーマを変更するにはメインプロセスから値を代入する必要がありますが、レンダラープロセスから操作できるように新しくipcを生やしました。
より良い方法があれば修正したいので、教えていただけますと幸いです。
close #1132

[macOS] テーマを改善 #1132

---

build/installer_linux.sh
src/background.ts
src/background/vvppManager.ts
vue.config.js

タイトル通り。
（なし）
（なし）
理由としては、
`engine.0.vvpp`の場合、バージョンを名前に入れている場合、`engine.1.0.0.vvpp`と`engine.1.0.1.vvpp`が分割vvppとして認識されてしまっていたためです。

複数エンジン対応：分割vvppファイルの拡張子をvvpppに

---

src/components/ErrorBoundary.vue

`ErrorBoundary`にある`unhandledrejection`イベントはPromiseでrejectされたときのオブジェクトが`event.reason`に渡ってくる。
objectの型はerror型じゃないこともあり、その場合は何が起こったか全くわからない（`.stack`がundefinedになる）
error型が返った場合はlogErrorに、そうでない場合はErrorに包むようにした。
ついでにhttp通信エラーによる`Response`の場合はURLがlogErrorに書かれるようにした。
そもそも全てのrejectでErrorを返すべきな気がしますが、かなり大変だしコーディングが面倒そうなので、とりあえずFIXMEコメントを書いています。

Promiseのエラーハンドリングを改善

---

src/components/SettingDialog.vue
src/store/engine.ts
src/store/type.ts
src/store/ui.ts
tests/unit/store/Vuex.spec.ts

cudaかDirectMLが利用できないときに、GPUモードへの切り替えをできないようにしました
ref #298
- cudaかDirectMLを利用できるとき(GPUがないので手動で状態を変えています)
- cudaかDirectMLを利用できないとき
- GPUがないためCPU環境のみでの検証しています。GPUを持っているどなたか確認していただければ...
- Vue初心者なのでとんでもないコードを書いているかもしれません。お伝えいただければ修正いたします。

#298 CPU版でGPUモードへの切り替えを不可能に

---

.github/workflows/build.yml
build/generateLicenses.js

タイトル通り。
- MacのビルドがEEXISTで落ちていたのを修正します。参考：https://github.com/electron-userland/electron-builder/issues/3179
- ライセンス生成がENOBUFで落ちていたのを修正します。
（なし）
（なし）
ライセンス生成は、適当なファイルに書き出すようにして、それを読むようにした方が良いかもしれません。
今の実装だとライセンスのjsonが10MiBを超えると死ぬはずです。

Fix: ビルドが通らないのを修正

---

src/views/EditorHome.vue

isEngineWaitingLongの初期値がtrueになっていたので修正。
エンジン起動開始したらfalseに戻るけど、変なので。
thx @sevenc-nanashi ！

isEngineWaitingLongの初期値がtrueになっていた

---

src/components/MenuBar.vue
src/components/SettingDialog.vue

- タイトルバーのCPU/GPU表記が常にCPU表記になっている（削除することで対応、 @Hiroshiba さんからの同意も得ています）
- エンジン選択のセレクトメニューが常に表示されている
のを修正します。
（なし）
（なし）
（なし）

Hotfix: タイトルバーとエンジン選択を修正

---

src/type/preload.ts

zodToJsonSchemaがかかるz.objectに`.passthrough()`を付与し、ConfigSchemaViolationを阻止します。
（なし）
（なし）
脱electron-storeの理由がまた一つ増えた…

Hotfix: ConfigSchemaViolationを修正

---

public/qAndA.md

Q&Aの一部表記がぶれていたので修正

---

src/components/DefaultStyleListDialog.vue
src/components/DefaultStyleSelectDialog.vue

script setup: デフォルトスタイルのダイアログを移行

---

src/components/CharacterButton.vue

キャラ選択ダイアログを開いた時、現在のキャラがリストの一番上に来るようにしました。
これにより、ダイアログ下側のキャラをスクロールせずにスタイル変更できるようになります。
ref #897 
- 例1
- 例2
実装やクラス名が非常に残念な感じになってしまいました。お伝えいただければ修正いたします。
クラスを出し分けしているところは下にあったものをコピペしたので変数にまとめたほうが良いかもしれません。

選択中のキャラが一番上に表示されるようにした

---

src/store/audio.ts

デフォルトエンジン以外のキャラクターが先頭になっていると正しくキャラクターが選ばれない問題を修正します。
- close #1167 
`0.14`では選択される`EngineId`がデフォルトのエンジンに固定されているため先頭にしているstyleIDがCOICEVOXにない場合は無効なスタイルが選択されてしまいます。
- #1092 
の変更で無効なスタイルになることはなくなりましたが、ミスでキャラクターの順番が反映されなくなってしまいました。
https://github.com/VOICEVOX/voicevox/blob/a22046c731dbd88794a0e2e0d0a632b977bf5e29/src/store/audio.ts#L489-L494

FIX: 最初に設定されるキャラクターが正しく選択されない問題を修正

---

src/background.ts
src/background/engineManager.ts
src/background/vvppManager.ts
src/components/EngineManageDialog.vue
src/components/LibraryPolicy.vue
src/components/SettingDialog.vue
src/electron/preload.ts
src/store/audio.ts
src/store/dictionary.ts
src/store/engine.ts
src/store/project.ts
src/store/setting.ts
src/store/type.ts
src/type/ipc.ts
src/type/preload.ts
src/views/EditorHome.vue
tests/unit/store/Vuex.spec.ts

EngineIdをただのstringからユニークな型（brand型）に変更します。
これによりRecordのキーなどの変数が厳密になり、コーディングミスを失くしやすくなるはず･･･！
- https://github.com/VOICEVOX/voicevox/issues/1148
方針としては、string型になっていたところを全てEngineIdにしています。
またzod schemaが必要なとろろはengineIdSchemaを指定しています。
一部undefinableにする必要があり、throw Errorするロジック周りがたされていたりします。

EngineIdをユニークな型にする

---

src/store/audio.ts

テキストの読み込みを行った場合の最初のキャラクターが常にキャラクター順の先頭のものでした。
これを引き継ぎ元のキャラクターを選択するようにします。
https://twitter.com/efusuku/status/1616358760607514625

ENH: テキスト読み込みで最初に選択されるスタイルを引き継ぎするようにした

---

.github/workflows/build.yml
.github/workflows/test.yml

タイトル通り。
参照： https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#node-version-file 
（なし）
（なし）
これを機にNode.jsを18にあげてもいいかもしれない？

Fix: Node.jsのバージョン取得にnode-version-fileを使うように

---

src/components/HotkeySettingDialog.vue

ダークモード時のショートカットキー初期化ダイアログのボタンの視認性が悪かったので、text-colorをsecondaryからdisplayに変更しました。
ref #1193 
close #1193

ショートカットキーの初期化のtext-colorをdisplayにした

---

src/components/CharacterButton.vue

- https://github.com/VOICEVOX/voicevox/pull/1176
で、モーフィング側の順番も変わってしまうのを修正しました。
ついでに`-item`という名前のクラスが`q-item`に付いてないことが多かったので、itemにつけるものは`-item`に統一し、そうでないものは`selected-background`に統一しました。

モーフィングでの並び順が変わっていたので変更

---

src/components/AudioCell.vue
src/components/AudioDetail.vue
src/components/AudioInfo.vue
src/components/CharacterPortrait.vue
src/components/Dialog.ts
src/components/HeaderBar.vue
src/components/LibraryPolicy.vue
src/store/audio.ts
src/store/project.ts
src/store/type.ts
src/type/preload.ts
src/views/EditorHome.vue

AudioKeyをブランド型にしました。
EngineIdやSpeakerIdと全く同じやり方です。
- https://github.com/VOICEVOX/voicevox/issues/1210

AudioKeyに型を付ける

---

src/components/CharacterButton.vue
src/components/CharacterOrderDialog.vue
src/components/CharacterPortrait.vue

タイトル通り。
- ref: #1065 
（なし）
（なし）

script setup：キャラクター系を移行

---

tests/e2e/example.spec.ts
vite.config.ts

e2eテストを走らせたときの細かい挙動を修正します。
- vite-plugin-electron側でelectronを立ち上げないようにします。
- ESLint/tscのチェックを消します。（テストが9秒くらい遅くなっている、ログが流れる、専用のscriptがある）
- ref: #182
（なし）
（なし）

Fix: e2eテストの細かい挙動を修正

---

src/background.ts
src/electron/preload.ts
src/store/project.ts
src/store/type.ts
src/store/ui.ts
src/type/ipc.ts
src/type/preload.ts

Twitterでこのような要望をみかけたためある程度改善してみました。
https://twitter.com/HanoMotoCraft/status/1629101061415006209
- デフォルトのカーソルをキャンセルに変更。
- 保存ボタンを追加して保存が成功した場合はそのまま終了、キャンセルした場合は警告をキャンセルした場合と同じ状態へ。
(Windowsのメモ帳と大体同じ動作?)
Windows以外の環境での表示は確認できていません。

ENH: 未保存時のダイアログを改善

---

src/store/project.ts
src/store/type.ts
src/store/ui.ts

プロジェクトの変更を破棄するかを聞く箇所は３箇所あり、その１箇所が良い感じになりました。
- https://github.com/VOICEVOX/voicevox/pull/1238
このPRでは処理を共通化し、残り２箇所も良い感じにします。
- https://github.com/VOICEVOX/voicevox/pull/1238

プロジェクトの変更を保存するかを聞く部分を統一化

---

src/components/EngineManageDialog.vue

同じエンジンを重複して保存できてしまう問題を修正します。
1. テキストの追加等をして未保存状態(閉じようとすると保存ダイアログが表示される状態)にする
2. EngineManageDialog開きエンジンを追加する
3. 再起動のダイアログが表示されるので再起動ボタンを押す
4. プロジェクトの保存を確認するダイアログが表示されるのでキャンセルする
5. 追加ボタンが押せる状態なので押すともう一度追加操作ができてしまう
特に既存エンジンを重複登録すると同じエンジンを同時に起動させようとしてしまうため起動が不可能になってしまいます。
ついでに型エラーを修正しておきましたがこの辺りのいい対処方法が分からなかったのでエラーのままにしています。
https://github.com/VOICEVOX/voicevox/blob/cb7203df19b407ca9c7d086ea02cf7748cff2ee4/src/components/EngineManageDialog.vue#L280-L285

FIX: エンジン追加後にプロジェクトの保存をキャンセルすると同じエンジンを複数登録できてしまう問題を修正

---

.github/workflows/build.yml
public/qAndA.md

ubuntu 18がGithub Actionsから4/1に消えるので、脱却します。
- https://github.com/VOICEVOX/voicevox/issues/913
close #913
現在お試しビルド中です
2023/03/11 19:18　ビルドが完了しました
https://github.com/Hiroshiba/voicevox/releases/tag/0.15.0-remote-ubuntu18.0

ubuntu18の脱却

---

.github/workflows/build.yml

- https://github.com/VOICEVOX/voicevox/issues/837
関連のPRです。
build.ymlのbuild-prepackageジョブとbuild-distributableジョブを統合し、１つのジョブにします。
実際にビルドしてみてwindowsのzip版が動くことを確認済みです。
https://github.com/Hiroshiba/voicevox/releases/tag/0.15.2-buildtest
#837
あとはreleaseアップロード周りを統一すればかなり早くなる＆リファクタリングもしやすく鳴るはず！！

build-prepackageとbuild-distributableを統合する

---

docs/UX・UIデザインの方針.md

ボイボ系ソフトに関する名称の方針について、COEIROINK・SHAREVOX・LMROID・ITVOICEの方々とは連絡を取っていたのですが、そういえばドキュメントに書いていなかったので追記してみました。
- https://github.com/VOICEVOX/voicevox_project/issues/2
（ドキュメントは別リポジトリに移したいですね･･･ 😇 ）

ボイボ系ソフトに関する名称の方針を追記

---

.github/actions/upload-release-and-artifact/action.yml
.github/workflows/build.yml
.github/workflows/typos.yml
_typos.toml

- https://github.com/VOICEVOX/voicevox/issues/837
を一旦完了させるタスクです。
build.yml内に書かれていた多段のjobが、これで１つのjobになります。
artifactにアップロード・ダウンロードする工程がなくなり、遅いjobを待つこともないため全体的に早くなりました。
以前のAction（54min）
https://github.com/Hiroshiba/voicevox/actions/runs/4454000489
PRのActoin（26min）
https://github.com/Hiroshiba/voicevox/actions/runs/4455163321
close #837
実際にRelease assetsを作ってみたのの比較です。
以前の https://github.com/Hiroshiba/voicevox/releases/tag/0.15.0-noreleasejob
PRの https://github.com/Hiroshiba/voicevox/releases/tag/0.15.0-noreleasejob.2
実際にどちらもダウンロードしてアーカイブファイルを展開し、ファイル名が一致することを確認しました。
<details>
<summary>確認コード</summary>
```bash
set -eux
repo="Hiroshiba/voicevox"
tag1="0.15.0-noreleasejob"
tag2="0.15.0-noreleasejob.2"
gh release download $tag1 --repo $repo --dir assets1
gh release download $tag2 --repo $repo --dir …
```

build.ymlのbuild部分とupload部分を一貫させる

---

.github/actions/upload-release-and-artifact/action.yml

バージョン999.999.999が勝手にリリースされる問題が起きたバグを解消します。
close #1260

upload_releaseとupload_artifactフラグを使うように修正

---

.github/workflows/build.yml

release-0.14ブランチはまだbuild.ymlのJobの一本化がされておらず、mainブランチでは一本化後にubuntu18脱却をしていたため、ubuntu18の部分が残ってしまっていました。
その部分の修正です。
- https://github.com/VOICEVOX/voicevox/issues/913

[release-0.14] ubuntu18脱却漏れ

---

src/components/AudioCell.vue

タイトル通り。
- close: #1268 
（なし）
（なし）

Fix: テキスト欄削除ショートカットが動かないのを修正

---

src/components/AudioDetail.vue
src/views/EditorHome.vue

- #1271 の修正です
`ref` の型定義はこうなっています。
```
ref: VNodeRef
type VNodeRef = string | Ref | ((ref: Element | ComponentPublicInstance | null, refs: Record<string, any>) => void);
```
`addAudioCellRef` の型は `(audioCellRef: typeof AudioCell) => void` です。（ `typeof AudioCell ≒ ComponenPublicInstance` ）
これが `(ref: Element | ComponentPublicInstance | null, refs: Record<string, any>) => void` と互換性がなくエラーになっていました
（ `(A | B) => void` を要求しているところに `A => void` は入れられない。 `(A => void) | (B => void)` ならOK）
`addAudioCellRef` の型は `VNodeRef` にしておき、中で型の絞り込みを行っています。
また、 `AudioCell` であることも分からないのでtype assertionしています。
`<audio-cell>` コンポーネントの `ref` を指定しているんだからvueが推論して欲しい気もしますね・・・
- close #1271

コンポーネントのrefを追加する関数の型を修正

---

.eslintrc.js
src/electron/preload.ts
src/type/globals.d.ts
src/type/ipc.ts
src/type/preload.ts
src/type/shims-vue.d.ts

Electron非依存でEditorUIを動作させるのに、型的にも非依存であることが示されていると進めやすいため、型の調整を行いました。
また今後electronのモジュールをimportしてしまわぬようにlintでも弾くようにしています。
ref: https://github.com/VOICEVOX/voicevox/issues/1204

Electronのmain processで直接動作するコード以外からelectronに関する型を排除する

---

src/composables/useDefaultPreset.ts
src/store/audio.ts
src/store/preset.ts
src/store/type.ts

- #1247 
で後回しにしたリファクタを行いました。
以下は上記issueのコピペです
- **mutation内で渡した引数を直接書き換えているコードをどうにかする**
- https://github.com/VOICEVOX/voicevox/pull/1228#discussion_r1129821236
- 同コメントのツリー内に修正方針をコメント済み
- **`determineNextPresetKey` の引数を整理する**
- https://github.com/VOICEVOX/voicevox/pull/1228#discussion_r1125717135
- **defaultPresetか判定する関数がcomposablesに存在するが、vuexでも同様の判定をしていて重複している**
- https://github.com/VOICEVOX/voicevox/pull/1228#discussion_r1131799080
- getterにO(1)で判定できるようにしたデータの中間表現を置いて、それを使って判定できるようにすると良さそう
引数で渡したaudioItemを直接書き換えていた問題  https://github.com/VOICEVOX/voicevox/pull/1228#discussion_r1129821236 は、「audioItemと presetItemを取ってプリセット適用済みの新しいaudioItemを返す関数」に切り出すことで解決しました。
該当コミット： 92bf9ad
close #1247

デフォルトプリセット周りのリファクタ

---

src/components/MenuBar.vue
src/components/MenuButton.vue
src/components/MenuItem.vue
src/store/project.ts
src/store/setting.ts
src/store/type.ts
src/type/preload.ts

Add: 最近開いたプロジェクト一覧を追加

---

src/components/AudioCell.vue
src/components/SettingDialog.vue
src/store/setting.ts
src/store/type.ts
src/type/preload.ts
tests/unit/store/Vuex.spec.ts

オプション機能として, 行番号を追加します
closes #1149 
視認性は悪くないですね...たぶん
_なし_

行番号を表示するオプション機能をつける

---

tests/e2e/example.spec.ts

e2eテストで、起動が遅くタイムアウト扱いになりFlaky化してしまっていたのを修正します。
- ref: #1276 
（なし）
（なし）

Fix: e2eテストのタイムアウトの指定を修正

---

.github/workflows/build.yml

mac上ではlinuxやwindowsと違って、sedコマンドがGNU sedではなくBSD sedになっています。
sed_nameで切り替えていましたが、`/usr/local/opt/gnu-sed/libexec/gnubin`をPATHに追加するとスマートかもと思ったのでそうしてみました。
リリーステスト https://github.com/Hiroshiba/voicevox/releases/tag/0.15.0-check-gnused.0
Actions https://github.com/Hiroshiba/voicevox/actions/runs/4710848233

build: macOS on Github ActionsでGNU sedをデフォルトにする

---

src/components/AudioAccent.vue
src/components/AudioCell.vue
src/components/AudioDetail.vue
src/components/AudioInfo.vue
src/components/DictionaryManageDialog.vue
src/components/HeaderBarCustomDialog.vue
src/components/HotkeySettingDialog.vue
src/components/MenuButton.vue
src/components/MenuItem.vue
src/views/EditorHome.vue

``` bash
npm run typecheck:vue-tsc
```
で出てくる型エラーの一部を修正しました。
残りのエラーは自分には手に負えそうもなさそうです…

FIX: 型エラーの修正

---

src/components/DictionaryManageDialog.vue

辞書登録時の正規表現によるスペースのチェックで最初のみではなく全ての一致にマッチするようにしました
close #1300

Fix: 辞書の単語入力で全てのスペースを置換するようにする #1300

---

src/components/CharacterButton.vue

キャラクター選択メニューが常に下方向に展開されるようにすることで以下の問題を解決します。
- 選択しやすいように先頭の方に配置したキャラクターが逆に選択しにくくなる。
- タイトルバーにメニューが被りタイトルバーに操作が吸われてしまう。
- fix #1110 
- ref #1030
ウインドウサイズを変更したときは可能な限り追従するようになっています。

ENH: CharacterButtonのメニューが常に下方向に展開されるようにする

---

.github/actions/setup-environment/action.yml
.github/workflows/test.yml

テストのWorkflowを高速化します。
- build-test: ビルドできるかの確認（Windows）
- electron:build_pnever
- test: 単体・e2eテスト（Windows）
- test:unit
- test:e2e
- lint: 静的検査（Ubuntu）
- ライセンスチェック
- lint
- markdownlint
- typecheck
（なし）
（なし）
（なし）

Improve: テストを高速化

---

src/store/preset.ts

エンジン起動時に一括作成されるはずのデフォルトプリセットが一番最初のキャラクターしか作成されていなかったのでそれを修正します。
- ref https://github.com/VOICEVOX/voicevox/issues/956#issuecomment-1441530269
- ref #1228

FIX: デフォルトプリセットが正常に生成されない問題を修正

---

src/views/EditorHome.vue

アクティブなセルが切り替わったときそのセルが表示範囲外なら表示範囲内に自動的にスクロールするように修正します。
これにより連続再生時に再生しているテキスト欄が追従します。
- fix #530
[このツイート](https://twitter.com/kishimi_284304/status/1652867748958212097)を見てボタンのある行を表示範囲外にするつもりでしたが移動範囲が大きくて使いにくくなった気がしたので止めました。

ENH: 表示範囲外のAudioCellがアクティブになったとき表示範囲内までスクロールするようにする

---

src/store/engine.ts
src/store/type.ts

エンジン再起動時にポートが切り替わった場合接続するポートが切り替わらない問題を修正します。
- fix #1308
#1310 の問題により追加エンジンの動作確認ができていません。

FIX: エンジンの再起動時にEngineInfoを更新する

---

src/components/CharacterOrderDialog.vue

Voiceboxを初めて起動したときに表示される画面を、スクリーンリーダーで正しく操作できるようにしました。並べ替えのD&Dは即対応が難しいのと、頑張れば操作できるのでなにも触っていません。
ref #46 
本業の開発では React を使用しているので、 Vue のお作法はあまりわかっていません（というか、今日初めて書きました）。違うところがあればご指摘ください。
少しずつPRを出させてもらって、ほかの画面もアクセシブルにしていきたいと思っています。差分は毎回このぐらいの小さいものになると思います。

Fix: ボイスの紹介・並べ替え画面のボタンをアクセシブルにする

---

package-lock.json
package.json
src/components/EngineManageDialog.vue
src/components/HotkeySettingDialog.vue
src/components/LibraryPolicy.vue
src/components/MenuBar.vue
src/components/MenuItem.vue
src/helpers/map.ts
tests/unit/lib/map.spec.ts

ref: https://github.com/VOICEVOX/voicevox/pull/1293
の続きをやってみました
`vue-tsc` を上げればそもそも対応しなくて良いコードも出るのではという仮説のもと上げてみた所、`MenuItem` の `onClick` が対応不要になったため、エラーを減らす文脈として `vue-tsc` のバージョンアップも併せて行っています
```shell
npm run typecheck:vue-tsc
```
で出力されるエラーをより減らします
```
npm run typecheck:vue-tsc
> voicevox@999.999.999 typecheck:vue-tsc
> vue-tsc --noEmit
src/components/MenuBar.vue:11:8 - error TS2322: Type '{ type: "separator"; label?: string | undefined; } | { type: "root"; label?: string | undefined; onClick?: (() => void) | undefined; subMenu: ({ type: "separator"; label?: string | undefined; } | ... | { ...; } | { ...; })[]; icon?: string | undefined; disabled?: boolean | undefined; disableWhenUiLocked: boolean; } ...' is not assignable to type 'MenuItemData'.
Type '{ type: "root"; label?: string | …
```

Vueファイル内の型エラーを減らす

---

src/components/AudioInfo.vue

プリセット名表示欄になぜか横幅制限があったので外します。
AudioInfo欄を広げたときにプリセット欄に表示されるテキスト数も自動的に増えていたのですが、このスタイルの影響で１文字ほど表示されるテキスト数が少なくなっていそうでした。
（もしかしたらなにか意図があったのかも･･･？）
@sevenc-nanashi さんのPRに不要なことを教えてもらいました。
https://github.com/VOICEVOX/voicevox_mobile/pull/24#discussion_r1199625833
こちらの @Segu-g さんのPRっぽみです。
- https://github.com/VOICEVOX/voicevox/pull/428/files#diff-21392cf965830cf5140c9f694b14d53ba51086d861e77b7a7b7a2f1384ed4e16R683
なにか覚えていらっしゃったりしたらコメント頂けると！！

適用中のプリセット名表示欄になぜか横幅制限があるので外す

---

src/components/AudioInfo.vue

タイトル通り。
- ref: voicevox/voicevox_mobile#24
（なし）

Refactor: AudioInfoのパラメータ一覧周りをリファクタ

---

.github/workflows/check_version.yml
README.md
package.json

Voltaによるバージョン管理を追記し、また`.node_version`とVoltaでのバージョンが同期していることを確認するワークフローを追加します。
* ref https://github.com/VOICEVOX/voicevox/issues/1306
将来的にpackage-lock.jsonの差分確認などを入れてinstallをしてしまった場合に気付けるようにしてもいいかもしれません。

Voltaによるバージョン管理を追記

---

src/components/Dialog.ts
src/components/HeaderBar.vue
src/components/MenuBar.vue
src/store/setting.ts
src/type/preload.ts
tests/unit/store/Vuex.spec.ts

音声・テキスト書き出し成功時にトーストを表示するよう変更しました。
トーストには `今後この通知をしない` ボタンを追加し、非表示に設定できるようにしています。
- メニュー
- `音声書き出し` ボタン・書き出し成功時
- `一つだけ書き出し` ボタン・書き出し成功時
- `テキストを繋げて書き出し` ボタン・書き出し成功時
- ヘッダー
- `１つ書き出し` ボタン・書き出し成功時
ref #1329 
書き出し先を固定していなくても、成功時にはトーストを表示するようにしました。（書き出し先設定でフィードバックを出し分けするとユーザーが混乱するため）

Update: 音声書き出し成功時にトーストを表示 (#1329)

---

src/components/Dialog.ts
src/components/HeaderBar.vue
src/components/MenuBar.vue
src/store/setting.ts
src/store/type.ts

#1335 での実装では引数に `confirmedTips` を利用しており関数の役割が明確でない状態でした。
今回の改修では `Dialog.ts` で `confirmedTips` を参照せずに `notifyOnGenerateAudio` を更新できるよう、 `SET_CONFIRMED_TIP` を作成しています。
```typescript
// 変更前
dispatch("SET_CONFIRMED_TIPS", {
confirmedTips: {
...confirmedTips, // この部分ために引数で受け取る必要があった
notifyOnGenerateAudio: true,
},
});
// 変更後
dispatch("SET_CONFIRMED_TIP", {
confirmedTip: {
notifyOnGenerateAudio: true,
},
});
```
https://github.com/VOICEVOX/voicevox/pull/1335#discussion_r1228905078
- `src/store/setting.ts` に `SET_CONFIRMED_TIP` を追加
-  `src/components/Dialog.ts` 内の関数で受け取る引数を `notifyOnGenerateAudio` に変更
ref #1329
別でIssueとして上がっている `Dialog.ts` の処理共通化とは別のタスクとしてPR出しました。
そのため、変更差分が内容に対して少し大きくなってしまっています。。。

Refactor: `src/components/Dialog.ts` の引数を変更

---

src/background.ts
src/electron/preload.ts
src/type/ipc.ts
src/type/preload.ts

ブラウザ版の作業を進めるにあたり、ブラウザ版の Sandbox の実装が必要である。
実装するためにコードの精査をしたところ、使われていないコードが見つかったため、作業量を減らすために削除する。
ref https://github.com/VOICEVOX/voicevox/issues/1204

使用していないコードの削除

---

.github/workflows/build.yml
.github/workflows/check_version.yml
.github/workflows/labeler.yml
.github/workflows/test.yml
.github/workflows/typos.yml

`shell: bash`を不要にできるオプションがあったので指定してみました。
とりあえずubuntu以外でのOSで実行していたworkflowにのみ付けています。
https://docs.github.com/ja/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun
ついでにディスク容量の心配がなくなっていたので`df -h`を消してみました。
2023/06/19 14:30追記
shell: bashを付けるか付けないかでubuntu/mac上の挙動が変わり、かつ付けたときのほうが良さそうなので全部に付けました。

Github Actionsでshell: bashを毎回書かなくても良いようにする

---

src/background.ts
src/type/staticResources.ts

ブラウザ版の実装にあたり、public に配置しているファイルの読み込み処理の実装が必要になった。
もしも public に配置しているファイル名が変わった場合、2箇所の変更が必要になるため、定数に切り出し、その値を使うようにリファクタリングを行った。
ref https://github.com/VOICEVOX/voicevox/issues/1204

publicディレクトリに配置しているファイルのファイル名を定数に切り出す

---

src/store/setting.ts

editorFontの同期ができてなかったののバグ修正です。
フォント設定が毎回リセットされる感じになります。
ref: https://twitter.com/mayA9896/status/1670167566537621504

バグ修正、editorFontの同期ができてなかった

---

src/background.ts
src/background/engineManager.ts

EngineManagerのadditionalEngineInfosをメンバ変数にするというアプローチで追加エンジンのポートが切り替わらない問題を修正します。
- fix #1310
https://github.com/VOICEVOX/voicevox/issues/1310#issuecomment-1540752389
>また、エンジン再起動時は変更後のportが入ったengineInfoが参照されるので、元のポートに戻ろうとしない気がします。
この問題は解決していません。

FIX: 追加エンジンのポートが切り替わらない問題を修正

---

src/components/Dialog.ts
src/components/HeaderBar.vue
src/components/MenuBar.vue
src/store/setting.ts
src/type/preload.ts
tests/unit/store/Vuex.spec.ts

`src/components/Dialog.ts` の処理をリファクタしました。
- 処理の共通化
- 通知表示処理の関数切り出し
- ダイアログ表示処理の関数切り出し
- `generateAndSaveAllAudioWithDialog` のリファクタ
- 可読性向上のため `for` と `switch` の組み合わせの処理を `flatMap` に置き換えました
close #1329 
close #1337

Refactor: `src/components/Dialog.ts` をリファクタ

---

src/background.ts
src/background/vvppManager.ts

再起動フラグが立っていないと`event.preventDefault()`を呼び出しません。
そのため非同期処理であるエンジンの削除が行われないままエディタが終了してしまいます。
VvppManagerに処理の予約がある場合`event.preventDefault()`を呼び出し処理をするように変更します。
- fix #1319

fix: 再起動ダイアログで断るとエンジンがアップデートされない問題を修正

---

src/background.ts

`npm run electron:serve` 実行時に以下のようなエラーを吐いて vue-devtools が起動しなかったため修正しました。
` [error] Vue Devtools failed to install: Error: Invalid header: Does not start with Cr24`
`electron-devtools-installer` で設定されていた `extension id` が古く参照できなくなっていたたため
参考：https://github.com/MarshallOfSound/electron-devtools-installer/pull/222#issuecomment-1295273667
- `src/background.ts` の `VUEJS3_DEVTOOLS` を `VUEJS_DEVTOOLS` に変更

Fix: vue-devtools が起動しない問題を修正

---

src/components/MenuBar.vue
src/store/project.ts

#1357 が先です。
`SAVE_PROJECT_FILE`でのエラーハンドリングがなかったので、`LOAD_PROJECT_FILE`に倣って内部でエラーダイアログを出すようにしました。
ref #1357

SAVE_PROJECT_FILEでエラー発生時にダイアログを出すようにする

---

src/components/EngineManageDialog.vue

OpenAPI周りが改善したため、いくつかあったOpenAPI周りのワークアラウンドが解消されました。
- https://github.com/VOICEVOX/voicevox/pull/1361
そのうちの１つの`versionVersionGet`が未対応だったので、対応してみました。
ref #1361 
PRはこのときだったのですが、これがOpenAPIのバグっぽい挙動だったのかは特にメモが見当たりませんでした。
https://github.com/VOICEVOX/voicevox/pull/982/files#diff-1c1ce532e98b27633d850d2c08dd39481a59fa12a3311b77eaf2a53e1fe76763R305
ちなみにエラーはこんな感じです。
```log
SyntaxError: Unexpected non-whitespace character after JSON at position 4
at JSON.parse (<anonymous>)
at watch.immediate (http://localhost:5173/components/EngineManageDialog.vue:68:24)
```

engineVersionがダブルクォーテーションで囲まれなくなったので対応する

---

src/background/engineManager.ts
src/background/portManager.ts

実際にlistenすることでポートが使用可能であるかの確認と代替ポートの取得を行うように変更します。
`[Errno 13] error while attempting to bind on address ('127.0.0.1', 50021): アクセス許可で禁じられた方法でソケットにアクセスしようとしました。`といったエラーでエンジンが起動できない問題を回避することができます。
- fix #1330 
https://github.com/VOICEVOX/voicevox/issues/1330#issuecomment-1577077884 で提案された[get-port](https://www.npmjs.com/package/get-port)には取得したポートを一定時間再取得を防止する機能があるようです。
エンジンを起動直後に再起動するとポートが切り替わってしまうため使用しないことにしました。

fix: 他のプロセスが使用中以外の理由でポートが使えない場合に起動できない問題を修正

---

src/background/portManager.ts

題のとおりです。Mac/Linuxでひとまず起動を可能にします。
- ref #1360 (electronのバージョンアップまで含めてIssueの解決として扱いたいので、closeはしないようにします)
- ref #1368

lsofがエラーを吐くことに対するエラーハンドリングを追加

---

src/components/AudioCell.vue
src/styles/visually-hidden.scss

マウスを使用せずにキーボードのみによる操作を行う際に分かりにくかった点を、とりあえずですが2点修正しました。
- 行削除ボタンを使用するためにマウスカーソルをその行に合わせる必要をなくしました。
- `display: none;`の代わりに以下のcssを適用して、見た目上から消えた場合でも [Tab] キーを使えばフォーカス可能にしました。
https://www.a11yproject.com/posts/how-to-hide-content/
- キャラクター選択ボタンにフォーカスが当たった際もアクティブ行を更新するようにしました。
https://github.com/VOICEVOX/voicevox/issues/46#issuecomment-1627751835
一行しかない場合の削除ボタン非表示も、`hidden`ではなく`disable`した上で見た目から消すべきなのかもしれませんが、どちらにすべきか分からなかったのでとりあえず見送りました。

Update: アクセシビリティを改善

---

src/type/preload.ts

- https://github.com/VOICEVOX/voicevox/issues/1218
の解決PRです。
互換性の維持のために、以前はUUIDに限定していなかった型を、元のstring型に戻します。
４箇所あって重複しちゃうので、まあコメントはなくても良いかなと思いました。
ただのstringを持っているprojectファイルが読み込めるようなテストを書くのが良さそう。
マージ後のタスク
fix #1218 
ちょっと確認してみたのですが、speakerUuidはもとからUUIDだった箇所がちょくちょくありました。[`defaultStyleIds`もuuid](https://github.com/VOICEVOX/voicevox/blob/release-0.14/src/type/preload.ts#L484)になっていました。
まあでも厳密にUUID4でなくても良いのは事実なので、緩めるのが良いと思います。
現在のコードでuuidとしてそうなのは以下４つです。（全体を`uuid(`で検索）
* engineIdSchema
* speakerIdSchema
* audioKeySchema
* presetKeySchema
このうち下２つはエディタが生成するものなので厳密にuuidでも良さそう･･･ですが、まあ[以前は`uuid()`にしてなかった](https://github.com/VOICEVOX/voicevox/blob/65a4465333e4c4963aa726d6cb8de7841ffedc13/src/store/project.ts#L424-L431)っぽいので、uuidにしないでおきます。

ブランド型をUUIDじゃなくする

---

src/components/CharacterOrderDialog.vue
src/components/CharacterTryListenCard.vue
src/styles/variables.scss

題の通りです
ライブラリ管理機能において使用するため、使い回せるようにコンポーネントを分離しました。
表示内容は大きく変わっていませんが、キャラクターのスタイルごとに立ち絵に対応するため、処理を少し追加しました。
このため、試聴ダイアログ内においても、スタイルを切り替えるとスタイルごとの立ち絵が存在する話者については、そちらが表示されるようになりました。
ライブラリ管理機能は規模が大きいのと、画面上のモックから実装していく(完全に動作しない)ため、ここからブランチを一旦分けています。

キャラクターボイス試聴カードを単体コンポーネントに分離する

---

src/views/EditorHome.vue

https://github.com/sabonerune/voicevox/blob/5c9103ae557ea5fa6cca7e93b00ed62d1e0b0ad1/src/views/EditorHome.vue#L494
の判定により先頭のキャラクターを変更しない限りAudioCellが変更されないようになってしまっていた。
- ref #1309
- ref #1229

fix: #1309 で最初のAudioCellを変更しない条件を間違えていた問題を修正

---

src/components/CharacterOrderDialog.vue
src/components/CharacterTryListenCard.vue
src/styles/variables.scss
src/type/preload.ts
src/views/EditorHome.vue

題のとおりです、mainに取り込まれたキャラボイス試聴コンポーネントやbrand型のUUID矯正を解除する2つの変更をrebaseでマージします。
このPRをマージするために、一時的にPull Requestマージ設定のrebaseをonにします

[project-library-manage] mainをマージ

---

src/components/HelpDialog.vue
src/components/UpdateInfo.vue

欠落していた`downloadLink`をとりあえずハードコードして修正します。
また、`UpdateInfo`の`href`部分の記法が間違っていたのでそこも修正しました。
- fix #1294
`HelpDialog`でplopsが間違っていても型エラーにならない問題は解決していません。
https://github.com/VOICEVOX/voicevox/issues/1294#issuecomment-1517320008

fix: 「アップデート情報」内のダウンロードページリンクが機能しない問題を修正

---

src/views/EditorHome.vue

「FAQを見る」ボタンのリンク先がQ&Aページ　のlssueに対処
「FAQを見る」ボタンのリンク先がQ&Aページ #1402

「エンジン起動に時間がかかっています」のFAQをQ&Aに変更

---

src/components/SettingDialog.vue
src/store/audio.ts

タイトル通り。
- close: https://github.com/VOICEVOX/voicevox/issues/1405#issuecomment-1637507897
Firefox / Chrome
設定自体を隠しましたが、disabledにする+tooltipにサポートされてないことを書く実装でも良いかも

Fix: setSinkIdがないブラウザの処理を追加

---

README.md
src/index.html
src/router/index.ts

- https://github.com/VOICEVOX/voicevox/issues/1409
の解決です。実際にNetlifyを経由してデプロイしています。
https://voicevox-browser-dev.netlify.app/#/home
今はサンプルでこのブランチをデプロイしていますが、後でmainブランチに変えるつもりです。
fix #1409 
- https://github.com/VOICEVOX/voicevox/pull/1345

ブラウザ版をデプロイ可能にする

---

src/components/DictionaryManageDialog.vue

変更前のコメントアウトにある通り、keyCodeは非推奨となっています。
`@keydown`はIME確定時のEnterも捕捉しますが、`@keydown.enter`は捕捉しないみたいです。
[参考](https://r17n.page/2020/04/04/vue-submit-on-enter-japanese/)
(念のため実際に試して確認しました。)
これを使うことで、keyCodeの使用をやめます。

keyCodeの使用をやめる

---

src/store/utility.ts

デフォルト出力ファイル名が(「あああ...んんん.txt」などではなく)「あああ.txt」と省略される条件が、「最初と最後のテキストが同じ時」になってます。これはテキスト欄が以下のようなときにも省略されて「あああ.txt」となってしまいます。
例:
「あああ」
「いいい」
「あああ」
この省略条件を「AudioCellの数が1つの時」に変えることで、例の場合なら「あああ...あああ.txt」とします。
ちなみにデフォルト出力ファイル名は、[テキスト/音声を繋げて書き出し] や [プロジェクトを名前を付けて保存] した時に参照されます。
[追記]
- ref https://github.com/VOICEVOX/voicevox/pull/549#discussion_r762551049
これを見る限り、バグに近かったようです。

Update: デフォルト出力ファイル名の"..."省略条件の見直し

---

src/background.ts
src/background/engineManager.ts

- https://github.com/VOICEVOX/voicevox/issues/1349
を解決します。
そもそもEngineMangerがwinを受け取っていたのがよくなかったので、エラーが発生した時にゴールバックを呼び出すように設計を変えました。
EngineMangerは他にもダイアログを使っているところがいくつかあるのですが、とりあえず今回はプロセス実行時のエラーだけをハンドリングするように書き換えてみました。
close #1349

fix #1349 （初回起動したエンジンが異常終了したときにエラーダイアログが表示されない）

---

src/browser/fileImpl.ts
src/components/AudioDetail.vue
src/components/HotkeySettingDialog.vue
src/electron/device.ts
src/store/audio.ts
src/store/setting.ts

全ての`array.indexOf(hoge)`・`string.indexOf(hoge)`と`-1`との比較(`>`,`!==`,`===`)を`array.includes(hoge)`と`string.includes(hoge)`に置き換えます。
参考:
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String/includes
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/includes
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf
ちなみに今回置き換えたものは関係ないですが、微妙に動作が違うようです
https://qiita.com/ryusaka/items/cbdb3ed1dcb8bcc46f2a

Refactor: `indexOf()`と`-1`の比較を`includes()`へ統一

---

src/store/audio.ts
src/store/utility.ts

txtファイル書き出しがONの時に無視するテキスト(読みとメモ)が一部無視されなかったのと無視されすぎたのを修正します。
- 一つだけ書き出し時に無視されない。
- Shift_JISで音声を繋げて書き出し時に無視されない。
- 音声を繋げて書き出し時に、以下が構文と認識されて無視されてしまう。
```
{字幕もどき|(改行)
読みもどき}
```
また、utilityから関数一つで呼べるようにします。
- #1355
メモ機能
- #1383
字幕/読み機能

fix: 無視テキスト関連のバグ修正

---

docs/全体構成.md

テキストと画像が同じ行になってしまって、横幅の短い画面では変に表示されていたので修正します。
[org内の説明](https://github.com/VOICEVOX/.github/blob/main/profile/README.md)の方はすでに正しくなってました。

[docs] 全体構成.mdの画像配置がおかしいのを修正

---

src/components/AudioDetail.vue
src/components/AudioInfo.vue
src/components/AudioParameter.vue
src/helpers/previewSliderHelper.ts

#1437 の修正PRです。
Vue力不足により、再生と保存にしっかり反映されること以外大丈夫なのかよく分かっていません…。
唯一機能していたモーフィングの実装を真似したのですが、ダメそうだったらcloseしていただいて他の方にお任せしようかと…！
close #1437 
https://github.com/VOICEVOX/voicevox/assets/7900586/e52ec876-4d3a-4883-aa96-b97e050bbf3e

Fix: マウスホイールでパラメータ調整ができないバグ(#1437)を修正

---

src/background.ts

エンジンのエラー発生がめちゃくちゃ早かった場合（そもそもexeファイルがなかった時とか）、ウィンドウが表示される前にエンジンエラーが発生します。
この場合に画面に通知を送ろうとして失敗し、その後のダイアログ表示ができていなかったので、とりあえずダイアログ表示だけでもできるようにとりあえず問題を迂回します。
- https://github.com/VOICEVOX/voicevox/issues/1460
一番いいのはそもそもUIが表示される前にエンジンを起動しようとしないことだと思います。
なぜそうしないかというと、ポートの自動変更が実装される前まではそうなっていたのですが、エンジンを起動してみようとしない限りそのポートが使えるかどうかわからないという関係上、現状の起動シーケンスだと、必ずエンジンの起動の方が早くないといけない感じになっているためです。
- https://github.com/VOICEVOX/voicevox/pull/1317#pullrequestreview-1434765325
これはもうどうしようもないので、UIを表示した後にエンジンを起動しようとするのではなく、Vuex側からエンジンを起動するようにするのが一番いいのかなと思いました。
そのためのissueがこちらです
- https://github.com/VOICEVOX/voicevox/issues/1460
それはそれとして、UI側が`DETECTED_ENGINE_ERROR`を受け付けられるようになるまで待機してからメッセージを飛ばすという方法もあるのですが、色々考えてちょっとすぐに実装できなさそうだったのと、↑のissueが解決したらそもそも不要になるのと、ユーザー向けにはダイアログが表示されてかつVOICEVOXがまともに動かないので、まあ一旦これでいいかなと。。。

エンジンのエラーが早かった場合にwin存在しない問題を迂回する

---

src/components/Dialog.ts
src/components/HeaderBar.vue
src/components/MenuBar.vue
src/store/audio.ts
src/store/type.ts

labファイル・テキストファイルのファイル出力がコピペコードになっているのをaudio.ts先頭にまとめます。
また、encodeをaction内でstateから取得するようにします。
さらに、いくつかエラーハンドリングが上手くいってなさそうだった箇所も修正します。
ユーザー視点での変更はエラーハンドリングの改善以外はありません。

Refactor: 文字コード系のwriteText関連処理を一箇所にまとめる

---

public/qAndA.md

タイトルの通りです。こちらのissueの解決です。
- https://github.com/VOICEVOX/voicevox/issues/1452
fix #1452
electronが使うパスでビルド時のアプリの名称（voicevox-cpu）が入りそうなところはlogsとuserDataくらいっぽいです。なのでエラーログの案内さえ変えればとりあえず解決かなと。
https://www.electronjs.org/ja/docs/latest/api/app#appgetpathname
それはそれとして、CPU版とGPU版で変えているアプリ名称の影響を抑えたいので、background.ts内でsetAppNameしちゃうのも良いかなと思いました。
issueを作ってみようと思います。

[docs] mac版のログ保存ディレクトリの案内が間違っていたので訂正する

---

src/background.ts
src/browser/sandbox.ts

起動直後に一瞬真っ白な画面が表示される不具合(#1425)の修正PRです。
`mainWindowState.manage(win);`の[内部処理](https://github.com/mawie81/electron-window-state/blob/2701d9a0f90a44dc8dbf81430538ceb16c9ff27a/index.js#L134)によって[自動的にshow状態になる](https://www.electronjs.org/ja/docs/latest/api/browser-window#winmaximize)のが原因でした。
(このため、前回最大化状態でウィンドウを閉じた場合にのみ起こる不具合でした)
new BrowserWindowのオプションに背景色(backgroundColor)を設定しました。
- `mainWindowState.manage(win);`の直後に`win.hide();`をしてもウィンドウが一瞬表示されました。
- また、背景色を設定してかつこれを行うと、不具合がなぜか再発しました。
- on`ready-to-show`以降に最大化すると、変化前のサイズのウィンドウが一瞬表示されました。
- 初期ウィンドウを小さいサイズで開き、最大化してから裏でウィンドウサイズの変更する、という方法を試みましたが、最大化中はサイズ変更を受け付けないようでした。
- opacityでの制御はLinuxだと不可、かつ標準のウィンドウアニメーションが効きませんでした。
もっと厳密にするならopacityを併用してOSごとに処理を分けるべきだと思いますが、そもそも最大化状態でしか発生せず、また読み込み中のUIが見えてもそこまで酷い見た目にはならないので、このシンプルな実装が妥当かなと思いました。
close #1425 …

`new BrowserWindow`時に背景色を設定し、不具合#1425 を修正

---

tests/e2e/browser/初回起動時.spec.ts
tests/e2e/browser/辞書ダイアログ.spec.ts
tests/e2e/navigators.ts

辞書ダイアログのe2eテストを作成しました。
ref #1462

辞書ダイアログのe2eテスト作成

---

src/components/AudioParameter.vue

長さパラメーターが0になった時に、ラベルに値が何も表示されなくなるバグを修正しました。
currentValueがundefinedではない場合、valueをラベルに表示するようにしました。
close #1439
[![Image from Gyazo](https://i.gyazo.com/e46699714ac1f5e7b697b2bb8f1c33f5.gif)](https://gyazo.com/e46699714ac1f5e7b697b2bb8f1c33f5)

長さパラメーターを0にしたときに、ラベルに値が表示されるように修正しました

---

src/background.ts

app.setNameを使い、アプリ名をvoicevoxとしてsetしました
ref #1456
以下のようにvoicevoxフォルダ内に各種ファイルがあることを確認できました。
Windowsでのスクリーンショット
Macでのスクリーンショット

アプリの名称をvoicevoxとしてset

---

tests/e2e/browser/テキスト追加・削除.spec.ts
tsconfig.json

テキスト追加・削除のe2eテストを実装しました。
本来、追加だけをe2eテストするよう書かれていますが、削除の方もテストしたほうがいいと考え、テスト内容を変更しました。
ref #1462

テキスト追加・削除のe2eテスト実装

---

src/store/audio.ts
src/store/type.ts

上書き防止のために以下のような処理を行っています。
「こんにちは.wav、こんにちは[1].wavが既に存在していた場合にこんにちは[2].wavに名前を変える」
これが3か所でコピペコードになっているのを、1か所にまとめます。
ref #1475

Refactor: 上書き防止処理を関数化し共通化

---

src/components/CharacterOrderDialog.vue

題のとおりです。
#1385 をやったときに、少し挙動が変わっていたので修正しました。
具体的には、並び替えダイアログキャラ名ホバー時、キャラ名に併せて立ち絵も変化していましたが、キャラクター音声試聴カードを分離したことによって、立ち絵を変更する機能がそちら側に移ったため、ホバー時の挙動がキャラを選択した状態にはなってたものの、立ち絵が変化しないといった挙動になっていました。
#1385 
https://github.com/VOICEVOX/voicevox/assets/34832037/4ed01640-ebd5-441b-8887-06ea30f77d9b

キャラクター並び替えダイアログでの並べ替えカードホバー時の挙動を修正

---

src/components/FileNamePatternDialog.vue
src/store/audio.ts
src/store/utility.ts

DEFAULT_FILE_NAME_TEMPLATEから`.wav`を取り除いた定数を新たに定義します。
さらに、PROJECT_NAMEと混ざらないようにAUDIOを名前に付け足します。
また、それによって処理を簡略化できる`src\components\FileNamePatternDialog.vue`もリファクタリングします。
ref #1475
上記の一環です。

`DEFAULT_FILE_NAME_TEMPLATE`の拡張子無し版を定義

---

src/components/AudioParameter.vue

VSCode上で「nullの可能性があります」と警告が出ていたので比較を厳密でなくしました(`!==`から`!=`へ)。
バグ自体は直ったままなのを確認しました。挙動に変更はありません。
- #1469
- #1035
(個人的には厳密演算子派で、なんならif文の条件式にはboolean以外含めるべきではないとすら思っています。が、nullOrUndefinedに限っては、例えば`{ text: string | undefined } | null`を返す外部の関数hogeがあった場合に`if ((hoge()?.text ?? undefined) === undefined)`みたいな記述は微妙なのでif (hoge()?.text)という記述になり、falsyな`""`(空文字列)をスルーしてしまう可能性があるのを懸念しています。それを見越してかeslintの[eqeqeq](https://eslint.org/docs/latest/rules/eqeqeq)ではnullとの比較だけは厳密でなくても良いオプションがあるみたいです)

厳密には`undefined`ではなく`null`だったのを修正

---

src/store/audio.ts
src/store/project.ts
src/store/type.ts
src/store/utility.ts

デフォルトのプロジェクト名と音声ファイル名を返す関数をstore.getterに移動しました。
ref #1475
上記の一環です。
プロジェクト名取得(`DEFAULT_PROJECT_FILE_BASE_NAME`)は、名前的には`project.ts`が妥当なんですが、`audio.ts`の繋げて書き出し2種の時にも参照されているのと、内部処理的にもaudioItemを参照しているのでどちらに置くべきか微妙なところかもです。とりあえず`audio.ts`のほうに置いてみました。

Refactor: デフォルトファイル名取得関数2つをgetterへ移動

---

tests/e2e/browser/オプション/書き出しファイル名パターン.spec.ts
tests/e2e/browser/ツールバーカスタマイズダイアログ.spec.ts
tests/e2e/locators.ts
tests/e2e/navigators.ts

書き出しファイル名パターンのテストを追加します。
連番がパターンに含まれていないとボタンが押せないとか、保存したら内容が表示されるとかをテストしています。
- https://github.com/VOICEVOX/voicevox/issues/1462

書き出しファイル名パターンのe2eテストを追加

---

src/type/globals.d.ts
src/type/preload.ts

ブラウザ版のmacOS判定がおかしかったっぽいので直します。
- https://github.com/VOICEVOX/voicevox/pull/1470
electronだとprocessが必ず存在しているけど、`process.platform`はレンダラー側にはなさそう。
ここが以前の判定だと間違ってた。
chrome系は実験的機能だけど`navigator.userAgentData`が便利そう。
`navigator.platform`は非推奨機能だけどどのブラウザも実装しっぱなしなので一番これが利便性高そう。
ユーザーエージェントで判断するところまではだいたいのブラウザで来ない気がするけど、スマホをブラウザとかだと違うかもなので必ず値を返すように置いてます。
もし将来的にユーザーエージェントをしっかりと判定に使うようにするのであれば`UAParser.js`とかのライブラリを使うと良さそう。

ブラウザ版のmacOS判定がおかしいのを直す

---

src/components/AudioParameter.vue

イントネーション項目の無声化されたスライダーをクリックした際に開発者ツール上で`fn is not a function`とエラーが表示されるのを修正します。
特に動作に変更はありません。 
(修正前)

fn is not a function エラーを修正

---

tests/e2e/browser/オプション/書き出しファイル名パターン.spec.ts
tests/e2e/browser/テキスト追加・削除.spec.ts

e2eテストで、追加ボタンを押した直後のアサーションで落ちていたので、waitForTimeoutを追加しました

テキスト追加後に待つ処理を追加

---

src/components/AudioDetail.vue
src/components/DictionaryManageDialog.vue
src/store/audio.ts
src/store/type.ts
src/views/EditorHome.vue

`store/audio.ts`の
```ts
const audioElements: Record<AudioKey, HTMLAudioElement> = {};
```
を
```ts
const audioElement = new Audio();
```
とします。
以前の実装は複数の同時再生をしたい場合は便利ですが、少なくとも現在は使われておらず、また将来的にも使われる可能性が低そうなため、変更しても大丈夫そうです。
（かなり厳密に言うと、辞書登録で長い文章を読ませている最中に［キャンセル］>［閉じるボタン］後に詳細調整欄の再生ボタンを押すと辞書の読みが停止されるようになりますが、実質影響なしだと思います）
----
- ref #1475
上記の一環です。
- ref ##1492
上記で話題に出ました。(具体的な該当コメントは「その他」を参照)
（前略）将来をひとまず考えないなら、現状同時に複数再生する必要はないはずなので、
```ts
const audioElements: Record<AudioKey, HTMLAudioElement> = {};
```
を
```ts
const audioElement = new Audio();
```
としてしまうことで何か所か単純化できる気がしました。再生中の音声が高々一つになるので、そこら辺の実装を省けそうかなと。結構レビューしていただいた範囲も変更が必要そうなので、そこはアレなんですが…。
今のところは音声を複数再生できた方が良いissueは無いはず…？
_Originally posted by @thiramisu in https://github.com/VOICEVOX/voicevox/issues/1492#issuecomment-1693 …

Refactor: `audioElements`をRecordから単体にする

---

src/components/AudioDetail.vue
src/components/HeaderBar.vue
src/store/audio.ts
src/store/type.ts

#1525 により、再生中の`audioKey`が高々1つになりました。
そのため、`nowPlaying`を`audioKey`ごとに管理する必要がなくなります。
これを反映し、`store.state.audioStates[audioKey].nowPlaying`から`store.state.nowPlayingAudioKey`に独立させます。
また、それにより`STOP_CONTINUOUSLY_AUDIO`が不要になったので、削除します。
- その際、`STOP_AUDIO`内で諸々の処理が行われていない（ように見える）理由が分かりにくいと感じたので、説明コメントを追加しました。
ユーザー視点の変更はありません。
- ref #1475 
上記の一環です。
- ref #1525 
上記を受けての変更です。

Refactor: `audioStates`から`nowPlayingAudioKey`を独立させる

---

src/components/AudioDetail.vue

具体的には以下の点を変更しました。
- `setInterval`を`requestAnimationFrame`に変更
- `currentTime !== undefine`の判定を`for`ループの外に出す
- `for`ループを`findIndex`へ変更
- エラー分岐を詳細にする
- [追記]  必要時(`activePoint.value`変更時)のみ`scrollToActivePoint`が実行されるように変更
- #785
エラー分岐の理由に関係
[Window.requestAnimationFrame() - Web API | MDN](https://developer.mozilla.org/ja/docs/Web/API/window/requestAnimationFrame)
次フレームの直前に実行される処理を指定できるメソッドです。

Refactor: 再生中のアクセント句の見た目を強調する処理を改善

---

src/infrastructures/AudioRenderer.ts
src/store/singing.ts

音声周りのリファクタリングです。
AudioEventSchedulerとNoteEventSchedulerを直接使用してスケジューリングを行う形に変更します。
Schedulerの抽象化をやめて処理を追いやすくするのが目的です。
ref #1041

[project-s] 各Schedulerを直接使用してスケジューリングを行う形に変更する

---

src/store/audio.ts

上書き防止をしてさらにテキスト防止を２回押した際に２回めに保存したファイルの拡張子がwavになっていたので、txtになるようにしました。
関数の引数で拡張子をいじれるようにしました
close #1521

テキストをつなげて保存を二回押したときの処理を変更

---

src/components/AudioDetail.vue
src/components/HeaderBar.vue
src/store/audio.ts
src/store/type.ts

#1530 で、`STOP_CONTINUOUSLY_AUDIO`が`STOP_AUDIO`に統一されました。
これにより、停止ボタンでの処理が通常再生時と連続再生時で共通化され、簡単に共用ができるようになったので、ボタンを統一します。
具体的には以下の2点を実施します。
- これまで連続再生中専用だったツールバーの［停止］ボタンを通常再生中でも使えるようにします。
- これまで通常再生中専用だった［再生ボタン］での停止を連続再生中でも使えるようにします。
- #1530
上記で提案をいただきました。（当該コメントは「その他」を参照）
両方使用できます。
該当コメント：
`STOP_COUNTINIOUSLY`が削除可能なのが意外でした。
実は連続再生を開始すると、詳細調整欄に表示されてある方の停止ボタンがhiddenになる実装になってるんですよね。
これは連続再生用と通常再生用で停止させるべき関数が異なるからこういう実装にしていたのですが、停止ボタンを共通化できるのであれば話が変わってきそうに感じました！！
_Originally posted by @Hiroshiba in https://github.com/VOICEVOX/voicevox/pull/1530#pullrequestreview-1601711006_

feat: 停止ボタンを連続再生中と通常再生中で共用にする

---

src/infrastructures/AudioRenderer.ts
src/store/singing.ts

チャンネル周りのリファクタリングです。
シーケンスの追加・削除をチャンネル内で行わないようにします。
（チャンネルに音を調整する機能のみ持たせるようにします）
また、名前をSingChannelからChannelStripに変更して、AudioRenderer.tsに移動します。
チャンネルに持たせていたSequenceとAudioPlayer・SynthはひとまずPhraseに持たせる形にします。
ref #1041

[project-s] シーケンスの追加・削除をチャンネル内で行わないようにする

---

src/store/audio.ts
src/store/type.ts

#1525 により`GENERATE_AUDIO_KEY`内でstateを参照する必要がなくなったため、独立した関数として定義します。
また、その周辺で未使用の戻り値のために複雑になっている実装があったので、解消します。
- #1475
上記の一環です。
- #1525
上記により実現しました。

`GENERATE_AUDIO_KEY`をストアの外に出す

---

src/components/LibraryManageDialog.vue

題のとおりです。頭が混乱していたのか、判定を誤っていたので修正しました。
ついでに、頭がこんがらがらないようにコメントを追記しました。
#1560 を適用しないと、sharevox engineによるUIでの確認ができません。

[project-library-manage] 音声ライブラリの最新バージョン判定の誤りを修正

---

src/components/AudioDetail.vue

#1554 のために`<context-menu>`をどこに書くかを検討したかったのですが、ぱっと見整理されておらず迷子になりました。
一箇所条件を整理してコメントを書くだけで見やすさが改善されるように思えたので、実施してみました。
- #766
目指すはこれな気がしますが一気にやるのはつらそうなので、とりあえず道標を置いておきたいです。

refactor: `AudioDetail.vue`のHTML部分の記述を整理しコメントを追加

---

src/components/DefaultStyleListDialog.vue

デフォルトスタイルの変更ページのレイアウトを
- 名前太字
- スタイルそのまま
- 全スタイル数縮小
で変更。
ref #1512

デフォルトスタイルページのデザイン変更

---

src/store/audio.ts
src/store/type.ts

audioElementに割と密接に関係している処理を`audioPlayer.ts`へ分離する準備として、別ファイルに分ける前に一旦ファイル内で分離しました。
- #1475
上記の一環です。

refactor: `audioElement`関連の処理を分離

---

src/infrastructures/AudioRenderer.ts
src/store/singing.ts

`AudioRenderer.ts`のリファクタリングとコメントの追加を行います。
[`AudioContext`](https://developer.mozilla.org/ja/docs/Web/API/AudioContext)の場合は、`AudioContext`を作成してからの経過時間になります。単位は秒です。
現在のコンテキスト時間は[`currentTime`](https://developer.mozilla.org/ja/docs/Web/API/BaseAudioContext/currentTime)プロパティで取得できます。
``` ts
// 現在のコンテキスト時間を取得する
const contextTime = audioContext.currentTime;
```
Web Audio APIでは音声処理は[レンダリングスレッド](https://g200kg.github.io/web-audio-api-ja/#control-thread-and-rendering-thread)で行われるため、再生・停止のタイミングをメインスレッドから正確にコントロールするには、コンテキスト時間で再生時刻・停止時刻を指定（スケジュール）する必要があります。
[`OfflineAudioContext`](https://developer.mozilla.org/ja/docs/Web/API/OfflineAudioContext)を使用して行うレンダリングで、音声デバイスへの出力を行いません。
DAWの[トランスポート](https://www.g200kg.com/jp/docs/dic/transport.html)のイメージです。
イベントスケジューラーを使用して複数のシーケンスのスケジューリングを行います。 …

[project-s] AudioRenderer.tsのリファクタリングとコメントの追加

---

src/components/AccentPhrase.vue
tests/e2e/browser/音声詳細.spec.ts

以下の挙動を改善し、fallbackしないようにします。
- 読みに読点の連続が含まれる場合にfallbackしていた
- 最後のアクセント区間の変更時かつ読みに読点が含まれる場合にfallbackしていた
（「fallbackする」は、以下の行が実行されることを指します。この場合は読みが解析されるため、例えば「ハ」「ヘ」が「ワ」「エ」に変換されたりがありそうです。）
https://github.com/VOICEVOX/voicevox/blob/7a4242cf9ebad27f3ee0c4d5ce1a97128c2fc161/src/store/audio.ts#L2289-L2294
また、これに関連するe2eテストを追加しました。
さらに、その際に書きにくかったのでついでにaria-labelを追加しました。
ただし、現状キーボード操作では各モーラにフォーカスできないため、アクセシビリティ的にはほぼ無意味です。
- https://github.com/VOICEVOX/voicevox/issues/766#issuecomment-1722661052
[追記ここから]
- #796
isKana: trueになるようになっているはずなので、図らずも上記のバグの一部が修正されているかもです
（分割位置が変わるのは修正されるはず。ただ、アクセント位置が変わるのはそのままです。）
[追記ここまで]

feat: 詳細調整欄でのアクセント区間単位の読み変更時に読点が含まれる場合の挙動を改善

---

tests/e2e/browser/オプション/書き出しファイル名パターン.spec.ts
tests/e2e/locators.ts

#1488 で実装された、書き出しファイル名パターンのテストが結構な確率で落ちます。
狙って再現できないので正確な原因はよく分からないんですが、playwrightの動画を見る限りだとボタンを押すのが早すぎて値の変更が保存できていないように見えます。そこで、少しの間waitForTimeoutで（#1515の一つ前の処理で）待つようにしました。
GitHub Action上でubuntu, mac, windowsを各3回ずつ回して落ちなかったので多分修正できているはず…。
ついでに以下のコメントアウトの誤字も修正しました。
https://github.com/VOICEVOX/voicevox/pull/1488#discussion_r1292810546
- #1488 
- #1515
修正出来ているかを簡単に判別できる方法がもしあれば教えていただきたいです…。

test: 「書き出しファイル名パターン」のe2eテストが落ちるのを修正

---

package-lock.json
package.json
src/background.ts
src/components/AcceptTermsDialog.vue
src/components/MinMaxCloseButtons.vue
src/components/Sing/CharacterMenuButton.vue
src/components/Sing/MenuBar.vue
src/components/Sing/ScoreSequencer.vue
src/components/Sing/SequencerKeys.vue
src/components/Sing/SequencerNote.vue
src/components/Sing/SingerPanel.vue
src/components/Sing/ToolBar.vue
src/plugins/ipcMessageReceiverPlugin.ts
src/router/index.ts
src/store/index.ts
src/store/singing.ts
src/store/type.ts
src/store/ui.ts
src/type/ipc.ts
src/views/EditorHome.vue
tests/unit/store/Vuex.spec.ts

[mainブランチのマージ](https://github.com/VOICEVOX/voicevox/pull/1582)のコンフリクトを解消し、フォーマッターを動作させ、エラーが起こる箇所を変更・追従しました。
実行するにはおそらく `Node`のバージョン更新と、npmパッケージの更新（`npm run ci`）と、`.env` ファイルの更新が必要です。
主な仕様変更点
- `PROCESS_BEFORE_QUIT`アクションを解体して元の`CHECK_EDITED_AND_NOT_SAVE`を改造する形にした
- マルチエンジンが入った関係でアプリの[終了シーケンス](https://github.com/VOICEVOX/voicevox/blob/660736d53fde1796ea7c8a450598715945e4f0fd/docs/res/%E7%B5%82%E4%BA%86%E3%82%B7%E3%83%BC%E3%82%B1%E3%83%B3%E3%82%B9%E5%9B%B3.md)が変わり、CLOSE経路とRELOAD経路ができた
- 両方の経路でレンダリングの停止を入れる必要がある
- とりあえず両経路にくっついている`CHECK_EDITED_AND_NOT_SAVE`内に組み込みました
- https://github.com/VOICEVOX/voicevox_project/issues/15
あとTTS側のVueファイルがComposition形式になってとても楽になったのですが、全範囲にコンフリクトが発生してしまうので、そこはとりあえず追従していません。

[project-s] mainブランチマージのコンフリクト解消、及び追従

---

src/components/AudioAccent.vue

アクセント位置の変更スライダーのクリック時に`fn is not a function`エラーが出るのを修正します。
#1509 と同じ実装が別のファイルにもありましたが、修正が漏れていました。
- #1509
https://github.com/VOICEVOX/voicevox/assets/7900586/421961b6-b648-4734-8204-ac0657c05986
(Discordより、posted by @Hiroshiba )

fix: fn is not a function エラーを修正

---

.eslintrc.js

↓ こちらのissueを修正したPRになります。
- https://github.com/VOICEVOX/voicevox/issues/1513
eslintにundefinedとnullの厳密比較を禁止する設定を追加しました。
下記のコードを、main.tsなどに張り付けていただければ確認できます。
```ts
const fuga = "null";
const a = fuga != undefined; // OK
const a_1 = fuga !== undefined; // NG
const b = fuga == undefined; // OK
const b_1 = fuga === undefined; // NG
const c = fuga != null; // OK
const c_2 = fuga !== null; // NG
const d = fuga == null; // OK
const d_2 = fuga === null; // NG
const e = "fuga" == undefined; // OK
const e_2 = "fuga" === undefined; // NG
const button = { text: null };
const f = button.text == null; // OK
const f_2 = button.text === null; // NG
const g = "fuga" == null; // OK
const g_2 = "fuga" === null; // NG
```
ref #1513
初めてOSSにPRを切らせていただきました。
何かやり方が間違っているなどあれば教えていただけると幸いです🙇

undefinedとnullの厳密比較を禁止する設定を追加

---

src/views/EditorHome.vue

エンジンが起動していないときに渡される `FAILED_STARTING` ステートをハンドリングしてエラーメッセージを表示するようにしました。
~ついでに `ERROR` ステートのハンドリングも追加しました。~
close #1538

エンジンが起動していないときはエラーメッセージが表示されるようにする

---

src/infrastructures/AudioRenderer.ts
src/store/singing.ts

出力する音声が0dBを超えないようにします。
`Limiter`で大きい音を抑え、抑えきれなかった音を`Clipper`で-1～1の範囲にクリップします。
`Limiter`は内部で`DynamicsCompressorNode`を使用していて、パラメーターは以下のように設定しています。
``` ts
compNode.threshold.value = -5;
compNode.ratio.value = 20; // 最大に設定しています
compNode.knee.value = 8; // 0でも良いかも
compNode.attack.value = 0;
compNode.release.value = 0.25;
```
`DynamicsCompressorNode`ではメイクアップゲインが自動で設定されますが、音圧を上げることが目的ではないので、`GainNode`を繋いでメイクアップゲインで上がった分を下げています。
``` ts
correctionGainNode.gain.value = 0.85;
```
コンプレッションカーブは以下のようになります。
`Limiter`、`Clipper`は以下のページを参考に実装しています。
- [15.コンプレッサーの使い方（Web Audio API 解説）](https://www.g200kg.com/jp/docs/webaudio/compressor.html)
- [1.19. DynamicsCompressorNode インターフェース（Web Audio API 日本語訳）](https://g200kg.github.io/web-audio-api-ja/#DynamicsCompressorNode)
- [14.ウェイブシェイパーの使い方（Web Audio API …

[project-s] 出力する音声が0dBを超えないようにする

---

README.md
src/background/engineManager.ts

`VITE_DEFAULT_ENGINE_INFOS`の`executionFilePath`で相対パスでもエラーが起こらないように変更します。
- ref #1237
直接の修正ではない。
エンジンのディレクトリを分ける場合はこのPRに加えてビルド周りを変更する必要があります。
実際に変更するかどうかまだ議論が必要だと思います。
ついでにEngineManagerの`=== null`周りを`== undefined`に統一しておきました。

feat: VITE_DEFAULT_ENGINE_INFOSのexecutionFilePathで相対パスが使えるようにする。

---

src/components/Sing/ScoreSequencer.vue
src/components/Sing/SequencerKeys.vue
src/components/Sing/SequencerNote.vue
src/helpers/singHelper.ts
src/store/singing.ts
src/store/type.ts
tests/unit/store/Vuex.spec.ts

以下を行います。
- 計算の整理・修正
- マジックナンバーを無くし、変換処理などを関数化する
- 変数やクラスの名前をわかりやすいものに変更
- なるべく単位をつけるように
- `midi`から`noteNumber`に変更
- `resolution`から`tpqn`に変更
- 拍子やスナップが変わっても、グリッドが適切に描画されるようにする
以下のように行っています。
``` mermaid
flowchart LR;
Ticks <-->|TPQN| QuarterNotes
QuarterNotes <-->|BaseXPerQuarterNote| BaseX
BaseX <-->|ZoomX| ViewX
NoteNumber <-->|BaseYPerNoteNumber| BaseY
BaseY <-->|ZoomY| ViewY
style Hidden1 fill-opacity:0, stroke-opacity:0;
Hidden1[" "] ~~~ NoteNumber
style Hidden2 fill-opacity:0, stroke-opacity:0;
ViewX ~~~~ Hidden2[" "]
```
`TPQN`＝4分音符あたりのティック数（Ticks Per Quarter Note）です。
`QuarterNote`＝4分音符です。4分音符の長さは拍子（小節の長さ）に依存しません。
`BaseX`、`BaseY`はズーム適用前の値、`ViewX`、`ViewY`はズーム適用後の値です。
（ズーム適用前の値を保持する変数は、`Base`をつけています）
- `singing.ts`の方も後で修正したいと思います

[project-s] シーケンサーの計算の整理と修正

---

src/components/Sing/ScoreSequencer.vue

拍の線を描画する処理を追加します。
グリッドセルを描画するエリアの上に、小節・拍の線を描画するエリアを重ねています。
グリッドセル（スナップの線）と小節・拍の線を別々に描画し、
拍子が3/4、スナップが1/4（三連符）の場合でも適切に描画されるようにします。
- スナップを設定する機能もこの後実装します

[project-s] 拍の線を描画する処理を追加

---

src/components/Sing/ScoreSequencer.vue
src/components/Sing/ToolBar.vue
src/helpers/singHelper.ts
src/store/singing.ts
src/store/type.ts

スナップを設定する機能を追加します。
スナップタイプの型はひとまず数値型のままにして、`SET_SNAP_TYPE`内で値をチェックするようにしています。
https://github.com/VOICEVOX/voicevox/assets/62321214/6e78de11-cb3e-41ae-b0bb-bebd45cad795

[project-s] スナップを設定する機能を追加

---

.env.production
.github/workflows/build.yml
electron-builder.config.js

今までエンジンをエディタの実行ファイルと同じディレクトリに展開していました。
これを別の別のディレクトリに移動することで問題を回避します。
- fix #1237
- close #1603
とりあえずディレクトリ名は`engine`にしました。
個人のリポジトリでリリースビルドはできました。
WindowsとLinuxは動作テストをしましたがMacは所有していないためテストできていません。

build: エンジンの配置ディレクトリを変更

---

build/installer_linux.sh

v0.15からエンジンに`libsndfile`のバイナリが付属するようになりました。
これによりシステムに`libsndfile`のインストールが不要になります。
そのためLinux版インストーラーで`0.15.0`以上をインストールする時に`libsndfile`のインストールチェックをスキップするように変更します。
- ref VOICEVOX/voicevox_engine#212
- ref VOICEVOX/voicevox_engine#747
- ref VOICEVOX/voicevox_engine#769
バージョン番号の切り出し方法がかなり楽観的な気がしますが大丈夫でしょうか？
あまりシェルスクリプトを書いたことがないのであまり自身がないです。
https://github.com/VOICEVOX/voicevox/blob/bc1d6abf4cea18637b61cc87e93d3a0cc4fe69a1/.github/workflows/test.yml#L56-L61
テストのワークフローに`libsndfile`のインストール処理があります。
現状は`v0.14.x`のエンジンを使用しているためまだ削除できません。
`v0.15`をリリース後に削除する必要があります。

feat: Linuxインストーラーでインストールするバージョンが0.15以上のときlibsndfileのチェックをスキップする

---

src/components/Sing/ScoreSequencer.vue
src/components/Sing/SequencerNote.vue
src/components/Sing/ToolBar.vue
src/infrastructures/AudioRenderer.ts
src/store/singing.ts
src/store/type.ts

以下を行います。
- `IMPORT_MUSICXML_FILE`の修正
- `tie`（タイ）の`start`、`stop`が最初と最後の音符だけに設定されている場合でも正しく読み込めるように修正
- リファクタリング
- `IMPORT_MIDI_FILE`、`IMPORT_MUSICXML_FILE`のリファクタリング
- `resolution`を`tpqn`に変更
- `midi`を`noteNumber`に変更
- 引数の順番を変更（`tpqn`が最後になるように）

[project-s] インポート周りの修正とリファクタリング

---

src/components/Sing/ScoreSequencer.vue
src/components/Sing/ToolBar.vue
src/helpers/singHelper.ts
src/store/singing.ts
src/store/type.ts
src/views/SingerHome.vue

以下を行います。
- 修正
- スナップタイプのソートを行っていなかったので、ソートを行うように修正
- リファクタリング
- `ScoreSequencer.vue`のリファクタリング
- `singHelper.ts`のリファクタリング
- `GET_EMPTY_SCORE`を削除
- `SET_SCORE`の変更・リファクタリング
- `SET_TEMPO`、`REMOVE_TEMPO`のリファクタリング
- `SET_TIME_SIGNATURE`、`REMOVE_TIME_SIGNATURE`のリファクタリング
- `POSITION_TO_TIME`を`TICK_TO_SECOND`に変更
- `TIME_TO_POSITION`を`SECOND_TO_TICK`に変更

[project-s] スナップ周りの修正とリファクタリング

---

src/components/Sing/ScoreSequencer.vue
src/components/Sing/ToolBar.vue
src/helpers/singHelper.ts
src/store/singing.ts
src/store/type.ts
src/views/SingerHome.vue

以下を行います。
- 拍子の位置をTickではなく小節番号で保持するようにする
- 曲中のテンポ・拍子も考慮して小節の数を算出するようにする
- 拍子の分母が16以下の2の倍数になるようにする
- バリデーションの追加
- リファクタリング

[project-s] 拍子周りの修正とリファクタリング

---

src/components/HotkeySettingDialog.vue

ショートカットキーを「初期値に戻す」とした時、他の action と衝突する場合はショートカットキー設定のダイアログを出すようにしました。
```setting``` が undefined の場合は、従来通り何の処理も行わないようにしています。
ref #566 
特になし
特になし

ショートカットキーを初期値に戻す際に、衝突チェックを行うようにしました

---

playwright.config.ts
tests/e2e/browser/アクセント.spec.ts
tests/e2e/browser/オプション/書き出しファイル名パターン.spec.ts
tests/e2e/browser/キャラクター並び替えダイアログ.spec.ts
tests/e2e/browser/ツールバーカスタマイズダイアログ.spec.ts
tests/e2e/browser/テキスト追加・削除・入れ替え.spec.ts
tests/e2e/browser/デフォルトスタイルダイアログ.spec.ts
tests/e2e/browser/ヘルプ.spec.ts
tests/e2e/browser/初回起動時.spec.ts
tests/e2e/browser/複数選択/値変更.spec.ts
tests/e2e/browser/複数選択/選択.spec.ts
tests/e2e/browser/調整結果.spec.ts
tests/e2e/browser/辞書ダイアログ.spec.ts
tests/e2e/browser/音声.spec.ts
tests/e2e/browser/音声パラメータ.spec.ts
tests/e2e/browser/音声詳細.spec.ts
tests/e2e/electron/example.spec.ts
tests/e2e/navigators.ts

e2eテストを改善します。
- テストサーバーをポート7357で開くようにします。
- 開発サーバーが既に起動してると競合して別のポートにテストサーバーが起動し、それでe2eが落ちることがあったので
- 7357はTESTのleet表記です（5173がSITEのleetなので）
- test.beforeEachを共通化します。
- navigateToMainをbeforeEachにいれてもいいかも
（なし）
（なし）
（なし）

Improve: e2eを改善

---

src/components/Sing/ScorePosition.vue
src/components/SingerTab.vue
src/store/type.ts
tests/unit/store/Vuex.spec.ts

型を簡単にできそうだったのでやってみました。
`state.score?.hoge ?? fuga`となっているところをundefined考慮しない形にできそうだったのですが、とりあえずundefinedを省いただけにしました。
ref https://github.com/VOICEVOX/voicevox_project/issues/15
ついでにsetupでnullを返すとワーニングが出るっぽいのでそちらも変更しておきました。

[project-s] state.scoreからundefinedを消す

---

src/background.ts
src/background/electronConfig.ts
tests/e2e/browser/辞書ダイアログ.spec.ts

electron-storeから離脱したあたりで、config.jsonの読み込みに失敗した時のフォールバックが発動しなくなっていたので、修正してみました。
具体的には以前はConfigインスタンス作成時にスキーマエラーが発生していたのが、initalize時にエラー発生するように変わったタイミングでコード移動できてなかったのが原因でした。
- https://github.com/VOICEVOX/voicevox/issues/1156
この後↓やろうかなと思います
- https://github.com/VOICEVOX/voicevox/issues/1626
ついでにelectronのメインプロセスでダイアログを開く周りのテストを書こうかなと思ったのですが、モックを指す方法がパッとなさそうだったので諦めました。
たぶんplaywright+electrongでモックを刺せない気がしているので（実はさせるかも･････？）
多分テスト時だけ何かしらの関数を呼ぶようにコードの方直接書き換えないといけない気がします。
（書き換えた先の関数が呼ばれたかどうかの獲得方法が分からない･･････。ログを吐くようにして、ログを参照する･･･？）

fix: config読み込みに失敗したときのフォールバックを復活させる

---

src/components/Sing/ScorePosition.vue
src/components/Sing/ScoreSequencer.vue
src/components/Sing/SequencerKeys.vue
src/components/Sing/SequencerNote.vue
src/components/Sing/SingerPanel.vue
src/views/SingerHome.vue

以下を行います。
- シーケンサーのコンポーネントのレイアウトをCSS Gridで行うように変更
- スクロール判定はひとまず`sequencer-body`エリアのみ（鍵盤はスクロール判定なし）
- 横スクロールバーが表示されるように修正
- 鍵盤の描画処理の変更
- 白鍵のアウトラインが描画されるようにする
- リファクタリング
https://github.com/VOICEVOX/voicevox/assets/62321214/49f06650-5f2d-4964-b134-8ea4bd4c96bc

[project-s] シーケンサー周りの調整

---

package-lock.json
package.json
src/components/MenuItem.vue

警告が出ていた依存を更新します。0 vulnerabilitiesまで減らしました。
ちなみにこのアプデでelectron-builderの拡張子割り当てで日本語が使えるようになってたりelectron-builder.config.tsにできたりするはずです
（なし）
（なし）

Update: 警告が出ていた依存を更新

---

.github/actions/download-engine/action.yml
.github/workflows/build.yml

リソースのバージョンが0.15じゃないと実行時に問題が生じるようになっていたので、修正しました。
ついでにjqは-eをつけないとキーが見つからなかった時にエラーにならないので、そこも修正しました。
- https://github.com/VOICEVOX/voicevox/issues/1637
の解決プルリクエストです。
fix #1637

[fix] リソースを0.15に、jqが何も見つけられなかった場合はエラーに

---

src/components/Sing/ScoreSequencer.vue
src/components/Sing/SequencerKeys.vue
src/components/Sing/SequencerRuler.vue

スライダーを操作したときは画面の中央を基準にズーム、
Ctrlキーを押しながらホイールを回したときはマウスカーソル位置を基準にズーム（水平方向）するようにします。
また、`SequencerKeys`の幅と`SequencerRuler`の高さを`ResizeObserver`で取得するようにします。
https://github.com/VOICEVOX/voicevox/assets/62321214/0d435cad-8b9b-4be1-bc16-a42c16bdafdf

[project-s] ズーム周りの調整

---

src/background.ts

初回起動だと`experimentalSetting.enableMultiEngine`が存在しないため、`store.set("enableMultiEngine", enableMultiEngine);`にundefinedが渡され型違反 -> 死亡という感じで死んでたのを直します。
（なし）
（なし）
（なし）

Hotfix: 初回起動と0.13からの更新が出来ないのを修正

---

src/components/Sing/ScoreSequencer.vue
src/components/Sing/SequencerKeys.vue
src/components/Sing/SequencerRuler.vue
src/components/Sing/ToolBar.vue
src/helpers/singHelper.ts
src/store/singing.ts
src/store/type.ts
src/views/SingerHome.vue

以下を行います。
- 再生ヘッド（再生位置インジケータ）の描画処理を実装
- DOM + `translate`で実装
- 再生時の再生ヘッド位置の更新をストア側で行うように
- `requestAnimationFrame`を使用して更新（最大60fps）
- オートスクロールを実装
- 再生ヘッドが表示範囲の外に出たらスクロール
- 停止時でも再生ヘッド移動（シーク）時にスクロール
- リファクタリング
https://github.com/VOICEVOX/voicevox/assets/62321214/655e30ac-35b8-48d8-bdb2-9a4bd29dc6e7

[project-s] 再生ヘッドの描画処理とオートスクロールを実装

---

src/components/Sing/ScoreSequencer.vue
src/components/Sing/SequencerRuler.vue

ルーラーをクリックで再生ヘッドの位置を設定できるようにします。
また、マウスカーソルの位置が正しく取得できていなかったので、その修正も行います。
https://github.com/VOICEVOX/voicevox/assets/62321214/fa7ceb5b-b730-4c04-9b4e-47e2a5d2541a

[project-s] 再生ヘッドの位置を設定する機能を追加

---

src/components/AudioCell.vue
src/store/audio.ts
src/store/type.ts

複数削除を実装します。
- ref: #457 
https://github.com/VOICEVOX/voicevox/assets/59691627/78290ca2-7187-452a-a979-fc72b5829a72
これがマージされたらとりあえずは完成でいいかなぁ、感があります。

複数選択：複数削除を追加

---

src/store/singing.ts
src/store/type.ts
src/views/SingerHome.vue
tests/unit/store/Vuex.spec.ts

音声書き出し時にダイアログを表示するようにして、書き出しをキャンセルできるようにします。
また、以下も行います。
- 書き出し範囲を楽譜全体に変更
- 書き出し音量を最大に変更
- 保存ダイアログを表示した後にレンダリングを待機するように変更
- レンダリングの有効・無効を設定する機能は使用していないので一旦削除
書き出し処理を関数化したので差分が大きくなっていますが、書き出し処理自体はほどんど変更していません。
https://github.com/VOICEVOX/voicevox/assets/62321214/a6430cc8-2802-4991-91ca-d9df95aa1986

[project-s] 音声書き出し時にダイアログを表示する

---

src/store/singing.ts
src/store/type.ts
src/views/SingerHome.vue
tests/unit/store/Vuex.spec.ts

`Phrase`をストア（VuexのState）で持つようにし、ストアで持てない`Blob`などは`PhraseData`で持つようにします。
また、以下も行います。
- `Phrase`の`startTime`の計算を`AudioQuery`生成・編集時に行うようにする
- `AudioQuery`のハッシュを計算・比較する処理を一旦削除
- `exportingAudio`を`nowAudioExporting`に変更
- `EXPORT_WAVE_FILE`にレンダリング未完了の場合の処理が残っていたので削除

[project-s] Phraseをストアで持つようにする

---

src/store/audio.ts
src/store/type.ts

タイトル通りです。
- ref: #457 
（なし）
（なし）

複数選択：話者変更するとAudioQueryのテキストがAudioCellのテキストと一致しなくなるバグを修正

---

src/components/Sing/ScoreSequencer.vue
src/components/Sing/SequencerKeys.vue
src/components/Sing/SequencerNote.vue
src/helpers/singHelper.ts
src/infrastructures/AudioRenderer.ts
src/store/singing.ts
src/store/type.ts

鍵盤クリック時とノート編集時に音を鳴らす機能を追加します。
また、以下も行います。
- 鍵盤の描画を`symbol`を使わない形に変更
- ノートオン・ノートオフ周りの処理を修正
- パラメーターの調整とリファクタリング

[project-s] 鍵盤クリック時とノート編集時に音を鳴らす機能を追加

---

src/components/Sing/ScoreSequencer.vue
src/components/Sing/SequencerNote.vue
src/store/singing.ts
src/store/type.ts
tests/unit/store/Vuex.spec.ts

重なっているノートを検出して色を変えて表示する機能を追加します。
また、以下も行います。
- action、mutationを整理
- `ADD_NOTE`から`ADD_NOTES`に変更（複数ノートに対応）
- `UPDATE_NOTE`から`UPDATE_NOTES`に変更（複数ノートに対応）
- `REPLACE_ALL_NOTES`を削除
- `REMOVE_NOTE`から`REMOVE_NOTES`に変更（複数ノートに対応）
- `SET_SELECTED_NOTE_IDS`のactionを削除
- `SELECT_NOTES`を追加
- `CLEAR_SELECTED_NOTE_IDS`から`DESELECT_ALL_NOTES`に変更
- `REMOVE_SELECTED_NOTES`のmutationを削除（`REMOVE_NOTES`を呼び出すように変更）
- `REPLACE_ALL_NOTES`を削除したので、それに合わせてドラッグ周りの処理を修正
- レンダリング時の重なっているノートを削除する処理を修正
- `state.overlappingNoteIds`を元に削除するように変更
- リファクタリング
重なっているノートを検出する処理は計算量が$`O(n^2)`$になっています。

[project-s] 重なっているノートを検出して色を変えて表示する機能を追加

---

src/components/AccentPhrase.vue
src/components/AudioInfo.vue
src/components/CharacterOrderDialog.vue
src/components/CharacterPortrait.vue
src/components/DefaultStyleListDialog.vue
src/components/DefaultStyleSelectDialog.vue
src/components/Dialog.ts
src/components/EngineManageDialog.vue
src/components/FileNamePatternDialog.vue
src/components/HeaderBarCustomDialog.vue
src/components/HotkeySettingDialog.vue
src/components/MenuBar.vue

- components群のwarningが出ていた箇所を緩い等価比較に修正
ref #1513
- src/components/AccentPhrase.vue
変更前後で挙動に変動がないことを確認
---
- src/components/AudioInfo.vue
number型のためundefinedになることはないが、既存実装を優先して `==` に修正
---
- src/components/CharacterOrderDialog.vue
変更前後で挙動に変動がないことを確認
---
- src/components/CharacterPortrait.vue
変更前後で挙動に変動がないことを確認
---
- src/components/DefaultStyleListDialog.vue
変更前後で挙動に変動がないことを確認
---
- src/components/DefaultStyleSelectDialog.vue
変更前後で挙動に変動がないことを確認
---
- src/components/Dialog.ts
`==` で挙動上問題なし
---
- src/components/EngineManageDialog.vue
変更前後に挙動に変動がないことを確認
---
- src/components/FileNamePatternDialog.vue
変更前後に挙動に変動がないことを確認
---
- src/components/HeaderBarCustomDialog.vue
ref参照によりundefinedの可能性があるが、基本10個のボタンが選択されるため、挙動自体に問題なし
---
- src/components/HotkeySettingDialog.vue
変更前後で挙動に変動がないことを確認
---
- …

コンポーネント群の修正

---

src/components/Sing/ScoreSequencer.vue
src/components/Sing/SequencerNote.vue
src/store/singing.ts
src/store/type.ts

以下を行います。
- 歌詞編集時にのみ`input`を表示するように変更
- ノートをダブルクリックで歌詞編集モードに移行
- Tabキーで次のノートに、Shiftキーで前のノートに移動する機能を追加
- Enterキーで歌詞編集を終了
- `change`イベント発生時に歌詞の変更を適用するように変更
- ノートの描画をSVGからDOMに変更
- カーソル周りの処理を一旦元に戻す（カーソルのちらつきを防げていなかったので）
- 修正とリファクタリング

[project-s] 歌詞入力周りの実装

---

src/components/Sing/ScoreSequencer.vue

Ctrl＋クリックまたはShift＋クリックでノートを複数選択できるようにします。
また、以下も行います。
- ノートのダブルクリック判定の処理を前の形に戻す

[project-s] 複数選択を実装

---

src/components/Sing/ScoreSequencer.vue
src/components/Sing/SequencerNote.vue
src/components/Sing/ToolBar.vue

以下を行います。
- ノートが追加される位置を表示する機能を追加
- 縦線で表示
- プレビュー中（移動中・リサイズ中）も判定が分かるように表示
- ノート追加位置の判定を「スナップ幅の1/4」右にずらす
- グリッドの線とグリッドセル、どちらを狙っても意図した位置にノートが追加されるように
- 移動・リサイズを行ったあとにノートの選択をすべて解除するようにする
- 複数ノートを選択して編集後に単一ノートの編集ができるように
- 今のところ選択を解除する手段がルーラークリックかノート追加しかないので
- ノートの端の判定を調整
- 色を調整
https://github.com/VOICEVOX/voicevox_project/issues/15

[project-s] ノートが追加される位置を表示する機能を追加

---

README.md

ライセンス情報の手動更新は必要ないことを伝えたいので、自動で作られていることを案内するようにしてみました。

[docs] 依存ライブラリのライセンス情報の生成は自動であることを案内

---

src/components/help/HelpDialog.vue
src/components/help/UpdateInfo.vue
src/composables/useFetchNewUpdateInfos.ts
src/type/preload.ts
src/views/EditorHome.vue
tests/unit/composable/useFetchNewUpdateInfos.spec.ts

アップデート情報を取ってくる`useFetchNewUpdateInfos`コンポーザブルのテストを書きました。
[バージョンごとにアップデート通知を切れるようにするタスク](https://github.com/VOICEVOX/voicevox/issues/1633)をテスト可能にしたくて、その前に既存の関数のテストを書いてみた感じです。
fetchのモックを刺してみています。こんな感じ。
```ts
// fetchのモックを作成
vi.stubGlobal("fetch", async () => {
return new Response(JSON.stringify(updateInfos), { status: 200 });
});
```
refの値の待機は`vi.waitFor`が便利でした。
```ts
await vi.waitFor(() => {
if (!isCheckingFinished.value) throw new Error();
});
```

useFetchNewUpdateInfosのテストを追加

---

src/store/utility.ts
tests/unit/store/utility.spec.ts

メモとルビを全角記号`［］,｛｜｝`を使って記述できるようにしました。
close #1699

メモ機能・ルビ機能の記法を全角記号にも対応させた

---

src/components/PresetManageDialog.vue
src/components/UpdateNotificationDialog.vue
src/store/setting.ts
src/store/type.ts
src/type/preload.ts
src/views/EditorHome.vue

0.15アプデに向けて、アップデート通知周りの実装を調整しつつ、UIを他のダイアログと混ざる感じにしてみました。
* 「このバージョンをスキップ」をチェックボックスからボタンに変更
* skipUpdateVersionを直に変更する形からVuexを介するように
- https://github.com/VOICEVOX/voicevox/pull/1708
こんな感じになりました。
色々と試したりしてたら3時間ぐらいかかったけど、コードの変更行数が少なくて絶望しました。。

アップデート通知周りのUIと実装調整

---

src/components/Sing/MenuBar.vue
src/components/Sing/ScoreSequencer.vue
src/components/Sing/ToolBar.vue
src/sing/domain.ts
src/store/singing.ts
src/store/type.ts
tests/unit/store/Vuex.spec.ts

ハミング対応のエンジンでレンダリングできるようにします。
また、以下も行います。
- bpmの下限を40に設定
- `isSelfEventTarget`関数が呼ばれていなかったので修正

[project-s] ハミング対応のエンジンでレンダリングできるようにする

---

.github/workflows/test.yml

CIでのエンジンポートを50021からランダムに変更します。
- ref: #1558 
（なし）
（なし）

Change: CIでのエンジンポートを変更

---

src/components/Sing/CharacterMenuButton.vue
src/components/Sing/ScoreSequencer.vue
src/components/Sing/SequencerKeys.vue
src/components/Sing/SequencerPhraseIndicator.vue
src/components/Sing/ToolBar.vue
src/infrastructures/AudioRenderer.ts
src/sing/domain.ts
src/sing/storeHelper.ts
src/store/singing.ts
src/store/type.ts
tests/unit/store/Vuex.spec.ts

以下を行います。
- リファクタリング
- `ScoreSequencer.vue`、`ToolBar.vue`、`singing.ts`、`domain.ts`のリファクタリング
- `state.phrases`の型を`Record<string, Phrase>`から`Map<string, Phrase>`に変更
- ドラッグ開始時の`guideLineTicks`を保持するように変更
- `isValidBpm`、`isValidBeats`を追加し、`ToolBar.vue`でそれらを呼ぶように変更
- `getSnapTypes`と`isValidSnapType`を`domain.ts`に移動
- `OverlappingNotesDetector`に`clear()`を追加
- `NOTE_IDS`（getter）を追加
- `=== undefined`、`!== undefined`の箇所を修正
- コメントの追加
- シンセの音量を変更

[project-s] リファクタリング

---

.github/workflows/build.yml
public/qAndA.md

- https://github.com/VOICEVOX/voicevox/issues/1736
の解決です。
release-0.15に含めていますが、この後mainブランチにも導入予定です。
ついでにQ&Aのところで段落ミスがあったので修正します。

[release-0.15] macOSのatributeからバージョン名が抜けているのを解決

---

src/components/Sing/ScoreSequencer.vue
src/store/singing.ts

レンダリングできなかった（クエリのフェッチ・音声合成に失敗した）フレーズがレンダリング中の表示のままにならないように（赤く表示されるように）します。
また、プレビュー処理が毎フレーム実行されるようになっているので、マウスカーソルが動いたときにプレビュー処理が実行されるようにします。

[project-s] レンダリングできなかったときの表示を修正

---

docs/res/起動シーケンス図.md
src/App.vue
src/router/index.ts
src/views/EditorHome.vue

エンジン起動をEditorHomeからApp.vueに移管します。
あとはメニューバーの移管して、切り替えをメニューバーへ移動させたらmainにマージしても大丈夫なはず！
- https://github.com/VOICEVOX/voicevox_project/issues/15
- https://github.com/VOICEVOX/voicevox/issues/1745
どなたか見てほしいけど難しそう。ちょっと時間おいてえいやでマージしようと思います。

[project-s] エンジン起動をApp.vueに移管

---

src/background/configMigration014.ts
src/components/help/LibraryPolicy.vue
src/helpers/SelectionHelperForQInput.ts
src/helpers/map.ts
src/helpers/previewSliderHelper.ts
src/infrastructures/EngineConnector.ts
src/store/audioPlayer.ts
src/store/dictionary.ts
src/store/engine.ts
src/store/index.ts
src/store/preset.ts
src/store/project.ts
src/store/proxy.ts
src/store/utility.ts
src/type/result.ts
tests/unit/lib/map.spec.ts

タイトル通り。
- closes: #1513 
（なし）
（なし）

=== undefined/nullを消す

---

src/components/Sing/ScoreSequencer.vue
src/infrastructures/AudioRenderer.ts
src/sing/viewHelper.ts

以下を行います。
- トーク・ソング切り替えでスクロール位置が変わらないようにする
- トーク・ソング切り替え時にイベントリスナーの追加・削除を行う
- `onMounted`・`onUnmounted`から`onActivated`・`onDeactivated`に変更
- ノート追加のプレビュー（ノートの長さの設定）では、カーソル位置ではなくドラッグ量で判定を行うように変更
- カーソル位置で判定だとグリッド・ノートを見る（判定を確認する）必要がある
- ドラッグ量で判定だとグリッド・ノートを見ずに感覚（マウスの移動量）でノートの長さを設定できる
- シンセの音を調整

[project-s] シーケンサーのスクロール・編集周りを調整

---

src/components/DictionaryManageDialog.vue
src/components/Sing/CharacterMenuButton.vue
src/components/Sing/CharacterPortrait.vue
src/components/Sing/ToolBar.vue
src/components/Talk/AudioCell.vue
src/components/Talk/AudioInfo.vue
src/store/audio.ts
src/store/project.ts
src/store/singing.ts
src/store/type.ts

題の通りです。
根本のデータソースから修正しました。
このため、ソング画面でシングスタイルをフィルタリングしているコードをstoreに移植・利用しました。
これ以外にもバグが起こりそうな箇所があるのですが、ひとまずここだけ修正して後でIssueにします。

トーク画面でハミング・歌のキャラクター・スタイルが表示されないように修正

---

src/components/Sing/MenuBar.vue

ソングのメニューから動かないボタンを削除します。
コメントアウトしても良かったのですが、まあトーク側からコピペすれば良いので、削除で良いかなと思いました！

ソングのメニューから動かないボタンを削除

---

src/components/Talk/EditorHome.vue

題の通りです。
- ref #1785
トークスタイルのみ表示・カウントされるようになります。

デフォルトスタイル選択ダイアログでトークスタイルのみを表示する

---

src/components/Sing/CharacterMenuButton.vue

題の通りです。
簡易的に問題を解決します。
本質的な解決としては、「ソングエディタでもデフォルトスタイルが選べるようにする」だと思いますが、それは別途Issueに起こすべきかなと思いました。
- close #1782

ソングエディタでキャラクター選択の挙動がおかしくなる問題を修正

---

src/components/Sing/ScoreSequencer.vue
src/components/Sing/SequencerNote.vue

以下の変更を行います。
- 歌詞入力表示時に選択状態にする
- 歌詞タブ移動時に選択状態にする
- 歌詞の位置を調整
- 歌詞入力時にIME変換のEnterであれば入力モードを継続 → この動作でいいのか議論必要？
ref #1751
close #1751

#1751 歌詞入力時に選択状態にする

---

src/components/TitleBarEditorSwitcher.vue
tests/e2e/browser/初回起動時.spec.ts

UI_LOCK中はソング・トーク切り替えができないようにします。
テストも書いてみました。
close #1795 
操作感的にもそんなに問題がない（そもそもソング側でロックが発生することがほとんどない）感じでした。
唯一ソングに切り替えた直後はキャラクターが最初に表示されるまでロックがかかり続けるのでそこはちょっと不便でした。

UI_LOCK中はソング・トーク切り替えができないように

---

src/components/Sing/CharacterPortrait.vue

ソングの立ち絵がスタイルごとに変わらないようになっていたので変更しました。
エンジン内のハミングスタイルの立ち絵を追加したら差し替わるはず。
まあエラーにはならないと思うので、デバッグ実行はなしでも良さそうかなと！

ソングも立ち絵をスタイルごとに変える

---

public/themes/dark.json
public/themes/default.json
src/components/Sing/ScoreSequencer.vue
src/components/Sing/SequencerKeys.vue
src/components/Sing/SequencerNote.vue
src/components/Sing/SequencerPhraseIndicator.vue
src/components/Sing/SequencerRuler.vue
src/components/Sing/ToolBar.vue
src/styles/colors.scss

- ソングエディタのダークモード対応
ref #1755 
close #1755
- 初期リリース時対応用
- 色は仮(のちほど相談後、全体とあわせられればと思います)
- シンガーが表示されていないのは手元環境のため、本来表示されます
※ 昼頃また調整できればと思いますが、時間がなかった場合のためプルリク作成

#1755 ダークモード対応(初期調整)

---

src/shared/ConfigManager.ts

Discordで報告があった設定が同時に書き込まれる問題に(恐らく)対処します。
恐らく`save()`をawaitせずに呼び出したので保存完了前にlockを抜けていることが原因だと思います。

fix: 設定が壊れる問題を修正

---

src/components/Sing/CharacterMenuButton.vue
src/components/Sing/CharacterPortrait.vue
src/components/Sing/ScoreSequencer.vue
src/components/Sing/SequencerNote.vue
src/components/Sing/SequencerRuler.vue
src/components/Sing/ToolBar.vue
src/sing/storeHelper.ts
src/store/singing.ts
src/store/type.ts
tests/unit/store/Vuex.spec.ts

以下の形に変更します。
```ts
type Track = {
singer?: Singer;
notes: Note[];
};
type SingingStoreState = {
tpqn: number;
tempos: Tempo[];
timeSignatures: TimeSignature[];
tracks: Track[];
...
};
```
`singer`もトラックが持つようにします。
- https://github.com/VOICEVOX/voicevox/issues/1800
- `phrases`や`phraseData`などもトラックが持つ・トラックに紐づけて持つようにした方が良いかも
- レンダリング周りの変更が必要なので、一旦そのまま

楽譜情報とsingerの持ち方を変更する

---

src/sing/audioRendering.ts

タイトル通りです。
将来のブラウザ版対応や、開発時にブラウザを使って軽量化みたいなことをしてる人に役立ちます。
（なし）
（なし）
（なし）

[ソング] Fix: Firefoxだと音が止まらないのを修正

---

public/qAndA.md

Q&AでMacのエラーログの場所が違っていたので修正しました。
なぜwindowsは`voicevox-cpu`から`voicevox`にしてるのにmacの方はしてないのか調べてみた感じ、
- https://github.com/VOICEVOX/voicevox/pull/1159
で１回voicevoxにしたあと、なんかmacのログディレクトリは違ってたらしく
- https://github.com/VOICEVOX/voicevox/pull/1455
で戻して、そのあと
- https://github.com/VOICEVOX/voicevox/issues/1456
で解決したけどQ&Aは変えてなかったという感じっぽみです。

[docs] Q&AでMacのエラーログの場所が違っていたので修正

---

src/components/Dialog/DictionaryManageDialog.vue
src/components/HeaderBar.vue
src/components/Talk/AudioDetail.vue
src/store/audio.ts
src/store/audioGenerate.ts
src/store/type.ts
src/store/utility.ts

`src/store/audio.ts`にある`dispatch`群のうち，音声生成に関係する部分を`src/store/audioGenerate.ts`として分離します．それに伴い，いくつかのシグニチャを変更します．
ref: #1475
もともと`GENERATE_AUDIO`系と`GET_AUDIO_CACHE`系が別々であったことを鑑み，`cacheOnly`フラグを生やしてありますが，現状使われていません．

`store/audio.ts`から音声を生成する部分を分離

---

src/store/audio.ts

audio.tsのリファクタリング

---

src/components/Sing/ToolBar.vue
src/sing/domain.ts
src/sing/storeHelper.ts
src/store/singing.ts
src/store/type.ts
tests/unit/store/Vuex.spec.ts

キーを変更する（キーシフトを設定する）機能を追加します。
キーはノートのキーと歌声（f0）のキーの2つがありますが、ひとまず歌声のキーのシフト量をUI（仮）で設定できるようにして、ノートのキーのシフトは処理のみ実装します。
ref #1838
- UIは仮です
- 数値をクリックで設定UI（テキストボックスなど）が表示される形の方が良いかも…？

キーを変更する機能を追加

---

src/components/Menu/MenuBar/BaseMenuBar.vue
src/components/Sing/MenuBar.vue
src/components/Talk/MenuBar.vue
src/store/project.ts
src/store/singing.ts
src/store/type.ts

題の通りです。ソングエディタの状態をプロジェクトとして保存できるようにします。
また、これに合わせてプロジェクトの構造を変更しました。
close #1781 
zodのスキーマを有効活用するために一部リファクタリングを行っています。
また、現状ではソング部分のプロジェクトの変更検知を行っていない(変更検知がCOMMANDに依存しているため)ので、変更していてもプロジェクトを保存せずに閉じれてしまう問題があります。wipでもいいので、ソング部分のプロジェクト変更検知機能を付けるか迷ったのですが、変更前のプロジェクトを保持しておく以外に変更検知をする手段が思いつかなかったので、このPRでは取り組んでいません。

ソングエディタの編集状態を保存できるようにする

---

src/components/Sing/ScoreSequencer.vue

題のとおりです。
複数選択をしたい際や、マウスホイールに関連した操作をする際に、Ctrlキーが使われていましたが、MacだとCtrlキーは右クリックの扱いで操作が吸われる事があり、特に複数選択で支障があります。
これを既存の`isOnCommandOrCtrlKeyDown`関数を使うことで解決します。

[ソング] Macにおいて、スコアシーケンサー内でCtrlキーではなくCommandキーを使うようにする

---

src/store/audio.ts
src/store/audioContinuousPlayer.ts

連続再生中に，バックグラウンドで音声を合成します．これにより，合成速度が再生速度を上回る場合，連続再生は途切れなく再生されるようになります．
`EventTarget`を継承した管理クラスのインスタンスにより，「合成が完了したら，次の合成を発火して，さらに再生中の音声がなければ今できたものを再生する」といったような処理の集合として実装しています．かなり複雑になりましたが，うまく動いてくれるようになりました．
補遺
- 最初のロードや，短い文の後に長い文が来て事前に合成が終わっていない場合など，どうしても待ち時間は存在します．ここではローディングのダイアログが出ます．
- 停止ボタンは，再生中は押すことができます．しかし，バックグラウンドで合成しているものがあれば，それが合成し終わるまで操作できません．なお，合成が終わったら他に再生されることなく，操作が可能になります．
- フローを表す図を置いておきます．
<details>
<summary>Mermaidのソース</summary>
```
flowchart TD
開始
生成中/待機中
生成中/再生中
終了/再生中
終了/終了
次が生成済{次が生成済？}
最後の生成{最後の生成？}
最後の再生{最後の再生？}
開始 --> 生成中/待機中
生成中/待機中 -->|生成完了| 最後の生成
生成中/再生中 -->|生成完了| 最後の生成
生成中/再生中 -->|再生完了| 次が生成済
終了/再生中 -->|再生完了| 最後の再生
次が生成済 -->|true| 生成中/再生中
次が生成済 -->|false| 生成中/待機中
最後の生成 -->|true| 終了/再生中
最後の生成 -->|false| 生成中/再生中
最後の再生 -->|true| 終了/終了
最後の再生 -->|false| 終了/再生中
``` …

連続再生中にバックグラウンドで音声を合成する

---

src/store/singing.ts

src/store/singing.tsの1981行目に以下を追加しました。
```javascript
var fileName = "song.wav"
const singer = getters.SELECTED_TRACK.singer;
const singerName = 
(getters.CHARACTER_INFO(singer!.engineId,(singer!.styleId))!.metas.speakerName);
if(singerName){
const notes = getters.SELECTED_TRACK.notes.slice(0, 5);
const beginningPartLyrics = notes.map((elem) => elem.lyric).join("");
fileName = singerName + "_" + beginningPartLyrics + ".wav";
}
const projectName = getters.PROJECT_NAME
if (projectName){
fileName = projectName.split(".")[0] + ".wav";
}
```
ref #1833 
> プロジェクトファイル名が指定されている場合はプロジェクトファイル名.wavが良い気がします。
> プロジェクトファイル名が指定されていない場合は、たとえば[キャラ名]_[出だしの歌詞数文字]とかが良いと思います。
両方に対応しました。

fix 歌wave出力時のデフォルトファイル名を変更

---

src/components/help/HelpDialog.vue
src/components/template/HelpLibraryPolicySection.vue

残っていたヘルプ画面の音声ライブラリの利用規約セクションの新しいデザインへの変更を行います。デザインはライセンス情報のものとほぼ同一のものです。

ヘルプ画面の音声ライブラリの利用規約セクションのリデザイン

---

.github/workflows/build.yml

dmgのファイル名のスペースをピリオドに変更することで問題を修正します。
これによるリリース後のファイル名に影響はありません。
また、Windowsのインストーラーはビルド後にファイル名を置換してからアップロードしていましたが最初からスペースのないファイル名でビルドするように変更しました。
- fix #1845
この処理はいらない？
https://github.com/sabonerune/voicevox/blob/02fbce2e7c7ccd323f6a7210b8da1094b162ca9f/.github/workflows/build.yml#L474-L479

fix: dev版のアップロードが失敗する問題を修正

---

src/components/Sing/ToolBar.vue
src/components/Talk/ToolBar.vue

ソングでのundo/redoがショートカットキー設定されてなかったので追加します。
- https://github.com/VOICEVOX/voicevox/pull/1822
- https://github.com/VOICEVOX/voicevox/pull/1836
macでcmdキーが効かなくなってることに気づいたのでissue作成します。

[ソング] undoとredoのショートカットキー登録

---

src/components/Dialog/HotkeySettingDialog.vue
src/plugins/hotkeyPlugin.ts
src/shared/ConfigManager.ts
src/type/preload.ts
tests/unit/lib/hotkeyManager.spec.ts

HotkeyのCombinationはただのstringなのですが、型がついてないとちょっと不安だったのでブランド型を作ってみました。
- https://github.com/VOICEVOX/voicevox/issues/1862
のタスクでhotkeys-js用の型に変換するための布石でもあります。
ref #1862 
ref https://github.com/VOICEVOX/voicevox/pull/1822

[refactor] HotkeyCombinationブランド型を導入

---

README.md

タイトルの通りです。
Github Actionsでのビルド方法を忘れるかもだったのでメモしておきました。
たぶんコントリビューターの方にも役に立つはず。

[Docs] READMEにworkflow_dispatchを使ったビルド方法を追加

---

src/components/Talk/AudioParameter.vue

イントネーション欄で「無声化した音」のイントネーションが変更出来ないようになっている理由を表示する
close #243
（マウスカーソルをスクショに含められなかったので書きました）
https://ja.wikipedia.org/wiki/母音弱化 で母音の無声化も弱化の一種とあったので信じたのですが大丈夫でしょうか？

Add: 無声化したものがdisabledになっている理由の表示

---

src/components/Sing/SequencerPitch.vue

`startTime === 0`のフレーズでピッチがレンダリングされないバグを修正します。
close #1889

Fix: `startTime === 0`のフレーズでピッチがレンダリングされないのを修正

---

src/components/Sing/ToolBar.vue
src/sing/domain.ts
src/sing/storeHelper.ts
src/store/project.ts
src/store/singing.ts
src/store/type.ts

色々考えた結果、音域補正用のパラメーターを増やすのが良さそうだったので増やしました。
ついでにリリースに向けて開発時のみの機能にしました。
変更点は以下の４点です。
* GUIでのラベルと仕様を「音域補正」に
* 見た目の音程と出力の音程は一致させるやつ
* https://github.com/VOICEVOX/voicevox/issues/1838#issuecomment-1944175490 の反映
* `voiceKeyShift`を`guideKeyShift`に
* https://github.com/VOICEVOX/voicevox/issues/1899#issuecomment-1975468968 の反映
* 音域補正を保管する`keyRangeAdjustment`パラメータを追加
* 今ある`notesKeyShift`と`guideKeyShift`の２つともに干渉する値なので別定義が必要だった
resolve #1899 
迷ってることがいくつかあります。
* `keyRangeAdjustment`は直訳すると音域"調整"だけどこれで良いか
* 補正`Correction`と迷ったのですが、何を持って「正しい」とするのかわからなかったので調整にしてみました
* ラベルの方も「音域調整」のが合ってるかも？　手動ですし。
* `notesKeyShift`と`guideKeyShift`を削除するかそのままにするか
* YAGNI則的には消しても良いかも
* 特に`guideKeyShift`は将来的に使わない可能性がありそう
* どちらかというと`guideKeyShift`が議論の結果`keyRangeAdjustment`に変わったという感じかも

音域補正用のパラメーターを増やしつつ、開発時のみの機能に

---

src/components/Sing/ToolBar.vue

音域・音量域調整機能を開発環境じゃなくても使えるようにします。
ちょっと緊急で必要になっているのでマージします 🙇 
- https://github.com/VOICEVOX/voicevox/issues/1870
- https://github.com/VOICEVOX/voicevox/issues/1899
- https://github.com/VOICEVOX/voicevox/issues/1838
どう考えても手動補正するUIは難しい･･･････。
使い方案内と適切な値を SNS で案内するのは必須。
自動調整も入れたいけどさすがに間に合わなさそう。。。。

音域・音量域調整機能を開発環境じゃなくても使えるようにする

---

src/components/Sing/SingEditor.vue
src/components/Sing/ToolBar.vue
src/store/project.ts

- https://github.com/VOICEVOX/voicevox/issues/1926
の解決プルリクエストです。
解説はコード内で行おうと思います。
#1926 
プロジェクトファイルには保存されてたので良かった。
マイグレーションも特に必要ないはず。

[release-0.17] hotfix: プロジェクトファイル読み込みと声量・音域パラメータの初期化バグ修正

---

src/components/Sing/SingEditor.vue
src/store/singing.ts
src/store/type.ts

ソングのエディター起動時に初期化されているけれども使われていなさそうだったので、いっそのこと消しちゃいました。
どちらかというと消しても大丈夫かなという確認ですが、特に使う予定がなかったら消しちゃってもいいかも？
初期化するにあたって大事な初期化なのかそうでもないのかがわからないので、ない方がメンテナンスが高いなと感じました！

ソング：leftLocatorPositionとrightLocatorPositionが使われていないので削除

---

src/components/Sing/SequencerNote.vue

- ノートの重なりエラー時にホバーでツールチップ表示
- ノートのフレーズエラー時にホバーでツールチップ表示
**いったん動作しますが、可能であればホバー表示条件のリファクタをおこなればと思います**
(来週火曜まで時間とれるか不明なため、プルリクとして作成)
ref #1864
close #1864
※ 色は仮です・別途別Issue

#1864 ノートのエラー時にツールチップ表示

---

src/backend/common/ConfigManager.ts
src/components/Dialog/SettingDialog.vue

書き出し先を固定を有効にしたときに書き出し先が未選択の場合、自動的にダイアログを表示するようにします。
これにより意図せずインストールディレクトリにファイルが保存されてしまう問題を回避します。
- fix #1847 
既に書き出し先を固定・未選択の場合起動直後に突然ダイアログが表示されてしまうのでとりあえずマイグレーション処理で書き出し先の固定を無効に切り替えるようにしてしまいました。

feat: 書き出し先を固定を有効にしたときに書き出し先が未選択の場合は自動的にダイアログを表示する

---

src/components/base/BaseDocumentView.vue
src/components/template/HelpLibraryPolicySection.vue
src/components/template/HelpMarkdownViewSection.vue
src/components/template/HelpOssLicenseSection.vue
src/components/template/HelpUpdateInfoSection.vue
src/styles/mixin.scss

ヘルプダイアログのリデザインの最終調整です。具体的には以下のことを行います。
- スタイルにブレがあった箇所を統一
- a要素がfocusされた際のoutlineのデザインを合わせる
- 見出し1のフォントサイズを少し増加
- セクションの内容に最大幅と中央揃えを設定
これがマージされた後はmainブランチとディレクトリ等々合わせてマージに持っていくのみになりそうです。

[project-redisign-help-dialog] ヘルプダイアログのデザインの最終調整

---

src/components/Sing/ScoreSequencer.vue

Add: Ctrl+Shift+ドラッグで追加選択できるように

---

src/components/Sing/MenuBar.vue
src/store/singing.ts
src/store/type.ts

- UTAU用USTファイルをインポートできるようにする
ref #1908 
close #1908

ソング: USTファイルのインポート機能の追加

---

src/components/Dialog/ImportMidiDialog.vue
src/components/Sing/SequencerNote.vue

バージョン0.18.0に向けてデザインを少し調整しました。２点だけです。
* ノートを選択したときの色を以前のオレンジのに戻した
* まだノートの色周りをダークモード含めるとまだ調整しきれていない
* もしかしたら次に選択デザインを変える可能性がある
* 今回変えた上でまた変更があるとUXが落ちてしまう
* ので、一旦前回のに戻してリリースして差分をなるべく少なくし、次回のデザイン調整を受けいれてもらえやすくする
* MIDIインポートダイアログのツールバー上の文字の色を変えた
* デザイン調整だけ
* ツールバーの有るダイアログとないダイアログの２種が産まれることになったが、一旦これで良いかなと
- https://github.com/VOICEVOX/voicevox/issues/1810
マージします！

バージョン0.18.0に向けてデザインを少し調整

---

src/store/singing.ts

一部のUST(SynthesizerVなど)でノートセクションの形式が異なるため
インポートできないのを修正
正規表現で #以降数字4桁 `/^#\d{4}/`としていたが、 #以降数字 `/^#\d+$/)` に変更
ref #1956
close #1956
なし

ソング: 一部のUSTが読めないのを修正 #1956

---

src/components/Sing/ScoreSequencer.vue
src/sing/viewHelper.ts

以下を行います。
- ダブルクリック判定処理をクラス化
close #1938

ダブルクリック判定処理のリファクタリング

---

src/domain/project/schema.ts
src/store/project.ts
src/store/singing.ts
src/store/type.ts

プロジェクトファイルのマイグレーションをファイル切り出ししてテスト可能にしたいです。
その第1弾として、マイグレーションで使っている部分の型宣言をdomainディレクトリ以下に移動します。
domain/projectディレクトリを新たに作ってそちらに移動しています。
- https://github.com/VOICEVOX/voicevox/pull/1912
```bash
git --no-pager  diff -w --color-moved=dimmed-zebra --color-moved-ws=ignore-all-space upstream/main
```
したら変更は移動だけなことがわかるかと！

[refactor] projectのschemaをdomainディレクトリ以下に移動

---

src/components/App.vue

refactor: 不要なref定義を削除する

---

package-lock.json
package.json

新しいVueのバージョンとかを使いたくなってきたので、最新バージョンにアップデートしてみます。
現在のバージョンは3.2です。
3.4辺りでcomputed周りがちょっと最適化されて、出力値が一緒であっても入力値が変更されたら下流は全て再計算されていたのがされなくなりました。
たぶん意図してないところで割と恩恵があるので早めに入れておきたいなと。
とりあえずテストが通るかどうかをチェック

Vueのバージョンを3.4.21に

---

.github/workflows/test.yml
tests/e2e/browser/song/ソング.spec.ts
tests/e2e/browser/アップデート通知ダイアログ.spec.ts

2024年4月25日現在、github actionsにて最新バージョンのmacOSでe2eテストが落ちるようです。
https://discord.com/channels/879570910208733277/893889888208977960/1232870129809883156
応急措置としてテストをスキップします。
ref #2003

macOSのみ、e2eテストを実行しない

---

src/components/Sing/ScoreSequencer.vue

macOSでのピッチ編集結果削除の操作をcommandキーを押しながら左クリックに変更します。
close #2009

ソング：macOSでのピッチ編集結果削除の操作をcommandキーを押しながら左クリックに変更

---

src/components/Sing/ScoreSequencer.vue

ソングエディタで、Cmdキー + マウススクロールでのピアノロールの水平方向の拡大縮小を行うと、同時に垂直方向にスクロールする問題を修正しました。
ref #1995

ソング：水平方向の拡大縮小時に垂直スクロールするのを修正

---

src/components/Sing/ScoreSequencer.vue

cursorNoteNumberをチェックして境界を越えないようにします．
close #1959

ノートをドラッグ移動する処理の際に上下への境界チェック処理を入れる

---

src/components/Sing/ScoreSequencer.vue
src/components/Sing/SequencerNote.vue
src/components/Sing/SequencerPitch.vue
src/components/Sing/SequencerRuler.vue

リリース用に一部のデザイン修正要素を取り入れます(必要であれば取り込んでいただけると幸いです)
- ズームスライダーをQSliderに置き換える(input: rangeデフォルトだったため…)
- ルーラーグリッドを小節だけでなく拍にも表示
- ノート選択時の表示を修正
- 複数入力時の表示を修正
- プレイヘッドの色を修正
- 高解像度ディスプレイなどでピッチラインがぼやけていたのを修正
#1810 
https://github.com/VOICEVOX/voicevox/assets/9082140/6a5d596c-4f3a-4920-b5fb-a92e2d0ae42c

一部のデザイン調整を取り入れる [update snapshots]

---

src/backend/common/ConfigManager.ts
src/store/project.ts

コンフィグのshowPitchInSongEditor -> enablePitchEditInSongEditor、
トラックのpitchEditDataの追加をマイグレーションするコードを追加します。
- ref: https://github.com/VOICEVOX/voicevox_project/discussions/49 ：ソフトウェアアップデート/マイグレーション
（なし）
（なし）

Add: 0.19のマイグレーションを追加

---

src/sing/domain.ts
src/store/project.ts
src/store/singing.ts
src/store/type.ts

プロジェクトファイルにピッチ編集データが保存されていましたが、ロードができてなかったのでロードするようにしました。
ついでに新規プロジェクトファイルを作った時にピッチ編集データが消えない問題に気づいたのでそっちも修正しました。
ピッチ編集データのセッターがなかったのでクリア関数を作りました。
セッターになればクリア関数いらないと思うので、こちらのissueが解決されるタイミングでクリア関数を消してもよさそう？
- https://github.com/VOICEVOX/voicevox/issues/2020

ソング：プロジェクトファイル読み込みでピッチ編集データもロードする

---

src/components/Menu/MenuBar/MenuBar.vue

- https://github.com/VOICEVOX/voicevox/issues/2022
の解決プルリクエストです。
close #2022 
エディターを指定しなくても全体でショートカットキーが効くような方法も欲しいところ

[fix] ソングで保存ショートカットキーが効かないバグを修正

---

src/components/Sing/ScoreSequencer.vue
src/components/Sing/SequencerNote.vue
src/components/Sing/SequencerRuler.vue
src/components/Sing/SingEditor.vue
src/components/Sing/ToolBar/EditTargetSwicher.vue
src/components/Sing/ToolBar/ToolBar.vue

デザインをちょっとだけ調整させていただきました！
* ノートの選択色をプライマリーカラーに寄せる
* ノートのアニメーションをなくす
* ピッチとノート編集の切り替えボタンをトグル形式からグループボタン形式に変える
* コンポーネント化しました
* ついでにツールチップ置いておきました
* 再生位置インジケーターの線の色を薄く
- https://github.com/VOICEVOX/voicevox/pull/2014

デザインをバージョン0.19.0に向けて調整

---

src/components/Sing/SequencerPitch.vue

GPUがWebGL2に対応していない場合はピッチの表示ができないので、
webGLVersionをチェックして2未満の場合にエラーとしてロギングするようにします。
ref #1977
- GPUがWebGL2非対応の場合はOffscreenCanvasで描画するようにしても良いかも

ソング：webGLVersionが2未満の場合にエラーとしてロギングするようにする

---

src/components/Sing/SequencerPitch.vue
src/sing/domain.ts

#2031 の修正PRです。
`applyPitchEdit`で`startFrame`がマイナス値になり、f0にundefinedが入ってレンダリングに失敗するのを修正します。
SequencerPitchの方も`startFrame`がマイナス値になってました…それも修正します。
close #2031
- `applyPitchEdit`のテストがあれば防げたと思うので、テストを書いていった方が良さそう
- 区間を扱うユーティリティー関数を作った方が良いかも
- 1小節目の頭からノートを入力すると書き出し時に一番最初の子音が消えるので、1小節目は入力不可にするorノートをエラー表示でも良いかも

ソング：startFrameがマイナス値になりf0にundefinedが入るバグを修正

---

src/store/singing.ts

<s>音量生成時に音域調整の処理（noteのkeyのシフト）が行われて</s>、正しく音量が生成されていないのを修正します。
また、歌い方生成直後の`scaleGuideVolume`は行う必要はないので、削除します。
VOICEVOX小夜、音域調整-3、声量調整-4
0.18.1→このPRの順です。
https://github.com/VOICEVOX/voicevox/assets/62321214/a4d5324f-4d8f-402b-bb86-cf48b14dbebf
たぶんこれで0.18.1以前と同じ声量に戻ったはず

ソング：音量が正しく生成されていないのを修正

---

.github/CODEOWNERS

自動アサインされるレビュワーをmain-reviewerチームに変更します。
今までは @Hiroshiba と @y-chan が自動アサインされていましたが、いったん @Hiroshiba だけアサインされる形になります。
経緯 https://discord.com/channels/879570910208733277/893889888208977960/1235452920691163206

自動アサインされるレビュワーをmain-reviewerチームに変更する

---

src/store/singing.ts

フレーズのレンダリングがエラーで止まらないように、ひとまずロギングしてcontinueするようにします。
ref #1976
レンダリング中に発生するエラーはほとんどが歌詞のエラーですが、現在は歌詞のエラーなのかそうでないのかが分からない（エンジンとのやり取りでエラーが発生したということしか分からない）ので、ひとまずロギングしてcontinueする形にしています。

ソング：フレーズのレンダリングがエラーで止まらないようにする

---

src/components/base/BaseRowCard.vue
src/components/help/HelpDialog.vue
src/components/template/HelpLibraryPolicySection.vue
src/components/template/HelpMarkdownViewSection.vue
src/components/template/HelpOssLicenseSection.vue
src/components/template/HelpUpdateInfoSection.vue
src/styles/new-colors.scss

ヘルプダイアログの各セクションの背景色の統合と、それに伴う--newcolor-background-drawer色変数の追加を行います。
また、ライトテーマ時のリストと背景の色が同一になったため、階層表現できるようリストに微量な影を付与しました。

[project-redisign-help-dialog]各セクションの背景色の統合

---

.github/workflows/build.yml

Github Actionsのmacos-11が来月にサポート終了になるので、早めにアップデートPRを作っておこうかなと。
CIの`build-test`が通ればとりあえず大丈夫かなと思ってます。
マージ後にdevでビルドされたのを実行テストすれば、まあ。
ちなみになぜかエンジン側では、macos-11でビルドできるけどmacos-11で動かないということになったので、一足先に[移行PR](https://github.com/VOICEVOX/voicevox_engine/pull/1205)を作りました。

macos-11を使わないようにする

---

package-lock.json
package.json
src/store/utility.ts

タイトル通りです。
ref https://github.com/VOICEVOX/voicevox/issues/1644

refactor: TuningTranscriptionのコード量を削減

---

public/qAndA.md

macOS Catalinaはテストできてなかった･･･。
その次のBig Surも動かなくなったので、2段階バージョンを引き上げます。
- https://github.com/VOICEVOX/voicevox_engine/issues/1191
ubuntu 20.04はもうちょっと持つはず。

doc: OSのサポートバージョンを更新する

---

src/backend/electron/manager/engineManager.ts

`node-tree-kill`のエラー処理が間違っていると思います。
現在、エンジンのキルは`try-chatch`を使用しています。
https://github.com/VOICEVOX/voicevox/blob/0fb559dd3d4a8a14b67a09b7bfdfdb73de67ae3b/src/backend/electron/manager/engineManager.ts#L437-L442
しかし`node-tree-kill`のWindowsでの処理は`child_process.exec()`で`taskkill`コマンドを呼び出しているため`child_process.exec()`には成功したが`taskkill`のコマンドに失敗した場合`resolve`も`reject`も呼ばれないため処理が停止してしまいます。
https://github.com/pkrumins/node-tree-kill/blob/cb478381547107f5c53362668533f634beff7e6e/index.js#L29
`node-tree-kill`で処理が停止することはなくなりますが何かしらの理由で`node-tree-kill`でエンジンのキルが不可能になっている場合無限ループに陥るリスクが残っています。

FIX: node-tree-killのエラー処理のミスを修正

---

src/backend/electron/main.ts

メインプロセス内で未捕捉の例外が発生した場合の処理を変更します。
製品版ではログの記録とダイアログの表示、
開発環境ではログを記録後に強制終了するように変更します。
- ref #1581
例外を補足した後に強制終了するかしないかはどちらにもリスクがあります。
強制終了すると今までは無視していた些細なエラーによって強制終了するリスクがあります。
逆に強制終了をしない場合エディタのプロセスが残った状態で停止してしまうリスクがあります。
理想を言えば継続可能な例外は全て捕捉してここには到達しないようにすることが一番いいのですが…

FIX: メインプロセスで未捕捉のエラーが発生したときの処理を変更

---

tests/unit/backend/common/configManager.spec.ts
tests/unit/backend/common/pastConfigs/0.19.1-bug_default_preset.json
tests/unit/backend/common/pastConfigs/index.ts

- https://github.com/VOICEVOX/voicevox/pull/2053 で実装されたマイグレーション処理に対してのテストを追加．
- https://github.com/VOICEVOX/voicevox/issues/2062 にある0.19.1のconfig.jsonをマイグレーションテスト対象に追加．
close #2062

ハミング/ソングスタイルを使用して作成されてしまったデフォルトプリセットを削除するマイグレーション処理に対してのテストを追加する

---

src/plugins/hotkeyPlugin.ts

event.code式に書き換え
.がPeriodだったりと様々な対応しきれないものがあるので対応しているもの以外は弾くようにした
ref #1947

FIX: ホットキーでshift+数字を登録時のエラーをなくす

---

src/store/audio.ts

- https://github.com/VOICEVOX/voicevox/issues/2067
https://github.com/VOICEVOX/voicevox/assets/100256521/2027a166-7e6e-4e41-a642-6e9409b946ff
テキストを無視する処理は、audio_queryや、accent_phrasesを生成する処理の直前に行った方が、記述ミスが減りそうな気がしました。
https://github.com/VOICEVOX/voicevox/blob/4c9550b089aeda07153a2ba203c54d27b988e9ff/src/store/audio.ts#L958-L963

fix: テキスト読み込みでルビ文字列を削除

---

src/components/Dialog/DictionaryManageDialog.vue
src/components/Dialog/ToolBarCustomDialog.vue

「単語の追加・変更を破棄しますか？このまま続行すると、単語の追加・変更は破棄されてリセットされます。」という文言に対し「キャンセル」「続行」となってた。
続行が何を示すのかわからなかったので案内を変更しました。
あと「このまま」という代名詞で分かりにくいので条件を崩しました。

辞書保存ダイアログ・ツールバーカスタマイズの編集破棄の案内がわかりにくかったので修正

---

src/components/Sing/ScoreSequencer.vue
src/components/Sing/SequencerGrid.vue
src/components/Sing/SequencerRuler.vue
src/sing/domain.ts
src/store/singing.ts
src/store/type.ts

シーケンサーのグリッドをコンポーネント化します。
また、以下も行います。
- 右いっぱいにスクロールした状態でマウスホイールで縮小すると表示がおかしくなるのを修正
- `PreviewMode`型の文字列を変更
- `SEQUENCER_NUM_MEASURES`を追加
- リファクタリング
ref #2041

ソング：シーケンサーのグリッドをコンポーネント化する

---

src/components/Dialog/AllDialog.vue
src/components/Sing/CharacterMenuButton/MenuButton.vue
src/store/singing.ts

ソングのデフォルトスタイルはとりあえず実装しない方針ということに決まったので、FIXMEコメントを削除しました。
- https://github.com/VOICEVOX/voicevox/issues/2063
close #2063

refactor: ソングのデフォルトスタイルは一旦実装しない方針

---

src/components/Dialog/DictionaryManageDialog.vue
tests/e2e/browser/辞書ダイアログ.spec.ts

表題の通り、「編集」「削除」ボタンは、タスク指向的ではなく、OOUI的に配置されるのが相応しいので、そのようにスタイルを変更してみました。
- Before
- リストのヘッダ部分
- 削除ボタン (選択中のアイテムがあるときのみクリック可)
- 編集ボタン (選択中のアイテムがあるときのみクリック可)
- 追加ボタン
- リスト本体
- アイテム1
- アイテム2 
- ... 
- After
- リストのヘッダ部分
- 追加ボタン
- リスト本体
- アイテム1 (選択中の場合)
- 削除ボタン 
- 編集ボタン
- アイテム2
- アイテム3
- ...
ついでに、
- リストの一番下の部分が少し窮屈にならないように 16px の padding を追加しました。
- リストの各項目を1行のみ表示、あふれたらエリプシス「…」に設定しました。
- アイコンボタンが現れたり消えたりするとき、行数が変わるとガタつくので
https://github.com/VOICEVOX/voicevox/assets/22636511/0a777765-f601-444b-8e69-6542e4fa45bd

【読み方&アクセント辞書 単語一覧】登録単語の編集・削除ボタンの常時表示をやめてOOUI的に

---

.eslintrc.js
README.md
tests/unit/backend/common/configManager.spec.ts

デバッグしていると不便なのでno-unused-varがwarnレベルになっていますが、mainブランチにマージされる段階では排除しておきたいです。
ということで開発レベルではwarnにし、そうじゃない時はエラーになるようにしてみました。
実際にエラーが出るか確認中です。
→ ちゃんとエラーになってそう！ https://github.com/Hiroshiba/voicevox/actions/runs/9235857203/job/25411080723
productionならエラーになっている場合でも`npm run electron:serve`はちゃんと動くことを確認しました！

no-unused-varを開発時以外はエラーに

---

src/backend/electron/electronConfig.ts

設定ファイルの書き込み失敗時にファイルが消失しないようにしました。
設定ファイル保存は以下の手順で行うようにしています。
1. <設定ファイル名>.tmpに設定の書き込み
2. 1で作成したファイル名を<設定ファイル名>に書き換え
2のタイミングで既存ファイルが存在する場合は上書きするようにしています。
テストは関連しそうなものが見つかりませんでしたので、追加していません。
手動テストとしては、以下の手順を実行しています。
- 設定変更を行い(メモ機能のON)、```config.json```に反映されていること
- ```ElectronConfigManager.save```の```moveFile```の直前に強制終了し、再起動後設定が消失していないこと
Issueの中に記載のあった、以下の記述に関しては現状```ElectronConfigManager.save```でしか使用しない処理なのでhelper関数には移動していません。
> 直接ファイルを書き込んでいるところはいくつかあるので、一度同じディレクトリの.tmpに書き込んだ後moveFileする便利関数を作って使いますと便利そう。
ref #2082 
close #2082

設定ファイルの保存をアトミック操作に変更

---

src/store/dictionary.ts
src/store/vuex.ts

store.ts内における関数の呼び出しにおいて、`dispatch("ACTION1", payloads)` のような引数におけるリテラル指定から `actions.ACTION(payload)` のようにdot記法によるアクセスに変更します。
とりあえずどのくらいの規模でPRを分割すべきかわからなかったので、元のコードは残し、`dictionary.ts`だけ新しい記法に変えています。
type.tsは残したままなので lsp上で `goto definition` をしても `type.ts` に移動するだけですが、 `goto implementation` で実装に飛べます。
ref #2088

vuexのstoreの呼び出しをリテラル引数からDot記法へ

---

.github/workflows/build.yml
.github/workflows/test.yml
electron-builder.config.js

GitHub Actionにdarwin-arm64ビルドを追加しました。
このPRのリリースは次のリンクでご覧いただけます: https://github.com/nix6839/voicevox/releases/tag/0.20.0-nix6839-macos-arm64.1
~~このPRのリリースは次のリンクでご覧いただけます: https://github.com/nix6839/voicevox/releases/tag/0.20.0-nix6839-macos-arm64~~
close: #348
~~VOICEVOXをApple Silicon macOSでネイティブに動作させるという根本的な目的は達成しましたし、Universal2アプリをリリースするには大変な労力がかかると予想されるため、このイシューをクローズしても良いと思います。どう思いますか？~~
~~すべて完成しましたが、voicevox_engineが0.20.0をリリースするのを待たなければならないので、今はドラフトです。~~
- [アクションのmacOSビルドでアドホック署名](https://github.com/VOICEVOX/voicevox/commit/900f0032d95b78494f244a23c4d7eaf1ed9d26f1):
Apple Siliconでネイティブに動作するアプリはコード署名がないと動作しないため、アドホック署名を追加しました。
- [macOSの.appファイルが正しい構造を持つように修正](https://github.com/VOICEVOX/voicevox/commit/030b772f6d549aeebac0a94bbac1a0330b28b39b):
次の部分を修正しました
> …

darwin-arm64プラットフォーム対応

---

src/components/Sing/CharacterPortrait.vue

シング側のポートレート位置を調整します
- ポートレート高さ以下の場合に表示位置を頭上基準(下が見切れる形)にする
- 常に画面一定サイズ(高さ60%)まで表示
ref: #2058 
一般
4K程度
高さが狭い
とても小さい

シング側のポートレート位置を調整する

---

src/components/Sing/ScoreSequencer.vue
src/components/Sing/SequencerLyricInput.vue
src/components/Sing/SequencerNote.vue
src/sing/viewHelper.ts
tests/e2e/browser/song/ソング.spec.ts

v-for1つでノートを描画する形に変更し、ダブルクリック判定処理を無くします。
また、以下も行います。
- `onNoteLyricMouseDown`を削除する
- ScoreSequencerのcontextMenuDataがcomputedになっていなかったので修正
- 編集のプレビュー中はノートの右クリックメニューをdisableにする
- 歌詞入力をコンポーネント化する
ref #2041
ノート編集時の動作が若干重くなってるかもです…

Refactor: v-for1つでノートを描画する形に変更し、ダブルクリック判定処理を無くす

---

src/sing/storeHelper.ts
src/store/singing.ts
src/store/type.ts

ノートの重なり検出を高速にします。具体的には`O(n^2)`から`O(2n log 2n + 2n)`くらいになります。
- Discord: [このあたりの会話](https://canary.discord.com/channels/879570910208733277/893889888208977960/1254731758763507722)
（なし）
（なし）

Improve: ノートの重なり検出のアルゴリズムを変える

---

src/backend/electron/main.ts

RELOAD_URLで飛ばすページをabout:blankにします。
（なし）
文脈：こんな感じのエラーがでて再起動しなかったことがあるので
（なし）

Change: RELOAD_URLで飛ばすページをabout:blankにする

---

src/backend/electron/main.ts
vite.config.mts

プロセスのサンドボックス化を有効化してセキュリティを向上させます。
ref: https://www.electronjs.org/ja/docs/latest/tutorial/sandbox
- close: #1017
`preload.js`が分割されていることがそのまま動かすことができないことの原因でした。
https://electron-vite.github.io/guide/preload-not-split.html
https://github.com/VOICEVOX/voicevox/issues/2071#issuecomment-2103801741 で触れて作業を開始したのですが本当に直接的に関係なかったかもしれません。
`--no-sandbox`を付けても`preload.js`が分割された状態では正常に動作しませんし、この機能を有効化してもUbuntu24.04(VirtualBox上)で`--no-sandbox`を付けて起動させることができました。

feat: sandboxを有効化

---

package-lock.json
package.json
src/components/Dialog/ImportSongProjectDialog.vue

utaformatix-tsを0.3.2に更新します。VoiSonaのプロジェクトを読み込めるようになります。
（なし）
（なし）
（なし）

Update: utaformatix-tsを0.3.2に更新

---

README.md
src/store/index.ts

Vuexのstrictモードでコマンドが積み重なるとだんだん重くなってきます。
環境をビルド時に近づけられるよう、productionモードを検知できるようにしました。
ついでに起動する方法をREADMEで案内するようにしました。
NODE_ENVとモードが別々にあるっぽみ。
https://ja.vitejs.dev/guide/env-and-mode#node-env-%E3%81%A8%E3%83%A2%E3%83%BC%E3%83%88%E3%82%99
これでビルド時、`--mode production`指定時両方でstrictじゃなくなります。
（今まではビルド時のみstrictじゃなくなってた）

Vuexでproductionモードを使用可能にし、productionモードで起動する方法を案内

---

.github/workflows/chromatic.yml

- https://github.com/VOICEVOX/voicevox/pull/2140
でchromaticのアクションズが落ちてしまったので修正です。
ビルドスクリプトがデフォルトと違うかったからなはず。

fix: chromaticのgithubactionsのエラー直す

---

build/installer_linux.sh

Ubuntu 24.04ではそのままでは一般ユーザーがUser NameSpaceを作成できなくなり，プロファイルで許可を出すか--no-sandboxを起動オプションとして渡すかなので，一時的なものとして--no-sandboxを追加します．
%Uの後なのはこうしないとプロジェクトファイルをダブルクリックした際に正常にファイルパスが渡されないのでそれを回避するためです．
close #2071

Ubuntu 24.04の制約を回避するために--no-sandboxオプションをdesktopファイルのExecエントリに追加

---

README.md
src/store/audio.ts
src/store/project.ts
src/store/singing.ts
src/store/type.ts
src/store/utility.ts
tests/unit/store/utility.spec.ts

- 設定で書き出しファイル名パターンにプロジェクトファイル名を設定できるようにしました
- プロジェクトファイル名がない場合、ある場合のそれぞれに対応させました
- プロジェクトファイル名がない場合は空文字にしています
- READMEの軽微な修正をしました
close #2075 
close #2136 
画像1
画像2
画像1の書き出しファイル名パターンを使用し、音声を書き出した際、
- 画像2における`001_.wav`はプロジェクトファイル名を設定していない音声ファイル
- 画像2における`001_開発テスト用.wav`、`002_開発テスト用.wav`はプロジェクトファイル名を設定した上で書き出したファイル
となっています。

ファイルの書き出し時の名前設定にプロジェクトファイル名を含められるようにする

---

src/components/Dialog/ImportSongProjectDialog.vue
src/sing/domain.ts
src/store/singing.ts
src/store/type.ts

インポートをマルチトラックに対応させます。
- ref: #1906 
（なし）

マルチトラック：インポートに対応

---

src/components/Base/BaseDocumentView.vue
src/styles/colors-v2.scss

HelpDialogのデザインの微調整として、DocumentViewのスタイルの調整と色変数のミスの修正を行います。
- 具体的なDocumentViewのスタイルの調整
- detailsタグのスタイルの追加
- ![image](https://github.com/VOICEVOX/voicevox/assets/53995265/e8a461ca-2859-4439-9bf3-853154663b13)
- 2階層目以降のul,olタグの不要な空白の除去
- pre要素の見た目調整
- paddingとborder-radiusをSCSS変数を用いるように変更

[project-redisign-help-dialog] デザインの微調整

---

src/backend/electron/ipc.ts

Electronのベストプラクティスに基づきセキュリティを強化します。
[17. すべての IPC メッセージの sender を確認する](https://www.electronjs.org/ja/docs/latest/tutorial/security#17-%E3%81%99%E3%81%B9%E3%81%A6%E3%81%AE-ipc-%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8%E3%81%AE-sender-%E3%82%92%E7%A2%BA%E8%AA%8D%E3%81%99%E3%82%8B)
開発時は開発サーバーから、製品版ではappプロトコルからであることを確認して意図しないフレームからのIPCを防ぎます。

feat: IPCメッセージの`sender`を確認する

---

src/backend/electron/main.ts

Electronのベストプラクティスに基づきセキュリティを強化します。
[13. ナビゲーションを無効化か制限](https://www.electronjs.org/ja/docs/latest/tutorial/security#13-%E3%83%8A%E3%83%93%E3%82%B2%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%92%E7%84%A1%E5%8A%B9%E5%8C%96%E3%81%8B%E5%88%B6%E9%99%90)
[14. 新規ウインドウの作成を無効化か制限](https://www.electronjs.org/ja/docs/latest/tutorial/security#14-%E6%96%B0%E8%A6%8F%E3%82%A6%E3%82%A4%E3%83%B3%E3%83%89%E3%82%A6%E3%81%AE%E4%BD%9C%E6%88%90%E3%82%92%E7%84%A1%E5%8A%B9%E5%8C%96%E3%81%8B%E5%88%B6%E9%99%90)
[15. 信用されないコンテンツで shell.openExternal を使用しない](https://www.electronjs.org/ja/docs/latest/tutorial/security#15-%E4%BF%A1%E7%94%A8%E3%81%95%E3%82%8C%E3%81%AA%E3%81%84%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84%E3%81%A7-shellopenexternal-%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%AA%E3%81%84)
(部分的) …

feat: ウインドウの作成とナビゲーションを無効化する

---

src/components/Dialog/EngineManageDialog.vue

マルチエンジン用のダイアログで表示される部分です。漏れていたので追加しました。
ついでにキーが漏れていたらエラーになるようにしました。キーがoptionalだとエラーにならなかった模様。

fix:`returnResourceUrl`の説明を追加

---

src/backend/electron/main.ts

プリロードスクリプトを変更したときに自動的にリロードされなくなってしまっていたのでこれを修正します。
- ref: #2154
プリロードスクリプトを変更するとナビゲーションが起こるようです。
これを完全に無効化してしまったことが原因です。
URLが変わっていなければナビゲーションを許可することでリロードをできるようにします。

fix: プリロードスクリプトを変更した時HMR(自動リロード)が機能しない問題を修正

---

src/backend/electron/main.ts

Electronのベストプラクティスに基づきセキュリティを強化します。
[18. Avoid usage of the `file://` protocol and prefer usage of custom protocols](https://www.electronjs.org/ja/docs/latest/tutorial/security#18-avoid-usage-of-the-file-protocol-and-prefer-usage-of-custom-protocols)
ref: https://www.electronjs.org/ja/docs/latest/api/protocol#protocolhandlescheme-handler
`app://`プロトコルのファイルパスを制限して意図しないファイルの読み込みを防ぎます。

feat: appプロトコルでfetch可能なディレクトリを制限する

---

src/store/vuex.ts
tsconfig.json

tsconfigの内容が若干怪しいものがありましたので修正します。
ref: [Vite | TypeScript コンパイラーオプション](https://ja.vitejs.dev/guide/features.html#typescript-%E3%82%B3%E3%83%B3%E3%83%8F%E3%82%9A%E3%82%A4%E3%83%A9%E3%83%BC%E3%82%AA%E3%83%95%E3%82%9A%E3%82%B7%E3%83%A7%E3%83%B3)
ref: [TypeScript で Vue を使用する | tsconfig.json の構成](https://ja.vuejs.org/guide/typescript/overview.html#configuring-tsconfig-json)
- `target`
Viteはこれを実質的に無視します。
ここでは制御していないことを明示するために`esnext`に設定します。
設定が必要な場合は`vite.config.mts`を変更する必要があります。
- [`useDefineForClassFields`](https://www.typescriptlang.org/tsconfig/#useDefineForClassFields)
`target`を変更したことによってデフォルト値が`false`から`true`に変更されます。
これにより`src/store/vuex.ts`に変更を加える必要があります。
- `jsxImportSource`
Vueの推奨値。
これを設定する必要は感じませんが`"jsx": "preserve"`が設定されていたのでそれに合わせます。
- `isolatedModules` …

fix: tsconfigをViteの推奨する設定に合わせる

---

src/store/command.ts
src/store/project.ts
src/store/singing.ts
src/store/type.ts
src/type/preload.ts

プロジェクトを編集したかどうかの判定に、コマンドごとに`unixMillisec`を持たせていました。
特に問題ないのですが、時刻よりも ユニークな ID を設定したほうが意図と合うのでそうしてみました。
というよりどちらかというと、コマンドが想定通りかsnapshotテストをしたく、時刻だとモックさせづらかったので他と合わせたいです。
こうしておけば、UUID4をモックにすることでID系もsnapshotテストできるようになって嬉しいです。

リファクタリング：コマンドのunixMillisecをUUID4にする

---

src/store/audio.ts
src/store/command.ts
src/store/engine.ts
src/store/preset.ts
src/store/project.ts

の続きです。
store内における関数の呼び出しにおいて、dispatch("ACTION1", payloads) のような引数におけるリテラル指定から actions.ACTION(payload) のようにdot記法によるアクセスに変更します。
+ store/command.ts
+ store/preset.ts
+ store/engine.ts
+ store/project.ts
+ store/audio.ts
を変更しています。
storeの残りのsinging.tsはコンフリクトが多そうなので色々終わってからにしようと思います。
dispatch
actions
actions\([\s\n]*"([A-Z_]*)",?
actions.$1(
commit
mutations
mutations\([\s\n]*"([A-Z_]*)",?
mutations.$1(
の順に置換してその後眼力チェックしています。

vuexのstoreの呼び出しをリテラル引数からDot記法へ: command.ts, preset.ts, engine.ts, project.ts, audio.ts

---

src/store/singing.ts

複数選択が出来ないのを修正します。
- closes: #2183 
（なし）
やっぱりtoRawしばりたくなってきた（structuredClone(toRaw())はcloneWithUnwrapProxyで代替できるので）

マルチトラック：複数選択が出来ないのを修正

---

src/store/singing.ts
src/store/type.ts
tests/unit/store/command.spec.ts
tests/unit/store/singing.spec.ts

REGISTER_TRACKは実質的に最後尾にトラックを追加する（add/appendする）挙動をしていました。
トラックリストの途中に挿入する時に不便なので`INSERT_TRACK`に変更します。
トラックをコピペする時とかは挿入された方が便利なので、基本的にこっちの方が使い勝手が良いと思います。
`prevTrackId`の後ろにトラックを追加します。prevTrackId=undefinedの場合は今まで通り最後尾に追加します。
このプルリクエスト自体は挙動変更がないはず。
ちなみにUX考えると、最後尾に追加したいことはほとんどないはず。（トークの経験上）
ref: https://github.com/VOICEVOX/voicevox/issues/2182#issuecomment-2258729695
ついでになんとなくテストも追加してみました。

ソング：REGISTER_TRACKをINSERT_TRACKに変更

---

src/store/singing.ts

- https://github.com/VOICEVOX/voicevox/issues/2194
の修正プルリクエストです。
ついでに全singing.tsのactionを検査して、RENDERが必要そうなやつを点検してみました。
`TIME_SIGNATURE`周りでRENDERが呼ばれてないやつはいくつかあったんですか、これ多分いりますよね･･･？
ということでついでに入れときました。
（`COMMAND_`の方にだけRENDERがなかった）
close #2194 
点検してた感じ、多分これ使わないだろうなっていうactionがいっぱいありました。
コマンド以外ありえないコマンドじゃない関数とか。
呼び間違いがいつか起こりそうだ、消してもいいかもしれない。

fix: ソロ全解除をして再生すると、全解除前のように聞こえるバグの修正

---

src/components/Sing/SideBar/TrackItem.vue

- https://github.com/VOICEVOX/voicevox/issues/2198
の解決プルリクエストです。
バッファ変数を作っていて、そのバッファ変数が変わった時にstoreの方に変わった方の値を投げないといけないのですが、storeの方の値を投げていたのが原因でした。
なのでバッファ変数（＝表示される値）だけ変わっていて、保存されていなかった感じでした。
fix #2198 
これ気づけなかったの申し訳ないですねぇ･･･。
バッファ変数作ってちょっと特殊だったから、テストを書いても良かったのかもしれない。けどまあ･･･。
1回実行チェックしておくべきだったかもしれない。

fix: トラック名が保存されないバグの修正

---

src/components/Dialog/DictionaryManageDialog.vue

関連 issue で報告された不具合の解消
選択せずホバーで「編集」「削除」ボタンが表出された場合のために、そのボタンの click イベントハンドラで `editWord()`  / `deleteWord()` の前に `selectWord(key)` を実行する。
close #2196

読み方&アクセント辞典: click イベントハンドラで `editWord()`  / `deleteWord()` の前に `selectWord(key)` を実行する。

---

CONTRIBUTING.md
README.md

READMEのエンジンのパスについての案内がかなり古くなっていたので変更しました。
ついでに多分貢献者向けの案内も一部意図と違ってそうだったので変更してみました。
何か説明が若干不格好だけど･･･。

docs: READMEのエンジンのパスについてもう少し詳しく案内

---

package-lock.json
package.json

utaformatix-tsを更新します。
- ref: https://x.com/okep_s/status/1819590460119413131
- ref: https://github.com/sdercolin/utaformatix3/pull/183
- ref: #2204 
（なし）
もうそろそろ色々アプデしてもいい時期かも

Update: utaformatixを0.4.0に更新

---

src/components/Dialog/HotkeyRecordingDialog.vue
src/components/Dialog/HotkeySettingDialog.vue
src/components/Dialog/SetHotkeyDialog.vue

- キー割り当て画面のホットキー設定ダイアログを抜き出してコンポーネント化
- `/components/Dialog/SetHotkeyDialog.vue`を作成
close #2002

キー割り当て画面からホットキー設定ダイアログを抜き出してコンポーネント化する

---

src/components/App.vue
src/components/Base/BaseListItem.vue
src/components/Base/BaseRowCard.vue
src/components/Base/BaseSwitch.vue
src/components/Base/BaseTooltip.vue
src/components/Dialog/ToolBarCustomDialog.vue
src/styles/v2/variables.scss

ツールバーのカスタマイズダイアログを新デザインに変更します。具体的に以下のことを行います。
- BaseSwitch, BaseTooltipコンポーネントを追加
- 表示するボタンのリスト部分のコンポーネントを置き換え
- （ヘッダー部分はHelpDialogと同様置き換えていません）
- ヘッダーボタンのツールチップを置き換え
- Tooltipの振る舞いをグローバルに制御するためのTooltipProviderコンポーネントをApp.vueに追加
ref voicevox/voicevox_project#40

ツールバーのカスタマイズダイアログのリデザイン

---

src/store/singing.ts

の続きです。
store内における関数の呼び出しにおいて、dispatch("ACTION1", payloads) のような引数におけるリテラル指定から actions.ACTION(payload) のようにdot記法によるアクセスに変更します。
+ store/singing.ts
を変更しています。
dispatch
actions
actions\([\s\n]*"([A-Z_]*)",?
actions.$1(
commit
mutations
mutations\([\s\n]*"([A-Z_]*)",?
mutations.$1(
の順に置換してその後眼力チェックしています。

vuexのstoreの呼び出しをリテラル引数からDot記法へ: singing.ts

---

.github/actions/download-engine/action.yml
build/codesign_setup.bash

curlの`--retry-all-errors`引数はubuntu-20.04でだけ使えなかったっぽいことがわかったので無くしました。
ちなみにこの引数はサーバー側が400エラーになったり500エラーになった場合でもリトライする仕組みです。
それ以外のエラーはちゃんとリトライされるはず。

fix: --retry-all-errorsの未対応をなくす

---

src/components/Talk/AudioCell.vue

- トークエディタ画面で右クリックメニューを使用する際、テキスト未選択時にコンテキストメニューヘッダー上で過去に選択したテキストが表示されるバグを解消
https://github.com/VOICEVOX/voicevox/pull/2156#issuecomment-2282126084
https://github.com/user-attachments/assets/189e2e9b-512b-4855-bd3f-fc4b2d7d920b
https://github.com/user-attachments/assets/54b37d19-9f73-483a-be0b-98ca369b265f

テキスト未選択時にコンテキストメニューヘッダーを非表示にする

---

src/components/Dialog/DictionaryManageDialog.vue

- 読み方&アクセント辞書の編集画面におけるリセットボタンの挙動を修正
close #2229 
https://github.com/user-attachments/assets/9803ed84-f370-4861-89c6-e597de745643

辞書のリセットボタンの挙動を修正する

---

.storybook/main.ts
.storybook/preview.ts
package-lock.json
package.json
src/components/Base/BaseButton.stories.ts
src/components/Base/BaseDocumentView.stories.ts
src/components/Base/BaseDocumentView.vue
src/components/Base/BaseListItem.stories.ts
src/components/Base/BaseRowCard.stories.ts
src/components/Base/BaseScrollArea.stories.ts
src/components/Base/BaseSwitch.stories.ts
src/components/Base/BaseSwitch.vue
src/components/Dialog/ToolBarCustomDialog.vue

今までに作成したBaseコンポーネントのStorybookファイルを作成します。また、それに付随して以下を行います。
- 色変数の使用とテーマ切り替えのため、storybook/addon-themesを導入
- onLabelがその命名のせいでStorybook上でprops判定されなかった（し、人間から見てもイベント関数で頻用されるon〇〇の形とこんがらがりそう）ため、onLabel/offLabelをcheckedLabel/uncheckedLabelに改名

BaseコンポーネントのStorybookファイルを作成

---

src/components/Dialog/HotkeyRecordingDialog.vue

このようなwarningが出ていたので、該当箇所を削除してみました。
```log
[@vue/compiler-sfc] `defineProps` is a compiler macro and no longer needs to be imported.
[@vue/compiler-sfc] `defineEmits` is a compiler macro and no longer needs to be imported.
```

refactor: definePropsのimportは不要らしいので削除

---

src/backend/browser/sandbox.ts
src/backend/electron/ipc.ts
src/backend/electron/main.ts
src/backend/electron/preload.ts
src/plugins/ipcMessageReceiverPlugin.ts
src/type/ipc.ts
src/type/preload.ts

#2088 の実現方法を参考に、IPC周りの呼び出しをdot記法で書けるようにしてみました。

IPC周りの呼び出しをdot記法で書けるように

---

.eslintrc.js
tsconfig.json

eslintの対象を`./*/**/`にするとroot直下にある`.`始まりのフォルダ内のものが見えないことに気づきました。
- https://github.com/VOICEVOX/voicevox/pull/2172
特に`*.ts`にしてもエラーにならなかったので、そうしてみるPR作ってみました。
> tsconfigで*.tsを指定すると大変になりそう
ということだったので、tsconfigはそのままにeslintを変えてみました。

eslintの観測範囲を`*.ts`へ

---

src/components/Sing/ScoreSequencer.vue
src/components/Sing/SequencerPhraseIndicator.vue
src/components/Sing/SequencerPitch.vue
src/sing/domain.ts
src/sing/phraseRendering.ts
src/store/singing.ts
src/store/type.ts
tests/unit/lib/selectPriorPhrase.spec.ts

以下を行います。
- `PhraseRenderer`を追加
- `QueryGenerationStage`を追加
- `SingingVolumeGenerationStage`を追加
- `SingingVoiceSynthesisStage`を追加
- 以下の関数を`phraseRendering.ts`に移動
- `createNotesForRequestToEngine`
- `shiftKeyOfNotes`
- `getPhonemes`
- `shiftPitch`
- `shiftVolume`
- `muteLastPauSection`
- フレーズのレンダリング処理を`PhraseRenderer`を使用して行うように変更
- フレーズの開始時間（`startTime`）を`Phrase`に持たせ、算出をフレーズ生成時に行うように変更
- `PhraseState`に`SINGER_IS_NOT_SET`を追加
- 型を整理
1. 重なっているノートを除外
1. `searchPhrases`を実行
1. 新しいフレーズまたは既存のフレーズに対して以下を行う
1. シンガーが未設定の場合、`state`を`SINGER_IS_NOT_SET`に設定
1. シンガーが設定されている場合、以下を行う
1. 新しいフレーズまたは`state`が`COUND_NOT_RENDER`の場合、レンダリング開始ステージを一番最初のステージに設定
1. 既存のフレーズの場合、適切なレンダリング開始ステージを決定する
1. `state`を`WAITING_TO_BE_RENDERED`に設定
1. 無くなったフレーズに対して、以下を行う
1. シーケンスが存在する場合、シーケンスを削除する
1. …

ソング：フレーズのレンダリング処理をリファクタリング

---

src/components/Base/BaseButton.vue
src/components/Base/BaseListItem.vue
src/components/Base/BaseNavigationView.stories.ts
src/components/Base/BaseNavigationView.vue
src/components/Base/BaseScrollArea.vue
src/components/Base/BaseTextField.stories.ts
src/components/Base/BaseTextField.vue
src/components/Base/BaseToggleGroup.stories.ts
src/components/Base/BaseToggleGroup.vue
src/components/Base/BaseToggleGroupItem.vue
src/components/Dialog/EngineManageDialog.vue

エンジンの管理ダイアログをリデザインします。具体的に以下を行います。
- 必要なBaseコンポーネント（BaseToggleGroup, BaseNavigationView, BaseTextField）の追加
- 追加したBaseコンポーネントのstoriesファイルを追加
- BaseScrollAreaで親のheightの100%が伝搬できるように変更
- ダイアログのフッター部の下固定をできるようにするため

エンジンの管理ダイアログのリデザイン

---

src/components/Base/BaseNavigationView.vue
src/components/Dialog/HelpDialog/HelpDialog.vue
src/components/Dialog/HelpDialog/HelpLibraryPolicySection.vue
src/components/Dialog/HelpDialog/HelpMarkdownViewSection.vue
src/components/Dialog/HelpDialog/HelpOssLicenseSection.vue
src/components/Dialog/HelpDialog/HelpUpdateInfoSection.vue

HelpDialog内のレイアウトをNavigationViewに置き換えます。また、NavigationViewとHelpDialogへの軽微なデザイン調整を含みます。
- NavigationViewの一番外側の要素で新デザインの色の文字色を指定するように
- 利用規約のsubtitleに上マージンを微量に付ける

HelpDialog内のレイアウトをNavigationViewに置き換え・調整

---

src/backend/electron/engineAndVvppController.ts
src/backend/electron/main.ts

- https://github.com/VOICEVOX/voicevox/pull/2260#issuecomment-2349275014
の時のコメントにあった、エンジン＆VVPP周りの処理を移動させてみるリファクタリングです。
処理用のクラスにしてみました。
エンジンマネージャーやVVPPマネージャーの参照を渡してもらって、複数の処理が必要な関数を切り出した感じです。
なので一部、ただgetやfetchするだけの関数は移動させてません。
操作部分だけ移行させましたが、そもそもマネージャークラスの作成から担うこともできそうですが、一旦どうなるかわからなかったのでやめてます。
main.tsからEngineManagerやVvppManagerを直接参照できなくなり、疎結合になる一方で設計がまだどうなるかわからないから最悪リバートもありえそうだなぁと思い。
ほぼ行を移動させているので、↓のコマンドだと差分が見やすいかも。
```bash
git diff -w --color-moved=dimmed-zebra --color-moved-ws=ignore-all-space upstream/main
```
- https://github.com/VOICEVOX/voicevox/pull/2260#issuecomment-2349275014
- https://github.com/VOICEVOX/voicevox/issues/1194
処理の流れは変わってないはず。
ただ関数の移動だけでは済まないところがいくつかあったので、そこはコードが書き換わってます。
* IPC 通信で レンダラーに命令を送っている部分(`reloadCallback`)
* …

refactor: エンジンとVVPP周りの処理の流れを制御するクラスを切り出し

---

src/store/singing.ts

レンダリングの必要はないのに`state`が`WAITING_TO_BE_RENDERED`のままになっているフレーズが存在してエラーになっていたので、修正します。
たぶん d3904c495ad0af7f57cb8e57c4578728ad008e0f からバグってます。

Fix: フレーズのレンダリングでエラーになることがあるのを修正

---

src/backend/common/ConfigManager.ts
src/components/Dialog/SettingDialog/SettingDialog.vue
src/components/Talk/AudioInfo.vue
src/store/preset.ts
src/store/setting.ts
src/type/preload.ts

- https://github.com/VOICEVOX/voicevox/pull/1719
で、プリセット機能を通常機能にしたはずなのですが、設定画面のUIだけ変えてconfig.jsonの中身を変えていなかったので、変更しました。
- https://github.com/VOICEVOX/voicevox/pull/1719
（config.vue周りの書き換えを忘れていたのであとで変更します）

fix: preset周りのコードを実験的機能から通常機能に変更する

---

src/components/Sing/ScoreSequencer.vue
src/composables/useCursorState.ts

useCursorStateのcursorClassを使用するようにします。
まだ`project-sequencer-statemachine`が完了していないので、
プレビュー中でないときの処理をひとまず`watch`の中に書いています。
https://github.com/VOICEVOX/voicevox/pull/2218#discussion_r1776676201

ソング：useCursorStateのcursorClassを使用するように変更

---

src/store/singing.ts

シーケンスを作成する処理を関数化して、RENDER関数の外に出します。
https://github.com/VOICEVOX/voicevox/pull/2152

ソング：シーケンスを作成する処理を関数化してRENDER関数の外に出す

---

docs/res/起動シーケンス図.md
src/backend/electron/engineAndVvppController.ts
src/backend/electron/manager/engineInfoManager.ts
src/backend/electron/manager/engineProcessManager.ts
src/type/preload.ts

EngineInfoManagerで、エンジン情報のキャッシュを作らないようにしてみました。
これは毎回エンジン情報をディレクトリやファイルから取ってくるようになってしまいますが、キャッシュ由来のバグがなくなるのでこっちの方がいいかなぁと。
↓の関連issueのタスクでエンジン情報を何度か取得・登録を繰り返しそうなので、一旦変えてみました。
不要そうならまた後で戻してもいいかも。
- https://github.com/VOICEVOX/voicevox/issues/1194
- https://github.com/VOICEVOX/voicevox/pull/2270
調査してそもそもこうした方がいいと思った経緯はこんな感じです。
* キャッシュを作ってる意味の調査
* additionalEngineInfosのキャッシュが作られた理由
* ポートが変わった時にEngineInfoの.hostも書き換えるから、インスタンス変数にしておく必要がある
* https://github.com/VOICEVOX/voicevox/pull/1352
* defaultEngineInfosのキャッシュが作られている理由
* blame追ってみた感じ、[昔はbackground.tsにconst変数を直書きしていて](https://github.com/sabonerune/voicevox/commit/0662bc791bb81b2e75d54dd448f3b3769698be82#diff-11db236acd6b02b1229e7d325e9bf8edb521032e6388f68b6a884ec24bbe291fL118)、それをマネージャークラスにそのまま移したからインスタンス変数になった
* …

refactor: エンジン情報のキャッシュを作らないように変更

---

src/components/Sing/ToolBar/ToolBar.vue

掲題の状態で使いづらいという報告をXで見つけたもの
小さな修正のためプルリク
ref #2277 
close #2277

ソング：誤操作を減らすため「最初に戻る」ボタンと「プレイ」ボタンの間にスペースを設ける

---

src/backend/browser/contract.ts
src/backend/electron/engineAndVvppController.ts
src/backend/electron/manager/RuntimeInfoManager.ts
src/backend/electron/manager/engineInfoManager.ts
src/backend/electron/manager/engineProcessManager.ts
src/backend/electron/portHelper.ts
src/components/Menu/MenuBar/MenuBar.vue
src/components/Talk/TalkEditor.vue
src/store/proxy.ts
src/store/type.ts
src/type/preload.ts
tests/unit/backend/electron/RuntimeInfo.spec.ts

https://github.com/VOICEVOX/voicevox/pull/2272#issuecomment-2374839607 で提案されたリファクタリングです。

refactor: ポート変更時に`EngineInfo`の情報を書き換えないようにする。

---

src/backend/browser/sandbox.ts
src/backend/electron/main.ts
src/backend/electron/preload.ts
src/store/index.ts
src/type/ipc.ts
src/type/preload.ts
src/type/staticResources.ts

https://github.com/VOICEVOX/voicevox/pull/2282#pullrequestreview-2354224261 で提案されたリファクタリングです。
それぞれ別の関数から取得していたリソースを一つの関数から取得するようにします。

refactor: テキストファイルの受け渡しの処理のリファクタリング

---

src/components/Sing/ScoreSequencer.vue

`mousemove`と`mouseup`を、`sequencerBody`ではなく`window`でlistenするようにして、
シーケンサーの外で起こった`mousemove`、`mouseup`も拾うようにします。

ソング：シーケンサーの外で起こったmousemove、mouseupも拾うようにする

---

.github/workflows/build.yml

`Error: write EPIPE`みたいなエラーが出てコケるのを防止します。
といってもバージョンを下げるだけ。

hotfix: リリースがコケるのをなおす

---

src/components/Dialog/ImportSongProjectDialog.vue

ソングのインポートで1->2->3->6->5->4の順にチェックマークを入れるとその順にインポートされていました。
これを1->2->3->4->5->6の順にインポートするようにします。
（なし）
（なし）
（なし）

Fix: インポート順をクリック順に依存しないようにする

---

src/backend/electron/electronConfig.ts
src/backend/electron/fileHelper.ts
src/backend/electron/main.ts
src/backend/electron/manager/RuntimeInfoManager.ts
src/helpers/fileHelper.ts

@RikitoNoto さんが #2098 で作成してくださったファイル保存を
~~`src/helpers/fileHelper.ts`にヘルパー関数として切り出しました。~~
上記のファイルはレンダラープロセスからも参照されるため、
`src/backend/electron/fileHelper.ts`にヘルパー関数として切り出しました。
それに伴い、
- `src/backend/electron/electronConfig.ts` の `ElectronConfigManager.save`
- `src/backend/electron/main.ts`の`WRITE_FILE`部分
- `src/backend/electron/manager/RuntimeInfoManager.ts` の`exportFile` 関数
のファイル保存処理をヘルパー関数で置き換えました。
それぞれ、
- `設定/ツールバーのカスタマイズ`から設定を変更し、保存ボタンを押した時
- プロジェクトを変更し、保存した時
- 起動時のruntime-info.json生成時
にwriteFileSafelyのmoveFile呼び出しの前でelectronを停止したときにtmpファイルが存在しており、electronを再起動してファイルが正しく開ける/正しく起動できることを確認しました。
ref #2103 #2098 
close #2103 
`src/backend/electron/main.ts`の`WRITE_FILE`部分を非同期関数に変えてしまったのですが、こちらで問題ないでしょうか？

ファイル保存全般をアトミックにする

---

src/components/Dialog/Dialog.ts
src/store/audio.ts
src/store/audioPlayer.ts
src/store/command.ts
src/store/dictionary.ts
src/store/engine.ts
src/store/index.ts
src/store/preset.ts
src/store/project.ts
src/store/setting.ts
src/store/singing.ts
src/store/ui.ts
src/store/vuex.ts

の続きです。
store/フォルダ内のdispatch("ACTION1", payloads) のような引数におけるリテラル指定から actions.ACTION(payload) のようにdot記法によるアクセスに変更します。
+ src/store/index.ts
+ src/store/audioPlayer.ts
+ src/store/project.ts
を対応しています。
また、`withProgressDotNotation` や `createDotNotationPartialStore` といったDotNotationが付いた名前を元に戻しています。

vuexのstoreの呼び出しをリテラル引数からDot記法へ: src/store/

---

src/components/Dialog/AcceptDialog/AcceptRetrieveTelemetryDialog.vue
src/components/Dialog/AcceptDialog/AcceptTermsDialog.vue
src/components/Dialog/AllDialog.vue
src/components/Dialog/CharacterOrderDialog.vue
src/components/Dialog/DefaultStyleListDialog.vue
src/components/Dialog/DefaultStyleSelectDialog.vue
src/components/Dialog/DictionaryManageDialog.vue
src/components/Dialog/EngineManageDialog.vue
src/components/Dialog/ExportSongAudioDialog/Container.vue
src/components/Dialog/HelpDialog/HelpDialog.vue
src/components/Dialog/HotkeySettingDialog.vue
src/components/Dialog/ImportSongProjectDialog.vue
src/components/Dialog/PresetManageDialog.vue
src/components/Dialog/SettingDialog/SettingDialog.vue
src/components/Dialog/ToolBarCustomDialog.vue
src/components/Dialog/UpdateNotificationDialog/Container.vue

+ https://github.com/VOICEVOX/voicevox/pull/2327
の続きです。
components/Dialog/フォルダ内のdispatch("ACTION1", payloads) のような引数におけるリテラル指定から actions.ACTION(payload) のようにdot記法によるアクセスに変更します。
+ src/components/Dialog/AcceptDialog/AcceptRetrieveTelemetryDialog.vue
+ src/components/Dialog/AcceptDialog/AcceptTermsDialog.vue
+ src/components/Dialog/AllDialog.vue
+ src/components/Dialog/CharacterOrderDialog.vue
+ src/components/Dialog/DefaultStyleListDialog.vue
+ src/components/Dialog/DefaultStyleSelectDialog.vue
+ …

vuexのstoreの呼び出しをリテラル引数からDot記法へ: components/Dialog

---

src/components/Menu/MenuBar/MenuBar.vue
src/components/Menu/MenuBar/MinMaxCloseButtons.vue
src/components/Menu/MenuBar/TitleBarEditorSwitcher.vue

+ https://github.com/VOICEVOX/voicevox/pull/2327
+ https://github.com/VOICEVOX/voicevox/pull/2328
の続きです。
components/Menu/フォルダ内のdispatch("ACTION1", payloads) のような引数におけるリテラル指定から actions.ACTION(payload) のようにdot記法によるアクセスに変更します。
+ src/components/Menu/MenuBar/MenuBar.vue
+ src/components/Menu/MenuBar/MinMaxCloseButtons.vue
+ src/components/Menu/MenuBar/TitleBarEditorSwitcher.vue
を対応しています。
dispatch\([\s\n]*"([A-Z_]*)",?
actions.$1(
と正規表現で置換してその後眼力チェックしています。

vuexのstoreの呼び出しをリテラル引数からDot記法へ: components/Menu

---

src/components/Sing/ScoreSequencer.vue
src/components/Sing/SequencerKeys.vue
src/components/Sing/SequencerNote.vue
src/components/Sing/SequencerRuler/Container.vue
src/components/Sing/SideBar/SideBar.vue
src/components/Sing/SideBar/TrackItem.vue
src/components/Sing/SingEditor.vue
src/components/Sing/ToolBar/ToolBar.vue
src/components/Sing/menuBarData.ts

+ https://github.com/VOICEVOX/voicevox/pull/2327
+ https://github.com/VOICEVOX/voicevox/pull/2328
+ https://github.com/VOICEVOX/voicevox/pull/2329
の続きです。
components/Sing/フォルダ内のdispatch("ACTION1", payloads) のような引数におけるリテラル指定から actions.ACTION(payload) のようにdot記法によるアクセスに変更します。
+ src/components/Sing/ScoreSequencer.vue
+ src/components/Sing/SequencerKeys.vue
+ src/components/Sing/SequencerNote.vue
+ src/components/Sing/SequencerRuler/Container.vue
+ src/components/Sing/SideBar/SideBar.vue
+ …

vuexのstoreの呼び出しをリテラル引数からDot記法へ: components/Sing

---

src/composables/useLyricInput.ts
src/composables/useRootMiscSetting.ts
src/plugins/ipcMessageReceiverPlugin.ts

+ https://github.com/VOICEVOX/voicevox/pull/2327
+ https://github.com/VOICEVOX/voicevox/pull/2328
+ https://github.com/VOICEVOX/voicevox/pull/2329
+ https://github.com/VOICEVOX/voicevox/pull/2330
の続きです。
今までのPR以外のファイルでのdispatch("ACTION1", payloads) のような引数におけるリテラル指定から actions.ACTION(payload) のようにdot記法によるアクセスに変更します。
+ src/composables/useLyricInput.ts
+ src/composables/useRootMiscSetting.ts
+ src/plugins/ipcMessageReceiverPlugin.ts
を対応しています。 …

vuexのstoreの呼び出しをリテラル引数からDot記法へ: composables, plugins

---

.vscode/launch.template.json
.vscode/tasks.template.json
README.md
src/backend/electron/ipc.ts
src/backend/electron/main.ts
src/vite-env.d.ts
tests/e2e/electron/example.spec.ts
vite.config.mts

いつからかはっきり覚えていないのですがVSCodeを使用したメインプロセスのデバッグの起動が自分の環境では非常に遅くなりました。(自分のPCのスペックが低いというのもありますが…)
恐らくデバッガが開発サーバーを監視していることが原因だと思います。
このPRで開発サーバーの起動とElectronの起動を分離することでメインプロセスデバッグ時の起動を高速化します。
`SKIP_LAUNCH_EDITOR`環境変数に`1`を設定したうえで`electron:serve`を実行するとエディタの起動とメインプロセスのリロードが行われなくなります。
この状態で `npx electron . --no-sandbox`を実行するとエディタが起動します。
そのための`launch.template.json`と`tasks.template.json`追加しました。
`VITE_DEV_SERVER_URL`はビルド時に埋め込まれます。
レンダラープロセスの`sourcemap`が正しく検出できていなかったので変更しました。

feat: `electron:serve`起動時にエディタを起動しないオプションを追加

---

src/helpers/fileHelper.ts

ファイルエラーのメッセージを少しわかりやすくします。
おそらくディレクトリが無いときもエラーになるので、ファイルがないorフォルダがないとしました。

fix: ファイルエラーのメッセージを少しわかりやすくする

---

src/store/singing.ts
src/store/type.ts

まだ音素タイミング編集機能の設計はできていませんが、ピッチ生成ステージは必要になるので、ひとまず実装します。

ソング：ピッチ生成ステージを追加

---

src/backend/electron/engineAndVvppController.ts
src/backend/electron/main.ts
src/backend/electron/manager/RuntimeInfoManager.ts
src/backend/electron/manager/engineInfoManager.ts
src/backend/electron/manager/engineProcessManager.ts
src/backend/electron/manager/vvppManager.ts

https://github.com/VOICEVOX/voicevox/pull/2298#pullrequestreview-2379408774 で提案されたリファクタリングです
`EngineAndVvppController`がget～で煩雑になった感じがします。
ただ、複数のマネージャーをまとめて管理するためのものだから仕方がない？

refactor: managerクラスの取得方法を変更

---

src/domain/japanese/index.ts
src/sing/domain.ts

moraPattern関数をjapanese.tsに移動させます。
- https://github.com/VOICEVOX/voicevox/pull/2152/
のために必要で、リファクタリングとして切り出しました。
#2152

Refactor: moraPatternをdomain/japaneseに移動

---

package-lock.json
package.json
src/components/Dialog/TextDialog/QuestionDialog.stories.ts

- https://github.com/VOICEVOX/voicevox/issues/2362
の解決プルリクエストです。
QuestionDialogが、Storybook上で`onHide`がなぜか呼ばれなくなってるっぽい。
Storybook内でDialog.createしたりしたのですが、onHideが呼ばれない続きだったので諦めて`modelValue`がfalseになることをテストするようにしました。
fix #2362 
なぜCI上では呼ばれてるのか不明･･･････。

fix: Storyのテストが一部通らなくなってるのを修正

---

src/components/Sing/ToolBar/ToolBar.vue

ソングのツールバーの拍子ラベルがずれていたのを修正します
ref #2370 
close #2370

Fix: 拍子ラベルがずれていたのを修正する

---

src/components/Sing/SequencerRuler/Container.vue
src/components/Sing/SequencerRuler/Presentation.vue
src/components/Sing/SequencerRuler/index.stories.ts
src/sing/domain.ts

以下の機能を追加します
- ルーラークリックでの再生ヘッド位置変更時にスナップにあわせる
たとえば小節頭などで微妙にずれる問題がなくなります
ref #2295 
close #2295
変化がわかりづらいためなし
(クリック位置と一番近いスナップグリッドの位置に再生ヘッドが移動します)
1/2など大きいスナップの場合は1/4が上限にするなども考えましたが
いまいち挙動がわかりづらくなった＆1/2であれば1/2にスナップして欲しい感あったので
単にスナップグリッドにあわせる形にしています

Add:ルーラークリックでスナップ位置に再生ヘッドをあわせる

---

src/components/Dialog/DictionaryManageDialog.vue
src/components/Menu/ContextMenu/Container.vue
src/components/Menu/ContextMenu/Presentation.vue
src/components/Sing/PlayheadPositionDisplay.vue
src/components/Sing/ScoreSequencer.vue
src/components/Sing/SequencerNote.vue
src/components/Sing/SideBar/TrackItem.vue
src/components/Talk/AccentPhrase.vue
src/components/Talk/AudioCell.vue
src/composables/useRightClickContextMenu.ts

タイトル通りです。
- ref: #2303 
（なし）
（なし）

ContextMenuをContainer/Presentationに分離する

---

tools/mergeLicenses.mts

- https://github.com/VOICEVOX/voicevox/pull/2361
でgenerateLicense側のyargs/yargsは変わっていた一方、こっちは変わってなくてエラーになってたので修正します。
ref #2361
なんでlintが通ったのか若干不明

Fix: yargsのインポートを修正

---

src/components/Sing/SequencerLyricInput.vue

同じ歌詞が連続した場合に、Tabキーによる歌詞ハイライトが動作しない問題を修正。
https://github.com/VOICEVOX/voicevox/issues/2345#issuecomment-2462328501
上記参照。手持ちの環境（0.21.1）でも、同じ歌詞が連続した場合に歌詞ハイライトが効かなくなる現象が再現できた。
よって上記を不具合原因として修正を行った。
watchの監視対象をノートの歌詞文字列ではなく、ノートIdに変更した。
これにより、同じ歌詞が連続した場合でも、Tabキーによる歌詞ハイライトが動作するように修正した。
ref #2345
修正内容を投入したVOICEVOXの動作動画。
不具合が解消されている。
https://github.com/user-attachments/assets/84824a13-1960-494b-8a6d-693b5ee57dbd
https://github.com/VOICEVOX/voicevox/pull/2218
既に@sigprogrammingさんが指摘されているように、元々watchの監視対象はeditingLyricNote（参照）でしたが、上記PRにおいて、歌詞の内容を監視対象とするように変更されています。
上記PRを若干漁ってみたのですが、該当箇所に関する議論は見当たりませんでした（私の見落としでしたら申し訳ないです）。
もしもこの変更が、何らかの明確な意図を持って行われたものであれば、教えていただけると幸いです。私が確認した限り、今回の修正によるデグレは起きないという考えです。

Fix:同じ歌詞が連続した場合に、Tabキーによる歌詞ハイライトが動作しない問題を修正（#2345）

---

.github/workflows/test.yml

Fix: update snapshotsのコミットが落ちるのを直す

---

src/components/Dialog/AcceptDialog/AcceptTermsDialog.vue

初回起動時の利用規約への同意ボタンの挙動が逆になっているのを直します。
- https://github.com/VOICEVOX/voicevox/issues/2391
close #2391

fix:  初回起動時の利用規約への同意ボタンの挙動が逆になっているのを直す

---

src/store/audio.ts

nodeのpathをimportしていたところが残っていたのを直します。
（なし）
（なし）
（なし）

Fix: nodeのpathをimportしていたところが残っていたのを直す

---

src/components/Sing/SequencerToolPalette.vue
src/styles/fonts.scss

ソングの編集ツールのアイコンが読み込まれていないときに表示が崩れるのを修正します。
フォントが読み込まれてない間、元の文字列が表示されていました。
これを表示されないように（block）し、空欄になってもなお横幅は取られてしまうっぽいのでmax-widthをフォントサイズと同じサイズにしました。
後々コンポーネント化してもいいかも。
- https://github.com/VOICEVOX/voicevox_project/discussions/57

fix: ソングの編集ツールのアイコンが読み込まれていないときに表示が崩れるのを修正する

---

src/components/App.vue

ツールチップのアニメーションの時間を微調整します。
ツールチップの現れ始めがデフォルト700ミリ秒なのを、500ミリ秒まで縮めました。
ちなみに遷移時間の100msのままです。
VS Codeのツールチップの表示と遷移と同じくらいになってるはず･･･？
（右上のこの辺にカーソルを当てるとツールチップが出てきました）
- https://github.com/VOICEVOX/voicevox_project/discussions/57

fix: ツールチップのアニメーションの時間を微調整

---

.eslintrc.js
src/components/Dialog/ImportSongProjectDialog.vue

10個以上のトラックをインポートするときにインポート時にトラック順が壊れていたのを修正します。
また、引数なしsortをESLintで禁止します。
（なし）
（なし）
（なし）

[release-0.22] Fix: インポート時のトラック順を修正 

---

src/store/audio.ts
src/store/engine.ts
src/store/singing.ts
src/store/type.ts

ソングで、Speakerの初期化時にUIをロックしないようにします。
トークではロックするようにします。（今までと同じ挙動）
close #2359

ソング：Speakerの初期化時にUIをロックしないようにする

---

src/backend/browser/sandbox.ts
src/backend/electron/main.ts
src/backend/electron/preload.ts
src/components/Dialog/HotkeySettingDialog.vue
src/type/ipc.ts
src/type/preload.ts

ファクタリングプルリクエストです。
ショートカットキーのデフォルトの設定を返す関数があるのですが、普通にただの定数なのでそのままエクスポートして使えばいいことに気づきました。
- https://github.com/VOICEVOX/voicevox/pull/2348
のプルリクエストを見ていて気づきました。
- https://github.com/VOICEVOX/voicevox/pull/2348
リンクしているプルリクエストがマージされた後にdraftを外そうと思います。

Refactor: いらないhotkeyデフォルト設定取得関数を失くす

---

tests/e2e/electron/example.spec.ts

- https://github.com/VOICEVOX/voicevox/actions/runs/12339042097/job/34654643682 で ubuntu-latest が Ubuntu 24.04 になり、テストが通らなくなったため、electron 起動時の引数に `--no-sandbox` を追加するように
ref: #2071 #2141

fix(test): Linux の e2e テストで、electron を --no-sandbox で動くように

---

src/components/Dialog/DictionaryManageDialog.vue
tests/e2e/browser/辞書ダイアログ.spec.ts

「破棄しますか？」に対して「キャンセル」「破棄する」となっていてややこしかったので修正します。
（もともとそうだったのを微調整の時に変えてしまっていました 🙇 ）
あとキャンセルボタン左の法則がVOICEVOXにあって辞書ダイアログがそれに従ってなかったので、そこもついでに変更しておきます。
- https://github.com/VOICEVOX/voicevox_project/discussions/57
↓で @jdkfx さんにご指摘いただけたのがきっかけで気づけました 🙏 
- https://github.com/VOICEVOX/voicevox/pull/2290

[release-0.22] fix: 「キャンセル」と「破棄する」がややこしそうだったので修正

---

src/backend/browser/sandbox.ts
src/backend/common/ConfigManager.ts
src/components/Dialog/HotkeyRecordingDialog.vue
src/components/Dialog/HotkeySettingDialog.vue
src/components/Menu/MenuItem.vue
src/components/Talk/TalkEditor.vue
src/domain/hotkeyAction.ts
src/plugins/hotkeyPlugin.ts
src/store/setting.ts
src/store/type.ts
src/type/ipc.ts
src/type/preload.ts
tests/unit/lib/hotkeyManager.spec.ts

タイトルの通り、ショートカットキー周りのコードをpreload.tsからdomainに移します。
preload.tsダイエットの一貫。
isMacがpreload.ts側に定義されていて相互参照になってしまいそうです。
これは
- https://github.com/VOICEVOX/voicevox/pull/2365
に含まれる、isMacなどをhelperに移すリファクタリングで解決するはず。
- https://github.com/VOICEVOX/voicevox/pull/2357
でisMacをDI可能にしようとしたとき、結構複雑だったのでとりあえず切り出しだけやってしまおうと思いました。

Refactoring: ホットキー周りの初期値などをdomainに切り出す

---

src/components/Talk/AudioInfo.vue
src/store/utility.ts
src/type/preload.ts

- https://github.com/VOICEVOX/voicevox/pull/2418
でトークのパラメーターのデフォルト値が共有されます。
データ構造がプリセットとデフォルト値で揃っておらず、データ構造を揃えるコードが重複してしまうので、ちゃちゃっとデータ構造を揃えてみました。
ref: #2418

refactor: プリセットパラメーターのデフォルト値などを持つデータ構造のキーをプリセットのキーにあわせる

---

public/qAndA.md

0.22からmacOS 12がサポートされなくなりました。
まあ････バージョン0.22.2からこの記載が入る感じで！！
- https://github.com/VOICEVOX/voicevox_project/discussions/57

doc: [release-0.22] macOSのサポートバージョンを上げ忘れていたので上げる

---

src/store/singing.ts

#2261 でレンダリングの流れを変更しますが、変更する前に一度リファクタリングを行っておいた方が良さそうなので、リファクタリングを行います。
以下を行います。（分けてコミットしています）
- `PhraseRenderContext`と`PhraseRenderer`を一旦無くす
- レンダリングの流れを変更しやすいように
- 以下の処理を分ける
- 新しく作られたフレーズと`state`にある既存のフレーズをマージ
- レンダリング開始ステージの決定
- `phrase.state`の更新
- 以下の処理を分ける
- 重なっているノートを削除する処理
- フレーズの生成
- `searchPhrases`から`generatePhrases`に変更
- スナップショットを作成する処理を関数化
- コメントを整理

ソング：レンダリング処理をリファクタリング

---

src/backend/electron/main.ts
src/plugins/ipcMessageReceiverPlugin.ts
src/store/project.ts
src/store/type.ts
src/type/ipc.ts

`LOAD_PROJECT_FILE`のconfirmがずっと使われてないので消しました。
無指定の時とtrueのときの動作が同じで、falseのときのみ確認ダイアログを必ず出さないようなロジックになってます。
でもfalseを与えているところが1つもないので、消してしまって大丈夫そうでした。
必要になったら足すのが良さそう（YAGNI原則）
- https://github.com/VOICEVOX/voicevox/issues/2431
の解決を行っている時に気づきました

refactor: LOAD_PROJECT_FILEのconfirmがずっと使われてないので消す

---

tests/e2e/browser/ツールバーカスタマイズダイアログ.spec.ts

- https://github.com/VOICEVOX/voicevox/actions/runs/12518033773/job/34919807377
にて落ちていたmacOSのテストを改善します。
メニューが閉じきる前にダイアログが表示されると、「ツールバーのカスタマイズ」というテキストが2箇所に現れてテストが落ちるっぽいです。
タイミングによっては落ちないので厄介。

test: ツールバーのカスタマイズダイアログの可視性チェックを改善

---

src/backend/browser/browserConfig.ts
src/backend/common/ConfigManager.ts
src/backend/electron/electronConfig.ts
src/components/Dialog/HotkeySettingDialog.vue
src/domain/hotkeyAction.ts
src/type/preload.ts
tests/unit/backend/common/configManager.spec.ts

ホットキー設定のデフォルト値やConfigManagerをisMac指定可能にしてテスタブルにします。
変更行数はやたら多いけど、ほとんどが空白追加です。
こういう設計を最初に実装するときから思いつけるようになりたい。

refactor: ホットキー設定のデフォルト値やConfigManagerをisMac指定可能に

---

.env.test-electron-default-vvpp
src/backend/electron/engineAndVvppController.ts
src/domain/defaultEngine/envEngineInfo.ts
tests/e2e/electron/example.spec.ts
vite.config.mts

VVPPデフォルトエンジンを使うテストを書きます。
途中でelectronのダイアログが来ますが、ダイアログ表示関数を直接上書きすることで無理やり突破します。
将来的にはelectronのダイアログではなくブラウザ表示になる予定なのでこのワークアラウンド不要になる予定です。
変更行数は少ないですが、結構複雑度が上がってしまっています。解決策募集中。。
* VVPPデフォルトエンジン用の.envが増えた
* VVPPデフォルトエンジンに統一されたらまた減るはず
* デフォルトエンジン情報はimport.meta.env経路以外にprocess.envルートもできた
* テストしたい環境が２つになったため
* これもVVPPデフォルトエンジンに統一されたらもとに戻るはず
* electronダイアログを無理やり通るためのモックが増えた
* これはそもそもGUIが整備されたらダイアログ自体がなくなるはず
- https://github.com/VOICEVOX/voicevox/issues/1194
おそらく動くのですが、VOICEVOXエンジンをダウンロードする部分が重くてタイムアウトになると思います。
Nemo用のlatestDefaultEngineInfosを作ろうと思います。

test: VVPPデフォルトエンジンを使うテストを書く

---

src/backend/electron/manager/engineProcessManager.ts
src/backend/electron/portHelper.ts

- プロセスIDからプロセスを特定するのを wmic から tasklist に変更
- wmic が 24H2 から非推奨になったため、tasklist に修正
close #2449

fix: プロセスIDからプロセスを特定するのを wmic から tasklist に変更

---

src/backend/electron/fileHelper.ts

`writeFileSafely`の一時ファイルが既存のファイルを上書きしないようにします。
また、ファイル移動に失敗した場合一時ファイルを削除するようにします。
- ref: https://github.com/VOICEVOX/voicevox/pull/2437#issuecomment-2562914679
一時ファイル名のランダム文字列部には`Math.rand()`を使っています。
これでも十分なはず？
とりあえず一時ファイルの作成試行回数は16回にしてあります。
あまり回数を増やし過ぎるとメインスレッドを長時間ブロックしてしまいます。

FIX: `writeFileSafely`の一時ファイルが既存のファイルを上書きしないようにする

---

src/backend/browser/browserConfig.ts
src/backend/common/ConfigManager.ts
src/backend/electron/electronConfig.ts
src/components/Dialog/HotkeySettingDialog.vue
src/domain/hotkeyAction.ts
src/type/preload.ts
tests/unit/backend/common/configManager.spec.ts
tests/unit/domain/hotkeyAction.spec.ts

ショートカットキー周りのisMacを`{isMac: boolean}`にします。
- https://github.com/VOICEVOX/voicevox/pull/2446
ちなみにDiscordで話題に上がりました。この辺り。
https://discordapp.com/channels/879570910208733277/893889888208977960/1322696371672842331

refactor: ショートカットキー周りのisMacを{isMac: boolean}にする

---

src/backend/electron/engineAndVvppController.ts
src/backend/electron/main.ts
src/backend/electron/manager/vvppManager.ts
src/backend/electron/type.ts
tests/e2e/electron/example.spec.ts

VVPPデフォルトエンジンのインストール状況などの進捗を出せるようにします。
将来的にはGUIで表示予定ですが、今はまだログに出すだけです。
ついでにDLしたものがオンメモリになってたのをstreamでファイル出力にします。
- https://github.com/VOICEVOX/voicevox/issues/1194#issuecomment-2296599278
の第六段。
進捗表示が必要な関数にonProgressが生えまくるけど、仕方ない･･･のかな。

feat: VVPPデフォルトエンジンの進捗を出せるようにし、オンメモリじゃなくする

---

.github/workflows/merge_gatekeeper.yml

デフォルトは10分で終了なので、timeoutを足して5時間動くようにします。
流石に長過ぎる気がしないでもないけど、まあ良いかなと。。

ci: merge-gatekeeyperのtimeoutを伸ばす

---

src/backend/electron/engineAndVvppController.ts
src/backend/electron/main.ts
src/backend/electron/manager/windowManager.ts
tests/e2e/electron/example.spec.ts

https://github.com/VOICEVOX/voicevox/pull/2339#issuecomment-2457798344 で提案されたwin周りの処理をWIndowManagerに切り出すリファクタリングです。
- ref: #2173

refactor: WindowManagerを追加

---

tests/e2e/electron/example.spec.ts

#2421 をproject-sequencer-statemachineブランチに取り込んでubuntuでのテストが落ちないようにします。
-

fix(test): [project-sequencer-statemachine] Linux の e2e テストで、electron を --no-sandbox で動くように

---

src/sing/stateMachine/sequencerStateMachine.ts
src/sing/utility.ts

以下を行います。
- `ResizeNoteLeftState`を追加
- リファクタリング

[project-sequencer-statemachine] ResizeNoteLeftStateを追加

---

src/backend/electron/engineAndVvppController.ts

VVPPデフォルトエンジンダウンロード後、確実にファイルが閉じられるまで待ちます。
close()を呼んで制御が返ってきても、OSがファイルを閉じているとは限らない･･･っぽい？
ので待機するようにしてみます。
fix #2459

fix: VVPPデフォルトエンジンダウンロード後、確実にファイルが閉じられるまで待つ

---

src/domain/defaultEngine/envEngineInfo.ts

electronでプロセスの環境変数がない場合に落ちないようにします。
（production環境などでは`process.env.VITE_DEFAULT_ENGINE_INFOS`が存在しないので）
- https://github.com/VOICEVOX/voicevox/pull/2444#discussion_r1899887386

fix: electronでプロセスの環境変数がない場合に落ちないように

---

src/mock/engineMock/talkModelMock.ts

エンジンモック内での読点の扱いがちょっと間違っていたので修正しました。
助詞の後にも「、」が入るようになりました。
- https://github.com/VOICEVOX/voicevox/pull/2442
から切り出しました。

fix: エンジンモック内での読点の扱いがちょっと間違っていたので修正

---

tests/e2e/browser/辞書ダイアログ.spec.ts

辞書ダイアログの読み方取得ロジックが若干不安定っぽく、たしかmacOSで不安定だったのでリファクタリングしました。
`waitForTimeout`をやめてtoBeVisibleとかを使っています。
- https://github.com/VOICEVOX/voicevox/pull/2442
の切り出しです。

refactor(test): 辞書ダイアログの読み方取得ロジックを改善

---

.github/workflows/test.yml

Merge Queueとpushで2回走っていたのをMerge Queueだけにします。
（なし）
（なし）
（なし）

Change: Merge QueueのCIを1回だけ走らせるようにする

---

src/backend/browser/sandbox.ts
src/backend/electron/preload.ts
src/components/App.vue
src/components/Menu/MenuBar/MenuBar.vue
src/components/Talk/TalkEditor.vue
src/components/Talk/ToolBar.vue
src/components/Talk/menuBarData.ts
src/plugins/ipcMessageReceiverPlugin.ts
src/store/audio.ts
src/store/project.ts
src/store/type.ts
src/type/ipc.ts
src/type/preload.ts

- https://github.com/VOICEVOX/voicevox/issues/2431
の解決プルリクエストです。
一応[このプルリクエスト](https://github.com/VOICEVOX/voicevox/pull/2432)が先に必要です。
経緯は[issue側のコメント](https://github.com/VOICEVOX/voicevox/issues/2431#issuecomment-2558514836)に書いています。
解決方法として、ブラウザ側に持ってこられたFileはelectronの関数を使ってパスを取得できるぽかったので、その経路を用意しました。
ブラウザの時はこの関数が使えないので、代わりにそのままFileオブジェクトを渡せるようにしました。
close #2431
ついでにブラウザでのドラッグ&ドロップも動くようになったはず。便利。

fix: ドラッグアンドドロップでプロジェクトファイルやテキストファイルが読み込めなかったのを直す

---

src/sing/stateMachine/sequencerStateMachine.ts

以下を行います。
- ResizeNoteRightStateを追加

[project-sequencer-statemachine] ResizeNoteRightStateを追加

---

src/backend/electron/manager/vvppManager.ts

vvppManagerのextractVvppの処理を関数切り出しします。
- https://github.com/VOICEVOX/voicevox/issues/1194#issuecomment-2296599278
のタスクの
> デフォルトエンジンと同じIDを持つvvppをインストールできないようにする
をする前準備です。
ちょっと関数切り出ししないとこのメソッドがどういう経路で何をやっているか分かりにくかったので、出してみました。
- #1194 
大半がコードの移動です。リファクタリングとかも意識してやってないです。
```bash
git diff -w --color-moved=dimmed-zebra --color-moved-ws=ignore-all-space df4ad342c0f62eadeae1819eaf55c249307626aa
```
すると差分が分かりやすいはず！

refactor: vvppManager.extractVvppの処理を関数切り出し

---

src/store/audio.ts

AudioCellが0個のときにDEFAULT_PROJECT_FILE_BASE_NAMEでエラーが発生しないようにします。
close #2483

hotfix: [release-0.22] AudioCellが0個のときにDEFAULT_PROJECT_FILE_BASE_NAMEでエラーが発生しないように修正

---

src/sing/stateMachine/sequencerStateMachine.ts

ErasePitchStateの追加とIdleStateの変更を行います。

add: [project-sequencer-statemachine] ErasePitchStateを追加

---

src/domain/frontend/log.ts

タイトルの通り、createLoggerを少しリファクタリングしました。
本当はelectron環境問わずloggerを作れる関数を作りたかったんですが、フロントエンドで`electron-log`をimportしようとするとエラーになる問題が解決できずに諦めました。。。
なにか解決策ないのかな。。

refactor: createLoggerを少しリファクタリング

---

build/installer_linux.sh

以前から更新が止まっているp7zipから公式で提供される7zipに移行する動きがいくつかのLinuxディストリにあって、  
Archは7zipに置き換え済み、Ubuntuは24.04、Debianは13でそれぞれp7zipを仮想パッケージにしていて実態が7zipになっている。  
7zzを対象に含めているのは7zip公式のをダウンロードして使う人や、Gentooでapp-arch/7zip、HomeBrewでsevenzipをインストールした人向け。

Arch Linuxがp7zipを7zipに置き換えたのでメッセージを変更。それと7zzを許容するように。

---

src/backend/browser/fakePath.ts
tests/unit/backend/browser/fakePath.spec.ts

ブラウザ版でファイル保存しようとすると、FakePathのparseが正しくなくてエラーになって保存できなかったので修正しました。
テストで使おうと思って動かなかったことに気づいたので修正しました。
特に製品版ソフトウェアのVOICEVOXには問題ないエラーでした。

fix: ブラウザ版でファイル保存できない問題を解決

---

tests/unit/backend/electron/vvppFile.node.spec.ts
tests/unit/backend/electron/vvpps/README.md
tests/unit/backend/electron/vvpps/invalid_manifest.vvpp/engine_manifest.json
tests/unit/backend/electron/vvpps/no_engine_id.vvpp/engine_manifest.json
tests/unit/backend/electron/vvpps/perfect.vvpp/engine_manifest.json

extractVvppのテストを書きました。
正常系のテストと異常系のテストをとりあえず書いています。

test: extractVvppのテストを書く

---

src/sing/stateMachine/sequencerStateMachine.ts

[project-sequencer-statemachine] StoreをDIするように変更

---

src/backend/electron/helper.ts
src/backend/electron/manager/vvppManager.ts
src/backend/electron/vvppFile.ts
tests/unit/backend/electron/vvppFile.node.spec.ts

- https://github.com/VOICEVOX/voicevox/pull/2490
で後回しにしたTODO系を片付けました。

refactor: extractVvpp周りのTODOを解決

---

src/sing/stateMachine/sequencerStateMachine.ts
src/sing/stateMachine/stateMachineBase.ts

ステートのインスタンスの作成をファクトリ関数で行うようにします。
（ステートの中で他のステートのインスタンスの作成を行わないようにします）

[project-sequencer-statemachine] ステートのインスタンスの作成をファクトリ関数で行うようにする

---

src/backend/electron/fileHelper.ts
tests/unit/backend/electron/fileHelper.node.spec.ts

writeFileSafely関数をmove-file非依存にし、テストを追加しました。
- https://github.com/VOICEVOX/voicevox/issues/2501
を解決します。
詳細は[こちら](https://github.com/VOICEVOX/voicevox/issues/2501#issuecomment-2610261884)
fix: #2501

fix!: writeFileSafely関数をmove-file非依存にし、テストを追加

---

src/backend/electron/engineAndVvppController.ts

こうなってしまっていました。
```log
src/backend/electron/engineAndVvppController.ts:238:34 - error TS2345: Argument of type '(value: unknown) => void' is not assignable to parameter of type '() => void'.
Target signature provides too few arguments. Expected 1 or more, but got 0.
238           fileStream.on("close", resolve);
```
これでビルド時にエラーが出ないと思います。

fix: engineAndVvppController.tsの型エラーを直す

---

vite.config.mts

- https://github.com/VOICEVOX/voicevox/issues/2515
の解決PRです。
開発時にelectron:serve等で実行するたびになかなか重たいので、vite-plugin-checkerでeslintを走らせないようにします。
型チェックは有用（発見が遅れると手戻りがすごいことがある・気付けないことも多い）なのと、そんなに重くないので残します。
CPU計測結果は[こちら](https://github.com/VOICEVOX/voicevox/issues/2515)。
fix: #2515 
Discordでのコメント
https://discordapp.com/channels/879570910208733277/893889888208977960/1334812766946459721

chore: 開発実行・ビルド時にvite-plugin-checkerでlintを実行しないようにする

---

src/sing/sequencerStateMachine/states/addNoteState.ts
src/sing/sequencerStateMachine/states/drawPitchState.ts
src/sing/sequencerStateMachine/states/erasePitchState.ts
src/sing/sequencerStateMachine/states/moveNoteState.ts
src/sing/sequencerStateMachine/states/resizeNoteLeftState.ts
src/sing/sequencerStateMachine/states/resizeNoteRightState.ts
src/sing/sequencerStateMachine/states/selectNotesWithRectState.ts

#2518 でtransitionToメソッドを追加したので、（processのsetNextStateではなく）transitionToでonExitが呼ばれることも考慮する必要があります。
これを考慮して、transitionToでonExitが呼ばれた場合（processが一度も呼ばれずにonExitが呼ばれた場合も含む）でもステートが正しく動作するようにします。
（mouseupの前にonExitが呼ばれた場合はプレビューの適用を行わないようにします）
また、以下も行います。
- onEnterでもguideLineTicksの更新を行うようにする
- SelectNotesWithRectStateでcontext.nowPreviewingの更新を行うようにする

[project-sequencer-statemachine] transitionToでonExitが呼ばれた場合でもステートが正しく動作するようにする

---

package.json

pnpmを10.3に更新します。
（なし）
（なし）
（なし）

chore: pnpmをv10に更新

---

src/sing/sequencerStateMachine/states/editNotesToolIdleState.ts

editNotesToolIdleStateのupdateCursorStateを修正します。

fix: [project-sequencer-statemachine] editNotesToolIdleStateのupdateCursorStateを修正

---

src/sing/sequencerStateMachine/common.ts
src/sing/sequencerStateMachine/states/editNotesToolIdleState.ts
src/sing/sequencerStateMachine/states/selectNotesToolIdleState.ts

`executeNotesSelectionProcess`を、`selectNotesInRange`、`toggleNoteSelection`、`selectOnlyThisNoteAndPlayPreviewSound`に分割します。

refactor: [project-sequencer-statemachine] executeNotesSelectionProcessを分割

---

src/sing/sequencerStateMachine/common.ts
src/sing/sequencerStateMachine/states/addNoteState.ts
src/sing/sequencerStateMachine/states/drawPitchState.ts
src/sing/sequencerStateMachine/states/editNotesToolIdleState.ts
src/sing/sequencerStateMachine/states/erasePitchState.ts
src/sing/sequencerStateMachine/states/moveNoteState.ts
src/sing/sequencerStateMachine/states/resizeNoteLeftState.ts
src/sing/sequencerStateMachine/states/resizeNoteRightState.ts
src/sing/sequencerStateMachine/states/selectNotesToolIdleState.ts
src/sing/sequencerStateMachine/states/selectNotesWithRectState.ts

https://github.com/VOICEVOX/voicevox/blob/074bcec52dcb5a16e4c2acee702fc1bc7d9c061c/src/components/Sing/ScoreSequencer.vue#L1777-L1782
に合わせてtargetAreaを修正します。

fix: [project-sequencer-statemachine] targetAreaを修正

---

README.md
src/backend/browser/sandbox.ts
src/backend/electron/main.ts
src/backend/electron/manager/windowManager.ts
src/backend/electron/preload.ts
src/components/App.vue
src/store/project.ts
src/store/type.ts
src/type/ipc.ts
src/type/preload.ts
vite.config.mts

`backend.getInitialProjectFilePath()`を追加します。
- ref: https://github.com/VOICEVOX/voicevox/pull/2521#discussion_r1947500780
（なし）
これのために`electron:serve`に引数を渡せるような改修をしました。

chore: 初回ファイルの取得をbackendの関数として表現するようにする

---

src/sing/sequencerStateMachine/states/addNoteState.ts
src/sing/sequencerStateMachine/states/selectNotesToolIdleState.ts

ノート編集の選択優先ツールでダブルクリックしたときはノート追加になりますが、このノート追加では「ドラッグでノートの長さを決める」というのは行わずに、すぐにノートの追加を適用させる必要があります。
https://github.com/VOICEVOX/voicevox/blob/074bcec52dcb5a16e4c2acee702fc1bc7d9c061c/src/components/Sing/ScoreSequencer.vue#L1442-L1448
なので、ダブルクリック時はaddNoteStateに遷移せずに、直接ノート追加の処理を行うようにします。

feat: [project-sequencer-statemachine] ダブルクリック時はaddNoteStateに遷移せずに直接ノート追加の処理を行うようにする

---

docs/res/エンジン再起動シーケンス図.md
src/components/App.vue
src/store/engine.ts
src/store/type.ts

タイトルのとおりです。
対象の関数は３つだけでした。
close #1020
こういう改善をどんどんやっていきたい。

chore: backendから情報を同期している関数の名前をGETからPULLに変更

---

src/backend/browser/sandbox.ts
src/backend/electron/main.ts
src/backend/electron/preload.ts
src/components/Dialog/EngineManageDialog.vue
src/store/audio.ts
src/store/project.ts
src/type/ipc.ts
src/type/preload.ts

ファイル読み込み系統の関数を統一し、重複を減らします。
引数はこうしてみました。
```ts
title: string;
name: string;
mimeType: string;
extensions: string[];
defaultPath?: string;
```
mimeTypeはelectronバックエンドで使えず、defaultPathはブラウザバックエンドで使えません。
まあ共通化しちゃっていいかなぁと。
close #2522
同様にファイル書き出し系のダイアログも統一できると思います。
といっても現状はSHOW_PROJECT_SAVE_DIALOGとSHOW_EXPORT_FILE_DIALOGだけかも。
やっぱりDRY原則は正しい気がします。

refactor: backendにあったファイル読み込み系統の関数を統一

---

src/components/Dialog/UpdateNotificationDialog/Container.vue

タイトルのとおりです。
`newUpdateResult.value.status`だけが書き換わることがあり、deepにwatchしてなかった関係でアプデダイアログが開かなかったのが原因だと思われます。
大体の場合でうまく行ってたのはたぶん、タイミングによってはあとで`canOpenDialog`などが書き換わって偶然開かることもあった･･･んだと思います。

fix(test): アップデート確認ダイアログのテストが落ちることがあるのを直す

---

src/backend/browser/sandbox.ts
src/backend/electron/main.ts
src/backend/electron/preload.ts
src/components/Dialog/HelpDialog/HelpDialog.vue
src/components/Dialog/UpdateNotificationDialog/Container.vue
src/components/Menu/MenuBar/MenuBar.vue
src/composables/useFetchNewUpdateInfos.ts
src/domain/appInfo.ts
src/store/project.ts
src/type/ipc.ts
src/type/preload.ts

たぶんwindow.backendからこの関数を省いても問題ないと思うので省き、ついでにipc通信からも省きます。
おそらく、最初期の実装だとelectron側から持ってこないといけなかった･･･？
今は直でVITEから得れば良い気がします。
- https://github.com/VOICEVOX/voicevox/pull/2521#discussion_r1957344395
のレビュー時に思い当たりました。

refactor: getAppVersion()をなくす

---

src/components/Sing/ScoreSequencer.vue
src/composables/useSequencerStateMachine.ts
src/sing/sequencerStateMachine/common.ts
src/sing/stateMachine.ts

`ScoreSequencer.vue`のプレビュー処理のところをステートマシンに置き換えます。
コメントの整理も行います。

feat: [project-sequencer-statemachine] ステートマシンに置き換える

---

src/mock/engineMock/characterResourceMock.ts

eagerにしたほうがわかりやすそうだったので変更しました。
ついでに`{default: string}`も要らないことに気づいたので省きました。

chore: mockのアセット取得をeagerにする

---

src/backend/browser/fileImpl.ts
src/backend/browser/sandbox.ts
src/backend/electron/main.ts
src/backend/electron/preload.ts
src/store/audio.ts
src/store/project.ts
src/store/singing.ts
src/type/ipc.ts
src/type/preload.ts

タイトルのとおりです。
ほとんど同じ処理をしていた関数２つを統合します。
close #2543

refactor: SHOW_EXPORT_FILE_DIALOGとSHOW_PROJECT_SAVE_DIALOGを統合

---

src/backend/electron/manager/vvppManager.ts

VvppManagerをリファクタリングしてみました。
markしてhandleする機構上、これ以上は割と難しそうかも。
ついでにバグを２つ直してます。
* パーミッションを変更してから移動するようにした
* 以前は移動してからパーミッション変更してた
* markで移動を予約した後はパーミッションを変更してないので、おそらくバグってた
* 移動の際に削除するエンジンディレクトリを、`to`ディレクトリではなく毎回取得するようにした
* 前はtoディレクトリのものを消していた
* エンジンIDそのままに名が変わったときなどはディレクトリが変わるので、toディレクトリを消すだけではダメなときもある
いずれも関数化して処理を整理していくと割と問題が見えてきたので、関数に切り分けていくのは大事だなと改めて思いました。
- https://github.com/VOICEVOX/voicevox/pull/2547
の続き

refactor: VvppManagerをリファクタリング

---

src/helpers/onetimeWatch.ts

タイトルのとおりです。
まあ引数名の順序が逆なだけなので動作に影響はないのですが、間違って使ってしまうと危ない気がしたので正しい順序にします。
現状使ってるのはこの２箇所だけで、どちらも動作に問題ないはず。
https://github.com/VOICEVOX/voicevox/blob/94995bf76da3bd06169f4de128803b00ee83b5ab/src/components/Sing/SingEditor.vue#L71-L74
https://github.com/VOICEVOX/voicevox/blob/94995bf76da3bd06169f4de128803b00ee83b5ab/src/components/Talk/TalkEditor.vue#L517-L519

chore: onetimeWatchのコールバックの引数の名前順序が逆

---

src/backend/electron/ipcMainHandle.ts
src/backend/electron/main.ts

https://github.com/VOICEVOX/voicevox/pull/2455#issuecomment-2567651395 で提案されたリファクタリングです。
特に大きな問題なく切り離せたと思います。

refactor: `getIpcMainHandle` を追加

---

src/backend/browser/fileImpl.ts
src/backend/browser/sandbox.ts
src/backend/electron/manager/windowManager.ts
src/store/audio.ts
src/store/audioContinuousPlayer.ts

@MT224244 さんが
- https://github.com/VOICEVOX/voicevox/pull/2560
でeslintをflat configにしてくださっています。
このPRをマージするといくつかエラーが出るので、それだけ解決しました。
一旦mainブランチに向けてPR出してますが、mainブランチでエラーになりそうだったら #2560 に向けてPR出そうと思います。
ref #2560

chore: FlatConfigにしたら出るエラーをいくつか解消

---

src/backend/electron/main.ts

[`window-all-closed`](https://www.electronjs.org/ja/docs/latest/api/app#%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88-window-all-closed)が必要なさそうなので削除します。
https://github.com/VOICEVOX/voicevox/pull/2563#issuecomment-2686319614

fix: 不要な`window-all-closed`イベントリスナーを削除する

---

src/helpers/errorHelper.ts
tests/unit/lib/errorHelper.spec.ts

errorToMessageを改造し、
DisplayableError以外のエラーは`（内部エラーメッセージ）`として、
DisplayableErrorのエラーはユーザー向けのメッセージとして文字列化するようにします。
ついでにAggregateErrorやcauseなどもメッセージ化できるようにします。
- https://github.com/VOICEVOX/voicevox/pull/2556
の改造版で、DisplayableErrorも追加します。
ref #2556
都合が良かったので`errorToMessages`も作りました。
IPC通信を通すときはこっちを使い、`displayable`なものと`internal`なものを分離してシリアライズ化して通信し、`new DisplayableError(displayable, { cause: new Error(internal) })`とする予定です。
ちなみに`DisplayableError`以外の名前を検討したけど良いのが見つかりませんでした。
AIくんは`UserError`推しだけど、これだとユーザー入力のエラーに見える。。
https://chatgpt.com/share/67bc5a21-71d0-8008-9711-c532c1d300b3
https://x.com/i/grok/share/bNQSK5cxxKMj7M2OvYcZbSZUn

chore: DisplayableErrorを追加し、テストも追加する

---

src/components/Sing/SequencerPitch.vue

`PitchLine`の初期化を`onMountedOrActivated`で行っていなかったので修正します。
（ピッチを表示した状態でソング→トーク→ソングと切り替えるとエラーになるのを修正します）
また、以下も行います。
- トーク/ソングの切り替えでPIXI（WebGL）のオブジェクトを破棄しないように（維持するように）する
- `onMountedOrActivated`から`onMounted`に変更
- 問題なく動くのと、パフォーマンスにも影響しないと思うので

fix: PitchLineの初期化をonMountedOrActivatedで行っていなかったので修正

---

.github/workflows/build.yml
public/updateInfos.json

arm64のエンジンをダウンロードしようとしていたのでx64のを使うようにしてみました。
- https://github.com/VOICEVOX/voicevox/issues/2575
を解決します。
close #2575
- https://github.com/VOICEVOX/voicevox_project/discussions/60
arm64版のlinuxエディタを作るとか、x64用の名前に今のうちに変更するかとかも考えたのですが、どっちも一旦なしにしました。
もしarm64版linuxエディタ作るなら命名はmacOSのに倣って、x64のはx64に、arm64のはarm64と書くのが良さそう。

fix(build): ビルド時にlinux x64のエンジンを使うように

---

tests/e2e/browser/song/ソング.spec.ts
tests/e2e/browser/song/歌詞.spec.ts
tests/e2e/navigators.ts

playwrightテストの共通部分をtest.stepにし、テスト結果を少しわかりやすくします。
- https://github.com/VOICEVOX/voicevox/pull/2561
から派生
stepにしておくとこんな感じでまとめてくれる（右の「ソング画面に移動」みたいに）ので、どのタイミングで落ちたのかわかりやすくなるから多用していきたい気持ち。

refactor(test): playwrightテストの共通部分を少しリファクタリング、歌詞編集テストの移動

---

src/sing/sequencerStateMachine/states/addNoteState.ts
src/sing/sequencerStateMachine/states/drawPitchState.ts
src/sing/sequencerStateMachine/states/erasePitchState.ts
src/sing/sequencerStateMachine/states/moveNoteState.ts
src/sing/sequencerStateMachine/states/resizeNoteLeftState.ts
src/sing/sequencerStateMachine/states/resizeNoteRightState.ts
src/sing/sequencerStateMachine/states/selectNotesWithRectState.ts
src/sing/viewHelper.ts

ステートのprivateメソッドを下の方に移動します。（移動のみ）
また、使われていない型の削除もついでに行います。

refactor: ステートのprivateメソッドを下の方に移動

---

src/sing/audioRendering.ts

音声のスケジューリングでずれが発生しないようにします。
（ https://github.com/VOICEVOX/voicevox/issues/2215#issuecomment-2288796954 の2番目の方法で実装します）
- https://github.com/VOICEVOX/voicevox/issues/2215

feat: 音声のスケジューリングでずれが発生しないようにする

---

tools/downloadTypos.mts

表題の通り、typosのバージョンを管理できるようにしました。
私の手元の環境(Windows, Linux(WSL))で動作確認はしています。
実装方法としては #2585 に書いていただいている方針です。
> 今URLを入れてるところをtar.gzについてるtriplet（x86_64-pc-windows-msvc）だけにして、
バージョンを定数としてURLの外に出して、
URLをバージョンとtripletから生成するようにして、
バージョンの書いたテキストファイルをtyposの隣に置くようにして、
ダウンロード時に更新チェック
注意点としてはバージョンを書いたテキストファイル(`.typos-version`)が存在しない場合は再ダウンロードが行われるようになっています。
close #2585

chore: typosのバージョンを管理

---

src/components/Sing/SequencerLyricInput.vue

Tabキーで自動スクロールしない問題を修正。
ref #2599

fix: Tabキーで自動スクロールしない問題を修正(#2599)

---

build/installer_linux.sh

https://github.com/VOICEVOX/voicevox/issues/2577 でLinux版のCPU版がX64とARM64の両方提供されることになり、7zファイルを展開するとVOICEVOX-CPU-ARCH_NAME.AppImageが出力される。
それまでは.voicevox下に配置されるのはVOICEVOX.AppImageだったのでアップデート時に上書きできるようにインストール時にrename処理を追加しました。  
X64は、`VERSION=0.24.0-dev NAME=linux-cpu-x64-appimage bash build/installer_linux.sh`  
ARM64は、`VERSION=0.24.0-dev NAME=linux-cpu-arm64-appimage bash build/installer_linux.sh`  
で試せます。
close #2587

build: インストール時にVOICEVOX-CPU-ARCH.AppImageからVOICEVOX.AppImageにrenameするようにする

---

.github/workflows/DANGEROUS_trigger_preview_pages.yml

#2353 への対応です。
"Trigger preview-pages' workflow"がfork先のリポジトリでは失敗するため、
トリガーの条件を追加してリポジトリオーナーがVOICEVOXであるときのみ実行されるようにしました。
close #2353

chore: preview-pagesのワークフローをownerがVOICEVOXであるときのみ実行するようにする

---

src/components/Talk/AudioDetail.vue
src/store/audioPlayer.ts
src/store/type.ts

ACTIVE_AUDIO_ELEM_CURRENT_TIMEがcurrentTimeを返すコールバックを返すようにします。
設計をひっくり返すレベルのリファクタをしないといけない可能性はある...
- close: #2620 
（なし）
（なし）

fix: 再生位置のハイライトが動かなかったのを修正

---

src/store/singing.ts

フレーズが無くなったときにシーケンスのみが削除されていて、フレーズに紐づくピッチやボリュームなどのデータが残り続けていたので、それらもシーケンスと一緒に削除するように修正します。

fix: 無くなったフレーズのピッチやボリュームを削除していなかったので修正

---

src/components/Dialog/AcceptDialog/AcceptDialog.stories.ts
src/components/Dialog/AcceptDialog/AcceptDialog.vue
src/components/Dialog/AcceptDialog/AcceptRetrieveTelemetryDialog.vue
src/components/Dialog/AcceptDialog/AcceptTermsDialog.vue
src/components/Dialog/AllDialog.vue
src/components/Dialog/CharacterOrderDialog.vue
src/components/Dialog/DefaultStyleListDialog.vue
src/components/Dialog/DefaultStyleSelectDialog.vue
src/components/Dialog/DictionaryManageDialog.vue
src/components/Dialog/EngineManageDialog.vue
src/components/Dialog/ExportSongAudioDialog/Container.vue
src/components/Dialog/ExportSongAudioDialog/Presentation.vue
src/components/Dialog/HotkeyRecordingDialog.vue
src/components/Dialog/HotkeySettingDialog.vue
src/components/Dialog/PresetManageDialog.vue
src/components/Dialog/SettingDialog/FileNameTemplateDialog.stories.ts
src/components/Dialog/SettingDialog/FileNameTemplateDialog.vue
src/components/Dialog/SettingDialog/SettingDialog.vue
src/components/Dialog/ToolBarCustomDialog.vue
src/components/Dialog/UpdateNotificationDialog/Container.vue
src/components/Dialog/UpdateNotificationDialog/Presentation.vue
src/components/Dialog/UpdateNotificationDialog/index.stories.ts

基本的にはdefineModelを使うように置き換えただけです。
留意点としては `const dialogOpened = defineModel<boolean>({ default: false })` していてもStorybookではmodeValueとして扱われます。
それとアップデート通知ダイアログが閉じれないバグを見つけてついでに修正してあります。
ヘルプダイアログについてissueが立っているのとこのPRの変更量がそれなりに多いので、このPRがマージされた後にやりたいと思います。

refactor: ヘルプダイアログを除くcomputed+@update:modelValueパターンで開くダイアログをdefineModelを使うようにする

---

src/components/Sing/SequencerPitch.vue
src/composables/useAutoScrollOnEdge.ts
src/composables/useMounted.ts

mountedされたかどうかを扱うref変数を使うロジックをコンポーザブルにして共通化します。
- https://github.com/VOICEVOX/voicevox/pull/2583
- https://github.com/terapotan/voicevox/pull/2

refactor: useMountedを追加し、mountedの管理を統一

---

eslint.config.js
package.json
pnpm-lock.yaml
tests/unit/backend/electron/vvppFile.node.spec.ts
tests/unit/components/help/HelpMarkdownViewSection.spec.ts
tests/unit/lib/hotkeyManager.spec.ts

タイトルのとおりです。公式から提供されてたので追加してみました。
今のテストだと「テストはexpectが１つ以上含まれてるべき」ルールに引っかかってるのがいくつかあったので、とりあえず対処しています。
ref: https://github.com/VOICEVOX/voicevox/issues/2627
ぶっちゃけ恩恵はあまりない気がします。
nodeのtestをimportしてたときにエラーにするみたいなのも入ってて、初学者の助けになるかもしれない･･･？
https://github.com/vitest-dev/eslint-plugin-vitest/

chore: eslintにvitestプラグインを追加

---

tests/unit/backend/browser/fakePath.spec.ts
tests/unit/backend/common/configManager.spec.ts
tests/unit/backend/electron/VvppManager.node.spec.ts
tests/unit/backend/electron/fileHelper.node.spec.ts
tests/unit/backend/electron/vvppFile.node.spec.ts
tests/unit/components/help/HelpMarkdownViewSection.spec.ts
tests/unit/composable/useFetchNewUpdateInfos.spec.ts
tests/unit/composable/useModifierKey.spec.ts
tests/unit/domain/defaultEngine/latetDefaultEngine.spec.ts
tests/unit/domain/hotkeyAction.spec.ts
tests/unit/domain/japanese.spec.ts
tests/unit/domain/project.spec.ts
tests/unit/domain/sing/applyPhonemeTimingEdit.spec.ts
tests/unit/domain/sing/shouldPlayTracks.spec.ts
tests/unit/lib/cloneWithUnwrapProxy.spec.ts
tests/unit/mock/engineMock/index.spec.ts
tests/unit/store/command.spec.ts
tests/unit/store/immerPatchUtility.spec.ts
tests/unit/store/singing.spec.ts
tests/unit/store/utility.spec.ts
tsconfig.json

ESLintの実行環境における挙動の不整合を解消するため、以下の修正を行いました。  
- 各テストファイルにおいて、vitestのグローバル変数（it, expect, describe, test, vi, afterEach など）を明示的にimportするよう変更しました。  
- tsconfig.jsonから "types": ["vitest/globals"] の記述を削除し、設定の一貫性を図りました。
これでplaywright系のときは明示的import・vitestのときは省いても良いというバランスだったのが、全部明示的に変わるので一貫性は上がったはず･･･！
（あと間違いも減る･･･････気がする。）
close #2627  
ref #2628
特になし
このプルリクエストは、ローカル環境でpnpm run lint実行時に発生するエラーの原因を調査した結果、ESLintとtsconfigの設定不整合が原因であると判明したため、その対策として行いました。  
テスト実行時の環境差異によるエラー発生を防止し、開発環境の一貫性を保つことを目的としています。

chore(tests): vitestのimportを明示的にする

---

src/sing/songTrackRendering.ts
src/store/singing.ts

ソングのレンダリング関係の型と関数を、`singing.ts`から`songTrackRendering.ts`に移動します。（移動のみ）
（変更が必要なものは残しています）
レンダリング関係はすべて`songTrackRendering.ts`に移動する予定です。

refactor: ソングのレンダリング関係の型と関数を移動

---

README.md

- https://github.com/VOICEVOX/preview-pages/issues/24
以降readmeからのリンクが途絶えていたっぽいので修正しました。

chore(docs): preview-pagesのURLを更新

---

src/sing/domain.ts
src/store/singing.ts
tests/unit/lib/selectPriorPhrase.spec.ts

selectPriorPhrase関数のインターフェースを変更します。
- `Phrase`ではなく`PhraseRange`を渡すように
- `[phraseKey, phrase]`ではなく`phraseKey`を返すように
レンダリング処理の変更をしやすくするために行っています。

refactor: selectPriorPhrase関数のインターフェースを変更

---

.github/workflows/build.yml

GitHub Actionsのworkflowで使用していたubuntu-20.04をubuntu-22.04に更新しました。
20.04がサポート終了となり、CIが失敗していたための対応です。
close #2646
（なし）
- 参考: [過去の20.04関連PR](https://github.com/VOICEVOX/voicevox/pull/2066)
- 20.04でのみ発生していた問題も今後は発生しなくなります。

ci: Ubuntu 22.04に更新

---

src/sing/songTrackRendering.ts
src/store/singing.ts

`generatePhrases` 関数のリファクタリングを行います。
- 単一トラックではなく全トラックのノーツを受け取り、そのノーツからフレーズを生成するように
- `notes`, `tempos` など個別の引数ではなく、必要な情報をまとめた `snapshot` オブジェクトを受け取るように変更
- 重なっているノート（`trackOverlappingNoteIds` に含まれるノート）を除外する処理を `generatePhrases` 関数内に移動
- トラックのノーツをフレーズ単位に分割する処理を `extractPhraseNotes` 関数として切り出し
- フレーズごとのノーツからフレーズを生成する処理を `createPhrasesFromNotes` 関数として切り出し

refactor: generatePhrases関数をリファクタリング

---

src/sing/songTrackRendering.ts
src/store/singing.ts

以下の関数をsongTrackRendering.tsに移動します。（移動とインターフェースの変更を行います）
- generateQuerySource
- generateSingingPitchSource
- generateSingingVolumeSource
- generateSingingVoiceSource

refactor: generateQuerySourceなどの関数をsongTrackRendering.tsに移動

---

src/sing/songTrackRendering.ts
src/store/singing.ts

以下の関数をsongTrackRendering.tsに移動します。（移動とインターフェースの変更を行います）
- generateQuery
- generateSingingPitch
- generateSingingVolume
- synthesizeSingingVoice

refactor: generateQueryなどの関数をsongTrackRendering.tsに移動

---

src/domain/project/index.ts
src/domain/project/schema.ts
src/sing/domain.ts
src/sing/utility.ts
src/store/project/index.ts
src/store/project/saveProjectHelper.ts
src/store/singing.ts
src/store/type.ts
tests/unit/domain/__snapshots__/project.spec.ts.snap
tests/unit/domain/sing/applyPhonemeTimingEdit.spec.ts

以下を行います。
- `Track`に`phonemeTimingEditData`を追加
- `phonemeTimingEditData`をプロジェクトファイルに保存するように
- ひとまず0.24.0で実装される想定でマイグレーション処理を追加
- ユニットテストのスナップショットを更新
- ユーティリティー関数として`recordToMap`関数と`mapToRecord`関数を追加
ついでに、以下も行います。
- `PhonemeTimingEdit`型と`PhonemeTimingEditData`型を`src/store/type.ts`に移動
- 編集データの持ち方は https://github.com/VOICEVOX/voicevox/issues/2261#issuecomment-2476100761 の通り
- プロジェクトファイルではRecord型で保持して、`store.state`ではMap型で保持

feat: 音素タイミング編集データをプロジェクトで保持するようにする

---

.github/workflows/build.yml
public/updateInfos.json
src/components/Dialog/AllDialog.vue
src/components/Dialog/CharacterDetailDialog.vue
src/components/Dialog/CharacterListDialog.vue
src/components/Menu/MenuBar/useCommonMenuBarData.ts
tests/e2e/browser/キャラクターの管理ダイアログ.spec.ts

0.24.0にアップデートします。
「キャラクター・スタイルの管理ダイアログ」のタイトルを・ではなく＆にさせていただいています。
キャラクター"と"スタイルの管理ダイアログだということをわかりやすくするためです･･･！
（まあこのダイアログはまだ製品版では表示されないのですが、覚えてるうちに･･･。）
- https://github.com/VOICEVOX/voicevox_project/discussions/64

build: [release-0.24] to 0.24.0

---

.github/workflows/test.yml

e2eテストで使用するエンジンを更新します。
これによりLinuxのテスト時にインストールしていたlibsndfile1のインストールが不要になります。
またmacOSのテストで使うエンジンも変更します。
ref VOICEVOX/voicevox_engine#1528
ref #2112

fix: e2eテストで使用するエンジンの更新

---

src/store/singing.ts

#2675 でfilteredTracksを生成する際にnoteとしてインポートファイルから生成されたtracksを元にしたtrackではなくrawTrackの方を使うようになっていたので、それ以前の様にtrackを使うように戻しました。
close #2692

fix: ソングエディタでvvproj以外のファイルからのインポートが動作していないのを修正

---

.github/workflows/build.yml

PyInstaller更新により正常に動作するか確認用のPRです。
特にmacOSのDMG版が正常に動作するか確認する必要があります。
ref VOICEVOX/voicevox_engine#1667
https://github.com/VOICEVOX/voicevox_engine/issues/1667#issuecomment-3041158926
多分変更するのはここだけでいいはず。

chore(build): PyInstallerv6エンジンに変更

---

.github/actions/download-engine/action.yml
tools/codesign_setup.bash

VOICEVOX/voicevox_engine#1775 および VOICEVOX/voicevox_core#1112 と同じことを行う。
[installer\_linux.sh](https://github.com/VOICEVOX/voicevox/blob/8558f68858f522b5fd63e9556028b0be9c52b549/build/installer_linux.sh)に関しては、`-f`は既に入っているので何もしない。`--retry`が入ってはいないが、 #2217 でもここには`--retry`は導入されなかったので今回もしない。
\[追記\] 仮にinstaller\_linux.shに`--retry`を入れようとなった場合は、"feat: "として別PRを作るのがよいのではと思ってます。

chore: GHA上で動かすcurlにも`-f`を付ける

---

src/store/index.ts
tests/e2e/browser/初回起動時.spec.ts

fix: 利用規約のテキスト取得メソッドのバグを修正

---

src/store/vuex.ts

- https://github.com/VOICEVOX/voicevox/issues/2088
上記issueによってVOICEVOXのstoreにおけるMutation, Actionへの呼び出しが`commit("MUT_NAME")`、`dispatch("ACT_NAME")`から`mutations.MUTNAME()`、`actions.ACT_NAME()`にて呼び出せるようになりました。
これに伴い`commit`や`dispatch`は使うべきではなくなったため、vuexデフォルトの型へ戻します。
また、`@deprecated`を付け、間違えて使わないように誘導を行います。
close #2088

refactor: storeにおけるDot記法への移行により使われなくなったリテラル記法インターフェースの削除

---

src/components/Dialog/Dialog.ts
src/components/Dialog/TextDialog/QuestionDialog.vue
src/store/project/index.ts

タイトル通りです。
- ref: #2726 
（なし）
（なし）

feat: QuestionDialogのボタン指定に型チェックを追加

---

.github/workflows/build.yml
build/appImageArtifactBuildCompleted.ts
build/artifactBuildCompleted.ts
build/electronBuilderConfig.ts
build/installer_linux.sh
package.json
tools/downloadAppimagetool.ts

ビルドしたAppImageを一度展開して編集してappimagetoolで再度パッケージすることで以下の問題を解決・回避します
AppRun(AppImageが起動したときに一番最初に実行されるスクリプト)にuser namespaceが使用可能か確認して自動的に`--no-sandbox`を引数に追加するようにします。
これによりuser namespaceが制限されているUbuntu 24.04では起動できるようにしつつ他の使用可能なディストリビューションではセキュリティを維持することができます。
ref #2071
appimagetoolでパッケージすることで起動するためにlibfuse2のインストールを不要にします。
- resolve #1006
(libfuse2が不要になるため結果的に不要になる)
動作確認は主にVirtualBox上のUbuntu 24.04上で行っています。
appimagetoolに安定性の問題があります。
appimagetool 1.9.0の動作するために`desktop-file-validate`が必要なので`desktop-file-utils`をインストールする必要があります。
Continuous buildの方は不要ですがmainにコミットがある度に更新されているようなので安定性が確保できません。
また、appimagetoolはデフォルトではビルドの度に自動的に`type2-runtime`を[Continuous build](https://github.com/AppImage/type2-runtime/releases/tag/continuous)からダウンロードしてきます。
これもmainにコミットがある度に更新されるようです。 …

feat: ビルドしたAppImageを展開して編集してappimagetoolで再度パッケージする

---

.github/workflows/build.yml

.tar.gzの作成時にファイルのパーミッションを保持する。
close #2740

fix: .tar.gz内のパーミッションを保持する

---

build/electronBuilderConfig.ts

[electronLanguages](https://github.com/VOICEVOX/voicevox/pull/2751#issuecomment-3335114827)で不要なロケールを消す。
macOSには何故か聞かない。#2751 を置き換える。
close #2748

build: {ja,en-US}.pakロケール以外の言語パックを削除する

---

src/components/Talk/ToolBar.vue

音声書き出し時のダイアログ表示部分を共通化しました。
ショートカットキー呼び出し時とツールバーのボタンから実行したときで同じロジックが実装されていた感じだったので。
↓のプルリクの変更が大きくなってきたので、少しでも減らせればと思って切り出してみました
- https://github.com/VOICEVOX/voicevox/pull/2737

refactor: 音声書き出し時のダイアログ表示部分を共通化

---

build/getElectronVersion.mjs
vite.config.ts

Viteの`target`をビルドするElectronのバージョンに合わせてピンポイントで指定するようにします。
これにより僅かにビルド後のファイルサイズが減少します。
ブラウザ版はViteのデフォルトのままです。
[Vite v6のデフォルト](https://v6.vite.dev/config/build-options.html#build-target)は`'modules'`であり具体的には`['es2020', 'edge88', 'firefox78', 'chrome87', 'safari14']`であり若干古いです。

feat: ElectronのNode.jsおよびChromiumの正確なバージョンをターゲットにビルドするようにする

---

build/getElectronVersion.mjs
vite.config.ts

#2758 によってmainブランチのビルドが通らなくなってしまったので修正します。
#2758
Github Workflowでのチェックを怠っていました。

fix: #2758 によりgithub workflowでビルドに失敗する問題を修正

---

src/backend/electron/engineAndVvppController.ts
src/backend/electron/ipcMainHandle.ts

メソッドにするほどのものではない不要っぽい処理をインライン化しました。
- `src/backend/electron/ipcMainHandle.ts:306` でエンジン設定更新処理を直接 `configManager` に適用するようインライン化。
- `src/backend/electron/engineAndVvppController.ts:340` から不要になった `updateEngineSetting` メソッドを削除。
- なし
- UI 変更なし

chore: `updateEngineSetting`をインライン化
